### ISSUE TITLE
Allow users to select from a handful (3?) stock themes

### ISSUE THREAD

**Issue by chrisdembia** [Reviewable/Reviewable#100]
From discussion in gitter:

![screenshot from 2015-05-18 20 27 09](https://cloud.githubusercontent.com/assets/846001/7694940/597e4ca6-fd9c-11e4-9339-6f77ec472920.png)

Inevitably some users won't like the default Reviewable theme. It seems that what people dislike can vary. But what if there were about 3 camps of opinions? Then Reviewable could provide 3 stock themes. This could include the monospace font, how distinct the file views are, whether "tabs" are rounded off or are square.

Personally, these are some features I don't like:

1. Conversation boxes kinda meld into the code; it's hard to see them distinctly. Maybe a really light grey background for the chat boxes?
2. If there's a comment on one side of the diff, the opposite side of the file is blank which is confusing. Maybe use a background color to show that there's space just b/c there's a comment on the other side?
![screenshot from 2015-05-18 20 31 01](https://cloud.githubusercontent.com/assets/846001/7694962/d68f2a30-fd9c-11e4-8670-49b67d8dfd8a.png)
3. The ripped-page aesthetic over gaps of unaltered code is cluttery to me. There's so much going on already.
4. A narrower monospace font. Or use whichever one I set with my browser settings to be my monospace font.
5. Rounded file tabs.
6. There seems to be a trend on the web of replacing text buttons with icons (github did this a few years ago). This is fine when someone is familiar with a site, but really hinders the ability to learn a site. *Even* if there is a nice legend, like you have.
7. The slanted "r5" text next to each comment box. I think having the revision number is good,but slanted text is harder to read and distracting. You can still use the diagonal cut-off, just put the text horizontal.

**Comment by pkaminski** [comment]
Thanks for the great feedback, @chrisdembia!  Let's see if I can address some of it right away:

1.  I tried playing with the discussion background but it didn't really work for me.  I also tried inverting the header but that was too strong.  I settled for saturating the top purple highlight line some more -- does that help?  I also think the avatars give a pretty strong signal that the comment's aren't code.
2.  You're absolutely right, fixed.
3.  I'm not ready to give up on the torn edges and rounded file tabs quite yet, but here's a stylesheet that gets rid of both: the [gist](https://gist.github.com/pkaminski/db9340182eec59f8774f) to fork and edit if you wish, and the RawGit URL to actually paste into the custom stylesheet URL field in your account settings, so that it's served as text/css: https://cdn.rawgit.com/pkaminski/db9340182eec59f8774f/raw/58cb11d1d25ceab960632b420d0bab9892508ef9/custom.css
4.  I guess after years of seeing Courier New as the default monospace font in browsers, I tend not to trust the defaults.  The font I picked matches the style of the proportional font and is narrow enough that you can fit two columns of 80 chars in a 1200px window.  However, if you have a favorite code font (and every developer seems to have a different one), using it is as simple as typing its name into the first account settings field (and tweaking the size to taste).
5.  See 3 above.
6.  I generally try to avoid icon-only buttons for precisely this reason, but sometimes need to make this trade-off due to layout constraints.  The good news is that I'm working on an onboarding experience that will unintrusively explain all the core features of the app, within the context of your own review.  Coming in a couple weeks, with any luck!
7.  Horizontal text won't fit in the diagonal cut-off: I need to be able to fit up to rNN⊥.  I agree that reading slanted text is hard, but to be honest this text isn't *really* meant to be read every time -- it's just there to provide a (somewhat) self-explanatory click target.  As for being distracting, you'll probably get used to it pretty quickly, but you can also lower the contrast some more by styling the `color` for `.ui.discussion.segment > .right.corner.label` (it's already at 0.65 of black by default).

If you share back any extra tweaks you end up making, perhaps we can start putting together a first alternative theme.  That said, I don't want to commit to formally supporting multiple divergent themes right now, as there's still some fairly invasive CSS refactoring to be done on the page first.

**Comment by pkaminski** [comment]
The torn paper edges are now gone, and at this point I'm not hearing enough complaints about the rest of the UI look-and-feel to warrant making custom themes.  Will reopen if the situation changes...

**Comment by chrisdembia** [comment]
The new paper edges are beautiful! Thank you.

**Comment by mmlb** [comment]
I wonder if you should have a wiki entry, or a tracking bug to put down all the custom css links you've made for people @pkaminski. There's #161, and I'm pretty sure I've seen others around here.

**Comment by pkaminski** [comment]
Yeah, there's more, and I'm happy to supply them on demand, but for now I
don't really want to encourage widespread use.
