### ISSUE TITLE
Participant status column can be confusing

### ISSUE THREAD

**Issue by pkaminski** [Reviewable/Reviewable#1007]
The status column in the participants panel combines multiple properties for the user:  their GitHub approval state, their discussion blocking state, and the LGTM emoji.  However, we only show one of these with the current priority order being:
1. GH review dismissed.
2. Blocking a discussion.
3. GH changes requested.
4. LGTM emoji.
5. Satisfied on all discussions.
6. GH review approved.

This means that, sometimes, important information (e.g., GH review approval) is not shown.  This is even more confusing since we always show the GH approval status on the dashboard, using a corner icon on the participant avatar.

Possible solutions:
- Change the priority order to a better one; perhaps GH status gets top billing, followed by LGTM, followed by discussion state.
- Combine icons when sub-statuses disagree:  if GH shows approved but there's still a blocking discussion, show both, and so on.  Otherwise, only show the highest priority icon.  (May want to combine with re-prioritizing.)
- Always show all icons.
- Split out into separate columns (👎 ).

Thoughts @earlAchromatic?

**Comment by earlAchromatic** [comment]
Re-prioritizing and showing multiple icons only during conflict both still hide away some information and I agree multiple columns should be a last resort. I think showing all icons provides the most insight into the state of the review and seeing the conflicting statuses is probably just what you want in order to resolve the conflicts and get merged.

Here is my interpretation of 'showing all icons': 

1. If reviewer is dismissed, show only that icon since nothing below would be relevant
2. LGTM if present
3. GH changes requested or GH review approved
4. Blocking discussion or satisfied discussions

Since you could have a single icon from each of the last 3 buckets simultaneously at most we would be showing 3 icons in the status column, which isn't too bad. If we wanted to reduce further to only showing 2 icons, we could go the cute route and do something like this with the LGTM, eliminating it from the column:

![image](https://user-images.githubusercontent.com/68669571/219145222-cd5c0849-0e18-46c0-9b62-ae606d6f90ec.png)

**Comment by pkaminski** [comment]
The dismissal is specific to GH's approved / changes requested signal and should be grouped with those.  It doesn't affect the rest of the status signals, except perhaps conceptually.

I'm not convinced the satisfied status is meaningful:  it appears to check for all of a participant's dispositions being satisfied, but that's pretty rare.  You'll usually end up with some dispositions remaining as Discussing (because somebody else resolved the discussion), or Informing, or even just Following.  I think we should either get rid of it, or just make it the converse of the blocking signal.

My reason for suggesting that we only show multiple conflicting signals is that, once you have a "strong" signal (like GH approval), "weaker" concurring signals (like satisfied discussions or LGTM) aren't particularly relevant and just clutter up the column.  I think all customers use only one PR approval system, and while we can't know for sure which one it is, the priority list below should capture the precedence fairly accurately.

Here's a concrete proposal:

1. If GH is approved / changes requested / dismissed, show that.
2. If LGTM and GH is not approved, show/add that.
3. If discussions are blocking and GH is not changes requested, show/add that.
4. If discussions exist and are non-blocking and we have neither GH approved nor LGTM, show/add that.

This would usually result in one icon, sometimes two, and three in only one corner case (dismissed, LGTM, blocking).
