### ISSUE TITLE
Discoverability of @mention in "informing" thread

### ISSUE THREAD

**Issue by xEtherealx** [Reviewable/Reviewable#1015]
A colleague @mentioned me in an "informing" comment on a PR, and subsequently the PR was merged. They let me know about the comment, otherwise I would have totally missed it -- I don't see any way to get notified nor have any indication that the comment existing. Is there a mechanism I can use to become aware of these types of comments?

**Comment by fahhem** [comment]
You would have been mentioned in the resulting comment posted back to the PR, which should automatically subscribe you as a participant to that thread. If you have turned GitHub's (admittedly borderline spammy) email notifications off, you can view them here: https://github.com/notifications?query=reason%3Amention

Would you prefer a feed of such comments in Reviewable's dashboard, or something else? We do have a webhook feature that's not used much for notifying review participants of progress, but due to lack of usage we haven't made it much more useful than for sending an email/slack message when a review moves forward

**Comment by xEtherealx** [comment]
> Would you prefer a feed of such comments in Reviewable's dashboard, or something else?

@fahhem a feed of comments would suffice; preferably we won't need to go to GH at all (except to modify PR descriptions). Webhook would be awesome though; integrating into slack would probably be the best solution for my personal workflow.

**Comment by fahhem** [comment]
Before that, would you mind checking that the PR doesn't show up under "Recently concluded" at https://reviewable.io/reviews? You might have to click "Show more concluded pull requests", but I would have expected the PR to show up there (and initially under "Involving me", before it was merged)

**Comment by xEtherealx** [comment]
The pr does indeed show up under recently concluded, but with no indication that there's any follow-up action required on my part

**Comment by pkaminski** [comment]
This situation gets a bit tricky since the review doesn't meet the threshold of "awaiting your action" (it's merged and done!) but there's still new stuff for you to read.  We handle it in two complementary ways:
1. On the dashboard, the discussion count for the review should be red until you've acknowledged your colleague's comment.
2. The [webhook](https://docs.reviewable.io/repositories.html#webhook) includes a special "New comments for:" section that will list your username if it's not in the usual "Waiting on:" list.

Between those two things you should be able to catch any post-merge comments.  Reviewable doesn't provide a feed of the comments themselves and we don't have plans for doing so at the moment.

**Comment by pkaminski** [comment]
It occurs to me that we might want to extend the webhook's "new comments for" feature to the dashboard as well, with a new "New comments for me" section below "Awaiting my action".  Merged/closed PRs won't stay there forever due to the way the dashboard queries need to be written, but it should still make it easier to fish out reviews with unread comments from the sea of other stuff.  Let me go and add that right now, shouldn't be too hard.  :)

**Comment by pkaminski** [comment]
The "new comments for me" dashboard section is now live!  Hopefully this helps.

**Comment by fahhem** [comment]
@xEtherealx Mind letting us know if this works for you?

**Comment by fahhem** [comment]
@xEtherealx Maybe we should make @mentions in closed issues more discoverable too 😆 

Any chance you're enjoying the new feature?
