### ISSUE TITLE
Merge PR button showing despite adding changes in the PR

### ISSUE THREAD

**Issue by pbharadiya** [Reviewable/Reviewable#1027]
Hello,

I have added a change in the PR via Reviewable. However, I can see "Merge Pull request" button instead of "Publish and Block" button.

Please find the attached screenshot.

PR link - https://reviewable.io/reviews/amuratech/crm/25593#-

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/3007434/227875502-f08f7302-970e-41d0-b257-0c56a2ef1f15.png">

**Comment by fahhem** [comment]
Did you leave comments on the PR that have a Blocking disposition?

If not, pour comments might be marked as informing or discussing, and therefore not blocking the PR.

**Comment by pkaminski** [comment]
The Publish button isn't showing because you have no drafts; we currently only allow blocking (or approving) if you also provide a comment.  GitHub has a similar restriction for requesting changes.

The Merge button is showing because 3 reviewers (including yourself) approved the PR and one commented.  I don't see any blocks (requested changes) in the review history either.

Do the above statements line up with your experience with the PR, or does something sound off?  Thanks.

**Comment by pkaminski** [comment]
Ping, @pbharadiya -- let's debug this before the PR changes state.  Thanks.

**Comment by pkaminski** [comment]
Closing due to lack of follow-up -- please provide more details and we'll reopen.  Thanks!
