### ISSUE TITLE
Uploading an image deletes the draft comment if it ends up with an error

### ISSUE THREAD

**Issue by mkow** [Reviewable/Reviewable#1033]
I just tried to upload an image and it ended up with an error ("Failed to upload asdf.png: Network Error"), which wouldn't be a huge problem in itself, but it deleted the whole comment draft when displaying the error :) Fortunately I backed it up before trying the upload button :upside_down_face:

**Comment by fahhem** [comment]
Hey @mkow I looked into fixing this, and I can only reproduce this error when I have the text of the comment selected when I drop in a file. Is that what happened here? If so, then we plan on changing that behavior to inserting the image without removing any text, so that will fix this. Otherwise, please let us know to try to repro this in other ways.

**Comment by mkow** [comment]
Hmm, that's quite likely that I had it selected! Now I see what happened :)

**Comment by pkaminski** [comment]
Fixed.

**Comment by fahhem** [comment]
Thank you @mkow , we decided to instead address the issue by not replacing/removing text when uploading images.
