### ISSUE TITLE
Revert to the previous form of PR author presentation

### ISSUE THREAD

**Issue by outofforest** [Reviewable/Reviewable#1046]
Hi Team,

I would like to suggest reverting to the previous version, when the PR author's avatar was presented on the left side of "the hand" on the list of PRs. At least in my team all the members find new way to be super unfriendly. In the previous version it was so easy to quickly find my PRs by screening through the list. Now, with that small leaf in the corner, it is just impossible.

All the best!

**Comment by fahhem** [comment]
Hello @outofforest ,

We moved the author avatar to the right side, so you don't have to skim through looking for the author icon.

![SmartSelect_20230414-004720_Chrome.jpg](https://user-images.githubusercontent.com/306100/231979354-879ee5a2-240e-4f52-820a-1afc406cb963.jpg)

Does that help at all?

**Comment by outofforest** [comment]
@pkaminski 

There are two use cases:
- I want to quickly go through my PRs to check who blocks them, so I know who I should hasten/ Yes, I could use a filter but it's slower
- When I review PRs, I might want to give a priority to some author, because I might know that he/she is working on sth important which must be reviewed ASAP.

**Comment by pkaminski** [comment]
Hey @outofforest:

> I want to quickly go through my PRs to check who blocks them, so I know who I should hasten/ Yes, I could use a filter but it's slower

All relevant PRs for this use case should already appear in the "Created by me" section of the dashboard.  The only ones that wouldn't show up there are those that are blocking on you (as they'd be in "Awaiting my action"), but you want them omitted anyway given your stated purpose.  Am I missing something?

> When I review PRs, I might want to give a priority to some author, because I might know that he/she is working on sth important which must be reviewed ASAP.

This makes sense to me and we're debating internally how best to support this use case.  More soon!

**Comment by outofforest** [comment]
@pkaminski 

Okay, now I get your idea. I would suggest these changes then:

1. Move "Created by me" section just below "Awaiting my action"
2. Show my PRs in "Created by me" all the time, even if they are present in other sections
3. Make section titles bigger (same size as PR titles on the list)

**Comment by outofforest** [comment]
@pkaminski 

And I still suggest moving the author's avatar to its original position.

**Comment by ysv** [comment]
I tend to agree with Wojtek
Was trying to get used to new format for the last ~1 week but still find it a bit confusing. Not critical though

**Comment by bitdancer** [comment]
I'm another vote for moving the author icon back to the left side.  Fairly often I will be scanning the list, including the unrelated to me list which can be quite long, looking for a particular PR that I know was written by a particular author.  With the author icons on the right I cannot see the author icons and read the PR titles at the same time, which makes it very hard to scan the list in that way.  And no, I can't text-search for the PR title because I either don't know what it is or I can't remember; instead I know the nature of the PR and when I see the title paired with the author I will recognize that I have found the correct one (at least if the authors have given the PRs good titles, which granted sometimes doesn't happen, but there is nothing reviewable can do about *that* :)

**Comment by bitdancer** [comment]
An alternative would be to put the author icons right in front of the issue titles.  Maybe they could even be the small version, but for teams with lots of people it might be hard to recognize the icons at the smaller size?  I suppose you could try that and see what the feedback is.

**Comment by pkaminski** [comment]
Quick update:  We're considering moving the author avatars next to the PR titles -- not 100% sure yet, but I think it's likely to happen.  They would probably stay small and faded out, but that's something that can be easily overridden with a custom stylesheet via Reviewable's settings (we'll provide directly usable examples).

We're also looking into a new mechanism to make it easier to find PRs authored by or related to a person, without having to use the search field.  More on that later if it works out.  :)

Regarding some specific feedback:

> Move "Created by me" section just below "Awaiting my action"
> Show my PRs in "Created by me" all the time, even if they are present in other sections
> Make section titles bigger (same size as PR titles on the list)

The dashboard is intentionally designed as a single list of (relevant) PRs that's ordered by inferred priority.  We don't want to duplicate items in this list, or treat it as a sequence of separate lists -- that would be a very different design.  The section headings are there just to call out the points at which the priority level goes down in the list.  The full order of section priorities is:
1. Awaiting my action
2. New comments for me
3. Working on it
4. Being reviewed by me
5. Assigned to me
6. Created by me
7. Involving me
8. Involving my teams
9. Recently concluded
10. Unrelated to me

It's not clear to me that there's a rationale for considering "Created by me" as higher priority than "Being reviewed by me", much less the other two sections above that.  Happy to hear counter-arguments, though.

> looking for a particular PR that I know was written by a particular author
> I can't text-search for the PR title

Tip:  filtering on the author name isn't perfect, since it'll also select PRs where they're a reviewer, but it would cut down your search space a lot.

**Comment by bitdancer** [comment]
That doesn't really match up with how I actually work.  Generally I only have a page or so of PRs in all the categories.  A fast visual scan is a much more efficient way of finding the relevant PR than trying to set up a filter (half the time I don't remember the developers github id). And I say that as someone who is very keyboard centric most of the time.  Add to that the fact that sometimes I'm wrong about which developer it is, but I do manage to spot it by title.

I'll also note that I just went looking for a PR I was asked to do a quick review on, and I wasted a number of seconds because all I initially saw in the "awaiting my action" section was things that had my icon in the front.  I *think* if the developer icons are in front of the PR titles I'll be able to retrain my eye.  I hope :)

**Comment by outofforest** [comment]
@pkaminski 

I 100% agree with all the arguments provided by @bitdancer

**Comment by pkaminski** [comment]
Hey folks, please take a look at the new version of the dashboard we just released.  Author avatars are now next to PR titles, and check out what happens when you click on any avatar -- I hope it helps you find the right review faster!

We're keeping the author avatars small and faded out but you can tweak this using a [custom stylesheet](https://docs.reviewable.io/accountsettings.html#custom-stylesheet) like so:

```
.open.reviews td.summary .author.avatar.image {
  filter: none;
  width: 2em;
  height: 2em;
}
```

If you'd just like to remove the fadeout I put the style in a public gist, so it suffices to put the following URL into the custom stylesheet field of your user settings:

```
https://gistcdn.githack.com/pkaminski/00261671ae3caefb56e9b8b3147e0516/raw/a8e02fb8906f5992e195306a2441bf6a1c906353/style.css
```

**Comment by outofforest** [comment]
@pkaminski 

Thanks for update! New version is much better but I would still prefer to have those avatars bigger.

**Comment by pkaminski** [comment]
You can do that yourself:  put the CSS snippet above in a gist, get a correctly MIME-typed URL to it from githack.com, then plug that URL into your Reviewable account settings and the avatars will be bigger for you from then on.
