### ISSUE TITLE
Review comments no longer point to a code span

### ISSUE THREAD

**Issue by orizi** [Reviewable/Reviewable#1052]
It seems i can no longer mark a span of code and comment over it or suggests edits to it.

**Comment by jwnimmer-tri** [comment]
I'm also a reviewable user, and this change confused me too.  Once you highlight the text, you now need to click the `?` icon to open a discussion with the suggestion box.

**Comment by pkaminski** [comment]
Hey folks -- we changed the UI flow as some users complained that they were inadvertently creating code quote comments because they happened to have some code selected for other purposes.  We now consistently use the pop-up selection command bar to initiate actions on the selection, whether for quoting comments or code.  I believe this is also more in line with how other web apps deal with selection actions.

Is the problem the unexpected new workflow, or just that the icon is unclear, or something else?  Detailed feedback appreciated!  Thanks.

**Comment by jwnimmer-tri** [comment]
For me, it's just unlearning the muscle memory.

What I previously did:

(1) Highlight the problematic code snippet (e.g., click-drag across the one word `foof` that had a typo).
(2) Click on the highlighted text to turn it into a review discussion with the selection as a suggestion.
(3) Type my review message (e.g., just `typo`) and then edit the suggestion with the correct spelling `foo`.

With the new UI, in step 2 instead of clicking on the highlighted text, I need to click on the nearby `?` icon instead.

It's just as easy to do it the new way, but because I've been doing the old way it hundreds of times a day for the past year, it's just taking me a while to retrain myself to click the `?` instead.  Often I still click the highlight and immediately start typing, only to realize after a second that the suggestion didn't get picked up, so I need to delete my comment and start over.

I can understand the argument about the select-click spuriously quoting.  I don't read by selecting as I go, but I know some people do.  It seems like a fine change but it will probably take me another week or two before I've fully retrained myself.

**Comment by jwnimmer-tri** [comment]
It might be a tiny improvement if the `?` icon had hovertext explaining what it does.  Once I shared this issue link with my team, some commented that they thought the quote-and-edit feature had evaporated entirely (like the OP), because they interpreted the `?` link as a help screen instead of as a command to open a new discussion.

**Comment by jwnimmer-tri** [comment]
Oh, and I just had another brainwave.

Imagine this:
(1) I highlight a snippet of code.
(2) I click on it to open a discussion.  The selection is lost.  I type my review text ("typo", or whatever).
(3) When I click the `</>` button to make a suggestion as part of the discussion, the default selection is my previously-highlighted text range, rather than the current line.

I wonder if that might be a good balance to keep everyone happy.

**Comment by SeanCurtis-TRI** [comment]
For my own 2-cents, my one pet peeve in using my mouse is having to aim. Under the old regime, I didn't have to aim as carefully to click on my highlighted text and turn it into a suggestion. Now, I have to aim carefully to hit a quite small icon. Admittedly, I recognize for those who were frustrated in accidentally creating discussions, these traits were exactly what caused them problems. So, there is definitely no single UI that satisfies everyone.

How about a configurable setting for a project? Those who like it can turn it on?

**Comment by jwnimmer-tri** [comment]
As I understand it, config knobs are generally dispreferred because it adds onramp complexity, implementation complexity, and now the UX works differently per-person which is a teaching hurdle for showing new users the ropes, making tutorial videos, etc.  There is a large payoff in having a uniform UX/UI for all users, and I don't think this small awkwardness is enough of a pain point to break the glass.

**Comment by SeanCurtis-TRI** [comment]
Well, I hadn't thought about it in terms of *per-user*. More, per-project. But I'm sympathetic with the challenges of changing organizations (or even projects within organizations) and finding they're configured differently.

I like the idea of positioning the `?` strategically.

**Comment by pkaminski** [comment]
Hey folks -- thanks for the feedback!  Your comments were very timely as we happened to be discussing the issue live at the same time.  :)  We had much the same ideas, which gives me confidence we're on the right track.  Our plan at the moment is to keep workflows as-is, but make the button clearer and easier to hit in the hopes that you'll pick up new muscle memory.  (Keeping track of a selection past the creation of a draft is wrought with corner cases so we'd rather avoid going that way if possible, but we'll keep this option in our back pocket.)

Expect some updates in the next day or two!

**Comment by pkaminski** [comment]
We deployed some improvements -- please let me know what you think.
