### ISSUE TITLE
Review completion check not triggered unless UI is opened

### ISSUE THREAD

**Issue by pcorpet** [Reviewable/Reviewable#1099]
When creating a PR from the GitHub API, then accessing it only from the GitHub website, I believe that Reviewable doesn't run the review completion script or at least does not report the success/pending state to GitHub. We end up with a pending status in GitHub for Reviewable and as we have made this check "Required", that means that our PRs don't get merged.

The workaround is for any user to open the PR in Reviewable which then triggers the Review completion check which, in some cases at least, validates the PR.
```
code-review/reviewable Expected — Waiting for status to be reported
```
<img width="799" alt="image" src="https://github.com/Reviewable/Reviewable/assets/7937848/d9b30a0d-8c9f-4994-9d6d-32c3c5523d26">

I have checked that Reviewable webhook does receive some events including a `pull_request_review.submitted` if someone has done a review on GitHub. I would have expected that event to trigger a check on Reviewable and for it to report the updated status back to GitHub API.

FYI some people in my team are not convinced by Reviewable UI yet 😢 so I'm trying to find a mixed setup where some of us can use Reviewable while other may use the GitHub UI only.

**Comment by pkaminski** [comment]
While Reviewable's status would usually be updated in response to a GitHub PR review being posted, there's a repo-level setting that might be preventing this from happening:
![image](https://github.com/Reviewable/Reviewable/assets/1646896/8b1ef21b-00ef-4f8f-8943-3cedf8df918b)
Could you check whether this happens to be set to "on for visited reviews only" (the default) for the repo in question?

If it *is* set to "on" then we may have a bug.  Could you let me know a specific PR and the approximate time a PR review was posted so I can check our logs for details of how we handled the event?  Thanks.

Also, any feedback from the above-mentioned unconvinced people would be very much appreciated!

**Comment by pcorpet** [comment]
Indeed, thanks for the quick answer. This has fixed my issue.

**Comment by pkaminski** [comment]
> confusing default state when reopening a review: when coming from GitHub and you're not used to the little r1, r2, ... r5 selectors, they sometimes end up not seeing the new code as the default view would open a file in a diff state that does not include the latest code. Maybe that could be a config

Are you using "review each commit separately" review style in your repo?  This is the only setting that might result in not putting the right diff bound at the last revision -- it's intentional if you have multiple unreviewed revisions (commits), so you can review one commit at a time.  Otherwise, though, (re)loading a review page should always show a diff with the latest code.  If you find that this is not the case I'd appreciate a screenshot of a freshly loaded page, along with the PR number and the user who loaded it.  Thanks!

**Comment by pcorpet** [comment]
One example just now: I've just opened one of my own PRs with only one commit and one revision. Reviewable is hiding the full diff which is pretty useless (doing a r1 to r1 diff)
<img width="816" alt="image" src="https://github.com/Reviewable/Reviewable/assets/7937848/3e83d85f-2338-44bb-813a-26ff3e6e0edc">

**Comment by pkaminski** [comment]
So this is intentional, though we can certainly debate whether it's right.  The general idea is that we only show you files that require your attention, whether for review or because they have unresolved discussions, to lower your workload in trying to find what you need to act on.  In the case above nothing requires your attention so we hide everything, explain why, and give you a one-click way to get the full diff in case you need to do something outside of the normal review workflow.

Is this the state that's been confusing other people, or did they run into different ones?  (All likely stem from the general rule above but may manifest in different ways.)

**Comment by pcorpet** [comment]
Indeed I think thy ran in different ones: they would go to a PR, mark as read, then going back later to the PR with new changes on some files and then not seeing the changes they initially saw on the first files. My suggestion would be to make the behavior you write about (hide file diffs that you do not need to review) configurable so that some users could prefer a focus by default, and some others could prefer to see the full diff by default.

**Comment by pkaminski** [comment]
TBH this sounds more that they're used to the way GitHub works and we need to provide better onboarding -- which we want to do!  Our bar for adding a setting is quite high and this doesn't clear it, but we do want to make diff control in general (and resetting to a full diff in particular) much easier to achieve.  You should see some new stuff show up in this area by EOY.
