### ISSUE TITLE
UI unusable whlie offline

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#1101]
# Expected

Pages such as My Reviews and the review page remain as usable as possible during temporary internet connection outages.

* At the very minimum, I expect to be able to keep looking at a review list or a review page (rather than at the “offline” banner) and scrolling it.
* Being able to keep typing a comment that I started typing before the outage would be nice.
* The best, of course, would be to be able to do anything that doesn't require receiving data that isn't already loaded. For example, starting a new review comment for a visible line of code should be possible, although I understand that expanding hidden code lines or changing the diff range is impossible.

# Actual

An “offline” banner prevents interacting with, scrolling and even reading a review list or a review page.

**Comment by pkaminski** [comment]
This behavior is intentional -- since we have no local persistence (and adding this to our database engine would be really hard), we lock out the UI if we lose our connection to the database.  There's a way to override this if you like to live dangerously:  run `Reviewable.workOfflineAtMyOwnRisk()` in the JS console.  This will disable the offline dialog and you'll be able to continue working with all data held in the tab's memory only.  If you reconnect before your tab closes (or your browser decides to flush it, or...), all data should be saved (overwriting any changes you might've made on a different machine in the meantime).  Otherwise, you'll lose your work.

**Comment by feldgendler** [comment]
Thanks for the workaround! I decided to try it and simulated a network outage by disabling WiFi.

Here is what I did:

1. Start typing a comment in a review.
2. Disable WiFi. Reviewable shows the “bad connection” icon.
3. Keep typing.
4. A few seconds later, the offline dialog appears.
5. Call `Reviewable.workOfflineAtMyOwnRisk()`. The offline dialog disappears.
6. Keep typing.
7. Reload the page. The browser shows the “offline” page.
8. Enable WiFi. The browser detects that and reloads the page.
9. Look at my comment.

To my surprise, on step 9 I saw everything I had typed, including what I typed on step 6. Without local persistence, how is this possible?

I tried a few variations of this sequence. No matter what I did, I coudln't cause my comment text to be lost.

What am I missing?

**Comment by pkaminski** [comment]
Heh, I think you got lucky:  the client-side cache is held both in the main page process and in a shared web worker used to communicate with Firebase.  While reloading the page will definitely destroy the in-page copy, it seems that the browser didn't flush the worker before the page reloaded and reconnected to it.  (Normally shared workers are flushed once no page needs them anymore, but perhaps the semantics when reloading a page have some latitude to them.)

I'm happy to to hear it worked but I probably still wouldn't depend on it!  Like the function says -- work offline at your own risk.  :)

**Comment by feldgendler** [comment]
Thanks, this clears up my mental model. And one more thing I don't understand:

What's the difference between what happens on step 3 and on step 6? On step 3, I'm allowed to keep typing, even though the network issue is already detected (hence the “bad connection” icon), and my input is just as much as risk as on step 6. But on step 6, I wouldn't be able to type if not for the workaround. What determines the cutoff point after which it's considered too risky to keep typing?

**Comment by pkaminski** [comment]
The cutoff is arbitrary -- it's currently set at 5 seconds IIRC.  Our reasoning is that accepting some risk is necessary since short connection dropouts/brownouts are not uncommon but if it turns out to be a longer disconnection at worst you'll lose just a few seconds of work.

**Comment by pkaminski** [comment]
I hear you.  The current design is a sledgehammer, built under the assumption that going offline would be an exceedingly rare occurrence and that working offline was essentially impossible (even without artificial roadblocks).  If you're going offline regularly it's definitely a poor solution.  Ideally you could fix your connectivity issues but I understand all too well that those are often outside your control.

I'm hesitant to change the modal overlay to something less intrusive, though, since there is a real risk that users won't notice and will lose a substantial amount of work.  How about this, though:  I updated the `workOfflineAtMyOwnRisk` method to optionally take a boolean to toggle a sticky version of the setting on or off.  If you run the following code once you should never see the offline dialog again -- or at least until something clears your local storage:

```
Reviewable.workOfflineAtMyOwnRisk(true)
```

**Comment by feldgendler** [comment]
Hi, thanks for the advanced workaround!

My conditions for which this is relevant: sometimes I work in a moving car. It's not as productive as in a place with WiFi, but also not a complete waste of time. On long stretches of highway the coverage is often spotty. Whenever there is a gap in coverage, I take that as a cue to take a break from work until the next village — but I'd very much like to finish my current comment.

With `Reviewable.workOfflineAtMyOwnRisk(true)`, I'm afraid that I won't notice the “bad connection” icon in the corner. My desire isn't to ignore outages completely and work through them as if I were online — that would indeed be too careless. Finishing the sentence is probably the most I'm going to do while offline, and I'll almost certainly copy the unfinished comment away to a local text editor. I might scroll around and passively read what's already visible, too.

Assuming there isn't a proper offline mode with correct safety limitations, here two simple alternatives for the user experience while offline, the first one being preferable for me personally:

1. A very noticeable but non-intrusive signal. For example, a change of the background colour of the page, a thick red border around the viewport, or something similar. You have to know what it means, but once you do, it's perfect. It should also go away automatically when the outage is over, so you'll know when you're in the clear, too.

2. A button/link in the offline dialog that does the same as `Reviewable.workOfflineAtMyOwnRisk()`.

Either of these could be activated permanently with `Reviewable.workOfflineAtMyOwnRisk(true)` if you think it's too risky to apply by default.

**Comment by pkaminski** [comment]
Thanks for the concrete suggestions, but honestly that's more work than we could justify for this edge case.  Here's what I can offer instead:  I added an `offline` class to the `body` element that will be present precisely when an offline modal is showing, or would be showing if not for `workOfflineAtMyOwnRisk`.  You can use this to [add a custom style](https://docs.reviewable.io/accountsettings.html#custom-stylesheet) that fits your needs, e.g.:

```css
body.offline {background-color: red;}
```

Does that work for you?

**Comment by feldgendler** [comment]
Thank you very much! Combined with a single call of `Reviewable.workOfflineAtMyOwnRisk(true)` , this solves my problem completely.
