### ISSUE TITLE
Add a "Done"-like button to comments, even if they're in the Informative/Discussing disposition

### ISSUE THREAD

**Issue by fahhem** [Reviewable/Reviewable#1105]
Often these dispositions are used for nits or optional changes, so having an easy way to resolve them in the affirmative would be nice. If they're not done, then users can either ignore them or argue back, but when you do them, it would be nice to be able to click a button rather than click to reply, then type Done.

**Comment by pkaminski** [comment]
Can you expand on the workflow that makes it desirable to respond explicitly to Informing or Discussing discussions when one elects to satisfy their request?

In our team, we just have the author make the change and either resolve (for Discussing) or acknowledge (for Informing); the reviewer will see the change in their next review round and correctly infer that the author decided to take their advice.  If there's no code change, well, presumably the author did not feel it worthwhile and (by definition) the reviewer shouldn't care.  There's also a ["trust but verify"](https://docs.reviewable.io/discussions.html#resolution-workflows) mode that will bring any resolved Discussing conversations to other participants' attention without needing an explicit reply, which can be useful on occasion.

**Comment by tamird** [comment]
Chiming in as perhaps the original requester here - I'm not sure there's an explicit workflow need here, but it sometimes feels wrong to "acknowledge" a comment you've elected to address in the affirmative.

Perhaps this boils down to semantics. The word "acknowledge" suggests "thanks, but no thanks" to me.

**Comment by pkaminski** [comment]
Thanks, makes sense.  We intended "acknowledge" as a neutral word (and spent literally months looking for a better one!) but you're not the only one it sounds vaguely dismissive to.  If you can think of a better word we're open to suggestions!

In the meantime, you can [bind](https://docs.reviewable.io/accountsettings.html#custom-key-bindings) a key -- say `d` -- to a command like `replyToCurrentDiscussion('Done.')`, so you'll be able to focus the discussion (click anywhere inside it) and hit `d` to emulate what the Done button does.  Would that work for you?

**Comment by tamird** [comment]
I think we just need two different words here. Fundamentally I'd like to communicate to the reviewer whether I've taken action on or ignored their comment. They shouldn't have to open Reviewable to learn which.

**Comment by pkaminski** [comment]
Right, but the way to communicate with the reviewer is by posting a comment.  My suggestion to bind a key above will do precisely that, and you can even bind multiple keys each with a different message for convenience.

**Comment by tamird** [comment]
Is there a fundamental reason that a "Done" button cannot appear alongside the "Acknowledge" button?

**Comment by pkaminski** [comment]
Our bar for adding complications to the UI is pretty high and at this point putting a dedicated extra button in the middle of a core workflow doesn't clear it.  If anything, I could imagine adding a "canned responses" feature (as requested in #282) activated by a small dropdown button in the corner of the "reply" text field.  This would be less intrusive and more generally useful than a dedicated supernumerary Done button, and would only appear for users who intentionally opted into the complication.  That feature is not on our immediate roadmap, though.

I generally agree with what Jeremy said above.  I think the idea of letting the user pick whether to have a Done button instead of Resolve in these situations is interesting, but suffers from the problem that it would preclude being able to resolve the discussion without further comments -- presumably, you don't _always_ want to say Done.

Is there a reason the key binding solution doesn't work for you right now?

**Comment by pkaminski** [comment]
Closing due to lack of follow-up, but happy to reopen on request.
