### ISSUE TITLE
A second stacked PR makes the first PR error out in github saying there are multiple PRs open for the commit

### ISSUE THREAD

**Issue by im-sj** [Reviewable/Reviewable#1116]
Seems to be a recent problem. My workflow has always been to stack my commits in multiple PRs for reviews and merging to master. How to repro:

1. Create a commit A and open a PR_A
2. Add another commit B on a different branch rebased on A and open a PR_B with both commits A and B
3. Get PR_A reviewed and ready to go.

Expected: PR_A can merge to master
Observed: The merge button is disabled and reviewable seems happy but github complains that there are multiple PRs open for the commit.

Workaround: Closing or not creaating PR_B in reviewable lets PR_A merge.

**Comment by pkaminski** [comment]
Hi Sumit -- we did recently add a feature that detects PRs with the same head commit and fails out their Reviewable status check, since otherwise it can lead to fighting over the commit's status.  Let me see if we made the condition overbroad and it's activating for any shared commits as that would be a bug.

**Comment by pkaminski** [comment]
There was indeed a bug and we deployed a fix -- sorry about that!  Please let me know if it works.
