### ISSUE TITLE
Blockquote at the end of a comment is cut off

### ISSUE THREAD

**Issue by DerGuteMoritz** [Reviewable/Reviewable#1121]
The blockquote at the end of [this comment](https://github.com/clj-commons/aleph/pull/687#issuecomment-1801313614):

![2023-11-08_17-36-33_comment-on-gh](https://github.com/Reviewable/Reviewable/assets/19733/4a3fc265-cdf6-49e6-9b1a-bcd261154c6f)

Is completely cut off when viewed in reviewable:

![2023-11-08_17-37-33_rv](https://github.com/Reviewable/Reviewable/assets/19733/55461456-c1a1-4f27-af8b-8444a7c852eb)

**Comment by pkaminski** [comment]
Thanks for the report!  This was caused by our algorithm that cleans up bottom-quotes in messages imported from GitHub.  It's a balancing act, but I think bottom-quoting is most likely in email-originated comments so I tweaked the logic to let through tail quotes in messages sent from GitHub's UI.  Your message is now shown in full on Reviewable.

**Comment by DerGuteMoritz** [comment]
Thanks for the quick fix and the explanation, really appreciated :pray:
