### ISSUE TITLE
Self-reviews

### ISSUE THREAD

**Issue by mprobst** [Reviewable/Reviewable#114]
Reviewable is great, I'd like to use it even more. A common use case for me is reviewing my own code - before I bother my reviewer, I'd like to check it for myself.

In Reviewable, when looking at code I create myself, the keyboard navigation and "todo" aspects of it don't work (I presume that's the reason). It'd be great if this use case was better supported.

**Comment by pkaminski** [comment]
Thanks for the kind words, Martin!  While self-reviews are not the primary use case for Reviewable, they're definitely supported.  You can mark files as reviewed (navigate with n/p -- was broken for a short while, sorry!), create discussions that will be counted as "unresolved" (navigate with shift+J/shift+K) , resolve them yourself, etc.  The only trick is that, in general, counters won't show up in red since Reviewable doesn't know that you're doing a self-review and on the hook for reviewing and resolving everything.

However, this use case doesn't get as much testing, so if you can list specific things that are broken I'd be happy to take a look and see if I can get them to work better.

**Comment by mprobst** [comment]
Thanks Piotr. I think I interpreted `n`/`p` not working as self-reviews not really being supported. Good to know that this should work! I'll try this for a while and will open specific issues as I run into them.
