### ISSUE TITLE
Reviewable not updating GitHub check status

### ISSUE THREAD

**Issue by pcorpet** [Reviewable/Reviewable#1142]
The following PR is kind of stuck:
https://reviewable.io/reviews/gamma-co2ai/co2ai/7922

On Reviewable everything seems to be ready and complete
<img width="538" alt="image" src="https://github.com/Reviewable/Reviewable/assets/7937848/fc0528c7-0bfb-4fa4-a8c2-8d824269249b">

On GitHub, the check is still pending.
<img width="726" alt="image" src="https://github.com/Reviewable/Reviewable/assets/7937848/fa02d3e7-3922-43f8-b3a0-da90779d733d">

I'm not sure how to troubleshoot.

**Comment by pcorpet** [comment]
Note that we've forced the approval using the `gh` command line tool to unblock ourselves, however it would be interesting to understand either what happened, or a way to troubleshoot if it happens again

**Comment by pcorpet** [comment]
Maybe it's linked to a sync error with GitHub?
<img width="197" alt="image" src="https://github.com/Reviewable/Reviewable/assets/7937848/e482232f-ac00-4ec8-94b6-caf47a12448a">

**Comment by pkaminski** [comment]
A disconnected repo will not update PR status, so that's your root cause. Not sure why it says the repo wasn't found, though. Likely a permissions issue.

**Comment by pcorpet** [comment]
Thanks. It's weird, because we didn't change the permissions of the user's who's mentioned above. And also weird that it's not causing any issue for another repo by the same user. I've disconnected/reconnected to solve the issue around there for now. I'll reopen if a disconnection happens again.

Could you update the status update to reveal that "because the repo is disconnected the status are not updating on GitHub" or something like that, it would have helped troubleshoot.

**Comment by pkaminski** [comment]
(Back in the office, so I can look into this in more detail now.)

Checking our logs, `co2ai` was disconnected on 2/21 7:29:19 PST, and again on 2/22 4:23:49 PST.  Both disconnections were caused by a "repository not found" error and the second instance was followed by disconnection of another couple repos within 10 minutes or so.  I see that `co2ai` is connected now so I'm guessing that you noticed the second disconnection as well.

It's not clear why the repository was not found:  GitHub likes to return this error in a variety of situations.  If it's not a permissions issue then it might instead be cause by somebody turning on OAuth app whitelisting for the organization, or perhaps just a GitHub API hiccup (though I don't see any widespread issues with other repos).  Did you figure out a probable cause in the last couple of days, perhaps?

As for the "repo connection is broken" status update, I thought we already did that but I was confused — we only do it for broken reviews, not broken connections.  I'll add support for the latter case.

**Comment by pcorpet** [comment]
Thanks Piotr for checking. I indeed noticed the second disconnection (and knew how to fix it quickly). It sounds like a GitHub hiccup indeed. To fix, each time, I went to the repos list on Reviewable, disconnected one "red one" and reconnected it just after. This would also reconnect other red ones. 🤷 

Let's hope we don't have more of those.
