### ISSUE TITLE
As the person opening a PR, I wanted to assign it for review based on the number of PRs each person on my team has already to review

### ISSUE THREAD

**Issue by ruispideraf** [Reviewable/Reviewable#1160]
What's the simplest path to get this?

Thanks in advance.

Rui.

**Comment by pkaminski** [comment]
Hey Rui, assigning PRs for review is currently out of scope for Reviewable.  However, since reviews and PRs have a 1-1 correspondence, you should be able to use GitHub's [team auto assignment](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team#about-auto-assignment) with the load-balancing routing algorithm to spread the load.  This is not exactly what you asked for (as it uses a 30 day window for the number of PRs instead of an instantaneous measure) but it should have roughly the same effect.  Does that work for you?

**Comment by ruispideraf** [comment]
Thank you so much Piotr, it's really helpful. At least, I managed to have
the team discussing it, so it's going in the right direction.

Rui.
