### ISSUE TITLE
Make full commit messages available in review structure

### ISSUE THREAD

**Issue by nate-thirdwave** [Reviewable/Reviewable#1162]
We'd like to be able to add commit message sanity checks to the completion condition, but at current only the title of each commit is available in the review structure that's passed to the completion condition.  It would be great if the entire commit message could be represented there.   I could see this as either of: the message `body` is added as another member next to `title`, or the system file `-- commit` entry also gets its full contents entered into the structure.

**Comment by pkaminski** [comment]
Hey Nate — while I can certainly see how this would be convenient, it's out of scope for the completion condition.  These conditions are meant to assess the state of the review itself rather than the code (and metadata) under review.  I'd recommend using a GitHub action instead (e.g., the [GS Commit Message Checker](https://github.com/GsActions/commit-message-checker) or a custom fork of [Opinionated Commit Message](https://github.com/mristin/opinionated-commit-message)).  This will add a bit of extra admin complexity but ultimately will be much more flexible and maintainable, I think.  If you'd like, you can make this check optional, then add further logic in the completion condition to decide when it should be required.
