### ISSUE TITLE
feat: Add config option to disable reviewable integration for the PRs in draft state

### ISSUE THREAD

**Issue by candiduslynx** [Reviewable/Reviewable#1171]
Drafts should be left unreviewed until they're published.

**Comment by pkaminski** [comment]
Do you mean disable Reviewable's GH status check reporting while the PR is in draft?  If so, I think you can get partway there by switching the "[Review status in GitHub PR](https://docs.reviewable.io/repositories.html#review-status-in-github-pr)" setting to "On for visited reviews".  (This assumes that there's no reason to navigate to the review in Reviewable while it's a draft.)

Adding an "On for non-draft PRs" option would run into problems if a PR goes from draft to reviewable and back to draft, since there's no way to withdraw a previously posted status check in GH.  You could write a custom completion condition that forces the check to `success` for draft reviews but that could have undesirable side-effects depending on your workflow.

Or did you mean that you'd like an additional "but only if the review is not in draft mode" option for the Reviewable badge?

**Comment by candiduslynx** [comment]
> adding the badge only once a review has been requested

IIRC, this also covers the case with drafts unless you explicitly add reviewers, so it also works.

**Comment by pkaminski** [comment]
> IIRC, this also covers the case with drafts unless you explicitly add reviewers, so it also works.

Yup, that's the idea at least.  Cool, we'll get a "but only if the review is requested" option added in the near future.
