### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by sflanagan180251** [Reviewable/Reviewable#121]
The site bombed out a few times with the kooky glasses and an error about API permissions for my user.  Now, I cannot sign in at all on reviewable due to credentials issues.  

If it matters, I'm using 2 factor authentication, and I've tried logging out of github entirely and letting reviewable prompt me for username, password, and authentication key, but I still get the same error message: Unable to sign in: Invalid authentication credentials provided.

**Comment by dbertram** [comment]
FWIW, I *just* confirmed our subscription level prior to this happening. We still have 11 days left on our free trial according to the subscription UI though.

**Comment by pkaminski** [comment]
Investigating, but I'm pretty sure this is unrelated to the subscription.  I think the API quota for Sean's account might've run out, in which case it'll reset itself within the hour.  Digging...

**Comment by pkaminski** [comment]
Yes, looks like Sean's auth token exhausted its GitHub API quota.  It will reset in ~5 minutes.  This happens pretty rarely since the quota is quite generous (5000 requests per hour), but if you have access to a lot of repos then reloading the Repositories page often can chip away at that in a hurry.  I'll be pushing a fix to #117 today, after which you shouldn't have this problem any more.

BTW, typically you get a much nicer error to notify you of this problem, but apparently once you're over-quota you can't sign in any more and Reviewable doesn't get any meaningful error code to report back to you.  :frowning:

**Comment by sflanagan180251** [comment]
FWIW, that looks like the gist behind the error message that it was giving me, but I killed my browser and signed out to see if that would solve the problem and so couldn't recall the exact error message.  

Thanks for the quick response.

**Comment by pkaminski** [comment]
NP, looks like your quota has reset now so you can give it another try!

**Comment by sflanagan180251** [comment]
Yeah, it works now, so I should be good.

Thanks!
