### ISSUE TITLE
Use a single, full-browser-tab-width column for added/deleted file diffs

### ISSUE THREAD

**Issue by dbertram** [Reviewable/Reviewable#122]
Reviewable tells me when a new file has been added or when a file has been deleted. Could it use the entire page-width when showing the all-green/red diff?

It'd be nice to keep the side-by-side diffs for files that have changed, but be able to take advantage of the entire tab width when reviewing newly added files.

**Comment by pkaminski** [comment]
Unfortunately, the UI is written with the expectation that all files are in the same mode, so this would be a bit hard to implement.  Also, I'm assuming that if you're using side-by-side diffs then you've set up your window to work comfortably with those column widths, so there wouldn't be much to gain by making the column even wider.

Note that if you want to quickly switch to single column mode and back you can use the little hover menu off the margin notch (top-right corner of every file) to toggle "single" mode on and off.  (Somewhat confusingly, this is actually a global toggle rather than per-file.)
