### ISSUE TITLE
Show diff for renamed files?

### ISSUE THREAD

**Issue by dbertram** [Reviewable/Reviewable#123]
Reviewable tells me when a file has been renamed, but as far as I've seen I just get one all-red diff for the old file name and another all-green diff for the new file name. While that's mostly fine, often the file rename also includes content changes. It'd be really helpful if reviewable could show me a diff *between* the old file's content and the new file's content side-by-side.

**Comment by pkaminski** [comment]
This should already work if you diff the green revision against its "base" (which is actually set to be the version it was renamed from).  Can you confirm, or provide a link to a review where it's broken?  The red revision's diff should also be collapsed by default since it won't show any useful information under any condition.  My eventual intention is to unify the original and renamed files into a single "virtual" file, so that the rename shows as a change instead of a delete/add, but that will take longer since it breaks some architectural invariants.

**Comment by dbertram** [comment]
Hmm. I'm seeing the described behavior in all the reviews I have open now, but if I come across an erroneous one, I'll re-open this. Unfortunately I can't link you to anything since all my PRs are in private organization repos.
