### ISSUE TITLE
Make one side wider than 50% when the other side is empty (e.g. file added/deleted)

### ISSUE THREAD

**Issue by ryan-williams** [Reviewable/Reviewable#134]
This is maybe a strange idea, but I often end up in this situation:

![](http://f.cl.ly/items/3C3K173q313D000E2G2H/Screen%20Shot%202015-07-24%20at%2011.07.48%20AM.png)

I have to widen my browser window, at a 2x handicap, to get the lines in the added file to not wrap.

Feels like it might be a sane default to "cheat" with the width partition a little bit in cases like this… 60/40? 70/30? 100/0?

Just a thought, thanks!

**Comment by pkaminski** [comment]
This is very similar to #122 requested by @dbertram.  My argument against it there was that if you're working in side-by-side mode then you've set up your window to to comfortably fit the code into the columns, so there's not much to gain by widening (one of) them further.  And if a revision is all new files you can quickly switch to single-column mode via the "margin notch" popup.  But given that this has come up twice now I assume I'm missing something -- what is it?

**Comment by ryan-williams** [comment]
> if you're working in side-by-side mode then you've set up your window to to comfortably fit the code into the columns

Nah, either my editor (and code-style-guide line-length limit) must be capped at ~40% of my screen, or I can't have two of them side by side in reviewable.  Look at this full-screen review on my laptop:

![](http://f.cl.ly/items/0J0W3c2c3M3c1k1C1M11/Screen%20Shot%202015-07-29%20at%201.28.55%20AM.png)

I can't make my browser any wider on this machine.

> you can quickly switch to single-column mode via the "margin notch" popup

I believe that this exists. I've never seen it and couldn't find it just now when I looked around the page and hotkeys dialog. Anyway, why make me tell reviewable to not waste the 50% space on emptiness?

> if a revision is all new files 

yea but what if it's only *some* new files?

I guess I don't see the downside, and there is obvious (to me at least) upside.

**Comment by Walkman100** [comment]
> I believe that this exists. I've never seen it and couldn't find it just now when I looked around the page and hotkeys dialog.

You're contradicting yourself there.

**Comment by pkaminski** [comment]
I see, so you prefer side-by-side diffs sufficiently that you're willing to deal with wrapped lines, but would obviously rather not do so unless it's necessary.  That makes sense, but I didn't plan for it since my personal preference rates unwrapped lines over side-by-side diffs, so given a lack of screen space I'd force single-column diffs instead.  Let met see what I can do -- the diff layout has a lot of conflicting demands on it and this breaks an assumption that all files have the same layout at any given time, so it may not be possible.

For the record, the single-column mode switch is here:
![image](https://cloud.githubusercontent.com/assets/1646896/8980389/1b3c1a7a-3665-11e5-9436-7443003eb710.png)

**Comment by ryan-williams** [comment]
Cool, that makes sense @pkaminski, thanks

**Comment by dbertram** [comment]
Sorry, I was away last week otherwise I wouldn't have commented sooner.

Basically, what @pkaminski said: I generally prefer side-by-side diffs, and I'd rather not have to switch diff modes file-by-file. Especially if I'm going to be hopping back and forth between newly added/deleted files and others that were modified.

While I sometimes *do* have more screen real estate available to avoid wrapping, I'm almost always using less for a reason (e.g., so I can have my editor open or the application whose code I'm reviewing visible at the same time).

**Comment by pkaminski** [comment]
I managed to shoehorn this feature in -- it'll squeeze the empty column down, but not eliminate it completely as that would be even more difficult.  Note that this only takes effect if your margin is set to 'auto'.  Please let me know if you spot any visual anomalies.

**Comment by ryan-williams** [comment]
Just tried it out, really cool, thanks @pkaminski!
