### ISSUE TITLE
Links from github comments don't go anywhere

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#140]
I visited the links in https://github.com/servo/servo/pull/6741 and they all seem to take me to the top of the review, and not to any particular revision.

**Comment by jdm** [comment]
In fact viewing that review shows me a bunch of comments that aren't associated with any particular file it seems :/

**Comment by pkaminski** [comment]
Discussion links were broken for three separate reasons, some new some old.  Sorry -- all fixed now.

Can you expand on your second comment about comments not being associated with any particular file?  When a nil diff range is automatically picked for a file (because it's not in your next review set), comments will show up unattached to any line (since there's no diff) with a red corner.  This is expected, but could probably be improved by picking a more appropriate diff when arriving at the page via a discussion link.  Is that what you mean?

**Comment by jdm** [comment]
I was wrong about them not being associated with a file, but in the default limbo revision that was selected, all of the comments were associated with a file that wasn't present and it looked super confusing.

**Comment by pkaminski** [comment]
OK, makes sense.  Is the current behavior fine, or do you think it could be improved further?  I'm thinking maybe when you arrive at the page via a discussion link, the auto-diff should be set to base vs the revision that comment was made on.  Don't know if I should set that for all files or just the discussion's file to improve performance (at the expense of perhaps looking more confusing since all the other files will be hidden).  Thoughts?

**Comment by pkaminski** [comment]
When following a comment link, the app will now automatically select the best revision of the target file and nil out the diffs of all the others, to optimize how fast the comment appears.

**Comment by jdm** [comment]
Makes sense. Thanks!
