### ISSUE TITLE
Click Reviewable links in PR doesn't let you see comments

### ISSUE THREAD

**Issue by dzbarsky** [Reviewable/Reviewable#143]
I couldn't get Ms2ger's review in https://github.com/servo/servo/pull/6880 to show me the actual comments.
This used to work (a few days ago?)

**Comment by pkaminski** [comment]
It's worse than that -- the discussions are gone from the review.  :scream:  Investigating this as high priority.

**Comment by pkaminski** [comment]
My current hypothesis is that an error occurred between publishing @ms2ger's comments to GitHub and committing them to Reviewable -- this is not (and cannot be made) atomic, unfortunately.  @ms2ger, did you run into any issues when publishing your comments on servo/servo#6880?

**Comment by Ms2ger** [comment]
I don't recall anything special, but my connection has been pretty crappy lately.

**Comment by pkaminski** [comment]
Yeah, I'm  pretty sure that's what happened -- I saw the draft comments still sitting in your personal area in the datastore.  I'm a bit worried that you didn't notice anything unusual, since the toolbar should've turned into a big red error message when the publishing failed.  Looks like you resent everything now, though (resulting in a duplicate message in GitHub), and all the links are working.

Sorry for the trouble, but hopefully this situation is rare enough to not become a major pain since I can't think of any way to mitigate it.  :disappointed:
