### ISSUE TITLE
Request: Ability to hide ALL whitespace changes

### ISSUE THREAD

**Issue by veqryn** [Reviewable/Reviewable#144]
I have a particularly long pull request to review, that should be only formatting changes.  (You can take a look here: https://reviewable.io/reviews/triplea-game/triplea/23#-).  When whitespace is hidden, the actual amount of change in the files is quite minimal.

When trying to review it, your system automatically hides whitespace changes that are far away from any actual code changes, but it still shows whitespace changes that are close by, by highlighting the change in red.

So how do I hide this in Reviewable.io?  I would like to hide ALL whitespace changes.  Do not highlight in red, do not show it to me, they are incredibly distracting.

I've been told there is not an option for this, so I would like to request it.

**Comment by veqryn** [comment]
GitHub allows me to hide the whitespace using the semi-secret parameter 'w=1', but then GitHub has other issues, namely that they limit the diff they show you to the top 10 or 20 files, and refuse to show you the rest.  You can see the difference here:
https://github.com/triplea-game/triplea/commit/868d1da2d179dc0bc5fb30ac8db7e83cfefd4dc4
vs: https://github.com/triplea-game/triplea/commit/868d1da2d179dc0bc5fb30ac8db7e83cfefd4dc4?w=1

**Comment by Walkman100** [comment]
Woah, that parameter `w=1` is really useful, thanks for sharing it.

**Comment by veqryn** [comment]
I really can't beg for this enough.
Reviewable.io just isn't useful enough until this gets added as an option, if not the default behavior (you already hide whitespace elsewhere, this really should be the default).

**Comment by pkaminski** [comment]
I intend to get to this soon, along with #94 and #136.  I'm curious, though: besides the giant reformat-the-world commit (which is hopefully a one-off event), how do you end up with lots of whitespace deltas in your team's PRs?

**Comment by pkaminski** [comment]
OK, I've retuned the stylesheets so that whitespace-delta-only lines (as well as base-delta-only lines) now use very weak highlighting and show an informative symbol in the gutter.  If this is still too much, you can tune it further using a custom stylesheet (which Reviewable will load and apply for you) -- let me know if you need a hand with that.

I also added in code so that leading whitespace diffs won't be classified as "whitespace only" in languages where indentation is significant (Python, Haskell, YAML).

Let me know if this addresses your concerns.

**Comment by veqryn** [comment]
Thanks, this should be pretty cool!
Two questions about these new custom css sheets:
1. Which one does reviewable.io use by default, and what is the actual link to it?
2. I tried a few from the directory you listed in the faq, and none of them seem to change anything.  I am probably doing something wrong, but not sure what.  For example, trying to use this stylesheet does not work: https://raw.githubusercontent.com/isagalaev/highlight.js/master/src/styles/darkula.css

**Comment by pkaminski** [comment]
Note that the delta coloring is separate from the syntax highlighting.  The new delta coloring (weaker colors for whitespace and base changes) is the default no matter what syntax highlighting you're using.  I can give you the classes needed to tweak delta coloring if you'd like -- they're not documented and subject to change without notice, but in practice have been quite stable.

For the syntax highlighting, Reviewable uses an inlined copy of the `color-brewer` style.  If it was loading it externally, though, the URL would be `https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.8.0/styles/color-brewer.min.css`.  Requesting the stylesheet directly from GitHub won't work because it gets served as `text/plain`, and for security reasons browsers will only render it if it's `style/css`, so use the CDN or take advantage of https://rawgit.com/.  This is mentioned in the FAQ, but not in the (space-limited) help popup.

**Comment by veqryn** [comment]
Yes please, I'd definitely like to change the delta coloring.

**Comment by pkaminski** [comment]
OK, the relevant styles are:
```
.diff.line.base:not(.keep) .line.wrapper:not(.empty) .left.line.content,
.diff.line.whitespace:not(.keep) .line.wrapper:not(.empty) .left.line.content {
  background-color: #FFF7F7;  /* rgba(91, 220, 114, 0.05) on white */
}
.diff.line.base .left.line.content .delta, .diff.line.whitespace .left.line.content .delta {
  background-color: rgba(240, 92, 92, 0.05);
}
.one.column.diff .diff.line.base .left.line.content .delta,
.one.column.diff .diff.line.whitespace .left.line.content .delta {
  background-color: rgba(240, 92, 92, 0.15);
}

.diff.line.base:not(.keep) .line.wrapper:not(.empty) .right.line.content,
.diff.line.whitespace:not(.keep) .line.wrapper:not(.empty) .right.line.content {
  background-color: #EFFCF1;  /* rgba(91, 220, 114, 0.05) on white */
}
.diff.line.base .right.line.content .delta, .diff.line.whitespace .right.line.content .delta {
  background-color: rgba(91, 220, 114, 0.05);
}
.one.column.diff .diff.line.base .right.line.content .delta,
.one.column.diff .diff.line.whitespace .right.line.content .delta {
  background-color: rgba(91, 220, 114, 0.15);
}
```

Tweak as much as you'd like, though you might need to drop some `!important`s in there.  To make all the whitespace highlighting go away completely, this should do the trick (but not tested):

```
.diff.line.whitespace:not(.keep) .line.wrapper:not(.empty) .line.content {
  background-color: white !important;
}
.diff.line.whitespace .line.content .delta {
  background-color: transparent !important;
}
```

**Comment by veqryn** [comment]
Looks like it works.
Thank you very much!

**Comment by pkaminski** [comment]
Excellent, closing.  :smile:
