### ISSUE TITLE
30-day trial expired after one day?

### ISSUE THREAD

**Issue by ryan-williams** [Reviewable/Reviewable#151]
I believe I started some 30-day clock for https://github.com/hammerlab/internal-tools yesterday, but @armish is unable to see the review today:

![screen shot 2015-08-21 at 5 13 52 pm](https://cloud.githubusercontent.com/assets/465045/9419362/09016434-4829-11e5-85e8-18f294efc9df.png)

**Comment by armish** [comment]
just a quick update on this: this time, I was able to see the review and even post a comment there, but this message is still being shown at the bottom of the page.

**Comment by pkaminski** [comment]
@ryan-williams, your trial is good until Sept 19th, no worries.  The message is showing up "correctly" because the trial is for yourself only (not @armish), but it's clearly inappropriate so I'm going to massage the logic a bit.  In the meantime, it shouldn't prevent anyone from working on the review (only review creation is gated on subscription), or if you'd like it to go away immediately you can switch your subscription to any of the paid plans (no credit card required), which will make the trial apply to the whole organization.

Apologies for the confusion.

**Comment by pkaminski** [comment]
This should be fixed now.  I also took this opportunity to make a dent in the backlog of subscription-related features, one of which is that viewing a review may now also being an auto trial (and even if not, will start counting trial days).

Let me know if you spot any other weirdness!
