### ISSUE TITLE
Set GitHub commit status to success when reviewed

### ISSUE THREAD

**Issue by Mikulas** [Reviewable/Reviewable#159]
> Could you please add status success when code is reviewed? Would prevent us from merging unreviewed content.

I'm thinking `success` when all files are reviewed and there are no outstanding comments, `pending` otherwise.

**Comment by UberMouse** [comment]
:+1: just had a look to see if this was supported, but it doesn't seem like it. I would very much like to enforce that code review must be done to merge pull requests so I hope this gets implemented.

**Comment by pkaminski** [comment]
Yup, I'll be looking into this soon.  Just got a few higher-priority items to take care of first...

**Comment by UberMouse** [comment]
Excellent! Looking forward to it.

**Comment by jhoos** [comment]
:+1: This is the one neat thing ReviewNinja does that I liked (I far prefer reviewable.io so far aside from that), and it'll be really powerful when GitHub releases their new [branch protection feature](https://github.com/blog/2051-protected-branches-and-required-status-checks) that will allow you to enforce that PRs can't be merged if the Status API fails them.

**Comment by UberMouse** [comment]
Just wanted to check in on this @pkaminski

**Comment by pkaminski** [comment]
I've been building up towards with other features that give you more control over when a review is considered complete.  It's now at the top of the queue.

**Comment by UberMouse** [comment]
Awesome, great to hear.

**Comment by pkaminski** [comment]
This feature is now live.  Note that it's only active for connected repos (not ad-hoc reviews), and will only start setting the status once the review has been visited at least once by a signed-in user with the latest version of the client.  (The former is to ensure that Reviewable can update the status even if it changes due to actions by a user without push permissions, and the latter to support selective use of Reviewable, so that PRs where you choose not to use Reviewable aren't polluted with an extraneous status.)

Another tricky bit is that, due to Reviewable's architecture, I've had to implement the completion-detection code separately on the client and server.  As the data structure differs between them it's possible that a bug in my code will cause them to disagree on the answer in corner cases.  Please let me know if you spot any discrepancies between the info in the status and that displayed in the client's toolbar and I'll fix it right away.  Thanks!

**Comment by UberMouse** [comment]
Great! Tried it out before, just what I was after. If I encounter any bugs I'll make sure to raise an issue.

Thanks for doing this!

**Comment by Mikulas** [comment]
Good job, thank you!

> so that PRs where you choose not to use Reviewable aren't polluted with an extraneous status

While still useful and not a deal breaker for us, our developers including myself are likely to skip code review if not strictly enforced for all PRs. I understand this might not be the most common usecase, but I would very much welcome an option for that.

**Comment by pkaminski** [comment]
I forgot to mention that that use case works fine as well:  if you protect your branch and make the `code-review/reviewable` status check required, you won't be able to merge the branch when the status check is missing.

**Comment by Mikulas** [comment]
Oh right that is awesome! Thanks :star2:
