### ISSUE TITLE
F1/? icons can be jittery

### ISSUE THREAD

**Issue by mmlb** [Reviewable/Reviewable#162]
This is a minor nit, but when I stop scrolling with the touchpad and happen to land on a line within a change and do not remove my fingers from the touchpad the `F1`/`?` icons happen toggle shown/hidden breaking my focus.

I think this happens from minor position fluctuations, though the mouse icon is not moving around.

Like I said, this is a minor nit where I can get around it by removing my fingers, but that may take a while to learn... :/

**Comment by mmlb** [comment]
Also maybe they should not hide when the mouse is moving. When ever I move the mouse from one line of code to another I get a distracting flash at the edge of my vision, then a short time later another distraction... :(

**Comment by pkaminski** [comment]
Thanks for reporting these issues; I've made a first pass at fixing them.  When scrolling the page, it turns out that Chrome emits some bogus `mousemove` events, which I now filter out.  So the indicator should only pop up when you actually move the mouse now.  I also added a bit of jitter tolerance, but I don't think that's what you were running into.

Can you clarify which indicator you find disruptive?  The one that pops up next to your mouse cursor, or the one in the lower-right corner?  If it's the former, interacting with the control (or looking at the help) will move the indicator for that widget to the lower-right corner forevermore.  If the latter, then I have some more work to do, since it was meant to be completely undistracting.  Thanks.

**Comment by pkaminski** [comment]
One more question: do you have transition animations turned off by any chance?

**Comment by mmlb** [comment]
All fixed. The distracting one was the one at the bottom right of the page, but it has been fixed now. I think the minute fluctuations when I kept two fingers on the mouse pad had chrome emitting those bogus `mousemove` events, which made those icons go into a spasm.

I hadn't run into the icon right next to the mouse until today when I notice the white-space icon. It seemed a little off to me. The icons were much bigger than my mouse icon and very close, which looked weird to me. That's probably just my own setup though.

I do have transitions turned off, can't remember why right now.

**Comment by pkaminski** [comment]
Sounds good.  I also tweaked the code to fade the indicator in/out discreetly even with transitions turned off, deciding that those shouldn't count as animations after all.

The popup help icon is purposely big and close the mouse cursor, so that you can move over to click it before it disappears after a mousemove.
