### ISSUE TITLE
Extra deletions showing in a diff not in the changeset

### ISSUE THREAD

**Issue by larsbergstrom** [Reviewable/Reviewable#163]
https://github.com/servo/servo/pull/7581

There are three files listed as deleted by reviewable, but they are not deleted in the GH diff.

**Comment by pkaminski** [comment]
Uh-oh, looks like Reviewable has run into hardcoded size limitations in GitHub's API.  I'll need to devise a way to work around them (and no, it's not as simple as paging :disappointed:).  This will affect all servo PRs so I'll do my best to expedite the fix.

**Comment by pkaminski** [comment]
So it turns out that my code was blissfully unaware that data was being truncated by GitHub.  I've fixed this, and implemented a workaround to fetch large trees in smaller pieces (and more slowly).  Also, if it  runs into truncation that it can't work around, the PR sync will fail rather than producing a corrupted review.

I've fixed the review for servo/servo#7581 by hand (breaking the "revisions are immutable" rule in the process), but based on how badly the servo tree was truncated this might have been going on for a while.  :disappointed:  Please let me know if you spot any other reviews that need fixing, or observe a recurrence.  Sorry, and thanks!

**Comment by larsbergstrom** [comment]
@pkaminski Thanks for handling it so quickly! I'll tell the team to keep an eye out for similar issues.
