### ISSUE TITLE
Reviewable detecting a textual Makefile.in as binary

### ISSUE THREAD

**Issue by larsbergstrom** [Reviewable/Reviewable#166]
In the review below, reviewable thinks that the file scripts/ots-autoconf-snapshot/Makefile.in is binary and doesn't show the diff:
https://reviewable.io/reviews/servo/fontsan/5

Not a blocker at all, but thought I'd report it.

**Comment by pkaminski** [comment]
Yeah, that file has raw escape characters in it.  I could easily relax the binary detector to allow them, but that seems like a bad idea since they won't show up in the diff.  Perhaps it would be best to replace them with explicit character escape sequences (e.g., \e or \033, or whatever works in that context) if that's possible?

**Comment by larsbergstrom** [comment]
@pkaminski Aha! Good catch - I didn't notice. User error this time :-)
