### ISSUE TITLE
Awareness of @homu bot

### ISSUE THREAD

**Issue by Valloric** [Reviewable/Reviewable#169]
We're using [homu.io](http://homu.io/) for [YouCompleteMe](https://github.com/Valloric/YouCompleteMe) and [ycmd](https://github.com/Valloric/ycmd).

For now, the only feature I'd like to see is that Reviewable ignores comments made by the @homu bot ([example](https://github.com/Valloric/YouCompleteMe/pull/1698#issuecomment-142160115)). Otherwise, Reviewable gets confused and thinks that discussion is ongoing on a PR.

**Comment by pkaminski** [comment]
Top-level comments never count as "unresolved" in Reviewable, so is the only problem that the unread comment count goes up (and goes red) when @homu posts a comment?  I can certainly see how that could be annoying, but on the other hand I'm not sure you'd want to suppress all of @homu's messages.  For example, if a build fails, presumably you'd want to see an unread message on the review so you'd know to go investigate.

Is it possible to make @homu less chatty?  If it only posted when the test succeeded (and the PR was merged) or failed, then you'd only see a red discussion counter in the failure case on your Reviewable dashboard since merged PRs don't show counters.

What do you think?

**Comment by pkaminski** [comment]
Also, @larsbergstrom, it looks like `servo` uses a very similar bot.  What do you think about this issue?

**Comment by Valloric** [comment]
> so is the only problem that the unread comment count goes up (and goes red) when @homu posts a comment? 

Yeah, it makes me think "I need to go look at that PR, someone is commenting." To be fair, GitHub does the same thing by sending notifications for homu's comments; I'd love it if it didn't.

> For example, if a build fails, presumably you'd want to see an unread message on the review so you'd know to go investigate.

That's a solid point. Homu's messages follow pre-set patterns, so if that message could still bump the comment count, that would be great. But if I had to pick between "no notifications for homu's comments" and "notifications for all of homu's comments," I'd pick the former.

> Is it possible to make @homu less chatty?

From configuration, no. Note that we didn't write it, we merely use it. It comes from the Rust community.

**Comment by Ms2ger** [comment]
From my experience in Servo, it offends my sensibilities a little bit, but not enough to complain about it. I don't use the dashboard at all, though, even if I'd like to have a useful dashboard.

**Comment by larsbergstrom** [comment]
Yeah, it seems most people don't really notice the need to acknowledge these comments because we don't use the dashboard and the comments only come in after an "r+" is sent (which goes to the autolander) or when the PR has bitrotted and is unmergeable, which is going to result in another round of reviews anyway.

**Comment by pkaminski** [comment]
OK, thanks all.  I poked around the code a bit and it turns out that this would be difficult to implement, because the "is discussion unreplied" algorithm doesn't have access to comment metadata (it's not even loaded on the dashboard page), and the discussion-level metadata is tied into tracking of the old/new comments split (which I wouldn't want to mess with).  It would also be problematic to make this a per-repo setting (or worse, per-user setting), so I'd need to be sure any change had widespread buy-in and wouldn't be too surprising.

Given all that, I'm going to mark as won't fix for now, sorry.  :(  You may want to poke at the Homu team to see if they're willing to make it less spammy, either by default or via config.  It looks like it might be "just" a question of having `add_comment` in https://github.com/barosl/homu/blob/master/homu/main.py take an extra `help_me_human` flag, and noop'ing if the flag is false (and the right config option is set, if that approach is taken).  I actually think this would be a good improvement for Homu overall, even for people who don't use Reviewable.

And @Ms2ger, I'd like to know what would make a useful dashboard for you!
