### ISSUE TITLE
Renaming a GitHub repo during a review results in losing all Reviewable data for that review

### ISSUE THREAD

**Issue by tavinathanson** [Reviewable/Reviewable#170]
We started a review on the `gtftools` repo, then renamed it to `gtfparse` during the review. And now:

* https://reviewable.io/reviews/hammerlab/gtftools/1 shows a strange API-related error
* https://reviewable.io/reviews/hammerlab/gtfparse/1 works, but loses all the original review/comment data

You can see original review comments on GitHub: https://github.com/hammerlab/gtfparse/pull/1

**Comment by pkaminski** [comment]
Sorry about that -- Reviewable indeed tends to fall over when a repo (or organization) is renamed.  I recently discovered some undocumented GitHub APIs that should allow me to fix this but it's going to take a lot of work.

In the meantime, I manually migrated the review from `gtftools` to `gtfparse`.  Please let me know if you notice any issues, and note that you'll need to connect the renamed repo from the Repositories page again, as it doesn't inherit the old repo's settings.

I'll keep this issue open to track progress on an automated solution to renames.

**Comment by tavinathanson** [comment]
Thanks Piotr!

**Comment by pkaminski** [comment]
Reviewable will now automatically detect repo (and organization) renames and alert me, though with some (theoretically unbounded) latency since GitHub doesn't fire an event.  I can then run a supervised script to automatically (fingers crossed) move data around, and the updated client will load reviews correctly through either the old or new URL.  If the renaming detection and data move process prove reliable enough I'll automate this fully, but I'm sure there's some corner cases to be flushed out first.

Good enough for now, though.  Closing.
