### ISSUE TITLE
Always "include changes in files previously reviewed only by others"

### ISSUE THREAD

**Issue by Valloric** [Reviewable/Reviewable#175]
The first thing I do on every review is check that option and then click "show unreviewed diffs." Just because someone else reviewed parts of the PR doesn't mean I don't want to review it. 

I'd love it if there were an option for me to _always_ have this checked (and not have to also click "show unreviewed diffs").

**Comment by pkaminski** [comment]
Yeah, I didn't do anything like that originally because honestly I wasn't even sure anybody would use the toggle.  Most teams I know tend to "split up" multi-party reviews by file type or area of specialization.

But as of now, the last value you set for the checkbox will be automatically applied to all future reviews.  I didn't spend a lot of time testing the mechanism so please let me know if it fails in some corner cases (race conditions, etc.).  Note that it won't apply retroactively to reviews you've already visited.

**Comment by Valloric** [comment]
Holy crap, you're fast! Thanks for the change! I'll be sure to file bugs if I encounter any.
