### ISSUE TITLE
Completion when typing GitHub usernames

### ISSUE THREAD

**Issue by Valloric** [Reviewable/Reviewable#180]
There's no username completion after typing `@` like there is on GitHub. It would be nice to have this.

I love Reviewable so much! :)

**Comment by pkaminski** [comment]
Hey @Valloric, @-completion should work.  Which repo are you having trouble in?

**Comment by Valloric** [comment]
The repo is [Valloric/ycmd](https://github.com/Valloric/ycmd).

I just tried typing a username in a Reviewable review and @-completion did indeed work. Weird. I'm 100% sure it was not working this morning.

Anyway, thanks for working on Reviewable and sorry for the noise!

**Comment by pkaminski** [comment]
No problem -- the autocompletion is done in the browser, and prefetches a list of potential users shortly after page load.  If it fails, it does so silently at the moment, so if you find @-completion not working you can always reload the page.  It's supposed to fail rarely enough that this is not really a problem but please let me know if you find otherwise.
