### ISSUE TITLE
Hide F1/? hint when user starts typing

### ISSUE THREAD

**Issue by bpflanz-adfin** [Reviewable/Reviewable#181]
I find that invariably when I click a line to add a comment, the F1/? hint hovers directly over where the first line is typed (and funnily enough, it seems always to be right over the place where I've just typoed, although this is likely just confirmation bias).
It would be helpful if the F1/? hint were hidden if it's on the textbox that the user is typing in (until the mouse is moved again), much like one's OS hides the mouse pointer over text boxes.

**Comment by pkaminski** [comment]
Thanks for spotting this!  So normally the annoying F1/? hint is supposed to turn itself off (and move to the lower-right corner of the screen) once you've "used" the control, but I screwed that up for the draft text box.  It's now fixed, and will turn off automatically once you've typed a suitably long message.  Of course, an alternative course of action is always to click on it, since that'll make it stop showing up too.  :)
