### ISSUE TITLE
Up/down don't work in new comment box

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#188]
In Firefox nightly this is broken for me. I haven't tried other versions of Firefox or other browsers.

**Comment by jdm** [comment]
Actually they seem to work after I remove focus from the textbox and then focus it again.

**Comment by pkaminski** [comment]
I've been unable to reproduce this in Firefox 42.0b8 on Windows 7 or in Firefox 42.0b7 on El Capitan.  So this looks like a regression in the FF nightlies, and as a rule I don't try to address issues in nightlies (and only reluctantly in betas) since they're too much of a moving target.  Please reopen if you observe the behavior in a more mainstream version... Thanks.
