### ISSUE TITLE
github error trying to publish review

### ISSUE THREAD

**Issue by rbtcollins** [Reviewable/Reviewable#198]

**Comment by rbtcollins** [comment]
![screenshot from 2015-11-04 15 04 26](https://cloud.githubusercontent.com/assets/499678/10927563/9a0f44fc-8305-11e5-9799-f53a1a0368b8.png)

**Comment by pkaminski** [comment]
This is very likely due to [third party application restrictions](https://help.github.com/articles/about-third-party-application-restrictions/) being set up in the `pypa` organization.  Unfortunately, the API purposely returns generic errors when an app isn't authorized due to "privacy" concerns.  I've complained to GitHub about this repeatedly to no avail.

If this is indeed the problem you'll need to [request access](https://help.github.com/articles/requesting-organization-approval-for-your-authorized-applications/) for Reviewable then get an organization owner to [approve it](https://help.github.com/articles/approving-third-party-applications-for-your-organization/).

**Comment by pkaminski** [comment]
Can you confirm that third-party app restrictions were indeed the cause and that the issue is resolved?  Thanks.

**Comment by rbtcollins** [comment]
Well its not enabled on that repo; I'm just seeking permission at the moment

On 5 November 2015 at 07:33, Piotr Kaminski <notifications@github.com>
wrote:

> Can you confirm that third-party app restrictions were indeed the cause
> and that the issue is resolved? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/198#issuecomment-153822365>
> .
>



-- 
Robert Collins <rbtcollins@hp.com>
Distinguished Technologist
HP Converged Cloud

**Comment by rbtcollins** [comment]
Yes, that was it.
