### ISSUE TITLE
Show line numbers in diffs

### ISSUE THREAD

**Issue by ihodes** [Reviewable/Reviewable#20]
It's more difficult than it ought to be to track down where in the code I should navigate to without line numbers on the diffs. 

Would adding them be reasonable?

**Comment by yaronyg** [comment]
I could really use line numbers in the files. The reason is that it is pretty common for me to be looking at a file under review in the editor, notice something wrong and want to switch from the editor back to reviewable in order to comment on that line. But since there are no line numbers there is no easy way for me to find what I comment on. Line numbers would be especially useful when I notice something that isn't actually part of the current review. In that case not only do I have to find where in the review the line is but I have to keep hitting expand until I see it. If I had line numbers then I could automatically hit expand until the right line showed up

I suppose it's a good thing that this issue is probably the most annoying thing to me about using reviewable. :)

**Comment by gregakinman** [comment]
Hey @pkaminski, do you have an updated link to the user guide since the wiki is gone now? Thanks in advance!

**Comment by pkaminski** [comment]
Good point, I updated the comment to point to https://docs.reviewable.io/#/accountsettings?id=line-link-template instead.  Thanks!
