### ISSUE TITLE
Set a default state for "overlap other reviewers" toggle, per repo

### ISSUE THREAD

**Issue by rbtcollins** [Reviewable/Reviewable#200]
I found 'last reviewed' is confusing because last reviewed is a global, not a per-user thing. Most orgs I'm in have each reviewer review the full diff, not just the changes since the last review by anyone. One way to improve this would be to make the reviewed flag be maintained per reviewer, so that I can see what I havent' reviewed, vs what some-random-other-person has reviewed.

**Comment by pkaminski** [comment]
This is actually tracked per-reviewer, and 'last reviewed' refers to the revision that you last reviewed.  The display of last-reviewed marks (in the file matrix) is purposely simplified to avoid overwhelming the entire table with eye icons, but your own latest mark for each file is always shown in black and, if somebody else's mark is more recent, it'll be shown in grey.  (Green marks are your draft marks awaiting publication.)

If that description doesn't match what you're experiencing, please point me to a specific review, list the affected reviewers, and the expected / actual behavior so that I can debug.  Thanks!

**Comment by rbtcollins** [comment]
When I first opened up https://reviewable.io/reviews/testing-cabal/testtools/157 I was shown only the incremental changes from r2, and had to click something ( I don't entirely know what, since I don't understand reviewable.io yet ) eventually I got it show me everything.

**Comment by pkaminski** [comment]
Yeah, what you probably ran into is the default "one reviewer per file" guidance.  In my experience, many organizations will split reviews among multiple reviewers, either by module or file type.  To facilitate this, once a file has been reviewed by a user, Reviewable won't offer it for review by others by default.  This is independent of the 'last reviewed' tracking and can be changed by toggling the checkbox in the Changes box on top.  The checkbox is "sticky" so you should only need to do it once if your organization's modus operandi is to have multiple reviewers per file.

**Comment by rbtcollins** [comment]
So if I change it, its changed for the other reviewers in our org? What is the checkbox labelled?

**Comment by pkaminski** [comment]
Apologies, I should've posted a screenshot:
![image](https://cloud.githubusercontent.com/assets/1646896/10929447/6218d632-8268-11e5-8900-f65ec68c55b1.png)
The checkbox is at the bottom, "include changes in files previously reviewed only by others".

The setting is personal, so your request for setting an organizational default is still pertinent.  If checking this for yourself makes things work as expected then I propose we turn this issue into an RFE for a repo-level (or org-level?) default setting.  As with most new settings, it will likely start out as a hidden, "open an issue to flip it" flag, and if it proves popular enough I'll introduce some UI for it.

**Comment by rbtcollins** [comment]
Thanks. If I may suggest, the intro docs should explain the defaults - because while you may have encountered many orgs that do split like that, many do not (the majority in my experience), and I think it would reduce friction if folk knew what to expect.

FWIW, even those orgs that do split things up by teams do necessarily review the way this option works - its more like there are N concurrent reviews, each of which may be done by several people who will want their own tracking, but are only reviewing some subset of the code changes that are happening.

**Comment by pkaminski** [comment]
It's hard to gauge how much should be put into an intro...  I opted to leave this feature out since most reviews are not multi-party, and once a user has learned how to control the diff bounds (which is far more important) they can easily override the diffs being shown.  The checkbox only affects the diffs shown when you click the "show unreviewed diffs" button (and the initial diffs when you load the page, which are the same).

And yes, the division of labor in multi-party reviews can get arbitrarily complex...  Short of reading minds (or letting orgs set custom rules -- which I'm working on!), the default "don't show changes in file previously reviewed only by others" mode actually gets you pretty far.  Although a file won't be proposed for your review if somebody else has already started on it, if you go ahead and review it (mark it) anyway, it'll be proposed for both you and the other person from then on.  Once you're comfortable with setting diff bounds in the file matrix it comes down to a single click-and-drag when you first start the review, though I'll readily admit this workflow is not obvious.  (And of course, as mentioned before, each reviewer gets their own tracking of what they've already reviewed, no matter what mode they're in.)

**Comment by pkaminski** [comment]
Please let me know if you're interested in a per-repo default for this flag, and if so which repos you'd like me to set it on.  Thanks.

**Comment by rbtcollins** [comment]
Yes please! Everything in the testing-cabal org.

**Comment by rbtcollins** [comment]
Also on the repos in the pypa org. Thanks!

**Comment by pkaminski** [comment]
OK, I implemented the feature and set the default to true for 3 repos in testing-cabal and 1 repo in pypa.  There may be more repos in those orgs, but Reviewable fetches the data lazily only when the first review is created in a repo.  Let me know if you need any more repos toggled after you've created a review in them.

Also note that the default will only be effective on reviews that a user hasn't yet seen (appearing on the dashboard counts as being seen too!).  And if a user ever toggles the checkbox manually, they'll set their own global default and ignore repo defaults from that point on.

**Comment by rbtcollins** [comment]
Awesome, thanks.
