### ISSUE TITLE
Resolve your own comments

### ISSUE THREAD

**Issue by jon-frankel** [Reviewable/Reviewable#203]
Maybe this is already possibly, but if so I can't figure out how to do in the UI. Sometimes I respond to an author just to say "okay" or "sounds good" instead of clicking the acknowledge button. Or maybe the last comment I made is no longer relevant. Is there a way to mark the discussion as resolved without requiring anyone else to click acknowledge?

**Comment by pkaminski** [comment]
In general, Reviewable implements a consensus model for resolving discussions: every participant in the discussion must acknowledge the latest comments.  However, there are some exceptions that may fit your needs:

1.  If you're the only person in the discussion (e.g., you just posted a comment and nobody replied yet), you can resolve it immediately with this button: 
![image](https://cloud.githubusercontent.com/assets/1646896/10979765/3c1ab5da-83b3-11e5-8070-0d177eb03f9c.png)

2.  If you're replying to a discussion you can mark your comment as "FYI only", either by beginning your message with "FYI" or "BTW", or by selecting the appropriate disposition from a pop-up menu at the bottom of the draft: 
![image](https://cloud.githubusercontent.com/assets/1646896/10979810/7250c9a0-83b3-11e5-8aef-1713bd8ecd7a.png)  <br>If there's only one other person in the discussion, this will also resolve it (otherwise, the rest of the participants will still need to acknowledge, or post their own FYI comments).

There are other valid reasons for wanting to resolve a discussion outright but they're not as common, and I hesitate to depart from the consensus model as it will allow discussions to "disappear" without a participant realizing it.  #182 is tracking this feature request but I haven't yet decided if/how to address it.  You may want to add your specific use cases there!  Thanks.

**Comment by jon-frankel** [comment]
Thanks for the quick and thorough response. I understand the reasoning behind the consensus model. I guess it may be a double-edged sword no matter what. The reason I asked about this is because I don't think other people want to be burdened with the need to go back in just to acknowledge a mostly content-free response. It's kind of like when I worked help desk, and people would reply to the help ticket with a thank you just because they're being nice and appreciative. But in fact, that reopens the ticket, which gives me another minute of work to get back into the system, find the ticket, deselect notifications, and finally re-close it again. Imagine that happens a dozen times a day and that's 15-30 minutes of lost productivity because of the graciousness of your users.

As for that drop down to make a comment informational only, I was able to set the default to require a response by the PR author. But your response here seems to indicate that I should be able to do this when I make a follow up comment, so that I can effectively close the discussion? If that were the case I think I would be fine with that workflow, but when I click that button, nothing happens and the comment box simply closes. Is that the expected behavior?

**Comment by pkaminski** [comment]
Yeah, the FYI setting is there precisely to address the "final thank you" use case.  The comment box is closing when you click on the button because it's empty, and an empty comment gets automatically deleted when it loses focus to keep things tidy.  Just start typing before you click the button (or, if you don't like taking your hands off the keybord, type "fyi" to switch modes then backspace).  I'll see if I can fix this behavior when you click the button but it's tricky, because the focus-loss event is async.

Also note that FYI messages will still show up as unreplied for the other person (since, presumably, you want them to read the thank you note!) but the discussion will remain resolved and won't prevent merging.

**Comment by jon-frankel** [comment]
Thanks, I see how that button works now. But I selected FYI Only and the
discussion is still not resolved.

**Comment by pkaminski** [comment]
Can you provide a link to the discussion?  How do you infer that it's not resolved?

**Comment by jon-frankel** [comment]
Sure, here's the link
https://reviewable.io/reviews/InternationalCodeCouncil/cdpaccess/1810#-K2J1qmIy5Cch3RRc1Mn

The comments icon is still gray, and has the same number next to it. Also
if I click on it, it takes me through all of the comments and brings me to
one that I had marked as FYI on the last comment.

**Comment by pkaminski** [comment]
Very odd as the underlying data looks correct.  Could you share a screenshot of the discussion's header?  (I can look at the data but not actually load the UI for a private review.)  Thanks.

**Comment by pkaminski** [comment]
Ah, no, I see what happened.  You replied twice, once with a "must respond" disposition, and once with "FYI".  The FYI messages doesn't supersede the previous one -- the PR author must still respond to it.

**Comment by jon-frankel** [comment]
Hmm...so I guess I just need to be careful when I say thanks and mark it as FYI. Since I set the default to require the author's response I'll need to manually choose FYI.

**Comment by pkaminski** [comment]
Yep, pretty much.  I'm certainly open to other ideas if you can think of a better way.

**Comment by pkaminski** [comment]
BTW, I fixed the empty draft deleting itself when you click on the disposition button.

**Comment by jon-frankel** [comment]
Thanks, awesome quick fix. I still wish I could resolve comments, though. I
understand your logic, but I think it might be a deal breaker for my
teammates. One teammate is saying that he can't just mark something
resolved, and that he has to actually type out a response, which makes it
even more onerous. I think it would really help the onboarding process, as
the person trying to persuade others to use the tool, if I could get as
much work out of their way as possible. Otherwise, they view it as needless
extra work and mental effort.

But I will say — end of the day, I absolutely needed this tool for a huge
PR I'm reviewing. So, thanks!

**Comment by pkaminski** [comment]
You mentioned that you had said the default to require a response from the author -- perhaps you should switch back to the original default of "acknowledge"?  Then authors wouldn't be forced to write a response (though note that hitting "Done" is just one click away and counts as a response) and they could either acknowledge (thus resolving the issue) or do nothing, in which case you could resolve it yourself (since you'd still be the sole participant).  If you want to drop by the chatroom I'd be happy to help you figure out a workflow that fits your team's needs.

**Comment by luxurystorecc1** [comment]
Chula Vista Vibes: Navigating Coastal Performance and Modern Athleticism
Chula Vista is a city of movement, sunshine, and a deep-rooted athletic pride. Whether you're at the elite training centers or the local courts, the gear needs to be top-tier. For sneaker enthusiasts in the 619, [iconic silhouette basketball sneakers for street style](https://www.google.com/search?q=https://www.jordan1s.com/) provide the necessary edge for any coastal adventure.

The passion for sports in Southern California is immense. Fans prioritize [official licensed professional league fan apparel](https://www.google.com/search?q=https://www.nflshopofficialonline-store.com/) to represent their teams during intense game days. To stand out in the local community, [personalized gridiron jerseys with custom names](https://www.google.com/search?q=https://www.nflshopofficialonline-store.com/collections/custom-nfl-jersey) have become a top choice for those wanting a unique fan identity.

Technical Luxury and Coastal Leisure
The lifestyle of Chula Vista is centered around the outdoors and water. High-end casual wear, specifically [premium moisture-wicking casual apparel](https://www.peter-milla.com/), is highly sought after for its versatility. For post-activity recovery near the bay, [premium slip-on designer athletic slides](https://www.yeezyboost-350.com/) offer the perfect blend of comfort and modern design.

Soccer’s popularity is massive here, with fans opting for [official national team soccer kits](https://www.google.com/search?q=https://www.soccerjerseysstore.com/collections/national-teams). Swimming is a critical part of the local culture, requiring [designer performance swimwear and accessories](https://www.swim-outlet.com/) for athletes at all levels.

For formal events along the coast, a [vibrant red cocktail dress for formal guests](https://www.swim-outlet.com/collections/dresses-red) is a seasonal favorite. For summer weddings, [stylish white bridal and formal dresses](https://www.google.com/search?q=https://www.cheapdressesformal.com/collections/dresses-white) are always in demand. Baseball fans show their pride with [fitted professional baseball league hats](https://www.google.com/search?q=https://www.cheapnfl-jerseys.com/collections/headwear-mlb-headwear), while the hockey spirit ensures [official league-certified hockey apparel and gear](https://www.custombaseball-jerseys.com/) is a winter staple.
