### ISSUE TITLE
Reviewable doesn't respect required status check settings from GitHub

### ISSUE THREAD

**Issue by donalt** [Reviewable/Reviewable#204]
We have several required commit checks for pull requests to protected branches. Reviewable does display the status of our Codacy code analysis check, but only once it is complete. Reviewable will allow us to merge while the Codacy check is pending, which is not the expected behaviour.

**Comment by pkaminski** [comment]
Could you please post a screenshot of what the Codacy status looks like in a GitHub PR while it's pending, and not showing up in Reviewable?

My suspicion is that this is a combination of two problems:  Codacy doesn't post a proper 'pending' status while running its analysis, and GitHub doesn't expose the 'required' status flag through its API so Reviewable doesn't know to expect the Codacy status.  I've already complained about the latter but you might want to add your voice at support@github.com so it'll get prioritized.

**Comment by donalt** [comment]
Hi, Piotr, thanks for the response.

Here is what the PR status checks look like:

![codacy_status](https://cloud.githubusercontent.com/assets/10187019/11032017/688cd4de-86d0-11e5-92b0-1c993c575384.png)

**Comment by imi44** [comment]
GitHub PR while it's pending, and not showing up in Reviewable?

My suspicion is that this is a combination of two problems: Codacy doesn't,!

**Comment by pkaminski** [comment]
Thanks @donalt, that confirms my original diagnosis.  I can think of 3 ways to fix it:

1.  Get Codacy to write an explicit 'pending' status to GitHub before starting their analysis.  This would narrow the window of vulnerability (probably to a few seconds) but not completely eliminate it.  If you open a feature request with them I'd be happy to jump in and explain exactly what's needed -- it shouldn't be difficult for them to add.

2.  Get GitHub to add an API through which Reviewable can retrieve a list of required statuses, and hence match GitHub's behavior.  They've promised such an API is coming... eventually.  You may be able to help them prioritize it by emailing support@github.com and referencing this issue.

3.  Reimplement the required status settings in Reviewable.  I'd really rather not do that, since it would just duplicate the feature from GitHub, you'd have to remember to change the setting in two places, and I'd have to tear it back out once the API is in place.

**Comment by donalt** [comment]
Thanks, Piotr. Codacy's feedback page is a mess, so I passed this on to them via Intercom. I'll see what they come back with.

**Comment by donalt** [comment]
This is the response from Codacy:

"We're always looking to improve time-to-analysis and improve our product based on our users feedback. At this point we have already this feature on the short term roadmap but I cannot at this point give you a roll out date.

We'll try to keep you up to date about this and as soon as it is available we'll let you know."

So no sign of a resolution there. I'll try emailing Github.

**Comment by pkaminski** [comment]
Hmm, it doesn't sound like Codacy quite understood the issue.  It's not about making their analysis faster, but rather about posting a "we're working on it" status as soon as possible (even if they don't start the analysis until later).

Let's see what GitHub says but I suspect we'll need more people to put any kind of pressure on them.

**Comment by donalt** [comment]
I think that was to placate me, as I also complained that their analysis is slow in another communication the day before.

**Comment by pkaminski** [comment]
GitHub just released the API -- I'll have it integrated tomorrow and this issue will be fixed.  :smile:

**Comment by imi44** [comment]
Thenth,

**Comment by donalt** [comment]
That's great, Piotr, thanks

**Comment by pkaminski** [comment]
This is now live, let me know if you're still having problems.
