### ISSUE TITLE
Show each commit when reviewing commits separately

### ISSUE THREAD

**Issue by nox** [Reviewable/Reviewable#205]
When reviewing commits separately, I can't find what is the actual commit I'm reviewing at any given moment. If the information is here, surely it is not presented very well.

**Comment by nox** [comment]
For example, https://github.com/servo/servo/pull/8355 includes 22 commits, and I have no idea where I am when I'm doing the review.

**Comment by pkaminski** [comment]
Hey Anthony, as you know Reviewable uses the "revision" abstraction both to save on screen space (commit shas are long, and descriptions even longer!) and because not everybody uses a "review each commit" strategy.  Knowing this, you should be able to spot "rN" in the toolbar, and if you click on it you'll see the mapping to commits.  Here's what it looks like for the review you linked to:

![image](https://cloud.githubusercontent.com/assets/1646896/11017882/9e3ff5d4-8563-11e5-80f2-636ca0f44480.png)

Furthermore, if you use the "Show next diff" button, the dropdown will stay open and you'll be able to immediately see the commit you're now reviewing.  The sha links to the commit on GitHub if you need more details.

Does this work for you?  Do you have any suggestions on how to improve it or make it more discoverable?  Thanks.

**Comment by nox** [comment]
I had not noticed there were various features available through that button, I guess that will do, thanks.

**Comment by nox** [comment]
When watching diff between rN and rN+1, Reviewable doesn't show the related commit.

**Comment by pkaminski** [comment]
Please provide a concrete example of this failure -- note that the sample screenshot above is a diff between r6 and r7 and the commit shows up fine.

**Comment by nox** [comment]
https://reviewable.io/reviews/servo/servo/8635

![capture d ecran 2015-11-21 a 11 01 41](https://cloud.githubusercontent.com/assets/123095/11317921/46ef68b4-903f-11e5-835b-da47178f40cc.png)

Looks like it gets confused because there are modified files that weren't modified in the previous revision.

**Comment by pkaminski** [comment]
Thanks, that's helpful.  I have an idea what the problem is. Could you please also post a screenshot of your file matrix in this state?  (It's specific to where you're currently at in the review process, so I can't easily reproduce it.)

**Comment by pkaminski** [comment]
Or are you just diffing r2 against r1?

**Comment by nox** [comment]
I just clicked the revision columns themselves.

![capture d ecran 2015-11-21 a 11 06 59](https://cloud.githubusercontent.com/assets/123095/11317947/00de0c9e-9040-11e5-88ec-52b6e0b63577.png)

**Comment by nox** [comment]
Yes, I am diffing r2 against r1.

**Comment by pkaminski** [comment]
Thanks, and apologies for the bug.  I think I have enough information to fix this -- I'll have a go at it tomorrow.  In the meantime, as a workaround the correct commit will show up in the dropdown when a diff has focus (its path is in the toolbar).

**Comment by nox** [comment]
No problem.

**Comment by pkaminski** [comment]
Fixed.  The PR you pointed to also revealed another bug in marking some renamed-with-changes files as changed in the file matrix -- thanks, and also fixed.
