### ISSUE TITLE
Allow to link merge button with another PR

### ISSUE THREAD

**Issue by ermshiperete** [Reviewable/Reviewable#206]
(Sorry, the subject line isn't very fitting, but I can't think of anything better ATM)

Occasionally we have two PRs in two different projects that need to be merged at the same time: e.g. when a library project creates a PR for a change of the API, and a PR in another project (that uses the library) implements the necessary changes for the modified library API. Ideally both PRs should be merged at the same time because one won't work without the other.

It would be great if those PRs could be linked so that the merge button only shows up when both PRs are ready to be merged.

**Comment by pkaminski** [comment]
That's an interesting use case, thanks for posting it.  I don't think it's a good fit for implementing directly in Reviewable, though, since it's not really specific to the review process.  Instead it would be better served with a separate app that posts its own status check to the PR: success if and only if all other checks (except its own) on all linked PRs are successful.  As a bonus, it could trigger a merge of all other PRs whenever one of them is merged.  I think that would a fun little app to write, and GitHub's API is clean enough that it shouldn't take more than a day or two if you scope its design specifically for your needs...
