### ISSUE TITLE
Merged and closed reviews are cluttering MyReviews page

### ISSUE THREAD

**Issue by sasha-s** [Reviewable/Reviewable#211]
I would like to be able to only see reviews that still need attention or all reviews that are still open.

**Comment by Mikulas** [comment]
:+1:

**Comment by pkaminski** [comment]
Could you send me a screenshot of your dashboard (support@reviewable.io) so I can see what cluttered means to you?  Also, do you usually keep your dashboard open in a long-lived tab, or do you open and close it (or navigate away from it) regularly?  Thanks.

**Comment by sasha-s** [comment]
Sent.
I usually open and navigate away (by clicking on one of the PRs) from it (I mapped "/" keyboard shortcut to go to the dashboard).

**Comment by pkaminski** [comment]
I've made the following changes that should address this issue without introducing new UI elements:
- I now show at most 3 closed PRs (instead of 5).
- You can now filter on `+open`, `+red` or `+mine` (must use exact spelling, cannot combine with other search terms).  They do what they say, you can see exact definition in help popup.
- The filter input field is autofocused on page load so you can apply a filter without taking your hands off the keyboard.

Does this work for you?

**Comment by sasha-s** [comment]
Thanks!

It almost works for me.
Would be great if filter became a part of url so I could bookmark it or use in key bindings.
Also, I rember opening a PR in reviewable by mistake(from a repo I am not tracking) and I could not remove it from the list.

**Comment by pkaminski** [comment]
Good idea, I added the current filter state to the URL hash and allowed you to use it in the navigation shortcuts.

As for accidentally becoming "involved" in a PR -- I'm not sure how that could've happened; in principle, just visiting a review should never do this.  If you can find the PR (or it happens again) please open a new issue so I can troubleshoot.  Thanks!
