### ISSUE TITLE
PRs ending in code block absorb the Reviewable image

### ISSUE THREAD

**Issue by redfern314** [Reviewable/Reviewable#215]
When PRs in github end in a code block, the "Review on Reviewable" image code appears to get [appended to the end of the code block] (http://i.imgur.com/Ot7nDF6.png) instead of being rendered correctly. Have not tested this extensively to confirm the cause, but it certainly looks like unintended behavior.

**Comment by pkaminski** [comment]
Hmm, this is certainly possible since markdown parsing is a black art, but the screenshot of the markdown that you posted seems all right to me.  I tried to reproduce with both a full code block and an inline code block at the end of the PR description and couldn't get anything to misbehave.  Is it possible that you have an unterminated code block in your PR description?

Could you please send a copy of the full markdown for the PR description, a screenshot of what the rendering looks like for you, and a pointer to the PR?  You can send to support@reviewable.io if this is in a private repo.  Thanks!

**Comment by pkaminski** [comment]
Without further details I'm going to assume this was an unterminated code block.  I could try to detect those and compensate, but I'm afraid that a simple regex matcher might have enough false positives (because Markdown) to negate the benefit of fixing the true ones.  And it's easy to fix this issue by hand anyway.

Please reopen if you have evidence that my guess as to the cause isn't correct.  Thanks!
