### ISSUE TITLE
Add option to hide renamed/moved files

### ISSUE THREAD

**Issue by PTDreamer** [Reviewable/Reviewable#216]
Renaming a directory containing hundreds of files makes the review being polluted with code that doesn't need reviewing.
Having the option to hide the renamed/moved files would be awesome.

**Comment by pkaminski** [comment]
That's a good idea, though it doesn't happen all that often.  Let me think a bit about how best to implement it.

**Comment by grant-hurley** [comment]
+1 as well. I'm reviewing a PR with approx 1500 file changes, of which about 1450 are because of a directory move :(

**Comment by clarissaj** [comment]
+1 in same situation as others above

**Comment by pkaminski** [comment]
Oh hey, it's been a few years since this got opened.  😄  I guess this should apply to files that were renamed but are otherwise unchanged, since otherwise guessing what changes are meaningful wouldn't be very reliable.  Filtering these files would be trivial but I'm not sure what UI would work well.  I'm thinking about putting such files into a group automatically, since those can already be collapsed or marked reviewed with one click, but it's not clear how that should interact with the users' own grouping logic (e.g., if the file is already grouped).

@cgiroux86, @anthonykawa, any thoughts?

BTW, you can implement this on your own repos right now with a custom completion condition that goes something like this:
```
_.forEach(review.files, file => {
  if (_.every(file.revisions, rev => rev.action === 'renamed')) file.group = 'Renamed';
});
return {files: review.files};
```

**Comment by pkaminski** [comment]
This is now implemented and automatic.  Enjoy!
