### ISSUE TITLE
When there are many revisions it's impossible to select last revision in the list

### ISSUE THREAD

**Issue by victou** [Reviewable/Reviewable#220]
We have a (too) big pull request and there are 22 revisions on this.
We can select manually the first 13 revisions only.

<img width="474" alt="capture d ecran 2015-12-16 a 07 44 07" src="https://cloud.githubusercontent.com/assets/586551/11834124/a8cb736e-a3c9-11e5-88e7-57185a0ae2da.png">

Add the possibility to scroll horizontally in this list, would be good :)

**Comment by pkaminski** [comment]
Yeah, I haven't found an elegant way to handle this yet.  As a workaround for now, the file matrix will scroll horizontally so you can select your revisions there.

**Comment by pkaminski** [comment]
Hey Victor, quick follow-up question as I make a plan to solve this:  what proportion of the horizontal space is used up the file path?  Perhaps you could send a more complete screenshot to support@reviewable.io (in confidence).  Thanks.

**Comment by pkaminski** [comment]
I now collapse file paths in the tabs, which will hopefully leave a lot more space for the revision grid.  I also have an idea on how to compress the grid itself to fit but this would be more difficult to implement -- please let me know if I need to look into it or if the current approach is good enough.  Thanks.

**Comment by victou** [comment]
I'm sorry, i didn't see your answer…
Now the PR is merged, so i haven't the history. :(
We had 80 revisions on this PR (yeah it's too much) but only 13 could be selected.

**Comment by porcus** [comment]
I wanted to add to what's been said here.  Hopefully the information I offer may illustrate why this is still a big issue for reviews involving many revisions.

I'm currently involved in a rather large review that's currently at 31 revisions.  (Not the typical use case for Reviewable, I'd wager.)  With so many revisions, reviewing files has become rather cumbersome, as you might imagine.

A situation that I routinely run into is what's identified by the OP.  I can't select revisions near the end of the revision history, because the corresponding revision boxes are clipped by the right edge of the tab.  In the past, when this has happened, I've had some success being able to see all revisions by simply increasing the width of the view (using the controls in the upper right corner of each file view).  But as the number of revisions has increased, this seems to have worked less and less effectively, and I suspect there may be a problem related specifically to the number of revisions that affects the x offset/position of the set of revision boxes that are supposed to appear in the file "tab" header.  The following pictures should illustrate what I'm referring to:

This is a file being viewed in _single_ mode where the width has been expanded to its maximum limit (i.e. 200 columns).  As you can see, none of the revision boxes are visible.
![image](https://cloud.githubusercontent.com/assets/1274180/18595042/8a2f9cc4-7c08-11e6-9d4e-6e32918c139f.png)

The next 2 images are of the same file being viewed in whatever the default mode is called.  The first shows that revision 1 becomes visible when the column breakpoints are set to about 126 characters, and the last revision (31) becomes visible when the column breakpoints are set to about 198 characters.
![image](https://cloud.githubusercontent.com/assets/1274180/18594958/163f8874-7c08-11e6-97e3-21863ccd35ab.png)
![image](https://cloud.githubusercontent.com/assets/1274180/18595327/cf5401b8-7c09-11e6-884a-3ea3881ab4a3.png)

What bothers me most about these examples is the fact that there appears to be lots of wasted space between the file name and the revision boxes.  I could be wrong, but I suspect this is unintentional that there is so much empty space that could otherwise be occupied by the revision boxes.

And while it's nice to hear that there's a workaround for this (using the scrollable file matrix), I really don't want to have to turn the file matrix on again, because with over 1000 files in my current review, it makes Reviewable painfully slow.

**Comment by pkaminski** [comment]
You're right, there's a buggy smell about this.  In principle, Reviewable is supposed to compute the highest width of the ...-collapsed filenames and hard-set that as the width in all the file tabs, so that the revision boxes line up when they stick in the toolbar.  I don't suppose you have any files with very long (collapsed) paths in this PR?  In any case, the reserved width should be the same for every file, independent of its path's length.  It also occurs to me that there's no need to line up the revision boxes in single-file mode, so I should be able to collapse all the whitespace in that case.  I'll look into it.

**Comment by pkaminski** [comment]
Arrgh, that was a fun bug:  every time the path width was recomputed, it increased by 13px because CSS.  Thanks for finding it!  Should be fixed now, and I also threw in no extra path padding in single file mode.

**Comment by porcus** [comment]
Nice!  I noticed earlier today that there was mention of this in the changelog, and I am happy to report that it now behaves exactly the way I'd expect it to for both single and dual file mode!

*Single-file mode* 
![image](https://cloud.githubusercontent.com/assets/1274180/18641965/63965d7e-7e64-11e6-81dc-18a1a4e640b0.png)
Even though not all of the [33] revisions show, I don't normally operate in this mode anyway.  And it's nice that when hovering over the name of the file, the revision boxes are temporarily pushed to the right to allow the full path to show.

*Dual-file mode*
![image](https://cloud.githubusercontent.com/assets/1274180/18642011/a7f856a2-7e64-11e6-98ee-1c47e27f555b.png)
Even without maxing out the width of the dual-file view, I can see both the full file name (without the need to hover over it) AND all the revision boxes in the header of the file tab.  

Thanks for the quick turn-around on this!  It's much appreciated!

**Comment by pkaminski** [comment]
Great!  I think between these fixes and the workaround of using the file matrix, I'm going to close this issue.  More could be done by, e.g., squashing the revision boxes when they start overflowing, but the slightly painful workaround should serve as motivation to have fewer revisions in a review.  😉
