### ISSUE TITLE
Edit comments

### ISSUE THREAD

**Issue by jGleitz** [Reviewable/Reviewable#225]
I can’t find a way to edit comments I made. As I often make typos, I wish I could do that. Editing the comment on GitHub dosn’t seem to update the comment on Reviewable.

Is there a way to edit comments? If not, is this feature planned?

**Comment by pkaminski** [comment]
There's intentionally no way to edit comments as this can easily cause confusing situations and breaks email-centric workflows.  Some customers are also taking advantage of this restriction to ensure compliance with regulations.  Instead, for the typos use case, Reviewable encourages a careful review of your comments before sending them all out -- there's a preview available from the Publish drop-down.  And while I empathize with perfectionism and trying to fix every error, most typos are not critical and those that are deserve a follow-up comment to ensure that everybody gets notified of the fix.

As for editing comments on GitHub, edits to comments originally made on GitHub will eventually be synced into Reviewable ("eventually" because GitHub doesn't fire an event for edits).  Edits on GitHub to comments originally made in Reviewable will not be synced and should probably be avoided.  (If there was a way to lock these comments from being edited on GitHub I would do that...)

**Comment by jGleitz** [comment]
Thanks for explaining!

**Comment by sempuki** [comment]
While I appreciate this is the primary use case you considered, there are other reasons to want retroactive changes. For example there was a bug in a system component that redirected keyboard input to the previous window which caused sensitive information to be leaked into reviewable comments. At best this is embarrassing, at worst it's a security issue. While you might counsel care when publishing, bugs by definition unexpected exceptions, and a lack of tools to immediately correct the problem is a concern.

**Comment by pkaminski** [comment]
Agreed, there are exceptional cases.  I've been taking care of these by hand, on demand, and they come up only once or twice a year so I think this is a reasonable trade-off.

That said, I think perhaps comment edits could be made compatible with the primary use case by explicitly keeping track of and publishing the edits.  If there's a lot of demand I can look into it but at the moment there are bigger priorities to worry about.

**Comment by sempuki** [comment]
For the use case I present it would be sufficient to remove a comment or a publish set atomically. Having to redo the review is insignificant compared to a security lapse.

**Comment by pkaminski** [comment]
Fair enough, and I'll do my best to add that if I ever get tired of deleting things manually, or a customer tells me that I didn't respond fast enough.  No issues so far, though.

**Comment by sempuki** [comment]
This is on a hosted install. The security information wasn't leaked to the internet, but it was leaked within the organization.

**Comment by pkaminski** [comment]
Thanks, that's an important detail.  I think the right thing to do in this case is to make available and document the admin tooling I use to take care of incidents like these and others, so your local admin can intervene in a timely fashion.

**Comment by sempuki** [comment]
This still may leave some customers unsatisfied if the admin isn't timely -- by the time he's looked up the documentation and run the query the damage may be done, and customers have already started to ask the question "why is it not a feature to just click 'unpublish'?"

**Comment by pkaminski** [comment]
Every decision is a trade-off; every feature adds (often unexpected) complexity.  At this point I don't believe this scenario is sufficiently common to warrant addressing directly but I'm always open to data showing otherwise.  In the meantime, since although rarely things can go wrong in a variety of ways, I believe it's a better return on investment to equip admins with flexible tools.

**Comment by sempuki** [comment]
As a customer this incident has hurt my trust in the product an will recommend it be abandoned.

**Comment by pkaminski** [comment]
I'm sorry to hear that.  The product is far from perfect and I'm always happy to assist customers when they hit a rough patch, but in this case I wasn't alerted to the problem AFAICT.  And while I always take use cases and feature suggestions under consideration I do not believe that customers have the context necessary to unilaterally dictate feature prioritization.  If this one feature is truly a blocker for your company then I would appreciate if your Reviewable admin would let me know, since it certainly didn't come up at any point during the product evaluation or subsequent discussions.

**Comment by sempuki** [comment]
I have no interest in unilaterally dictating feature prioritization -- only recovering from embarrassing or costly mistakes.

**Comment by miladroy** [comment]
Just an idea: Instead of editing the original comment, how about keeping it intact **and** collapsed(maybe with strikethrough?) by default, with the new comment expanded on its place? 
I feel like this might require less refactoring but won't address the leaked security issue use case.
