### ISSUE TITLE
Comment on GitHub doesn't snapshot revision, leaving no snapshotTimestamp in completion condition

### ISSUE THREAD

**Issue by jGleitz** [Reviewable/Reviewable#234]
In our PR Beagle-PSE/Beagle#590 there is only one revision. It got 2 lgtm but one is stale—why is that?

We have a similar situation in Beagle-PSE/Beagle#591 (1 revision consisting of only one commit, 1 lgtm given but staled at the point of writing)

**Comment by jGleitz** [comment]
Note that the lgtm by the PR’s author is automatically ignored by our acceptance code.

**Comment by jGleitz** [comment]
I found the root issue: Apparently, `review.revisions[x].snapshotTimestamp` was removed without notice.

This bug can be fixed by replacing the line 
```
var lastRevisionTimestamp = _.last(review.revisions).snapshotTimestamp;
```
in the Review Completion Code with

```
var lastRevisionTimestamp = _.last(_.last(review.revisions).commits).timestamp;
```

Note that the example code was not adapted and custom code users were not notified about this change, which is the actual issue.

**Comment by pkaminski** [comment]
I looked into Beagle-PSE/Beagle#591 and the actual issue there is that the revision was never snapshotted, hence no `snapshotTimestamp`.  Normally, a revision is snapshotted only when it's viewed (by somebody other than the author) in Reviewable, or a comment / review mark is attached to it.  But clearly this interacts badly with PRs where the LGTM status check is in place and the review is never visited.  I'll need to think a bit more about whether the bug is in the snapshotting (perhaps I should snapshot in response to GitHub comments as well?) or in the completion checking code (perhaps it should check against the revision's creation time, rather than snapshot time?).

BTW, using the commit timestamp is not a good idea in general, since it can be arbitrarily far in the past.  In other words, it's possible to commit something, then LGTM the current revision, then push the commit, and have the LGTM *not* be stale.

**Comment by jGleitz** [comment]
I see, thanks for pointing out!

We will only comment on Reviewable in the future and undo the change we made to the Review Completion Code.

**Comment by pkaminski** [comment]
That's probably best for now, but LGTM'ing on GitHub is definitely a workflow I want to support.  I think the right thing to do is to snapshot the appropriate revision(s) when a GitHub comment is made, but getting the details right is tricky due to API limitations (what was the current commit at the time the comment was posted?) and concurrency issues (what if the commit wasn't processed by Reviewable yet? what if it will never be processed because it got rebased away?).  I believe I see a way forward but I won't be able to get to it until next week sometime -- sorry.

**Comment by jGleitz** [comment]
It’s nice to hear you’re working on it.

I just want to add that add that a user, I’d expect this timestamp to refer to the time I created the PR (for the first revision) or the time I pushed the commit creating a new revision (for later revisions). This may also be the time Reviewable processed these events (which should not be much later).

**Comment by pkaminski** [comment]
Yeah, it's not that simple unfortunately.  :smile:  The processing time is unreliable since webhook deliveries are not guaranteed, may not be turned on for all repos, and the processing itself is async and may fail (and retry).  The push time would be better, but it's tricky to fetch reliably since it's not included in the PR data structure and GitHub doesn't provide access to the reflog.  Also, Reviewable has a concept of "provisional" revisions whose commit can still be changed because they haven't been used in the review yet, to minimize the number of "junk" revisions (e.g., push, notice typo, push again).

Anyway, I'll figure it out, and I promise the `snapshotTimestamp` will be something reasonable, though perhaps not exactly what you'd expect.  :smile:

**Comment by pkaminski** [comment]
So after consulting with GitHub support it turns out that the API doesn't provide sufficient data for a foolproof solution.  Basically, there's no way to tell what the head commit on the source branch was at the time a comment was posted.  The reflog would normally provide this information but it's not accessible through the API, and all the workarounds have severe deficiencies.

At this point my idea is a best-effort approach:  when syncing a comment, if the timestamp is no more than 30 seconds before the current time, assume that the state of the PR hasn't changed since the comment was sent and snapshot the revisions as of the comment's time.  The window for false positives is pretty small, and events are typically delivered within ~5 seconds so hopefully false negatives should be pretty rare too.  The approach won't work if the repo isn't connected but there's really nothing I can do about that.

Sounds good?

**Comment by jGleitz** [comment]
> Sounds good?

Absolutely. I it’s only reasonable to expect a little delay in synchronisation when mixing GitHub and Reviewable. I agree that there’s a small chance for errors.

**Comment by pkaminski** [comment]
This should now be fixed with the best-effort approach described above.
