### ISSUE TITLE
Commits with equal timestamps can badly mess up revision partitioning algorithm

### ISSUE THREAD

**Issue by marcinslusarz** [Reviewable/Reviewable#236]
I made a pull request with 7 commits and it's displayed as 2 revisions in Reviewable, even though mode is set to "Review each commit separately":
https://reviewable.io/reviews/pmem/nvml/580
If owner of the repo changes mode back and forth nothing changes, however...
I made another pull request with the same 7 commits to another branch in my repo:
https://reviewable.io/reviews/marcinslusarz/nvml/1
and "Review each commit separately" works as expected, but sometimes it switches back to "combine" mode (but combo stays in "separate" mode) when someone else loads this page (wtf?) and I can fix that by switching to "combine" mode and back.

**Comment by pkaminski** [comment]
Sorry about that!  Let's take these one at a time:

For https://reviewable.io/reviews/pmem/nvml/580, I can confirm that the setting is "Review each commit separately".  However, since the repo's default is "Combine commits", the initial mapping was done onto two revisions.  Then, before you switched to "Review each commit separately", those revisions got snapshotted by @krzycz; r1 on January 15th, 2016 5:33 PM UTC and r2 on January 19th, 2016 5:34 PM UTC.  As mentioned in the dropdown's warning text, this can prevent a clean mode switch.  There are only two things that will create a hard snapshot like this: a comment (even a draft) on a file's revision, or marking a file as reviewed (again, even just as draft).  This is necessary to avoid messing up the references in the datastore.  @krzycz, do you remember if you did any of these things?  If not, then there might be a bug that prematurely snapshots revisions.

> but sometimes it switches back to "combine" mode (but combo stays in "separate" mode) when someone else loads this page (wtf?) and I can fix that by switching to "combine" mode and back

Sorry, I don't quite follow this.  I had some issues a while ago with the dropdown showing up blank instead of the correct state but thought I fixed it -- perhaps this is related?  Can you explain in more detail what's happening, maybe with some screenshots to make it absolutely clear?  Thanks.

**Comment by marcinslusarz** [comment]
Thanks for the quick response.

@krzycz indeed temporarily marked some files as reviewed before he tried to change the review mode, so that explains what happened in pmem/nvml review. I think mode should be changeable on the fly... but I understand it's hard for you to implement it.

WRT the 2nd issue - we can't reproduce it as is, but IIRC it looked like this:
My review was set to "separate" mode, I gave a link to @krzycz, he opened it, saw it in "combine" mode, I refreshed the page and also saw it "combine" mode (but combo was saying it's in "separate" mode), I changed it to "combine" and then back to "separate" and it correctly switched to "separate" mode. 

Today I managed to reproduce it just by switching mode back and forth. I'm leaving it in broken state. Here's the screenshot: http://imgur.com/WlwaSyi - combo says one thing but the list of changes shows something else.

**Comment by pkaminski** [comment]
Yeah, ideally the mode would be changeable on the fly, but setting up the (NoSQL) datastore to enable tracking down all possible references to a revision and rewriting them (if even possible) would be a lot of work, and the common usage pattern for this feature is to either set the default mode per-repo, or have the reviewer switch it as soon as they load the review.

Huge thanks for the repro!  I now understand what you mean and there does seem to be something very wrong going on.  Please don't touch that review until I manage to track down the root cause -- thanks.

**Comment by pkaminski** [comment]
I started digging into this, and I think part of the problem is that the marcinslusarz/nvml#1 PR is a bit weird:  all the commits have the exact same timestamp, which is throwing off the revision partitioning algorithm.  Can you add any context about how the PR might've ended up like this?

I think this is just a secondary issue that's preventing the review from recovering from an earlier bug, though.  Assuming that all 7 commits were in the PR to begin with, there should be no way to end up with anything other than either 1 or 7 revisions, yet the review now has 2: the first commit in r1, and the rest in r2.  Do you remember what the review looked like just before it reached this state, by any chance?

Thanks again for spotting this problem!

**Comment by pkaminski** [comment]
So my guess was partly right and partly wrong:  it turns out that the equal commit timestamps are the root cause of the entire problem.  To reproduce, you just need to switch the (original, untainted) review to "One revision per commit", wait for things to settle, then reload the page.

I'm not sure how to best address this yet.  The code responsible for this is trying to avoid bringing in commits from "the past" into new revisions; I think it was originally added to avoid replicating the entire set of commits after a rebase, but this was before the "One revision per commit" mode was added.  This may also be related to #191.

I'll need to think a bit more about this, but in the meantime it would still be good to know how you ended up with commit author timestamps all equal to each other.  Thanks.

**Comment by marcinslusarz** [comment]
"git rebase --ignore-date" resets both author and committer timestamps.

**Comment by pkaminski** [comment]
I fixed the case where commit timestamps are equal to ones already snapshotted.  However, if they ever end up strictly smaller than currently snapshotted ones, the commits will still be skipped over when determining revisions to partition at.  In most situations this will result in a cleaner file matrix, so unless/until I find another way to achieve the same effect, I'm going to leave it in.
