### ISSUE TITLE
Un-reviewed PR is defaulting to "show latest revision", has no diff

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#280]
I had one PR open when I signed up my organization for Reviewable. Reviewable correctly picked up the PR and everything looked fine. Then a little while later I opened the Reviewable page again and the diff was gone. This was really confusing. It turns out that Reviewable was now defaulting me to viewing just the latest revision, and since the PR had no discussion this meant the entire diff was suppressed.

I had this same issue when checking out the demo yesterday, which I mentioned in [a HackerNews comment](https://news.ycombinator.com/item?id=11432799), but the issue there went away when the demo was reset.

If I click the link to show all files and expand the diff bounds for all files back out to the fullest range, everything looks good, but if I then reload the page it's back to showing just the latest revision.

Ultimately, there's two things wrong with this:

1. It shouldn't be defaulting to Show Latest Revision. This is a very confusing state to be in. I'm not really sure what the point of Show Latest Revision is anyway, all it does is show the existing discussions on the final state of the code, but when I'm looking at a PR I want to be looking at a diff. Also, as I experienced with the demo, when Reviewable is showing side-by-side, Show Latest Revision is especially confusing because it shows the same code on both sides.
2. There's no obvious way to get out of the Show Latest Revision state. The files are hidden, the link to show them is small and grey, and there appears to be no other way to fix this beyond showing all the files and manually changing the diff bounds on every file. I would have expected the "changes" dropdown to have a diff bounds widget that sets the bounds for the entire review. Similarly, if I'm viewing just the latest revision, the center "revision" column in the Changes panel should have a button that shows me the diff against the base revision.

The PR in question has 1 revision (and no provisional revisions) and has not been reviewed by anybody. Also, as I said before, the PR predates Reviewable being hooked up to the repo, although I don't know if that affects anything. It's also a PR in a private repo or I would link it here.

Reproduced with Safari 9.1 (11601.5.17.1) on OS X 10.11.4.

**Comment by pkaminski** [comment]
This is working as intended, but perhaps isn't ideal.  Here's the reasoning:

There are two reasons for a PR author to look at their own review: to check on the latest changes they pushed, or to reply to comments.  For the former, Reviewable shows a diff over the provisional revisions if there are any.  For the latter, Reviewable shows a nil diff so that only files with unresolved discussions in them will be shown.

If there are no provisional revisions and no unresolved discussions, Reviewable still shows the nil diff but I admit that can be confusing.  It may be better to show the full diff (base to latest revision) instead in that case, though that difference in behavior when all discussions are resolved may be confusing itself.  Perhaps the special case should be triggered only if there are no line-specific discussions at all...  Thoughts?

Note that this behavior is specific to your own reviews, so wouldn't have applied to the demo review.  Something else was going on there.

Manual diff control is via the file matrix, which is hidden by default (look for the toggle at the bottom of the Changes box on the main page).  This will be moving into a toolbar dropdown sometime next month.  I'm amenable to exposing special cases via buttons or links in the Changes box but it's not clear which ones are useful or important enough to make the cut.  "Diff against base" when reviewing a single revision may well qualify, though.

**Comment by kballard** [comment]
Ok, that reasoning makes sense, but showing no diff at all will still be confusing. I'm also hesitant to say that it should behave differently when there are no line-specific discussions, because that can also be confusing.

I think the best thing to do here is twofold:

1. If I'm viewing the latest revision and there are no line-specific discussions, the small text explaining that all files are hidden should be made much more prominent. This way it's immediately obvious why I'm not seeing a diff, and it's also immediately obvious how to view all the files (in case I want to comment on my own PR). You could also throw in a button in this prominent view that diffs against the base revision, because if I'm trying to comment at all it's very likely that I want to comment on the diff rather than commenting on just the final revision. This also makes sense if I'm not the PR author and got to this state by clicking "Show Latest Revision".
2.If I'm viewing the latest revision, I still think the changes box should have a button "Show All Revisions" (in the same place where you currently get "Show Latest Revision" when viewing all revisions). This solves the immediate case of "oops I don't want to view the latest revision, how do I get back to seeing everything?", which covers both PR authors viewing their own PRs and other people who click "Show Latest Revision".

Also, now that I'm looking at the file matrix, the behavior of the eye button is a little odd. If I haven't reviewed any revisions yet, why does it set the left bounds to r1 instead of setting it to the base? This is especially confusing for a PR that only has one revision. My reasoning is if someone hasn't reviewed a PR yet, they almost certainly want to see the diff against the base rather than comparing it against a past revision (or getting no diff at all if there's only one revision).

**Comment by kballard** [comment]
I think I know what's going on with the demo review. I just opened it up now and it was showing the latest revision again. I expanded the file matrix and saw the dimmed eye glyph in the latest revision for each file (e.g. someone else reviewed all the files). I then noticed the checkbox in the changes box "Include changes in files previously reviewed only by others". After checking that checkbox, the review immediately switched to diffing the latest revision against the base.

So basically, the problem is that if someone else reviews everything, it defaults me to seeing the latest revision even though I personally never saw anything else. This seems confusing. Just because someone else reviewed a file doesn't mean I don't want to review it. And if Reviewable is configured to require multiple reviewers then I would definitely want to see those files because one review isn't sufficient. So basically, I think you should have this checkbox default to being checked.

**Comment by pkaminski** [comment]
You make several good points!  After thinking about it for a while, I decided to go with the following set of changes: https://headwayapp.co/reviewable-changelog/3639

The reason I didn't overload the existing "Show latest revision" button is that it's intended to guide you through the review -- it's only enabled when Reviewable thinks you need to change your diff set to continue reviewing.  After you click it, it's supposed to be disabled until the state of the review changes in some other way.

As for the eye button, its behavior differs between PR authors and reviewers: for reviewers, it should work as you expect (diffing against base), but for authors it tries to diff provisional revisions against the last snapshotted one, since authors don't normally mark files as reviewed.  This means that if there's no provisional revisions then clicking on the eye as the author is equivalent to "Show latest revision".

Thanks for the great -- and thoroughly explained -- feedback!  Keep it coming!
