### ISSUE TITLE
Setting the assignee(s) from comment only works in the UI

### ISSUE THREAD

**Issue by pcorpet** [Reviewable/Reviewable#287]
In Reviewable.io if I add a comment with +@pkaminski the PR gets assigned to him, however if I do the same from GitHub (or for my workflow from the GitHub API using a command line tool), the assignment doesn't happen.

Could you check the new comments and do the assignment if the PR or the repo is linked with Reviewable.io please? Another alternative would be having an API to do the multiple assignment in Reviewable.io

**Comment by pkaminski** [comment]
The current behavior is intentional.  I decided not to implement assignee directives in GitHub-originated comments because they wouldn't work consistently: they would require the repo to be connected (not all are), even if it is the event webhooks from GitHub aren't guaranteed (and don't retry), and there's no way to warn the author if the assigment failed (e.g., because they don't have push permissions).  This would make for a poor experience.

As for an API, I've got nothing official available or planned at this time.  It's technically possible to access Firebase directly -- and I have no problem sharing the schema -- but even just to set assignees would require a sequence of lookups to find the correct review, applying a custom escaping scheme to keys, looking up GitHub user ids, queuing extra requests to fill the user profiles in Reviewable, etc.  I can provide some pointers if you're keen to try it, but it won't be straightforward.

**Comment by pcorpet** [comment]
Thanks for the quick answer, what about an API to add a comment through Reviewable? :-) This way you could reuse the same flow and code that you have to do the assignment, while still working consistently.

If it's too complex, I'll fallback on using GitHub API to assign one review, but I do like the multiple assignees of Reviewable.

**Comment by pkaminski** [comment]
Due to Reviewable's somewhat unusual architecture, comment sending happens almost entirely on the client (~500 LoC) so exposing it via an API would require some pretty serious redesign.  Sorry, I really don't see a way to make this happen right now...

**Comment by pkaminski** [comment]
I've been thinking about this some more and have come around to the opinion that the surprise of not supporting directives in GitHub-originated comments is even worse than the issues I've raised, some of which can be mitigated.  I'm currently working on improving the email-based workflow and will throw this in.

**Comment by pcorpet** [comment]
\o/ Tell me if I can help (I'm a Software Engineer).

**Comment by pkaminski** [comment]
Setting assignees (and labels / milestones, for good measure) is now supported in GitHub-originated comments.  Failed assignments will get you a warning email, as long as we have your email on file (usually the case if you've signed in to Reviewable at least once and haven't revoked the auth).  Some more details on the limitations here: https://github.com/Reviewable/Reviewable/wiki/FAQ/_edit#can-i-reply-to-reviewable-comments-by-email.
