### ISSUE TITLE
Cannot review commits separately on a specific PR

### ISSUE THREAD

**Issue by nox** [Reviewable/Reviewable#289]
https://reviewable.io/reviews/servo/servo/10081

The diffs from the two first commits are mixed, for some reason.

**Comment by pkaminski** [comment]
I suspect that this is a manifestation of an old bug that I fixed on March 30th, which caused top-level comments to hard-snapshot revisions so that a later review mode change had no effect.  (The PR was created on March 18th.)

It looks like nobody has done work on the review in Reviewable yet, in which case I can just wipe the data and have it resync from GitHub.  You'll need to change the mode to each-commit again, but it should work fine this time.  Let me know if it's safe to proceed this way.

**Comment by pkaminski** [comment]
Ping -- would you like me to reset this review?

**Comment by jdm** [comment]
Go for it.

**Comment by pkaminski** [comment]
Done.  Please reload the review page, which will automatically recreate it, then immediately switch it to each-commit mode and everything should be fine!

**Comment by nox** [comment]
Didn't notice you addressed this, thank you!
