### ISSUE TITLE
The eye icon in the file matrix doesn't select the last revisions I reviewed

### ISSUE THREAD

**Issue by wormyy** [Reviewable/Reviewable#290]
As seen on the gif, when I click on the eye icon but nothing happens. The base revision works well. I use Chrome, but neither it worked in Safari.

![gif](http://g.recordit.co/B7NIXffHMx.gif)

**Comment by pkaminski** [comment]
Is this your own PR?  If so, in that situation the eye icon is used to select a diff over the provisional revisions instead, or the nil diff on the latest revision if there are no provisional ones.

If this doesn't describe what you're seeing, could you please let me know which PR this is so I can investigate further?  Thanks.

**Comment by wormyy** [comment]
Yes, I am the author of the PR: https://reviewable.io/reviews/Quadric/network/24
Then I find the help text on the eye icon quite confusing, it says that it selects the last revision I reviewed as the left diff bound for each file, what is exactly what I want. Is there another way to do this?

**Comment by pkaminski** [comment]
Agreed, the behavior doesn't make sense if authors mark files as reviewed.  I changed it so that if an author has any review marks then it'll treat them as a normal reviewer for the purposes of diff range selection.  (With no marks, behavior will continue to be as described above.)  Give it another try!
