### ISSUE TITLE
No obvious way to get rid of Reviewable

### ISSUE THREAD

**Issue by gramster** [Reviewable/Reviewable#292]
Tried it; didn't like it. Now I want to remove it, and although I have revoked permissions and removed the webhooks, it still shows up on GitHub in the PRs. And the FAQ has no explanation of how to remove its tentacles.

**Comment by pkaminski** [comment]
Once you've revoked permissions there's really no way for Reviewable to access your repos.  But if by "tentacles" you mean the "This change is Reviewable" links in the PR descriptions, you can either just delete them manually (if there's a few), or temporarily reauthorize Reviewable and disassociate the affected orgs at https://reviewable.io/goodbye.  (I don't advertise the URL widely because this doesn't come up very often -- usually, people try Reviewable on just one or two PRs and can easily revert the descriptions by hand.)
