### ISSUE TITLE
Shift-click to make a group of files as reviewed

### ISSUE THREAD

**Issue by elliotchance** [Reviewable/Reviewable#300]
Sometimes we have to commit libraries to our codebase because it cannot be distributed any other way for license reasons. This can create a PR with hundreds of changes files that do not need to be reviewed, but some files that do. Also if we move 3rd party libraries.

It would be great if you could use the matrix or bunny-popdown to mark a first file as reviewed (green circle) then shift-click the bottom one (since they will be in order) and it will popup "Are you sure you want to mark 138 of 157 files as reviewed?" and click Yes.

**Comment by pkaminski** [comment]
I like it!  I had a "mark directory as reviewed" feature on my todo list but I think this approach may be better.  The popup may not even be necessary, and I generally try to avoid modals/confirmations in Reviewable since they're not good UX.

Might also need to help discovery by detecting quick toggling of successive files and popping up a hint.

**Comment by elliotchance** [comment]
I'm fine with not having a confirmation box. It's not easy to click + move the mouse + shift-click accidentally unless thats really what you intended to do.

**Comment by pkaminski** [comment]
Closing in favor of #527.
