### ISSUE TITLE
Please remove "offline" popover

### ISSUE THREAD

**Issue by elliotchance** [Reviewable/Reviewable#301]
It's *extremely annoying* when in the middle of a code review the whole screen is disabled because the internet connection is flakey. In most cases you don't need internet right now, reviewable should keep the changes and push it automatically when available. I assume this is how it works anyway.

You already have a red warning in the bottom right and a confirm popup if you try and close the review with unsaved changes, this is enough to protect against loss.

**Comment by pkaminski** [comment]
There are two conditions that trigger the offline overlay:

1.  The connection to the datastore has dropped completely.  In that case, due to the way the permission system is implemented and the lack of concurrent edit deconflicting, Reviewable can't guarantee that all your edits won't be lost when the connection comes back.

2.  A write has been pending for 30+ seconds even though the connection is supposedly open.  Again, in this case Reviewable has no confidence that your edits are being saved, or that they can be saved when the connection stabilizes again.

Basically, I'd rather have users annoyed at being blocked than angry at having lost work (which did actually happen).  The "right" way to solve this would be to have a fully persistent local datastore that syncs with the central one whenever possible, but this would require some pretty heavy work in Firebase infrastructure and Reviewable's schema design so it's not likely in the near future.

That said, it's possible that one or the other of these cases is misfiring -- if you see the overlay often, could you try turning on `Firebase.enableLogging(true)` and send me the logs from the console?  (By email, as there may be sensitive information captured therein.)  Thanks.

Finally and completely off the record, you can always run `Reviewable.workOfflineAtMyOwnRisk()` from the console to dismiss the overlay, but I really can't recommend it due to the risks detailed above and will edit this message to disavow all knowledge of the method if you lose work because of it.  :wink:

**Comment by elliotchance** [comment]
I understand the risks vs. the amount of time to refactor it to use local storage means this is the lesser of the evils.

Some days our internet can be flakey and for 10 minutes while I have the review up I do not need internet. I will use `Reviewable.workOfflineAtMyOwnRisk()` 😄

**Comment by pkaminski** [comment]
Thanks for understanding!  One tip:  while offline, drafts are pretty sure to save correctly when you reconnect, but other edits (review marks, disposition changes outside of a draft, etc.) require a repo-specific permission ticket that expires after 30 minutes and is refreshed every 15 minutes.  This means that after as little as 15 minutes (and always after 30 minutes) spent offline, those changes will fail to save and get *dropped* with no way to recover them other than redoing the work.  This is something I'm hoping to address in the next major revision of the platform, but it will require buffering all writes separately and making them block on reacquiring permissions after a disconnect.

**Comment by gabor-farkas** [comment]
would it make sense to add a 'Please retry now' button? Many times this 'offline' popover just stays there even if I'm definitely online, and it just never goes away. This way, I can't even copy-paste my long comment I haven't posted ...

**Comment by pkaminski** [comment]
In principle, Firebase should be trying to reconnect pretty much continuously, so there's not much an extra retry button could do.  But it's always possible it's buggy -- can you copy here the reason at the bottom of the offline modal when you're sure you're online?  Also, you can always use `Reviewable.workOfflineAtMyOwnRisk()` in the console to make the modal go away and copy out any potentially unsaved text.

**Comment by gabor-farkas** [comment]
it just occured again now. The reason I have is `Reason: 2 pending writes (2 stalled)`.
There are two errors in the console. Getting branches from the github api responded 404 (https://api.github.com/repos/**/**/branches/beta/protection?access_token=**&per_page=100&_nocache=988428 , and the feature branch). Requests to `https://status.github.com/api/last-message.json?callback=angular.callbacks._1m` succed.
In this current case actually I don't think I have any actual pending updates, I just left the tab open from last night.
