### ISSUE TITLE
Many empty revisions that claim to be rebases

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#319]
Reviewing https://reviewable.io/reviews/servo/servo/11308 has been interesting, since every revision past 12 has shown me some set of files that are marked unreviewed but don't show any changes (there's not even any in the collapsed lines).

**Comment by jdm** [comment]
<img width="1363" alt="screen shot 2016-05-26 at 1 29 36 pm" src="https://cloud.githubusercontent.com/assets/27658/15583917/e9663750-2345-11e6-92c1-91be5d651e8e.png">
From revision 23.

**Comment by pkaminski** [comment]
Sorry, I've been super busy and am about to travel -- I'll take a look as soon as I can, though.

**Comment by pkaminski** [comment]
So AFAICT (and without knowing the details of your commits / rebases) everything is working as designed, though arguably it could be more useful.  The PR rebases swathes of commits and the suggested diff pairs are based on the heuristic rebase matching, but the cell colors are always based on the diff from the *previous* revision.  So in your screenshot, r23 was rebased from r11 with no changes, but does introduce changes from r13.

Does that make sense?  What behavior would you prefer?  (Keep in mind that since the rebase matching is just a heuristic, I don't want to let it drive the fundamental data model.  Now if git had structured rebase support, with information on the transformations saved in the repo, that'd be a whole different ballgame...)

**Comment by jdm** [comment]
If I'm using keyboard shortcuts in the "review each commit separately" mode, I need to mark every file as reviewed before I can move on to the next revision. This PR was particularly frustrating in that respect, since I spent a disproportionate amount of time marking files as reviewed that contained no changes for me to review. I feel like anything that didn't make me explicitly acknowledge files with no changes would be an improvement.

**Comment by pkaminski** [comment]
This problem is specific to the combination of "review each commit separately" and rebasing, and I believe somewhat unavoidable.  While I could propagate review marks to rebased files with the same file (and base file?) shas, I'm not sure that would be semantically correct.  Does a review mark claim those specific file contents to be reviewed, or those contents in the context of the other files in the revision?  I tend to think it's the latter.

The only thing I can recommend is making judicious use of the "mark as reviewed" button in the Changes box (or dropdown) when you run into these situations, as it'll immediately mark all files as reviewed at the current right diff bound (as if you had hit the mark reviewed button separately for each file).

**Comment by jdm** [comment]
Could reviewable just not make me acknowledge the files that it claims don't contain any changes? I'm fine with acknowledging the ones with "base commit changes" that are hidden by default, but the ones like in the screenshot are just such a waste of time to deal with.

**Comment by metajack** [comment]
It seems like the UI knows whether this the case, so it could just auto-mark them I'd think.

**Comment by mmlb** [comment]
I'm in this same boat and metajack's comment makes sense. Reviewable knows there's no difference so why make me acknowledge it?
