### ISSUE TITLE
Unsaved Changes warning is misleading

### ISSUE THREAD

**Issue by erikwright** [Reviewable/Reviewable#323]
The warning text shattered our confidence that all changes were being automatically saved. We were left wondering if we needed to press a "save" button somewhere or publish before leaving the page.

It might help if the message explicitly said that there were "auto-save" transactions in progress. If the unsaved changes are due to network connectivity issues the message could mention that instead.

**Comment by pkaminski** [comment]
I assume you mean the `onbeforeunload` message that pops up if you try to close the page.  I changed it to:  "Autosave writes still in progress so recent changes may not be saved.  Please hang on for a second or two!".  But it doesn't really matter, since most browsers already ignore the message and show a generic dialog instead, and I believe the remaining ones will start doing so soon as well.
