### ISSUE TITLE
Allow filtering on the reviews view

### ISSUE THREAD

**Issue by s0undt3ch** [Reviewable/Reviewable#33]
I'd like to be able to filter the available PR's on the reviews page.

For example, "All" reviews, "My Connected Repositories" reviews, "Contributed Connected Repositories" which I contribute(not mine) which are reviewable enabled

Does this make sense?

**Comment by pkaminski** [comment]
Thanks for opening the issue.  Could you expand a bit on what workflow you're trying to enable with this feature?  i.e., how you conceptually "group" the repositories you have access to, why you want "separate" dashboards (well, filters) for different groups, etc.  Perhaps post a screenshot or two of what you're currently seeing and why it's messy / confusing.

In general, it doesn't make sense to distinguish between repositories based on who happened to connect them, since any admin can do so.  But I suspect there are other ways to get things working to your liking -- I have an idea, but want to make sure I understand your use case completely before suggesting it.

Thanks!

**Comment by pkaminski** [comment]
I added a toggle to hide unlinked PRs at the bottom of the review list, please let me know if this addresses your issue.  (Note that there's no way to unlink a previously linked PR, but I can do that manually if you give me a list.)

**Comment by s0undt3ch** [comment]
Sorry for my slow response. The filter does what I was initially looking for. Thanks!

Allowing a linked issue to be unlinked would also be a great feature :)

**Comment by pkaminski** [comment]
Great, thanks.  Allowing unlinking reviews is too dangerous in general
(since it's hard to tell who should be allowed to do it, and whether data
might be lost), and probably not useful enough to expose as a public
feature.  But if you'd like I can unlink some reviews for you manually --
just let me know which PRs.  Cheers.

On Wed, Jan 21, 2015 at 3:36 PM, Pedro Algarvio <notifications@github.com>
wrote:

> Sorry for my slow response. The filter does what I was initially looking
> for. Thanks!
>
> Allowing a linked issue to be unlinked would also be a great feature :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/33#issuecomment-70944365>
> .
>



-- 
Piotr Kaminski, Founder, reviewable.io
