### ISSUE TITLE
Chrome: Crashes on large PRs

### ISSUE THREAD

**Issue by iceydee** [Reviewable/Reviewable#34]
I have two very large PRs which will just give me a spinner for a couple of minutes until eventually I get the dead-computer icon and Chrome asks me if I want to kill the page.

One has 570+ files changed and the other has 680+ files changed (the second one is getting capped by github even, but the first one works as expected within github).

**Comment by pkaminski** [comment]
Thanks for the report Mio.  Yeah, Reviewable doesn't try to protect itself from very large PRs right now, though it probably should (see also #17).  It probably doesn't crash per se but is trying to compute and display the diffs for all the files, which isn't gonna happen in a reasonable amount of time.

How would you like to have Reviewable react to such large PRs?  (Besides not locking up the tab, of course.)  My thinking is to skip doing/showing the diffs if the number of files is above some threshold (say, 50), and instead let the user select the individual diffs they might be interested in.  This is assuming that even just displaying 500+ file headers isn't too much for the poor browser...

**Comment by pkaminski** [comment]
Forgot to mention that @ZachGoldberg was also interested in this.

**Comment by dannykopping** [comment]
:+1: for this.

Could you somehow defer the syntax-highlighting and even population of the `.file` div until the user scrolls to that point. This kind of deferred loading is pretty straightforward with a library like [Waypoints](http://imakewebthings.com/waypoints/). We had a similar thing for our eCommerce store when we implemented infinite scroll, and you could probably recycle divs and push/pop the stack of files based on the scroll position.

**Comment by pkaminski** [comment]
My working theory is that nearly all the performance hit comes from diffing and rendering the diffs, and that the diff-less DOM is lightweight enough to not require any special handling.  My idea is to throttle the differ (which already runs in a worker, but apparently that doesn't help much) so it'll stop after say 10 seconds and put "diff this" placeholders in for files it didn't get around to.  We'd also want to prioritize any files with comments, which gets a bit trickier...

I don't think scroll-based automatic deferred loading is a good approach in this case since users can skip between files, and if they skip towards the bottom we'd end up diffing all the files in between.

**Comment by pkaminski** [comment]
I've implemented the diffing cutoff as described in the previous message.  It'll usually get through 50-100 files (depending on file length, etc.) in 10-15 seconds before giving up and leaving placeholders for the rest.  The resulting page still chugs a bit but should be usable.  @iceydee, @ZachGoldberg, and @dannykopping, could you please give it a try on your large PRs and let me know if further improvements are needed?  Thanks.

**Comment by dannykopping** [comment]
Will verify when I next review a monster :)

**Comment by dannykopping** [comment]
`Diff skipped to avoid melting down your CPU` lol
