### ISSUE TITLE
"short-handed" discussions

### ISSUE THREAD

**Issue by erikwright** [Reviewable/Reviewable#345]
When I at-mention someone in a comment, will it show up as requiring their action on their end?

![image](https://cloud.githubusercontent.com/assets/187063/16126630/ff584c4c-33c6-11e6-9b49-1747b8f9796d.png)

**Comment by pkaminski** [comment]
Yes.  The mention will cause them to be involved in the PR in GitHub, so it'll show up on their review dashboard, and Reviewable will also add them to the review so the discussion counter will be red.  However, until they reply or acknowledge, they're not "active" in the discussion and not counting towards resolution (because you don't want a simple @-mention to block resolution), so Reviewable keeps indicating that it needs one more person to contribute.

**Comment by pkaminski** [comment]
Yes.  The mention will cause them to be involved in the PR in GitHub, so it'll show up on their review dashboard, and Reviewable will also add them to the review so the discussion counter will be red.  However, until they reply or acknowledge, they're not "active" in the discussion and not counting towards resolution (because you don't want a simple @-mention to block resolution), so Reviewable keeps indicating that it needs one more person to contribute.
