### ISSUE TITLE
Cannot publish review

### ISSUE THREAD

**Issue by nox** [Reviewable/Reviewable#347]
https://reviewable.io/reviews/servo/servo/11754

Fails with a crash report. Just filing for reference since you seem already notified of this.

**Comment by pkaminski** [comment]
I'm having trouble finding the right crash report for this.  The closest I can find is `undefined is not an object (evaluating 'a.path.replace')`, which is logged for you on this review, but it's not related to publishing.  Is that the crash you're seeing, or is it something else?

**Comment by pkaminski** [comment]
Is this still an outstanding issue?  The error I found above was likely a transient due to a race condition when updating the review structure, and should go away when reloading the page once the review has settled.  I also hope to dispose of this whole class of errors more permanently by implementing a new data management framework that applies lessons learned over the last couple years.

**Comment by nox** [comment]
Not an issue anymore.
