### ISSUE TITLE
Icon for each commit is not that of the owner of the commit

### ISSUE THREAD

**Issue by hkurokawa** [Reviewable/Reviewable#35]
When there are more than one contributors in a Pull Request, I suspect that each icon (shown in the below screen shot) is the owner of the commit, not the owner of the Pull Request.

![_wip__ __ __-_1_unreplied_-_reviewable](https://cloud.githubusercontent.com/assets/6446183/5933428/ad1848ca-a703-11e4-83e2-e299add1c861.png)

[Steps]
1. Create a Pull Request as a user (User A)
2. Push a commit to the same branch as another user (User B)

[Result]
The icon of the commit at step 2 is the icon of User A

[Expected Result]
The icon of the commit at step 2 is the icon of User B

**Comment by pkaminski** [comment]
Thanks @hkurokawa, you're right: the synthetic "new commits" messages always use the PR's author.  The reason is quite simply that I haven't personally run into a multi-author PR workflow so failed to plan for it.  I'll fix things so that 1) commits by different people are never collapsed into one revision and 2) each commit batch's author is used as the synthetic message author.

@dannykopping also suggested that it would be useful if there was an indication on each delta line of who's responsible for the changes.  Would you find that useful too?

**Comment by hkurokawa** [comment]
@pkaminski Thank you for your prompt response.  Honestly, such an indication is nice-to-have but not strongly required feature for me.

In fact, I usually review revisions one by one and if you have done the above 1) "commits by different people are never collapsed into one revision", then I expect the author of all the changes in one revision would be the same person. Correct? Then, a per-line indicator is not so useful for me.

Of course, I do not mind if such indication exists.

**Comment by pkaminski** [comment]
Yes, with the new algorithm all commits within one revision will always be by one author.  The updated code is now deployed but will only take effect for new commits / reviews, not retroactively.  Please let me know if it doesn't work as expected.  Thanks!

**Comment by hkurokawa** [comment]
Great!  Thank you.  I will verify it.

**Comment by dannykopping** [comment]
Thanks :+1: will let you know once I see it
