### ISSUE TITLE
Resetting a review

### ISSUE THREAD

**Issue by SimonSapin** [Reviewable/Reviewable#353]
Sometimes a PR is rebased a number of times before formal review really starts. But in the meantime, Reviewable has recorded many revisions that are not relevant.

Is it possible to "reset" a review? Make Reviewable pretend that a PR is new, without closing it and creating a new one?

See for example https://reviewable.io/reviews/servo/servo/11886

**Comment by pkaminski** [comment]
No, there's no user-accessible reset for now.  This is not a problem in "combined commits" review style, since commits mostly just keep getting collapsed into `r1` until the formal review starts.  But in "review each commit style", with rebasing, it can get messy.

I've been resetting reviews manually for people in particularly bad cases but since this can cause some data to be lost I haven't put the power into the users' hands yet.  It may be possible to allow a reset only of unsnapshotted versions, though, which should be safe.  I'd need to think about it a bit more, and make space in the UI for such additional controls.

In the meantime, would you like me to kill the review above so it can be regenerated?  It doesn't look like anything got entered via Reviewable so there should be no data loss.

**Comment by pkaminski** [comment]
Actually, it occurs to me that you may be able to do this yourself after all.  Can you try switching the review style to "combined" then back to "each"?  Switching styles uses a special flag to delete all revisions that haven't been hard-snapshotted before rederiving them from current PR data, and in this case I only see soft snapshots in the review.  (There's no way to tell from the UI, though.)

And perhaps I could put a reset link in the review style dropdown, if some revisions have commits that are no longer in the PR (i.e., it's been rebased or otherwise had its history mangled).  Did you try looking there for it?

**Comment by SimonSapin** [comment]
Yes, if you could reset the one linked above that would help. Thanks!

**Comment by SimonSapin** [comment]
> Can you try switching the review style to "combined" then back to "each"? 

Yes, that helped! I’m back to 10 revisions (as many as commits) instead of 30+. Please disregard my previous message.

**Comment by SimonSapin** [comment]
My immediate problem is solved, but we can make this issue about making this trick more discoverable.

**Comment by SimonSapin** [comment]
> Can you try switching the review style to "combined" then back to "each"?

While this works, each of these actions take several minutes for me. Could this time be improved?

**Comment by pkaminski** [comment]
Having a reset button would help a bit, since it would skip the unnecessary switch to "combined" -- but probably not much.  I expect the time to be basically proportional to the number of generated revisions times the number of files in the repo; the latter is very high for `servo`, and the former will usually be much higher for "each" style than for "commit" style.  It might be possible to cut this down by reusing still-valid revisions when resetting, but this would require some tricky logic that I don't feel comfortable adding for such a minor feature.

**Comment by SimonSapin** [comment]
> times the number of files in the repo

This might be the highest factor. Could files unchanged by the PR (most of them) be excluded early in that process?

**Comment by pkaminski** [comment]
Not early enough, I'm afraid.  Reviewable can't use GitHub's list of changed files from the PR because of differences in semantics, and hence is pretty much forced to fetch the full tree of shas at each revisioned commit.  There are some tricks I could play with very large trees to prune them early but so far I've optimized for number of API calls (which is quota-limited) rather than total data size (which is not tracked).

The way to "optimize" this would be to do it in the background.  For example, instead of having a reset button, have a (per-repo?) flag to discard rebased commits and their revisions until the review has been visited (or a comment, or...).  It's not clear to me that such a rule could gain acceptance repo-wide, though, across all reviewers.

**Comment by pkaminski** [comment]
I made a small tweak to the code: until a review page is visited, all revisions will be considered expendable (unless a GitHub line comment gets attached to one) and will (usually) get replaced when new commits are pushed.  I'm curious to see if this will improve the situation sufficiently that an explicit reset button is no longer needed.  I'll ping this thread in a couple weeks to see what your experience has been.

cc @kcore

**Comment by SimonSapin** [comment]
In servo/servo, the way to start at "try" build on CI is to open a pull request and write a comment with the appropriate keyword. Sometimes, it takes several iterations of this to get everything right, each one pushing new commits or amending existing commits. And since master keeps changing in the meantime, the PR might be rebased a few times to resolved conflicts.

By the time the actual review starts, Reviewable often shows many more revisions than the PR has commits. As a reviewer, these extra revisions are just noise, they get in the way. But it’s not even clear to me that any subset of revision correspond to the commits as they are now. Switching to "combine commits for review" and back doesn’t always help.

This can make Reviewable so unusable for me that I give up and do the review on GitHub instead. That has happened more often than not in the last week :(

**Comment by pkaminski** [comment]
Sorry Simon, that's unexpected: toggling review styles back and forth _should_ reset a review to match the commits exactly as long as only top-level comments have been made (and Reviewable wasn't otherwise used before then).  Could you please point me to a PR where you ran into this issue, ideally before you started the review itself to limit confounding data?  Thanks.

**Comment by SimonSapin** [comment]
Is a top-level comment one that’s not on a specific line of the diff? Does it matter if it’s made through Reviewable or GitHub?

It’s https://github.com/servo/servo/pull/12945 and I see now that someone did comment inline through Reviewable.

My point though is that in our workflow, the rebase history of a PR often has to do with CI try builds. I’m not interested in reviewing the trial and error that lead to it, only the end result commits that are going to be merged. I’d like to have *some* way of viewing and commenting on the diffs of the commit as they are now in the PR, even if the location of previous comments is not accurate or if I need to go to a different view to see them in context. (I think there’s already UI for "the context of this comment isn’t accurate in this view" ?)

**Comment by SimonSapin** [comment]
> I’d like to have some way of viewing and commenting on the diffs of the commit as they are now in the PR

Sorry it took a lot of back-and-forth and complaining. I think the quoted bit is the core of my request.

(Also, one thing is that I don’t fully understand how Reviewable creates revisions for non-fast-forward pushes of various forms, so I tend to distrust their mapping to commits which is what I want to see.)

**Comment by pkaminski** [comment]
Yeah, any line comment -- whether made through Reviewable or GitHub -- will freeze the relevant revision and all the ones in front of it.  Comments can indeed be remapped but their location info is not fully encapsulated but rather relative to a revision, so once a line comment is in play that revision must be made immutable.  I don't see any way to relax this constraint.

As for your request, this is possible right now but awkward.  The current set of commits will be mapped to the tail of the revisions so you "just" need to figure out what revision corresponds to the "first" commit and start reviewing it diffed against base.  The file matrix will remain messy but I see that as more of a general UI issue, since it can be caused by all kinds of circumstances, not just the situation you described here.

Thinking out loud: perhaps it's the range proposal algorithm that's wrong?  Currently, in review-each-commit mode it defaults to starting at the next revision after the "last covered one", defined as the last revision for which you've marked all files as reviewed (modulo multi-party reviews, files unchanged between revisions, etc.).  Perhaps instead it should look only at the last rebased batch of revisions and diff them against the corresponding last-reviewed revision in the inferred rebase prior chain, falling back on the base.

Would that be a better interpretation of "review each commit" than actually stepping through literally every commit, including ones that have been rebased away?  (I suspect @jdm and probably others would be interested in this issue as well.)

**Comment by SimonSapin** [comment]
> The current set of commits will be mapped to the tail of the revisions so you "just" need to figure out what revision corresponds to the "first" commit

https://github.com/servo/servo/pull/12945 has 8 commits currently. Do the 8 last revisions always correspond to respective commits exactly?

The connecting lines at the top are not particularly useful when there is more than one:

![screenshot from 2016-08-22 14-50-23](https://cloud.githubusercontent.com/assets/291359/17855233/defa8e7a-6877-11e6-9e80-b4cbe57212ee.png)

**Comment by pkaminski** [comment]
The PR is at 10 commits as of this writing but yes, in general in a "review each commit"-style review for a PR with N current commits, the last N revisions will correspond to exactly those commits (and do so in this specific case).  There can be exceptions if revisions were captured earlier in "aggregate commits" style, or maybe if you do some manual mangling of the commit tree via git...

I agree that the "matching prior revision" lines didn't turn out to be very useful in non-trivial rebasing scenarios like this one.  :disappointed:  The visual language was optimized for when you rebase a sequence of commits as-is but gets very messy once you start adding/removing/reordering commits.  I'm not yet sure if an effective visualization for complex rebases even exists, or what an algorithm to generate one would look like.  This will require some R&D.

What I'm thinking of doing for now is marking "outdated" revisions (revisions that consists entirely of commits no longer in the PR) and tweaking the diff suggestion algorithm to only consider "current" revisions.  I think that should help quite a bit.

**Comment by pkaminski** [comment]
I've implemented the proposed changed: outdated revisions are marked by being struck out in the file matrix header, and only current revisions are considered for auto-diffing.  I also adjusted how the left bound of the diff is selected to walk back the chain of prior commits until one you previously reviewed is found, and otherwise to fall back on either the base revision (if priors exist), or the sequentially previous revision (if they don't).  I'm hoping this will improve the review workflow but it's almost equally likely that it will screw things up instead, so feedback from actual reviews would be very much desired.

I also decided to cut the (metaphorical *and* literal) Gordian Knot that were the prior revision arcs and settled on an alternative visualization that is much less "accurate" but will always remain readable.  Exact prior arcs are still available when hovering over revisions in a file tab's mini-matrix.  The matrix header of servo/servo#12945 now looks like this instead, which I think is a reasonable high-level approximation of the rebase wrangling that occurred:
![image](https://cloud.githubusercontent.com/assets/1646896/17887699/85a7e8a8-68dc-11e6-9136-b4468db76806.png)

**Comment by pkaminski** [comment]
@nox, can you say more about the issues you ran into with marking files as reviewed please?  I'd like to get these fixed while the details are still fresh in my head.  Thanks!

**Comment by nox** [comment]
What happened is that when I hit "next unreviewed diffs" it selects the next one but not for consistently for all files, and then "mark as reviewed" stayed grey.

**Comment by pkaminski** [comment]
OK, that would be a lot easier to debug if you could point me to a review and a specific diff configuration that got picked.  Or provide a screenshot thereof, and of the message explaining why "mark as reviewed" is unavailable.  Thanks.

**Comment by nox** [comment]
I will next time it happens.

**Comment by pkaminski** [comment]
Thanks for that example @jordanlewis!  It was instrumental in helping me figure out what was going wrong -- basically, the algorithm was getting confused by files whose revisions are all obsolete, but had previously been marked as reviewed.  I tweaked it a bit so hopefully it'll pick more sensible bounds now.  Please give it another try and let me know how it goes!

**Comment by jordanlewis** [comment]
Thanks for the quick turnaround, @pkaminski! I'm glad the example helped, and I really appreciate your willingness to take a look at this example.

Did you mean that you expect this very review to no longer exhibit the problem? For me, it still seems to - neither the "mark as reviewed" nor "next unreviewed diffs" buttons are clickable, even after manually selecting a revision range (I tried r46->r47).

**Comment by pkaminski** [comment]
Yes, Reviewable should no longer be proposing a default range of [r47,
r47], where all the files are already marked reviewed and hence the mark
all button gets disabled.  I tried to reproduce your review state in my own
account and saw both the problem as reported and the correct behavior after
the fix.  Did you remember to reload the page to get the new code? If so
and it's still not working can you please supply another screenshot of as
much of the file matrix as well fit on the screen and I'll take another
look. Thanks!

**Comment by jordanlewis** [comment]
I did reload - doesn't seem to have changed things just yet.

Here are some screenshots of the file matrix.

![image](https://user-images.githubusercontent.com/43821/32816557-49f3c8ba-c987-11e7-81bb-ada7f872f334.png)
![image](https://user-images.githubusercontent.com/43821/32816572-5a0af4da-c987-11e7-8da7-afefa26d19e9.png)

**Comment by pkaminski** [comment]
Gah, turns out I had only half-fixed it:  the diff bounds were right, but some of the undiffed files were still preventing the mark all button from activating.  Should be _really_ fixed now -- sorry about that!

**Comment by jordanlewis** [comment]
It's fixed! Thank you so much! Major 🙌 for being so responsive - I really appreciate it.
