### ISSUE TITLE
Unconnected PRs displayed

### ISSUE THREAD

**Issue by johnmcfarlane** [Reviewable/Reviewable#356]
My personal projects, e.g. (this one)[https://github.com/johnmcfarlane/fixed_point/pull/120], are showing up in the [reviews page](https://reviewable.io/reviews#). But I have "Show pull requests not yet connected to Reviewable" turned off. 

The repository in question is not connected and has the disconnected icon next to its name. The description for this icon is:
> If _icon_ is shown, the pull re­quest­s’s repos­i­tory is not con­nected to Re­view­able and the re­view will be up­dated on de­mand only, so the coun­ters may be out of date. An ad­min can con­nect the repos­i­tory from the Repos­i­to­ries page.

I would expect PRs from this repository not to show up on the reviews page and do not wish to see my personal projects listed in an (albeit great!) tool which I use exclusively at work.

**Comment by pkaminski** [comment]
Hi John, I think this is working as intended but there's some confusion about "connected PRs" vs "connected repos".  Your personal repos are indeed not connected at the moment but they were connected at some point in the past, which caused open PRs to be connected to Reviewable reviews.  After a repo is disconnected, the PR connections remain and the PRs will continue to show up in the review list even if "show pull requests not yet connected to Reviewable" is off.  New PRs won't be connected, however, and won't show up.

There's no way to disconnect a PR once connected to a review to guard against data loss.  Since your personal repos are now disconnected, one strategy is simply to wait: the connected PRs will be closed sooner or later, or after 14 days of inactivity will be treated as "stalled" and hidden from the list by default.  Another thing you could do is filter the list for your work organization's name and bookmark the filtered page.

I neither of these approaches are satisfactory, let me know and I can manually destroy all the reviews for your personal repos -- but this will be irreversible.

**Comment by johnmcfarlane** [comment]
Neither approaches is satisfactory. My personal repos were never deliberately connected. Also, I never deliberately connected any PRs. I just tested and it appears that simply clicking through the link to the unconnected PR in an unconnected repo is enough to connect it. This should at least be reversible by the user. 

Yes please, could you disconnect my non-zooxco PRs. There is no data to lose. 

As for filtering, thanks for the tip.

**Comment by pkaminski** [comment]
No problem, done.

**Comment by johnmcfarlane** [comment]
Many thanks.
