### ISSUE TITLE
App hangs when trying to diff some files with very long lines

### ISSUE THREAD

**Issue by richburdon** [Reviewable/Reviewable#357]
Midway through a long CR, the server stopped being responsive (long latency) but eventually (after 10s) returning the next file to review. But as I progressed the browser actually started crashing (Page Unresponsive) indicating the possibility of a busy loop in the JS code?

Consistent repo (for last 20 mins). Kill tab. Reopen review. Select next file. Browser hangs (across machines). No JS errors/logs evident in console.

Clicking publish (i.e., half way through review) is possible, but doesn't stop the problem.

Surely not too big a CR (about 80 files)?

**Comment by pkaminski** [comment]
The Reviewable server is actually not called upon in the scenario you described, so the issue is likely solely with the client.  I'll need some more details to investigate, though:
- What OS? Which browser(s) and versions?
- Which pull request?
- How large are the files / diffs?
- Do specific files (or file types) trigger the issue, or does viewing any file contribute a bit to slowing things down?
- Is the issue user-specific?
- You say that neither reloading nor publishing resolves the problem, which implies that some persistent state is the root cause.  The obvious candidate is comments.  Approximately how many discussions are there in the review?

While 80 files is not a small review, it's not huge either, and people regularly review PRs this large with any problems so something unusual must be going on.  Let's figure it out.

**Comment by richburdon** [comment]
hi piotr

   - OS/X 10.11.5
   - Chrome 51.0
   - https://reviewable.io/reviews/alienlaboratories/nx-lite/20#- (60
   files?)
   - No: just fails (consistently after 40 files); repro on multiple
   machines
   - Cannot test
   - maybe 50 short comments

yes, i agree, this isn't a large review; there are a number of JS binary
files, which may be large, but shouldn't (by design) be loaded by the
client (the client already says too large to display).

if this is client only, why would it fail after a certain point -- and as
you suggest -- even after reload? are there no xmlhttp requests? i must
have misunderstood you, because clearly there are -- otherwise my comments
would be lost.

btw, still in this state. to begin with it was in single file mode. at this
point, it's multi-file, but i cannot scroll -- the chrome tab just freezes
as soon as the page renders.

lmk if you have other questions.

**Comment by pkaminski** [comment]
> - No: just fails (consistently after 40 files); repro on multiple machines

Can you expand on this?  It always fails after visiting any 40 files?  Is it always on the same file?  That would make sense given the symptoms you observed: in single file mode it only crashed when you tried to switch to that file, whereas in multi file mode it crashes immediately because it tries to render the file when the page loads.  It might get tricky to identify which file it is now that you're in multi file mode -- are there any files in the review that you find especially suspicious, or that haven't been in a review ever before?

While binary files aren't (supposed to be) displayed, they do need to be loaded to verify that they are binary.  If the file is very large this may well be crashing _something_ -- though it's all done in a background web worker so shouldn't affect the UI.  Still, this is my working hypothesis right now.

Regarding the Reviewable server not being involved, it's literally true but doesn't mean quite what you think it means due to the app's unusual architecture.  The client talks directly both to Firebase (to load data and persist your comments) and to GitHub (to load the files), but doesn't issue any requests to Reviewable's own server while performing a review.

**Comment by richburdon** [comment]
Inline

On Tue, Jul 12, 2016 at 9:06 PM Piotr Kaminski <notifications@github.com>
wrote:

>
>    - No: just fails (consistently after 40 files); repro on multiple
>    machines
>
> Can you expand on this? It always fails after visiting any 40 files?
>
This is the first CR where it has failed in this way.

> Is it always on the same file?
>
I can't get past the current state. I'm approx 40 files into a 60-70 file
review. The app hangs as soon as the page renders.

> That would make sense given the symptoms you observed: in single file mode
> it only crashed when you tried to switch to that file, whereas in multi
> file mode it crashes immediately because it tries to render the file when
> the page loads.
>
Right.

> It might get tricky to identify which file it is now that you're in multi
> file mode -- are there any files in the review that you find especially
> suspicious, or that haven't been in a review ever before?
>
Again, in multi-mode, it just hangs as soon as it renders. E.g., there is a
scrollbar, but I can't move it.

> While binary files aren't (supposed to be) displayed, they do need to be
> loaded to verify that they are binary.
>
Well, I would expect you to do that on the server. That doesn't make much
sense to me. [EDIT: ok see below].

> If the file is very large this may well be crashing *something* -- though
> it's all done in a background web worker so shouldn't affect the UI. Still,
> this is my working hypothesis right now.
>
Right. But again, why on the client?

> Regarding the Reviewable server not being involved, it's literally true
> but doesn't mean quite what you think it means due to the app's unusual
> architecture. The client talks directly both to Firebase (to load data and
> persist your comments) and to GitHub (to load the files)
>
OK, I see now -- but yes, this is an usual architecture. I guess it's to
minimize load on your servers (i.e., not require routing all of github
through your machines). That makes sense.

> , but doesn't issue any requests to Reviewable's own server while
> performing a review.
>
I'm quite used to crashing anything I touch :), but am surprised I hit the
limit with this CR.

Ok thanks Piotr.

**Comment by richburdon** [comment]
ok looks like we had a very large JS binary.
we tried removing this from the CR, but still having the same issue.

**Comment by pkaminski** [comment]
I'd need to remove it from the review as well, since once a commit is captured in Reviewable it's immutable.  Can you tell me the path name?

I'm also pushing a patch right now that will always force single-file mode for that review so that you can more easily figure out / confirm which file is crashing it.

**Comment by richburdon** [comment]
We tried to remove the file from the review:
We this the files was: sub/botkit/dist/bot_server.js
But still locking up again on another file

**Comment by richburdon** [comment]
Accidentally closed. Reopening

**Comment by richburdon** [comment]
We have a lot more of these files -- removing them now.

We use webpack to build JS binaries -- that are composites of other libraries (e.g., jquery). They are about 1M in size.

**Comment by pkaminski** [comment]
Hmm, I took a quick look and it seems that the files are in the 100K to 500K range -- large, but by no means huge.  They should also be detected as minified files as long as the median line length is >500 chars.  Perhaps this heuristic is failing on your files?  Can you positively identify a file that's locking up Reviewable and give me permission to temporarily download it to my dev machine, so I can reproduce the issue and potentially fix the heuristic?  Thanks.

**Comment by pkaminski** [comment]
So I think what happened is that some of your webpacked files have a few very long lines (100K+) but don't trigger the long line detection heuristic because most lines in the file are short.  I tweaked the algorithm to deal with this shape of file so Reviewable should no longer freeze when it tries to diff them.  Give it a try!

**Comment by richburdon** [comment]
Thanks Peter. We'll try it out and reach back if there's an issue.

**Comment by richburdon** [comment]
working well for me now
