### ISSUE TITLE
Redirect after authorization fails when the original URL was a review.

### ISSUE THREAD

**Issue by erikwright** [Reviewable/Reviewable#369]
I sent this link to a colleague:

https://reviewable.io/reviews/Shopify/starscream/12075#-

They had never authorized before. When they followed the link and did what they were told to authorize, they got the following:

![image](https://cloud.githubusercontent.com/assets/187063/17258283/2998b688-5594-11e6-9c6e-7da01c742dc0.png)

**Comment by pkaminski** [comment]
I'm guessing he got this after signing in, but before the second-stage authorization to access private repos?  And that after he authorized `repo` scope (and reloaded the page) everything started working fine?

If my guess above are right, then I believe the bug is that the review sync request is issued as soon as a user signs in instead of waiting for permissions to be granted.  Will fix.

**Comment by pkaminski** [comment]
Fixed.  BTW, did your colleague get the "welcome" popup after the initial sign-in?  If so, that should've obscured the error anyway.

**Comment by pkaminski** [comment]
Fixed.  BTW, did your colleague get the "welcome" popup after the initial sign-in?  If so, that should've obscured the error anyway.

**Comment by erikwright** [comment]
Not sure. He just sent me that.
