### ISSUE TITLE
My own comments show up as needing a reply

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#371]
After I submit a review on someone else's PR, when I go back to the Reviews page, all of the comments I just left show up in red as needing reply. And when I re-visit the review, all of my own comments show up with an Acknowledge button. This is of course nonsense, and it means I can't tell whether there actually are any comments I need to look at or whether I'm just seeing all of my own comments highlighted.

**Comment by pkaminski** [comment]
Sorry about that Kevin, it might be a side effect of some recent changes to
discussion tracking. Could you provide a link to one such discussion so I
can investigate? Thanks.

On Aug 2, 2016 11:49 AM, "Kevin Ballard" <notifications@github.com> wrote:

After I submit a review on someone else's PR, when I go back to the Reviews
page, all of the comments I just left show up in red as needing reply. And
when I re-visit the review, all of my own comments show up with an
Acknowledge button. This is of course nonsense, and it means I can't tell
whether there actually are any comments I need to look at or whether I'm
just seeing all of my own comments highlighted.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Reviewable/Reviewable/issues/371>, or mute the thread

**Comment by kballard** [comment]
https://reviewable.io/reviews/postmates/getitnow-ios/1109

Right now I see 10 comments to reply to, and they're all my own.

**Comment by pkaminski** [comment]
Sorry, I was fighting another fire so I wasn't able to investigate the issue until now and the review has moved on.  However, I'm going to make a guess that the discussions in question were ones where you were the reviewer, in disposition `discussing - not OK`, and the reviewee simply acknowledged the discussion without replying.  This leaves the discussion unresolved, but it used to also leave it grey for everyone, i.e., not in anybody's court.  I've recently changed the behavior to make the discussion red again for the reviewer, to let them know that they should either poke the reviewee some more or change their disposition to `satisfied`.  (Did you perhaps end up doing the latter in this review, for those discussions?)

I can see how the red status with no new comments could be confusing, though.  Would it help if I added a synthetic "Author has acknowledged" note in the comment stream, and mark that as new?

**Comment by kballard** [comment]
I was the reviewer, in disposition `discussing - not OK`, but the reviewee had *not acknowledged anything yet*. The discussions went read literally immediately after I published them. And they had an Acknowledge button that did nothing if clicked.

**Comment by kballard** [comment]
It just happened again. I published comments on a new review and they immediately went red: https://reviewable.io/reviews/postmates/getitnow-ios/1112.

**Comment by pkaminski** [comment]
Arrgh, I was out at a meeting and looks like I didn't catch it in time again since there are now replies to all your comments.  :(  Can you try to post a comment on https://reviewable.io/reviews/Reviewable/demo/1 and see if it repros there?  Failing that, I'll be around my machine for the rest of the day and should be able to look into any further reports immediately.  Thanks.

**Comment by kballard** [comment]
It reproduced. I left a comment, the red comments number went from 7 to 8, and my own comment has an Acknowledge button. https://reviewable.io/reviews/Reviewable/demo/1#-KOGtDfrXkwmJnbBcYYT

**Comment by pkaminski** [comment]
Fixed, I believe.

**Comment by kballard** [comment]
Excellent. I just tried again on the demo PR and it appears to be fixed there, so I assume it'll be fixed the next time I do a real review too. Thanks!
