### ISSUE TITLE
Payment failed email goes to wrong address

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#379]
The email notification for the card associated with the account being declined is sent to the email for the Github account that set up the subscription, instead of being sent to the email address set as the receipt address.

**Comment by pkaminski** [comment]
This is intentional: I think of the receipt email address as an "FYI, for filing only" endpoint, since I assume it may be filtered into a secondary folder, or sent straight to accounting (who wouldn't know how to update a card in Reviewable).  All actionable messages go to the account's primary email address.  (If you have multiple addresses attached to the account they would ideally go to the one for the relevant organization, but GitHub doesn't share this routing table via the API.)

**Comment by kballard** [comment]
Ok I guess that's reasonable.
