### ISSUE TITLE
Google Chrome: Last File in File Matrix Cut Off

### ISSUE THREAD

**Issue by 7enderhead** [Reviewable/Reviewable#389]
- (all extensions disabled)
- ![image](https://cloud.githubusercontent.com/assets/339726/17853446/c5cdc1b6-686c-11e6-921c-7743cc54e421.png)

**Comment by pkaminski** [comment]
I'm not able to reproduce this so far.  Can you reproduce this at https://reviewable.io/reviews/Reviewable/demo/1 and post a full screenshot?  Also, what's the exact browser version and platform you're on?  The text looks large -- are you by any chance zoomed in?  Thanks.

**Comment by 7enderhead** [comment]
- Chrome Version 52.0.2743.116 m on Windows 7 Enterprise
- cannot reproduce on the demo site, I guess there are not enough files listed there
  - our review has 42 files
- problem persists with zoom reset to 100% (was at 110%)

**Comment by pkaminski** [comment]
OK, that matches one of my test environments pretty closely, so let's keep looking...
* Did you reload the page after resetting the zoom level?
* Can you reproduce on a somewhat larger public review, e.g. https://reviewable.io/reviews/servo/servo/12945 (32 files)?
* Does your review have any obsolete files, which would be mentioned under the total file count in the Changes panel?  If so, are they concealed or revealed?

**Comment by 7enderhead** [comment]
- yes, page was reloaded after zoom adjust
- no obsolete files in topic
- test topic shows only 31 of 32 files: 
![image](https://cloud.githubusercontent.com/assets/339726/17888533/b0cee97e-692b-11e6-8762-db9cb9849c1b.png)

**Comment by 7enderhead** [comment]
- review style drop down box contents also seem cut off:
 
![image](https://cloud.githubusercontent.com/assets/339726/17889088/dde5e5b8-692e-11e6-8aed-a4a339d796ed.png)

**Comment by pkaminski** [comment]
It appears that all element size computations are off in your case -- and as the matrix and dropdown height expressions don't share code, it's likely that there's a common root cause somewhere outside of Reviewable proper.
* Do you have custom font settings in Chrome?  A minimum font size perhaps?
* Do you have any accessibility settings turned on in Chrome or Windows?
* Can you reproduce this issue after disabling all extensions?
* Can you reproduce this issue in another browser, e.g. Firefox?
* Could you take a screenshot of the overflowing dropdown at 100% zoom please?

**Comment by 7enderhead** [comment]
> Do you have custom font settings in Chrome? A minimum font size perhaps?

- Yes:
  - PT Sans 17pt as standard and sans-serif font
  - PT Serif 17pt as serif font
  - Input as fixed-width font
  - minimum font size 14pt

> Do you have any accessibility settings turned on in Chrome or Windows?

- No

> Can you reproduce this issue after disabling all extensions?

- Yes, as already mentioned in initial post

> Can you reproduce this issue in another browser, e.g. Firefox?

- FF 48.0.1
  - default settings: ok
  - setting sans-serif to PT Sans -> problem occurs
- back in Chrome
  - resetting all fonts to defaults, no zoom level, no minimum size, no extensions:
    - file matrix still cuts off last entry
    - dropdown ok

> Could you take a screenshot of the overflowing dropdown at 100% zoom please?

- After playing around with the font settings (and several Chrome restarts), I cannot reproduce this anymore (even when going back to my original font settings):

![image](https://cloud.githubusercontent.com/assets/339726/17922796/2432027e-69e1-11e6-9c12-694ed9db20ed.png)

**Comment by pkaminski** [comment]
OK, I determined that the root issue was having a custom default font size.  While ideally Reviewable would respect that and conform to it, in practice this will require a lot of work on many of my layouts.  Since the workaround of using whole-page zoom is available I have instead set the root page font size to override user preferences.  This should solve the immediate problem.

Please feel free to open another issue to request conforming to user preferences if this is important to you.  Thanks.
