### ISSUE TITLE
Single-file mode should automatically advance to next file after review

### ISSUE THREAD

**Issue by erikwright** [Reviewable/Reviewable#395]
I've had two developers in a single day provide this feedback:

After clicking the "eye" on a file in single-file mode they expected the tool to bring them to the next unreviewed file.

**Comment by pkaminski** [comment]
I think overloading the behavior of the "file reviewed" button would be confusing, especially since it would only advance to the next file in some modes and it appears in other locations where advancing wouldn't be appropriate (e.g., the file matrix).  But I agree the functionality would be useful and intuitive, so my plan is to add a new widget at the bottom of each file that would specifically "mark as reviewed and go to next file".  Merging with #264.
