### ISSUE TITLE
Allow option to move the Reviewable badge from PR description to an initial comment

### ISSUE THREAD

**Issue by chrisleck** [Reviewable/Reviewable#397]
Our org has two problems with the existing Reviewable badge showing up in PR descriptions.
1. When we attempt to update a description shortly after requesting a PR (something fairly common for us), our edit fails as we conflict with the edit made by Reviewable to add the badge.
2. Our downstream tools are not equipped to deal with HTML blobs in PR descriptions.

It would be great if there were an option for us to have the badge appear in a comment rather than in the PR description.  Might be worth prototyping this out to see how it feels compared to the current in-description option.

**Comment by kballard** [comment]
Regarding (1), I think the biggest issue is that GitHub does not automatically update the description of open PR windows, even though it live-updates almost everything else about the PR. I would encourage you to send feedback to GitHub asking for them to fix this annoying issue.

**Comment by pkaminski** [comment]
My record for getting GitHub to implement features is hovering very close to zero, but sure, I'll try.

Another reason that has emerged for supporting in-comment badges is to allow single-click access to Reviewable from email on a fresh PR, rather than having to traverse via GitHub.  (PR edits don't trigger notifications.)  I find this fairly compelling and have raised the priority of this feature accordingly.

**Comment by kballard** [comment]
I actually meant @chrisleck should send feedback to GitHub about it, but hey, the more the merrier.

**Comment by pkaminski** [comment]
I've implemented badge placement control and added an in-comment option -- you can access it via the repo settings panel.  Note that it won't move any existing badges from the PR description to a new comment since doing so would fire a notification for every affected PR, which would be pretty spammy.

Could somebody please give it a try to verify that it works as expected before I announce the feature more widely?  Thanks!

**Comment by edmorley** [comment]
Thank you for adding this! I notice there's a `None` option in addition to "PR description"/"comment", however it's disabled. Is this intentional? If so, in what cases is it not disabled?

**Comment by pkaminski** [comment]
The option to turn off badges is only available for paid (private) repos,
as mentioned in the contextual help blurb.

**Comment by edmorley** [comment]
Oh I'd tried hovering over the disabled `None` but no explanation was given.

I see there is an explanation if I press "F1", press "h", click the zone around the option. (That's several clicks so wasn't something I realised was even there).

**Comment by pkaminski** [comment]
Hmm, any one of those should be sufficient: f1, h, or click on the pop-up.
If that's not the case could you open a bug please? Thanks.

**Comment by edmorley** [comment]
Filed #427 :-)
