### ISSUE TITLE
Confirm before back-merging to catch up a PR with base branch...

### ISSUE THREAD

**Issue by al-the-x** [Reviewable/Reviewable#400]
There's a little branch icon button buried in the "Status" UI that attempts to "catch up" a branch to the `BASE` when the merge status check on GitHub fails by performing a back-merge from `BASE` to `HEAD` with no confirmation.

That doesn't jive with our team's workflow of `rebase`-ing topic branches to `BASE` when out-of-date, and I have no idea how Reviewable would resolve a potential merge conflict. Regardless, adding commits to my branch _should_ require confirmation, IMO.

Related Qs: 

* Does Reviewable attempt to update the merge status _before_ issuing the back-merge? 
* What if there's nothing to catch up?
* What if there are conflicts?

**Comment by al-the-x** [comment]
I recognize that you're just using the GitHub "Update Branch" feature, which _also_ doesn't confirm, but it really should.

**Comment by pkaminski** [comment]
My feeling is that the button is small enough and sufficiently out of the way that it's unlikely to be clicked accidentally, and matching GitHub's no-confirmation behavior is a reasonable approach here.  Also, since it only affects `HEAD` you can usually force-push safely to undo the merge.

Would you like to be able to turn the feature off for your repos?

> Does Reviewable attempt to update the merge status before issuing the back-merge?

Not sure I understand: the merge status updates are independent from the back-merge action.  If the back-merge succeeds it may well make the branch mergeable, but Reviewable will wait for GitHub to confirm this before updating the status.

> What if there's nothing to catch up?

Ideally, the button will be disabled.  There may be corner cases where it's enabled anyway, in which case clicking it will be a no-op.

> What if there are conflicts?

The back-merge will fail with a 409 and the branch will remain unchanged.

**Comment by pkaminski** [comment]
Closing for now, please reopen if you have further thoughts.
