### ISSUE TITLE
Switches on Reviews page have different sizes

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#405]
A coworker just pointed out to me that the switches on the Reviews page have different thumb sizes between the off and the on states. And he's right. The red "off" state isn't actually circular, it's more ovoid, but the green one is circular.

![screen shot 2016-10-06 at 5 46 15 pm](https://cloud.githubusercontent.com/assets/714/19175609/148eec00-8bed-11e6-930d-117b5549681e.png)

**Comment by pkaminski** [comment]
Your eyes are lying to you.  😝  Both toggles are set to 0.75em square, which translates to 9.75px, but due to differing alignments against the screen's pixel grid are rendered unevenly by the browser.  I'd say it's more of a browser bug (elements with the same dimension should have perceptually equal sizes) but I doubt they'll fix it.  Changing the dimensions to whole pixels would work around the problem but 1) font-relative sizes are nice, and 2) I don't want to start tweaking UI framework metrics case-by-case.  If you know of a way to tell CSS to round metrics to the nearest pixel that would be great, but otherwise won't fix, sorry.
