### ISSUE TITLE
Feature request: an option to merge PR once checks pass

### ISSUE THREAD

**Issue by dimonomid** [Reviewable/Reviewable#412]
Our team has complex CI which might run for 3-15 minutes, and it is really often desirable, especially on small PRs, to ask reviewable to merge the PR once CI is happy.

Otherwise the reviewer has to keep in his head that after a few minutes he/she has to get back to this PR, and if checks are passed, merge it.

So, it would be awesome if this feature is implemented!

Thanks.

**Comment by pkaminski** [comment]
One issue with the feature as proposed is what happens if the CI fails?  We'd need some sort of notification to the reviewer that the CI isn't going to get merged automatically after all.

Also, I think this might be a good fit for a separate tool, since it just needs to watch a PR's status (including Reviewable's review status) and merge when everything is green.

**Comment by dimonomid** [comment]
Well, makes sense. By the way we already have notifications in our CI: when build fails, email is sent to the PR's author. Probably we could improve it so that it can merge the PR e.g. if there is "LGTM".

So yeah, probably it's not a very appropriate thing to implement in Reviewable after all..

**Comment by pkaminski** [comment]
Yep, or just check the [head commit's status](https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref) via the GitHub API.  You can make Reviewable a required status check to ensure there's no window of opportunity for bypassing it.
