### ISSUE TITLE
Add a "Please melt my CPU" button or setting

### ISSUE THREAD

**Issue by SimonSapin** [Reviewable/Reviewable#423]
I first mentioned this on Twitter: https://twitter.com/reviewableio/status/799300532330315776

Reviewable seems to have several features designed to avoid having the browser do a lot of work at once: when a PR touches many files it automatically switches to only showing one file at a time. When clicking to switch to multi-file view anyway, it will not show some diffs at first with "Diff skipped to avoid melting down your CPU." and a "Show diff" button instead.

These features are probably great to some people, but they’re the opposite of what I want.

First, the "skipped" diffs sometimes are loaded when they are scrolled into view, but this seems somewhat random or unreliable. Some other diffs will stay unloaded. Then the "Show diff" buttons have to be chased around in order to click them, since they move as other diffs above them get loaded.

More generally, any kind of lazy loading means that the work/wait not done upfront will be done during the review, when going from one file to the next. It becomes an interruption/distraction. In a PR that I reviewed recently, 158 files were modified when something was renamed. Since these changes are very systematic, I can spend very little time per file, and want to switch to the next diff as quickly as possible.

I’d personally prefer to have some way to load everything up-front (without hunting many "Show diff" buttons), even if that takes minutes. I can read Twitter in the meantime or something.

**Comment by pkaminski** [comment]
FYI, there'll be a "show all the diffs at my own peril" button in the next major version that will override all performance-related redaction.

**Comment by SimonSapin** [comment]
Thanks!

**Comment by pkaminski** [comment]
Now live on https://beta.reviewable.io.

**Comment by hatton** [comment]
I just had a PR where several files were deleted in the middle, and thus had diffs omitted. Great. But my eyes saw those and didn't see that in among them was a file that was hidden because the diff was "too big". This coded turned out to be the *heart of the PR*, and I only eventually found it because I felt some code must be missing... I couldn't figure out how the PR would actually work. So I asked, and a teammate has had the same problem, missing things he needs to review because Reviewable hid it. So we went looking for a setting to stop this behavior... it's just way too risky. Couldn't find anything.  Reading through github issues, finally found this new feature via this issue. Still couldn't find it. I had to ctrl+f search the page to find this new "at my own peril" button. So any of 3 things would help:
1) Give a setting that just never hides diffs of files
2) Use a bright color to draw those hidden files to the reader's attention, so that they don't look the same as deleted-file entrie3
3) Put the "at your own peril" box at the very top and give it a bright color that will draw attention.

Thanks. Still in love with Reviewable, regardless.

**Comment by hatton** [comment]
Just discovered the custom css capabilty of Reviewable. Added

```
span[ng-switch-when="bigdiff"] {
    background-color: orange;
    font-size: 20pt;
}
```
which gets me:
![image](https://user-images.githubusercontent.com/8448/38585369-d1d3274a-3cd6-11e8-9c00-ffa756d53f76.png)

Satisfied.

**Comment by pkaminski** [comment]
I didn't rush to respond since you had resolved the problem, but you make a good point: some of these messages need to be more noticeable.  While I'm not willing to go _quite_ as far as your custom style by default, I did raise the level of selected messages to 'warning' and made the warning sign a bit more colorful to attract attention.  Hopefully this will help others.  Thanks!

As for the "at your own peril" button, it will find a new, better place in an upcoming UI rework.
