### ISSUE TITLE
Reviewable doesn't recognize vendored or generated files.

### ISSUE THREAD

**Issue by tmc** [Reviewable/Reviewable#426]
Github will show 'Diff surpressed. Click to show' for vendored or generated files (mostly working wiht Go).

**Comment by pkaminski** [comment]
GitHub doesn't expose its heuristics through the API so Reviewable needs its own.  It has a bunch of filename patterns hardcoded in and also looks for [marker comments](https://github.com/Reviewable/Reviewable/wiki/FAQ#how-do-i-tell-reviewable-that-a-file-is-generated-and-should-not-be-reviewed) in files.  For Go specifically it looks for paths that starts with `Godeps/`, which I'm told is (was?) where Go dependencies are stored.

I'm happy to add any other pattern (path or content) you can suggest as long as it's not likely to cause too   many false positives.

**Comment by chancez** [comment]
@pkaminski Could you do `vendor` as well?

**Comment by pkaminski** [comment]
Oops, I forgot to follow up and close this a while ago.  Instead of hardcoding these patterns into Reviewable you can now define them in your repo using a `.gitattributes` file.  Basic instructions here: https://github.com/Reviewable/Reviewable/wiki/FAQ#how-do-i-tell-reviewable-that-a-file-is-generated-and-should-not-be-reviewed
