### ISSUE TITLE
Link to GitHub PR on Review page

### ISSUE THREAD

**Issue by lsanwick** [Reviewable/Reviewable#43]
Just a minor request, is there any chance you could have the title of the review link back to the PR in GitHub? Or provide a link somewhere nearby if you don't want to linkify the title?  Would simplify the flow of merging a completed review, as I currently open a new tab, go to the PRs page, find the one that's been reviewed, click through to it, and then merge it.  

As another possibility, providing a merge button on the Reviewable page would also be great!

**Comment by pkaminski** [comment]
Hey @lsanwick, as it turns out the top-level discussion in Reviewable has a link to the PR in its top-right corner (where line-level discussions would normally have a line-specific link).  You can quickly jump to this discussion from the "bunny" menu off the floating status bar.  And yes, I know we need better onboarding to help folks find all this stuff.  :blush: Putting a merge button into Reviewable is also on the todo list but feel free to open a tracking issue for it.  Thanks!

**Comment by lsanwick** [comment]
Ahh, thanks, found it! It definitely is kinda hidden if I didn't know what I was looking for. :)
