### ISSUE TITLE
Use Github Pull Request Review API when posting multiple comments?

### ISSUE THREAD

**Issue by ibrahima** [Reviewable/Reviewable#437]
Now that this is available in preview, would it make sense to use the Pull Request Review API?https://developer.github.com/changes/2016-12-14-reviews-api/ This would probably make it possible to post multiple comments and have them actually appear as line comments, without sending multiple emails. Not completely sure if everything would work perfectly at this stage, but it'd be a nice feature to have in the future!

**Comment by pkaminski** [comment]
Yep, I'm looking into this.  Compatibility with GHE and support for email replies are two initial concerns.

**Comment by rjbell4** [comment]
FYI, this is fully compatible with GHE now

**Comment by pkaminski** [comment]
With the latest version of GHE, yes.  Not everyone is on it though.

**Comment by pkaminski** [comment]
So, I started digging into this and it's *still* not possible!  The API doesn't allow posting threaded comments, or posting comments on more than one commit in the same batch.  GitHub's UI does allow both these things so it's not impossible that the API will as well at some point, but it's been over a year since it went GA so clearly they're not in a hurry.

The lack of those two features compounded by the git-diff-only comment positioning system would make for a sufficiently terrible (and inconsistent) experience that I don't think it's worth implementing at this time.

**Comment by Pyton** [comment]
Ok, but there is API for posting batch of comments per commit:
https://developer.github.com/v3/pulls/reviews/#create-a-pull-request-review

Is this cannot be used to achieve the goal of creating comments per line per file? I believe yes.

**Comment by pkaminski** [comment]
This is precisely the API we're discussing here, and the (current) limitations listed above make it essentially unusable, yes.

**Comment by Pyton** [comment]
Is there any reason why can't implement sendint multiple API request with different commits? 

About threads could you explain what you mean?

**Comment by pkaminski** [comment]
GitHub sends one notification to users per request, so using multiple requests for a single Publish is a non-starter.

As for threads, the API doesn't support "replying" to comments.  All comments posted via the API will start a new thread, even if it's on the same line as a previous comment.  This will completely mess up conversations if some people are actually using the GitHub UI.

The other flaw alluded to above (that is not specific to this API but relevant) is that in GitHub comments can only be posted on lines that appear in the `git` delta.  Besides the difficulty in mapping target lines over any comments placed on lines not in range of the delta will need to be rendered as top-level comments anyway.

**Comment by AlecBenzer** [comment]
> GitHub sends one notification to users per request, so using multiple requests for a single Publish is a non-starter.

Is it? It's certainly non-optimal, but if the multiple emails came all at once at publish time (and not one at a time as the reviewer makes comments), I'd think that'd be pretty acceptable for certain folks. Personally, I think I'd make that trade.

**Comment by pkaminski** [comment]
Many customers also use chatroom notifications for published comments, and those don't collapse nicely like emails do in Gmail, so I still don't think this is workable.  Besides, this wouldn't address the other limitations listed above.

**Comment by AlecBenzer** [comment]
Oh, well I was imagining this being opt-in or something, not turning it on for everyone by default. I agree I see the latter as potentially causing major issues.

> Besides, this wouldn't address the other limitations listed above.

I guess that's true -- is the major missing piece the ability to reply to comment threads?

**Comment by pkaminski** [comment]
> Oh, well I was imagining this being opt-in or something, not turning it on for everyone by default. I agree I see the latter as potentially causing major issues.

But who would opt into it?  It affects the receivers rather than the sender, and different receivers may have different opinions on the matter, yet we can't send a review both ways at once.

> I guess that's true -- is the major missing piece the ability to reply to comment threads?

Threading and accurately targeting lines.  (Some lines are not targetable even in theory under GitHub's API!)

**Comment by cjancsar** [comment]
@pkaminski do you know if any improvements have happened for GH yet to allow this? We are want to continue using reviewable but also use Codeclimate Velocity (which analyzes commit comments etc.) and the two tools are incompatible due to the grouping of comments.

**Comment by pkaminski** [comment]
Thanks for the ping @cjancsar!  It doesn't look like there's any changes to the REST API, but I do see some new stuff in the GraphQL mutations that might be helpful.  I'll need to play with things a bit though since, as usual, the documentation is minimal.  At first glance it looks like the API resolves _either_ the "replies" issue _or_ the "lines outside diff" issue, but not both at the same time (!).

**Comment by pkaminski** [comment]
So after digging through the API some more, it looks like (maybe) it's now possible both to post replies and situate comments on an arbitrary line [1].  However, each review is still limited to a single commit, so if you create comments on multiple revisions it appears that Reviewable would have to send out a commensurate number of separate reviews.  (AFAICT replies can follow up on threads attached to other commits.)  I'm guessing this might be a reasonable trade-off for "aggregate commits" style reviews, where most new discussions will be created on the latest revision, but perhaps not for "commit by commit" style reviews.  And I don't think we want to have two different comment sending styles, from either a user confusion or code maintenance standpoint.

Thoughts, anyone?  @dhbradshaw?  Also, if anyone has experience with the `addPullRequestReview`, `addPullRequestReviewComment`, and `addPullRequestReviewThread` mutations I'd love to pick your brain.

[1] The API lets one specify "the line of the blob to which the thread refers", which seems promising, but then it also asks for "the side of the diff on which the line resides", which I can't make sense of.  🤷‍♂️

**Comment by chandlerc** [comment]
FWIW, I think comments across multiple commits triggering multiple notifications is a very reasonable trade-off. Common cases won't even hit it, and for larger reviews within a team on a project, they can adapt their notification settings to cope with it.

If this further unblocked suggested edits, I think I know multiple teams that would at least become much more interested in reviewable. Not sure if it would fully catch on, but would remove serious blockers without adding new ones (for those teams).

I do understand that others might find the multiple notifications problematic, but not sure what to do there...

**Comment by tamird** [comment]
@pkaminski 
 
> [1] The API lets one specify "the line of the blob to which the thread refers", which seems promising, but then it also asks for "the side of the diff on which the line resides", which I can't make sense of. 🤷‍♂️

Isn't the side of the diff just "before" or "after"? It seems necessary to provide that in order to identify a line.

**Comment by pkaminski** [comment]
@tamird

A blob doesn't have sides, so a line number in a blob uniquely identifies a line.  Sides are only needed if the line target is in a diff of two blobs, but then the diff would only contain deltas (plus context lines), which wouldn't support Reviewable's capability of making comments on any line.  My only guess is that the input data is a union of old-style (diff-based) and new-style (blob-based) properties, but if so it's really not well documented.

**Comment by tamird** [comment]
I had a long talk with ChatGPT about this. Some things I learned:

> There's also the confusing part about "the side of the diff on which the line resides". When looking at a PR diff on GitHub, there are two "sides":

> The left side represents the "base" or original code.
The right side represents the new changes or the "head".
When a comment is made on unchanged parts of the code or on deletions, it's made on the left side. When it's made on additions or modifications, it's usually on the right side.

Regarding comments "on each commit":
> The limitation you're facing is fundamental to how GitHub structures its review data model, where reviews are generally tied to a PR's current state rather than individual commits. Even in the web interface, when you comment on lines from multiple commits and submit a review, those comments are all technically associated with the PR's current state. The only indication that a comment pertains to an older commit is when the web interface displays "Outdated" next to that comment.

I think the takeaway is that GH reviews are always implicitly associated with the head of a pull request. I played around with the web UI and confirmed that even reviews done in the web interface plop all the comments on the head commit, not on whatever commit the user was viewing when they authored the comment.

That means reviewable can just:
- Start a review on the head commit using addPullRequestReview
- For each commit with comments:
  - add each comment with addPullRequestReviewThread
  - post replies to existing threads with addPullRequestReviewThreadReply
- submitPullRequestReview

It seems like everything is in place to move this forward. @pkaminski do you agree?

**Comment by pkaminski** [comment]
It's likely that some combination of parameters can make these API calls work, though the relation between `line` and `side` is still unexplained.  I'm especially heartened by this note on `AddPullRequestReviewInput`:

> Upcoming Change on 2023-10-01 UTC Description: `comments` will be removed. use the `threads` argument instead Reason: We are deprecating comment fields that use diff-relative positioning.

However, we have other priorities at the moment.

**Comment by pkaminski** [comment]
Latest update:
- The old comments API based on diff-relative lines is (about to be) removed.  Good riddance!
- The thread-based API is based on blob-absolute lines, which makes placing comments much easier, but it's somewhat deceitful:  if you specify a line outside the `git` diff deltas the thread is rejected as unprocessable.
- The thread query API exposes both `line` and `originalLine`, which may be relative to a different commit.  However, there's no apparent way to post threads on different commits in a single review via the API; this functionality is only available via GitHub's UI.
- It is possible (as of very recently) to post replies to threads that were made on any commit within a single review, so that's good.
- There's no way to post threads within a review that are not attached to a file.

As it stands this would make an integration both tricky and somewhat low quality:
- We would need to fetch the original `git` diff from GitHub (which is not the same as Reviewable's internal diff) to figure out which discussions can be posted as threads and which would need to be flattened into the top-level message.  You'd likely see a mix of both in any given review.
- If there are new discussions on more than one commit, we'd need to map them all to lines in a common one.  This would both be potentially confusing since some threads would be associated with the "wrong" commit in GitHub, and inaccurate if we can't map the discussion line accurately across commits.  Commit-by-commit reviews would suffer the most.
- We'd still need to flatten top-level discussions into the main review message as we currently do, though this is not a big deal.

**Comment by pkaminski** [comment]
GitHub has the following two items on its roadmap, though they're not on the schedule at least through Q2 2024:
- https://github.com/github/roadmap/issues/552
- https://github.com/github/roadmap/issues/347

**Comment by pkaminski** [comment]
After thoroughly reviewing this issue and #803, we decided that it's not possible to offer a good mixed-platform experience where part of a review is done in Reviewable and part on GitHub, due to both irreconcilable differences in semantics and limitations in GitHub's APIs.  This situation doesn't seem likely to change in the foreseeable future, though we can certainly revisit if it should do so.

In the meantime, our philosophy is that if Reviewable is used at all on a PR then it needs to be used by all human users.  We'll only support bots interacting through GitHub on a best-effort basis (e.g., by syncing GitHub line comments into Reviewable, threading replies to such comments correctly, and propagating Reviewable discussion resolutions back to GitHub).  This is admittedly limiting and means that some teams who can't come to a consensus won't be able to use Reviewable, but we think it's the right trade-off to make — the alternative would be to either offer an experience with a number of pitfalls, or to have Reviewable become a mere alternative UI for GitHub, and we're not on board with either of these.
