### ISSUE TITLE
3+ comments when there's really only 11

### ISSUE THREAD

**Issue by romrell4** [Reviewable/Reviewable#438]
I just think it's kinda interesting the that the reviewable shows "3+" instead of "11". See attached screenshot
![screen shot 2016-12-19 at 11 04 25 am](https://cloud.githubusercontent.com/assets/15692420/21325413/1c0e2d74-c5db-11e6-97a1-5bbd2c8cff5c.png)

**Comment by pkaminski** [comment]
Yeah, that's "3+" unreviewed files (not comments), and it's expected when the review has potentially renamed files (i.e., some files deleted and some added at matching revisions).  Because rename pairs are computed dynamically using data that's not loaded on this overview screen (to save bandwidth), it shows a lower bound estimate instead.  This could be improved upon but, since you classify the issue as just "kinda interesting", I'll leave it as "won't fix" for the time being.  :)
