### ISSUE TITLE
Off by one error in LGTMs obtained count

### ISSUE THREAD

**Issue by helin24** [Reviewable/Reviewable#440]
This is under the 'commit checks' menu: 

<img width="472" alt="screen shot 2016-12-21 at 4 56 56 pm" src="https://cloud.githubusercontent.com/assets/6379305/21571391/b2425300-ce83-11e6-8261-65acc155f82e.png">

**Comment by pkaminski** [comment]
Could you please post the full review completion condition script you're using?  I'm guessing it's a copy of the example one, but that has changed a few times over its lifetime.

**Comment by pkaminski** [comment]
Ping.

**Comment by helin24** [comment]
```
// The number of LGTMs required to merge.
let numApprovalsRequired = 1;
// Approval by username: true if current LGTM, false if stale,
// missing if not given or canceled.
let approvals = {};
// Timestamp of the currently latest revision.
const lastRevisionTimestamp =
  _.last(review.revisions).snapshotTimestamp;
_.each(review.sentiments, function(sentiment) {
  const emojis = _.indexBy(sentiment.emojis);
  if (emojis.lgtm_cancel) {
    delete approvals[sentiment.username];
  } else if (emojis.lgtm_strong) {
    approvals[sentiment.username] = true;
  } else if (emojis.lgtm && !approvals[sentiment.username]) {
    approvals[sentiment.username] = true; // timestamp
  }
});
const numApprovals = _.countBy(approvals);
let numGranted = numApprovals.true || 0;
let pendingReviewers = [];
const assignees =
  _.pluck(review.pullRequest.assignees, 'username');
if (assignees.length) {
  numApprovalsRequired = 1;
  //  _.max([assignees.length, numApprovalsRequired]);
  pendingReviewers =
    _(assignees)
    .reject(username => approvals[username])
    .map(username => ({username}))
    .value();
}
let description =
  numGranted + ' of ' + numApprovalsRequired + ' LGTMs obtained';
let shortDescription =
  numGranted + '/' + numApprovalsRequired + ' LGTMs';
if (numApprovals.false) {
  description += ', and ' + numApprovals.false + ' stale';
  shortDescription += ', ' + numApprovals.false + ' stale';
}
return {
  completed: numGranted >= numApprovalsRequired,
  description, shortDescription, pendingReviewers,
  debug: approvals
};
```

**Comment by pkaminski** [comment]
Thanks -- looks like you tweaked the script slightly but it shouldn't matter.  I don't see how the code above could produce the `-1` in your screenshot, since it's just using the value of `numGranted` which is taken directly from the results of `_.countBy`.  And unless Lodash has a pretty egregious bug the values there will always be strictly positive.

Could you please point me to the PR in question (email to support@reviewable.io if you'd rather not post the link publicly) so that I can check whether there's any oddities in the underlying data?  But if I don't spot anything there I'll probably need to catch a PR in the buggy state to be able to investigate.  Thanks.

**Comment by helin24** [comment]
Okay, this may have been resolved - I'm not the one managing the script, so it may have been changed since that issue arose, in which case maybe it's not a bug after all. I'll reopen if otherwise. Thanks!
