### ISSUE TITLE
Allow assignee directives in the PR description

### ISSUE THREAD

**Issue by arosequist** [Reviewable/Reviewable#443]
Currently, [+@](https://headwayapp.co/reviewable-changes/multiple-assignees-2793) only works within comments. It would be nice if it also worked when used from the PR description.

An example use case: we have some repos where all PRs created should be (at least initially) assigned to a particular group of people. It would be nice if we could +@ all of them in our [PR template](https://github.com/blog/2111-issue-and-pull-request-templates) to decrease manual clicking and user error when creating PRs.

**Comment by pkaminski** [comment]
Upon further reflection, I'm having second thoughts about this feature.  The problem is that PR descriptions can be (and often are) edited and it's not clear if there's any way to handle edits in a reasonable manner.  The main problem is that there's no event or (distinct) timestamp to indicate that the description was edited, so it would be hard to process edits in a timely fashion or ensure they weren't processed multiple times (perhaps overwriting later assignee changes).  It's also not clear how to interpret edits: for example, what should be the semantics of deleting a `+@username` directive -- remove the assignee, do nothing, ...?

While comments can be edited as well it's much more rare.  Also, GitHub fires events when comments are changed and has a last-edit timestamp, so Reviewable simply processes each comment once and doesn't look for directives on edits.  I don't think I could use this strategy with PR descriptions, though.  (See #287 for background on supporting directives in GitHub-originated comments, and how I eventually came around on the idea.)

It sounds like feature #288 would also address your use case more directly.  While I agree that not supporting directives in PR descriptions is surprising, I'm not convinced that doing so subject to the limitations above would reduce confusion sufficiently to counterbalance the additional complexity.

Thoughts?  (Also @mikesokolsky.)

**Comment by arosequist** [comment]
Yes, #288 would be a much better way to address my use case.

Thanks for describing the implementation problems with this; it's a shame that Github doesn't send events for description edits.
