### ISSUE TITLE
Editing repo settings should offer to change all repos with matching settings

### ISSUE THREAD

**Issue by lilyball** [Reviewable/Reviewable#448]
A number of our repos have identical customized settings. Whenever I customize the settings further, I have to remember which repos are supposed to match it, which is very error-prone. It would be nice if Reviewable had an option to let me auto-select all repos that match the same (un-edited) settings, so I can update everything that matches.

Also see #447, which proposes an alternative approach that obviates the need for this (but is a much larger change).

**Comment by pkaminski** [comment]
This is how I wanted it to work originally, but decided against it because if admins with varying levels of access start editing settings you'll end up with unexpectedly disjoint groups.  Guarding against this without revealing information about repos people don't have permissions for gets tricky but perhaps I can give it another try.  I think if I could detect this condition as soon as you open the settings panel and just say "N repos that you don't have admin access currently share these settings, and won't be updated with your changes" it might be OK, though.

**Comment by kballard** [comment]
That warning sounds like a great way to handle this.

**Comment by pkaminski** [comment]
Closing in favor of #447.
