### ISSUE TITLE
Store review completion condition in-tree

### ISSUE THREAD

**Issue by david-german-tri** [Reviewable/Reviewable#457]
On [RobotLocomotion/drake](https://github.com/RobotLocomotion/drake), our "review completion condition" is getting pretty complicated.  It would be awesome if we could version it in-tree.

**Comment by pkaminski** [comment]
It would be awesome but I don't think it's feasible.  The basic problem is that Reviewable needs to run the condition all the time, and the context doesn't always have an authorized user to impersonate to fetch the file from GitHub.  A secondary concern is the added latency / additional point of failure on such a fundamental computation.  I could imagine some kind of caching scheme but I'm afraid it would add a fair bit of complexity and lead to hard-to-debug failure modes.

My hope when designing this feature was that, after an initial spurt of adjustments, the condition would be fairly stable.  If that's not the case for you I'd be interested to understand why.  In the meantime, all I can recommend is to keep the condition checked-in manually and copy it into Reviewable when you change it.  Sorry.

**Comment by david-german-tri** [comment]
> My hope when designing this feature was that, after an initial spurt of adjustments, the condition would be fairly stable. If that's not the case for you I'd be interested to understand why. 

We keep adding new policies for particular subdirectories: approval from X is required here, and approval from Y is required there.

> In the meantime, all I can recommend is to keep the condition checked-in manually and copy it into Reviewable when you change it. 

Makes sense!  Thanks for the reply.

**Comment by pkaminski** [comment]
> We keep adding new policies for particular subdirectories: approval from X is required here, and approval from Y is required there.

Makes sense.  I've been thinking about a feature that would automatically pull additional metafiles from directories affected by the PR and provide them to the condition code (that, e.g., could hold a list of approvers for a subtree), but this runs into the same problems as keeping the condition in the repo to begin with.  I also know at least one customer that actually pulls additional data into the condition via an HTTP request, which gets a bit tricky (and adds another point of failure) but could be an option.

I'm going to keep thinking about ways around the problems above, but will close this issue for now since I don't see a way forward at the moment.

**Comment by DamienCassou** [comment]
I also think it would be a nice feature but I understand your point.
