### ISSUE TITLE
Set of changed files differs between GH and reviewable

### ISSUE THREAD

**Issue by jwnimmer-tri** [Reviewable/Reviewable#468]
See https://github.com/RobotLocomotion/drake/pull/5796 vs https://reviewable.io/reviews/RobotLocomotion/drake/5796.

Github shows only 1 file changed (correct) but reviewable shows me 28 files changed.  The PR was fine at the start, but some recent push seems to have confused reviewable?

**Comment by pkaminski** [comment]
Thanks, looking into it now.  It appears that Reviewable failed to correctly track changes in `master` -- it's still diffing against the state from two days ago.  I'll see if I can figure out what went wrong.

**Comment by pkaminski** [comment]
A forced resync (not user-accessible) has fixed this instance of the issue but I can't figure out the root cause.  My best guess is that the GitHub API reported an old base commit for the PR when the latest commit was pushed.  Even if that's the case I don't know how to protect against it, though.  Please report again if you notice this kind of discrepancy and perhaps I'll spot a pattern... Thanks!
