### ISSUE TITLE
Retro-BTW would be useful

### ISSUE THREAD

**Issue by david-german-tri** [Reviewable/Reviewable#469]
Suppose you've posted a comment:

`Gosh, you should really change this!`

Then, after further reflection, you realize you really meant:

`BTW, did you consider this other approach?`

There doesn't seem to be a way to convert your disposition retroactively from "Discussing, and I must acknowledge before the issue can be resolved" to "Discussing, but the author can resolve the issue without further input from me".  Your only option is to go all the way to "Satisfied", which resolves the thread and doesn't demand the author's attention at all.  

One possible approach: let the BTW-ness of a given user's last comment govern that user's disposition for the whole thread.  Example: https://reviewable.io/reviews/RobotLocomotion/drake/5797#-KhY2prPhOPDV5492Z19

**Comment by pkaminski** [comment]
Hey David, apologies for the very late reply -- finally cleaning out my inbox.  :)

Actually, while switching to "Satisfied" will resolve the discussion, it _won't_ hide it from the author: it'll still count as unreplied and show up with a red counter.  (Switching to "Withdrawn" on the other hand will resolve and hide.)  So I think it's a reasonable workaround in this case.  BTW-ness is purposely not retroactive since in multi-party reviews it's possible that you do want a previous comment to be acknowledged by everyone (and it may have already been acknowledged by some), but still want to add an FYI follow-up.

At a higher level, though, I agree the current system is baroque and rather confusing.  I'm looking forward to a redesign at some point.

**Comment by pkaminski** [comment]
Closing in favor of #510, which redesigns the discussion system and gets rid of this corner case.
