### ISSUE TITLE
Review each commit separately doesn't always correspond to PR commits 

### ISSUE THREAD

**Issue by marun** [Reviewable/Reviewable#479]
When reviewing https://github.com/kubernetes/kubernetes/pull/46527, I wanted to review only one of its 2 commits since I had reviewed the other commit in a different PR.  I attempted to use 'Review each commit separately' but the first set of unreviewed diffs included changes from both commits.  Is this working as expected?  I've been having to fall back to using github reviews in cases like this, and I'd really prefer to be able to use reviewable.

cc: @thockin

**Comment by pkaminski** [comment]
Hey Maru, looking at https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/46527 it appears that each revision holds just one commit (`r1` is `a37c004` and `r2` is `bab423e`), so that part seems to be working fine.  Is the issue that the automatically selected diff when you loaded the review was `⊥..r2` instead of `⊥..r1`?  If so, it's worth investigating why this happened, but an easy workaround in the meantime is to manually select the diff you'd like (e.g., `r1..r2`).

**Comment by pkaminski** [comment]
Ping?

**Comment by marun** [comment]
How do I choose an arbitary diff like ``r1..r2``?  The latest revision seems to always be selected (i.e. ``[chosen revision]..[latest revision]``).

**Comment by pkaminski** [comment]
You drag out a rubber band between the two revisions of interest.  (You can find this tip in the pop-up help you get when you hit F1 on any revision strip.)

**Comment by marun** [comment]
Ok, works for me.
