### ISSUE TITLE
Add comment when all discussions resolved

### ISSUE THREAD

**Issue by trainman419** [Reviewable/Reviewable#480]
It looks like reviewable doesn't post a comment or a timestamp on github when a review goes from having all files reviewed with open discussions, to all discussions resolved.

It would be great to have a final comment indicating that the review is complete in this case, for two reasons:
 * It informs the pull request author that their pull request is now fully reviewed and ready to merge
 * It provides a time-stamped log that allows the author to audit when the review was complete.

I'm particularly interested in this because we have a release process with automatic deadlines; all pull requests that have passed Reviewable and CI at a 8pm are automatically queued for testing. It would be nice to be able to go back and look at a pull request and easily answer "when was the review on this PR complete", which will help answer "why wasn't my PR included in the test batch?"

**Comment by pkaminski** [comment]
Hey Austin, I'm a bit confused -- AFAICT Reviewable already posts exactly the info you're looking for:
* When publishing comments/review marks, there's a line near the top of the message that will say "Review status: all files reviewed at latest revision, all discussions resolved." when the review is complete.
* For automation, Reviewable also posts a commit status that will indicate `success` or `pending` for the `code-review/reviewable` context (unless you disabled this).  The status is time-stamped, though the GitHub UI doesn't show the timestamp.

Are you not seeing these in your repo, or are you looking for something else/more?

**Comment by trainman419** [comment]
This happens specifically when the reviewer marks a discussion as resolved without adding a message. I have an example of this but unfortunately it's on a GitHub Enterprise / Reviewable Enterprise instance so I can't share it here.

I'm aware that status checks are timestamped, but if they're not visible from the web UI they're not very useful.

**Comment by pkaminski** [comment]
Ah, I see -- the concern is specifically with when you resolve a discussion via Acknowledge or a disposition change, and in doing so happen to complete the review.  This is a tricky situation since Reviewable can't post a message under some generic "app account" and probably shouldn't automatically post anything in the user's name.  The best thing I can think of at the moment is to automatically create a top-level draft that says something like "All done!" (if there are no other pending drafts) and hope that the user remembers to hit Publish before closing the page.  It still feels like it could be a bit unexpected / surprising, though...

Thoughts or other ideas?

**Comment by trainman419** [comment]
I'd be happy if reviewable posted a comment from my account that says "review complete" or something similar if I complete the review without a comment; similar to how it currently posts "N of M files reviewed" comments.

Maybe resolving a discussion should require the user to click the Publish button? I've been a bit surprised the few times that I was able to change the review state without hitting Publish.

For my particular use case a timestamp in the contents of the reviewable status would be fine, but that doesn't generate a notification that the review has been completed.

**Comment by jwnimmer-tri** [comment]
FWIW -- I'd agree (and upvote) that a change in the "number unreviewed discussions == 0" predicate should be cause for Publish to go green and require a click (to post a message).  Usually this happens already due to file matrix eyeballs turning from red to green as the reviewer reads diffs and ack's discussions, but not always.

**Comment by pkaminski** [comment]
So I dug into this a bit more and there's no easy fix.  Some options:
1.  Create a synthetic message in the client when the review gets "completed" and there's no other drafts pending, and encourage the user to Publish it.  Tricky because the review completion condition can be customized and gets evaluated asynchronously server-side.
2.  Treat any state changes that resolve a discussion as "draft state" (similar to review marks "green eyeballs") so that they need to be published to take effect.  Feasible, but requires deep changes in the discussion state engine.
3.  Include review completion as a trigger in a general-purpose notification system, which could append a synthetic message to the PR if desired (an extension of https://github.com/Reviewable/Reviewable/issues/168).

While 1 would be the "quick" solution it's sufficiently tricky that I probably won't attempt it.  I'm tempted to get 3 done later this year, but if not then I'll look into 2 once the client model has been refactored so it's manageable again (in progress!).

**Comment by trainman419** [comment]
(1) definitely seems a bit hacky. (2) or (3) seem more like what I would expect based on the other UI features; has there been any progress on either of those?

**Comment by pkaminski** [comment]
No progress on this, sorry.  The model rewrite is proving rather painful...

**Comment by pkaminski** [comment]
Closing in favor of #510, which should fix this by requiring publishing of disposition changes.  (Effectively #2 above, but applied to all state changes, not just resolving ones.)

**Comment by trainman419** [comment]
Awesome! #510 sounds like it would solve this issue quite nicely.
