### ISSUE TITLE
Review one file at a time button

### ISSUE THREAD

**Issue by Cellule** [Reviewable/Reviewable#481]
Sometimes reviewable doesn't correctly detect that the review is melting down my CPU, making review extremely slow.
In these cases I would really like an option to review one file at a time (actually I'd like to do that all the time even for small reviews).
Instead of trying to figure when is the best time to do it or not, can you add a button or keyboard shortcut to manually switch between showing one file at a time and showing multiple files.

This is probably the main reason I don't use reviewable much anymore since I review a lot of very big changes.

**Comment by pkaminski** [comment]
Yeah, the explicit single-file switch request is in #261, but blocking on the move from Angular to Vue.

In the meantime, can you point me to an example of a review that fails to be correctly detected as CPU-melting?  The automatic heuristics will have to remain even when the switch is implemented, to at least warn people if they picked a multi-file default and are about to open a huge review.

**Comment by Cellule** [comment]
It looks like the main heuristic to switch to single-file is the number of files (I think I saw 25 files).
But if I have a review with 23 files and some of them are really big/lots of comments.

For example: https://reviewable.io/reviews/Microsoft/ChakraCore/3141#-
Some of the files are build generated. I know you have a way to exclude them, but it's not always the case.

**Comment by pkaminski** [comment]
Looking at line delta counts to throttle isn't possible, since they're generated by diffing which is precisely what kills the CPU.  However, there's (supposed to be) a failsafe that prevents a set of diffs from running for more than 10 seconds; once that time is exceeded, the rest of the files get a "Diff skipped to avoid melting down your CPU" message instead.  Does that kick in for you, and if so why isn't it sufficient?

**Comment by Cellule** [comment]
Isn't it possible to fetch the number of lines added/removed from GitHub or the commit info?, i.e.:
![image](https://user-images.githubusercontent.com/4157103/27198374-c4cc8eca-51c6-11e7-8713-0e09d4bfcd75.png)

It doesn't look like the `running for more than 10 seconds` is enough because although it takes less than 10 sec to calculate the diff, the resulting view has too many lines and then scrolling is really laggy.

It looks like the main problem is when there is a change every few lines in a file.
Let's say there are 100 lines changes in a file, but they're all scattered across the file. Showing 10 lines of context for each change you end up with 1000 lines to show in the browser. If this happens on multiple files you quickly end up having thousands of lines to show in the browser page.
So although the diff is easy and fast to compute, the rendering is extremely slow and scrolling is excruciating. 
There could be a cap on the number of lines to render, if there are more than 50-100 lines about to be rendered, collapse that file and expand on demand.

Then again that won't solve the problem of once you expand that file it'll start lagging if there are other similar files already expanded.

I feel the page should switch to single-file review more aggressively, I understand that this decision happens before calculating the diffs, but there has to be something else to take into account to make that decision

**Comment by pkaminski** [comment]
The GitHub delta info isn't terribly useful since you can change the diff bounds arbitrarily in Reviewable, and even diff force-push-overridden versions that GitHub no longer knows about.  But as it turns out, Reviewable already has a heuristic to suppress diffs that exceed 1000 lines.  However, your example showed it to be faulty:  the code considers the number of diff lines, rather than the total number of lines that will be shown -- which includes context lines.  Also, the threshold is evaluated separately for each file, so you can still end up with a bunch of diffs that slip in just under the limit making the UI sluggish.

I rewrote the logic to take care of both these issues and your sample review is now much more responsive.  There's still no way to manually engage single file mode, but note that you can {ctrl,cmd}-click on any filename (e.g., one with a large suppressed diff) to open it in a separate tab.  That way, your main tab won't start lagging.

Let me know if this helped!

**Comment by Cellule** [comment]
It does make a big difference ! Now the files with lots of lines (including context) shown are hidden and the UI feels usable.
Thanks
