### ISSUE TITLE
Removed commits still require files to be removed

### ISSUE THREAD

**Issue by ryancahoon-zoox** [Reviewable/Reviewable#483]
I pushed a commit to a branch under review, then removed that commit (with a force push). Reviewable recognized that the commit had been removed by striking out the revision number at the top of the file grid, but a file that had been added by the transient commit was still part of the review and wasn't marked obsolete.

**Comment by pkaminski** [comment]
Apologies for the late reply -- I'm currently traveling.  You've found an interesting corner case that I think I know how to fix, but it also implies a larger issue: what happens if the reverted commit was the tip of a snapshotted revision with multiple commits?  The revision will not be treated as obsolete (struck out), yet its head commit sha will no longer be valid.  I'll need to think a bit about how best to deal with this scenario and will then fix both issues at the same time.

**Comment by pkaminski** [comment]
This should be fixed now.
