### ISSUE TITLE
Improve whitespace changes visibility  

### ISSUE THREAD

**Issue by johlju** [Reviewable/Reviewable#491]
Whitespace changes is hidden by default (which is awesome!) but, but in certain cases those needs to be reviewed, so when clicking on 'whitespace changes' it is possible to see them, but the visibility is not that great, so it's hard to find them.

Examples:
![image](https://user-images.githubusercontent.com/7189721/28704731-98c6e2cc-736c-11e7-82eb-57b28800260a.png)

![image](https://user-images.githubusercontent.com/7189721/28704751-ad349fec-736c-11e7-8c7f-a3d0061bded9.png)

Is it possible to mark these with green and red as well? Or any other form of marking so the eyes catch them quickly?

**Comment by pkaminski** [comment]
It shows up a bit better on my screen for some reason, but I agree it's very faint.  I made it that way because some people complained it was too intrusive before (even if whitespace changes are hidden, the whitespace deltas will still show up on lines that have other deltas in them).  Anyway, I raised the opacity a bit, hopefully everyone can live with this compromise.
