### ISSUE TITLE
The UI is terrible

### ISSUE THREAD

**Issue by yurivict** [Reviewable/Reviewable#493]
If not to say horrible.

I get a notification from github. URL leads to a screen from which it isn't clear who wrote the message. It isn't clear what lines the message refers to. The butterflies are flying all over the screen for some reason.

Why not just integrate reviews into gihub and do it in the same style as github works?

**Comment by pkaminski** [comment]
Sorry the UI didn't make sense to you -- as with anything, it's a work in progress.  As to your specific points:

> URL leads to a screen from which it isn't clear who wrote the message.

Each message has the author's avatar right next to it and you can hover to get details.

> It isn't clear what lines the message refers to.

If a discussion is specific to a line, it'll be immediately below the relevant line (as is customary), though this can get a bit fuzzy if it had to be mapped across revisions.  Do you have a specific example where you found it confusing?

> The butterflies are flying all over the screen for some reason.

They're trying to get your attention to explain how things work.  If you're not interested, clicking on one offers a switch to turn them off; just using the app will also tend to make them disappear as the system figures out you already know what you're doing.

> Why not just integrate reviews into gihub and do it in the same style as github works?

Integrating with GitHub's review mechanism is a pending issue; it's tricky, since Reviewable predates it and the semantics don't quite line up.  As for style, not everybody is happy with GitHub's PR mechanism -- that's rather the whole point of Reviewable.  If you like how GitHub does things you should stick with it!
