### ISSUE TITLE
Subscriptions are only editable by original subscriber, not organization owners

### ISSUE THREAD

**Issue by nikicat** [Reviewable/Reviewable#495]
Hello, currently only I have access to edit subscription, is it possible for my co-workers (that are also in my organization on github) to access subscription settings?

**Comment by pkaminski** [comment]
No, subscriptions are currently account-bound.  The original reasoning behind this design decision was to let multiple teams in a large organization maintain separate subscriptions, but it turns out that's a feature nobody actually wants and it's making life more complicated for everyone else.  Consequently, I'll be changing the implementation to be more GitHub-like, where all organization owners get control and perhaps get to invite billing managers as well (GitHub doesn't provide access to its billing managers list via the API, unfortunately).  This is fairly high in the feature queue but there are some big items still in front of it, so I can't give a good estimate of when it'll land, sorry.

**Comment by pkaminski** [comment]
At long last, this is resolved.  Here are the new rules:

Any organization member can start a subscription and they'll be able to manage it as long as they remain a member of the organization. Any organization owner is also allowed to manage the subscription but cannot delegate this privilege at the moment. Other members will be informed that a subscription exists with an “Organizational subscription active” message next to the organization name but will be unable to affect it in any way.

An organization may not have multiple concurrent subscriptions.
