### ISSUE TITLE
"Assigned to me" should include PRs on which I'm marked as the reviewer

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#497]
In GitHub, you can either assign a PR to someone or add them as a reviewer. It's not really clear what the distinction between these is intended to be.

If you're assigned a review on GitHub, the PR shows up under "Assigned to me" in the "Reviews" page in Reviewable. Makes sense!

But if you're added as a reviewer on GitHub, the PR shows up under "Involving me," where you're less likely to see it.

Seeing as Reviewable is all about reviewing PRs, I think that being marked as a reviewer and having a PR assigned to you should be treated identically.

cc @jacobbaskin

**Comment by sddamico** [comment]
@pkaminski if at all possible, I think you could break this up into two sections (I don't know if this is possible with the github API...)

- When a repo "protects" a branch so that only reviewed pr's can be merged, I think that should count as "assigned"
- When someone has already left a review on a PR requiring changes, that should be "assigned"
- When a pr can be merged at will, but the user is marked as a reviewer, that could be a new section "for review" (not 100% on naming)

**Comment by pkaminski** [comment]
So I dug into this a bit and it's non-trivial.  The first problem is that the response to the PR search request that Reviewable uses to fill the dashboard doesn't include any information about reviewers, requested or actual.  Without extra data all we can tell is that the user is "involved".  We could fetch reviewer data from GitHub as well but this would further increase the already high request load on the page, potentially leading to burst quota violations for long PR lists.  I should be able to mitigate this somewhat by caching this data in Reviewable's datastore for connected repos, but with no guarantee of freshness since GitHub webhooks are unreliable.  A further bit of complexity is how to deal with team review requests (#499): I think those should show up as assigned to all team members by default, but should be downgraded to involved once one or more team members have posted a review (except for those users, of course).  Since extra permissions are needed to access team membership that not all users grant I don't know yet how to deal with this.

@sddamico, I think the simplest approach that's most consistent with current behavior is just to treat requested reviewers as assignees, irrespective of branch protection or actual review activity.  This would match the current behavior where, if you post a comment on a review, you're just involved -- not assigned.  Especially since I'm planning to convert all comments posted via Reviewable into GitHub reviews...

**Comment by rjbell4** [comment]
I wonder if the GraphQL API would help with this querying.  Of course, that's not (yet) available for GitHub Apps.

**Comment by pkaminski** [comment]
I switched Reviewable to use GraphQL queries for listing PRs and this is now implemented in beta.  The way it works is that there's two new sections:  "waiting on me" and "reviewing".  Any review where you need to take an action (including, by default, one where you're a requested reviewer and haven't done anything yet) will appear in the first section.  Otherwise, PRs where you're a requested reviewer will fall into the second section (as will PRs you're assigned to but that have no requested reviewers).  I'm hoping this will be a reasonable fit for all the workflows I've heard of around assignees / requested reviewers, but if not I'm sure people will let me know.  :)
