### ISSUE TITLE
Indicate which commit each revision corresponds to

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#50]
Every revision in Reviewable corresponds to some SHA in the git repo (please correct me if I'm mistaken!). It would be nice if Reviewable surfaced that in some way.

Use cases I can imagine:

- You want to view the diff between particular revisions in another diff tool.
- You want to revert a file to how it looked at a particular revision.

This information wouldn't need to be prominently displayed -- it could appear when you hover over "r1", for instance. Another benefit is that this would make it more transparent what revisions are.

**Comment by ryan-williams** [comment]
+1. one question beneath the question here, for me, is: do reviewable revisions each correspond to a `git` commit?
* If they do, then I feel that the extra layer of abstraction has cons and no pros.
* If they do not, then I feel like they should.

**Comment by pkaminski** [comment]
Each revision corresponds to a single SHA, but may cover a range of commits; to put it another way, not every commit will have a matching revision.  Commit aggregation happens when multiple commits are pushed to the PR branch and nobody (other than the author) looks at them in Reviewable.  You can see this in action if, as the author of a PR, you visit the review immediately after pushing a commit.  The last revision will be "unsnapshotted".  (See #35 for some related discussion.)

I could see including the relevant SHA(s) in the synthetic "New commits in rN" top-level commits.  Would that be useful?  I'd rather not overload the file matrix UI any further, and I'm trying to avoid relying on hover triggers as much as possible so the app remains friendly to touch devices.

**Comment by danvk** [comment]
I'd be happy if the top-level discussion included a clear mapping from revision→SHA.

**Comment by ryan-williams** [comment]
Thanks @pkaminski. I might not be completely understanding you, but it sounds like each revision does correspond to a `git` commit.

Your distinction about a revision corresponding to a range of commits is confusing; do you mean that the thing you're calling `r1` in some way maps to the commits that git would represent as `c1..c2` (where `c1` is the "top" commit at the time that `r1` was created, and likewise `c2`<->`r2`)?

It feels like there's a simple model that should exist here where each `r[0-9]+` corresponds to a commit, and we are always viewing various ranges between commits. In such a model I don't understand why we wouldn't just use the commit SHA as the identifier, instead of the made-up `r[0-9]+`'s.

Let me know if I'm misunderstanding. My best guess is that you are thinking of a revision as [the diff between two commits], while I am thinking of a revision as a commit that, when combined with another [revision/commit], unambiguously implies a certain diff.

**Comment by pkaminski** [comment]
Hey @ryan-williams, I think you're misunderstanding.  Let me try a different way to explain:  each revision corresponds to a single git commit.  However, not every commit on the PR branch necessarily has a corresponding revision.  The corollary is that it's possible for a revision to represent the changes made in a sequence of git commits.

The reason for this approach is to avoid a proliferation of revisions in the UI when a series of commits get pushed to the branch in quick succession, e.g. when the developer notices a commit broke CI and immediately pushes a fix.  The way this works is that the latest revision is kept "open" and takes on the identity of the latest commit until somebody (other than the author) actually looks at it, at which points it's snapshotted to that commit forevermore.  &lt;Insert analogy to quantum mechanics wave function collapse here&gt;

This technique works well even in the face of rebasing and other reflog monkeying-about.  It also keeps the revision numbers short (much shorter than even compact SHA numbers), which is important given the layout of the file matrix.  And note that if you keep your commits to one per review iteration, then the situation reduces to a bijection between revisions and commits, as you were wishing for.

**Comment by ryan-williams** [comment]
great, that does make more sense.

It sounds more like that we just disagree on the pros vs. cons of using the `r[0-9]+` aliases instead of the abbreviated SHAs.

I would always prefer to see things always identified by `git` SHAs (I can think of a few ways to work around your concern about file-matrix-compactness) so, to the original topic of this issue, the more you feel like making that substitution or allowing easier access to that info, the better, as far as I'm concerned. 

When trying to use reviewable, the magical `r[0-9]+`s have actually been confusing/disconcerting to me because it makes me feel like I'm operating on some fake/inferred/copied view of the underlying `git` tree, which instantly raises suspicions about this copied version's robustness. As you've noted, your system does actually use the underlying objects in a robust way, which is great, but I was sort of tricked by the UI into thinking that it didn't.

Anyway, that's my $0.02. As a baseline, some way to click-through to each revision's commit on github or let me copy a revision's SHA (to locally `checkout` it) would be a big improvement for me.

**Comment by pkaminski** [comment]
I added links to GitHub commit pages into the synthetic revision comments.  Note that these will only show up on revisions created from this point onwards -- no backfill.  Please let me know if this is sufficient or if more is needed.
