### ISSUE TITLE
Clicking "acknowledge" on the top-level comments stream scrolls me down too far sometimes

### ISSUE THREAD

**Issue by mgalgs** [Reviewable/Reviewable#500]
Sometimes when I click "acknowledge" on the top-level comments I get scrolled down several files into the review, seemingly randomly.  I'll try to get a screencast showing it in action, but wanted to check if it was a known issue.

**Comment by pkaminski** [comment]
I think what may be happening is that hitting Acknowledge collapses the discussion and, instead of pinning the scroll location to the visible element, the browser keeps it absolutely fixed so it ends up much lower on the page (since it's now shorter).  Does that sound like what you're seeing?  If so, which browser are you using?  I can see if I can override this behavior...

**Comment by mgalgs** [comment]
Yes, that sounds exactly like what's happening. I'm using Google Chrome.

**Comment by mgalgs** [comment]
Here's a screencast showing the problem.  Not too bad in this case since it only scrolled to the first file, but you get the idea.

https://youtu.be/JouuhOtxdjo

**Comment by pkaminski** [comment]
Sorry this took a while, but I've got a counter-scrolling fix released now.  The design isn't perfect, but it's not obvious what's the right thing to do in all the possible "partially off-screen" vs how much gets collapsed scenarios.  I think it's an improvement, at least.
