### ISSUE TITLE
Emojis sometimes look plain and frumpy

### ISSUE THREAD

**Issue by mgalgs** [Reviewable/Reviewable#501]
Really really minor nitpick...  But in some places the emoji are just the basic representations from the font family itself, but in other places it's the nice, full color `img` of the emoji.

Example:

![image](https://user-images.githubusercontent.com/152014/29887758-5251aefa-8d73-11e7-8205-692d21907372.png)

The plain ol' ones are sometimes quite ugly...  Would be awesome if we could get the `img` ones everywhere.

Again, super minor nitpick.

Thanks for the amazing tool!

**Comment by pkaminski** [comment]
This is actually because at some point GitHub switched to using Unicode for rendering emojis in Markdown, and Reviewable delegates to GitHub's renderer for maximum compatibility.  The "nice" emoji are actually images from GitHub's original set, which Reviewable still uses because I never bothered to update to Unicode.  😛 (Specifically, Reviewable parses the raw markdown for colon-delimited emoji markers and looks up the corresponding image in GitHub's (legacy?) emoji table: https://developer.github.com/v3/emojis/.)

I don't want to mess with the Markdown renderer output so I'm going to close as won't-fix for now.  In fact, it's entirely possible I'll have to "downgrade" Reviewable to use the Unicode emojis in the future if GitHub continues on this path and drops support for the images altogether...
