### ISSUE TITLE
GitHub commit status doesn't get set after force pushing

### ISSUE THREAD

**Issue by marczych** [Reviewable/Reviewable#503]
Over the last few months (and maybe longer even), I've occasionally seen the commit status on GitHub be out of date compared to what Reviewable displays. The most obvious case is where Reviewable shows that the review is complete (evidenced by the "checks" dropdown and "Review complete: all files reviewed, all discussions resolved" text in the comment on GitHub but the commit status is still pending with "xx files left".

The most recent instance of this involved a PR with the following lifecycle (to the best of my knowledge):

1. PR/review opened.
1. Review is complete.
1. A new commit is pushed to the branch (review is no longer complete).
1. Branch is force pushed back to the reviewed revision.

No amount of reviewing files, starting blocking discussions, resolving discussions could get it to update the status (either to pending or passing).

This is all on Enterprise so I can dig up commit status history from GitHub's API and server logs from Reviewable if it'd help.

**Comment by pkaminski** [comment]
That's interesting -- does the issue occur only if a branch is rolled back to a previous commit?  If so, that's something I can try to reproduce quickly, otherwise we'll probably need to start digging through the logs.  (As it happens, there have been previous reports of missing status updates, so the code is pretty well instrumented and logs any time a status update was made and why/why not it was reported to GitHub.)

**Comment by marczych** [comment]
I'm not sure if this is the only way that the issue occurs but force pushing to an older revision that was complete seemed to be the cause for the most recent instance.

I can dig through logs before you try to reproduce it if you'd like. The PR number in question is `16689` with `dcc469d5f30bf9e6ac092ba1cb458659385bbc95` as the sha that was rolled back to and wasn't getting updated commit statuses. It'd be great to get some `grep` commands to run on the logs and I can email the output to you.

**Comment by pkaminski** [comment]
I wasn't able to reproduce following the instructions above, but I have a hunch.  Can you post (or send) your custom condition code?  I think there's a bug in one of the sample conditions regarding which revision to check for reviewers and I'm wondering if it might've snuck into your condition too.

**Comment by pkaminski** [comment]
My hunch was correct -- the problem is that the `_.last(file.revisions)` is not necessarily the _latest_ one if a force-push reverted to an earlier commit.  While it would be possible to kludge around this in the snippet it would be pretty awkward with the data currently made available, so I'll do some work on my side to make it easier first.  I could make the whole problem go away by simply excluding obsolete revisions from the data packet but I think there are some useful conditions that could make good use of that data so I'll probably just add a flag...

**Comment by pkaminski** [comment]
Fixed, see https://headwayapp.co/reviewable-changes/completion-conditions-and-obsolete-revisions-35080 for how to tweak your conditions.  This will go out in the next Enterprise release pretty soon.
