### ISSUE TITLE
Reviewed files count in GitHub comment doesn't match count in Reviewable

### ISSUE THREAD

**Issue by marczych** [Reviewable/Reviewable#504]
I recently updated our review completion condition so PR authors can't review files (rather, they _can_ but every file needs to be reviewed by somebody other than the author in order for the review to be complete). This has been working great other than some PR authors get a little confused when the review isn't complete because all of the files have been reviewed but it still can't be merged.

For example, the text in the checks dropdown said "Review in progress: 49 of 53 files reviewed" but the GitHub comment said "Review status: all files reviewed at latest revision".

I looked at the repo settings with that PR selected and all of the data returned looked good (indicating that not all files were reviewed). I just saw this on the FAQ but I'm not sure if it is what I'm looking for:

```js
  // optionally, per-file per-revision flags to override reviewed status (defaults to reviewers.length >= 1)
  // (it's OK to just augment the input files structure with reviewed flags and return the whole thing here)
  files: [
    {path: 'LICENSE', revisions: [key: 'r1', reviewed: true]}
  ]
```

What's the easiest way to get the GitHub comment text to match what is displayed in Reviewable?

**Comment by pkaminski** [comment]
The easiest way is for me to fix the comment-sending code.  :)  Currently, publishing comments generates the status message using a hardcoded algorithm -- I simply forgot to update it when I introduced custom conditions.  However, getting it to use the condition code will be a bit tricky since at the moment the server uses the current review state as input, and the GitHub comment must be sent before we update Reviewable's internal state (apply drafts, etc.) to allow graceful recovery from errors in this decidedly non-atomic process.  I'll figure it out soon.

**Comment by marczych** [comment]
Sounds good. This isn't very high priority so whenever you get around to it is fine.

**Comment by pkaminski** [comment]
I thought about it some more, and it'll be a lot easier to implement on the rewritten platform.  Basically, the client has to send a speculative delta to the server to apply in-memory to get the right review state for the condition; on the old platform this would require a bunch of custom code, but the new one already encodes transactions as deltas so it could be extracted easily.  So probably by EOY or so...

**Comment by pkaminski** [comment]
This is fixed now!
