### ISSUE TITLE
Option to disable the "Merge Bunny"?

### ISSUE THREAD

**Issue by aboyett** [Reviewable/Reviewable#506]
The appearance of the Merge Bunny can visually clutter the page once he makes himself known. From what I can see, whenever he appears the Merge button has also transitioned to it's green/actionable state making his presence a bit superfluous. If he does only appear when the Merge button is actionable, could we allow him to be disabled on a per-user basis?

**Comment by pkaminski** [comment]
Ironically, I added the bunny because some users found the green Merge button to not be sufficiently visible.  (Also because it's fun!)  I won't add a toggle for it, but you can disable it pretty easily by loading custom CSS (via the user settings) and adding this rule:

```
.victory.decor {display: none}
```

Keep in mind that the custom CSS file must be served with MIME type `text/css`, so if you want to serve it off GitHub (e.g., a gist) you'll want to avail yourself of a service like https://rawgit.com.

**Comment by aboyett** [comment]
I had noticed the custom key-bindings but I guess I had overlooked the custom CSS option. Thanks for that solution!
