### ISSUE TITLE
Review commit messages

### ISSUE THREAD

**Issue by DamienCassou** [Reviewable/Reviewable#507]
I'm not sure where to write reviews to commit messages (e.g., when a commit message contains a typo or doesn't follow conventions). Would it be possible to make each commit message part of the list of to-review elements just as the commited files?

**Comment by pkaminski** [comment]
Since all the commit messages appear in Reviewable's top-level discussion that would seem to be the natural place to raise issues about them.  If you'd like resolution of these to be tracked (and, by default, required to complete the review) you can open new top-level discussions with the "Start a new discussion" button for each issue instead.

How does that sound?  (Making commit messages a must-review element would be too aggressive for most teams, sorry.)

**Comment by DamienCassou** [comment]
Piotr Kaminski <notifications@github.com> writes:
> Since all the commit messages appear in Reviewable's top-level
> discussion that would seem to be the natural place to raise issues
> about them.  If you'd like resolution of these to be tracked (and, by
> default, required to complete the review) you can open new top-level
> discussions with the "Start a new discussion" button for each issue
> instead.

I will try that, thank you.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by sschuberth** [comment]
> Since all the commit messages appear in Reviewable's top-level discussion that would seem to be the natural place to raise issues about them.

But it's still quite inconvenient that there only is a single "Reply..." field below all commit messages. If you want to highlight a commit message typo in a PR with many commits, you need to quote the text to give some hint which commit message you're referring to.

I wish each commit message was just displayed as a code snippet that could get line comments.

**Comment by mmlb** [comment]
@pkaminski is there any chance to re-open this issue? You mention that requiring commit-message-reviews would be too aggressive but now that we have configurable review-completions this is no longer a blocker.

**Comment by pkaminski** [comment]
Never say never, but not reopening at this time, sorry.  There's a long queue of much higher priority features that have no workarounds...

**Comment by pkaminski** [comment]
I've had a change of heart / seen the light and am reopening this issue.  Not sure exactly _when_ we'll get it done but it's back on the list.  😄

**Comment by DamienCassou** [comment]
Piotr Kaminski ***@***.***> writes:
> I've had a change of heart / seen the light and am reopening this
> issue.  Not sure exactly _when_ we'll get it done but it's back on the
> list.  😄

Awesome. I thought about this old issue earlier this week too :-).

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by pkaminski** [comment]
Here's my current thinking on the design for this feature:

You'll be able to turn commit message reviewing on/off through a toggle in the review style dropdown (independently of the review style), available to anyone with push permissions.  Admins will be able to set it as the default for a repo through the same link as for the review style.  Once there is at least one comment made on the fake commits file the feature can't be turned off for that review.  (Implementation note: if this gets toggled off by one user while another has a draft pending, the draft will disappear but should come back automatically if the toggle gets switched back on.)

The fake commits file would have a name guaranteed to be unique, like `//commits`, and always show up first in the file list, outside any group.  The contents of the file would consist of the commit message comments that currently show up in the main discussion thread; the comments would no longer show up there when the feature is turned on.  Each revision would contain all the commits in all _non-obsolete_ revisions up to and including this one; that is, the contents of the file would be cumulative, so if you review the last revision you'll be seeing all the commit messages for the whole PR.  (Implementation note: each revision will need to keep track of the list of non-obsolete revisions that precede it at the moment it's snapshotted, since once it's rebased and obsoleted there will be no way to recover this information.)

That's pretty much it.  The normal diff bounds picking algorithm should work great with this design.  The feature may lead to more commit message editing so we may need to spruce up our commit-matching logic for rebases to do more than just an exact match on the commit summary.

And, if things go really well and the result is so awesome that we decide the extra bother of reviewing a fake file is a small price to pay for people who don't care about commit messages, we may just force it on for everyone and ditch the toggle.  😄 

Feedback?

**Comment by DamienCassou** [comment]
> The contents of the file would consist of the commit message comments

what are commit message comments?

> the commit message comments that currently show up in the main discussion thread

I'm not exactly sure what that means.

> Each revision would contain all the commits in all non-obsolete revisions up to and including this one

I would expect the "Review each commit separately" style to only show the commit message of the current revision.

> The feature may lead to more commit message editing so we may need to spruce up our commit-matching logic for rebases to do more than just an exact match on the commit summary.

That would be a very good first step. Reviewable is often confused by our frequent rewriting of commit messages.

**Comment by pkaminski** [comment]
> what are commit message comments?

They're the synthetic comments generated by Reviewable that show up in the main discussion and list the commits for each revision.

> I would expect the "Review each commit separately" style to only show the commit message of the current revision.

That's what I thought at first too, but then the diffs between revisions become nonsensical.  By having the "commits file" be cumulative diffs make sense -- both between successive revisions (the new commits are added lines) and between rebased revisions (showing commit message edits).

> That would be a very good first step. Reviewable is often confused by our frequent rewriting of commit messages.

Any thoughts on what would be a decent algorithm to try?  We can easily compute a Levenshtein distance and compare to a threshold, which would match up typo fixes but not more extensive rewrites.  Are you aware of any other heuristics for matching up rebased commits in git?

**Comment by DamienCassou** [comment]
>>That would be a very good first step. Reviewable is often confused by our frequent rewriting of commit messages.

> Any thoughts on what would be a decent algorithm to try?

Things I can think of:

1. comparing the "Author" and "AuthorDate" fields of the 2 commits;
2. Levenshtein distance of the 2 diffs (try including/excluding the commit message in the diff).

> We can easily compute a Levenshtein distance and compare to a threshold, which would match up typo fixes but not more extensive rewrites.

This will be a good first step. Good luck finding a reasonable threshold though.

> Are you aware of any other heuristics for matching up rebased commits in git?

I'm not :-(.

**Comment by sschuberth** [comment]
> Are you aware of any other heuristics for matching up rebased commits in git?

Sorry for jumping in here, but are you aware of the [range-diff](http://git-scm.com/docs/git-range-diff) command? There's a brief algorithm description on that page.

Also, Gerrit Code Review has implemented a feature to [disregard rebases when rewriting history](https://bugs.chromium.org/p/gerrit/issues/detail?id=217), which might be worth looking at.

**Comment by pkaminski** [comment]
Thanks for the ideas folks -- I wasn't aware of `range-diff` command and I think we can lift some ideas from there (though we don't want to access file contents on the server, so we're really limited to just the commit metadata).  I've split out improving commit matching into a separate issue (#827) since it looks like it'll be a non-trivial amount of work.

As for disregarding changes caused by rebasing, Reviewable already does this through a tricky 4-way diff process (on the client), and independently of commit matching.

**Comment by cgiroux86** [comment]
Hi all, we have a feature built out to address reviewing commit messages.  We'd like to invite anyone who's following to participate in our beta roll out.   Please let us know if you're interested :)

**Comment by pkaminski** [comment]
Specifically, we need a list of usernames who future PRs will have the feature enabled.  Once a PR gets its flag flipped every reviewer (even ones not on the list) will be able to use the feature in that review.  (Feel free to email support@ if you'd rather not post the list in public.)

**Comment by pkaminski** [comment]
@feldgendler, @dhalperi, @mkow, would you be interested in (helping us beta test) this feature for reviewing commit messages?  (I find it's also helpful for any kind of rebase-centric workflow, even if you don't care about formally reviewing the messages.)  If so, please let me know a list of usernames whose PRs to turn it on for.  Thanks!

**Comment by feldgendler** [comment]
The idea is great but the implementation doesn't work for us, so we probably won't be using it.

The way we merge PRs into master is by squashing. Individual commit messages on the PR branch don't matter. The PR title and description become the commit message on master. And while we indeed would like to review the PR title and description for this reason (currently I often start top-level discussions about them), this feature is not going to achieve that, as far as I understood.

**Comment by pkaminski** [comment]
Interesting.  You're right, the current implementation is specific to commit messages.  I think formal reviews of the PR description would go too far so I wouldn't expect the feature at this point... but then again that's what I initially said about reviewing commit messages, so who knows!  Thanks for the feedback in either case.  😄

**Comment by dhalperi** [comment]
I'm in the same boat as @feldgendler.

Incidentally, how do you make the PR Desc and Title become the commit message? I'd love that to be the default; right now, GitHub auto-generates some crap based on whether it's one commit or multiple.

**Comment by jwnimmer-tri** [comment]
My project also uses squashing, by default.

In most cases, we still use a rebase workflow with a single commit, and then use that sole commit's subject and body for the squash (+ the PR number parenthetical as added by GitHub), but occasionally we do end up with multiple commits and we need to to carefully edit reviewable's squash message within the merge drop-down chicklet, as part of the final merge operation.

For those cases with multiple commits, I've been consider customizing our [defaultSquashCommitMessage](https://docs.reviewable.io/repositories.html#defaultsquashcommitmessage) so that the squash text is the PR description, which makes it easier for others to weigh in on the message.  If the "review commit messages" feature extended to cover the `defaultSquashCommitMessage`, I would definitively take advantage of that.  Or at minimum, I think showing the _computed_ commit message somewhere, even if we can't have a discussion thread about it, would be a nice win.

**Comment by feldgendler** [comment]
> I'm in the same boat as @feldgendler.
> 
> Incidentally, how do you make the PR Desc and Title become the commit message? I'd love that to be the default; right now, GitHub auto-generates some crap based on whether it's one commit or multiple.

We use https://github.com/palantir/bulldozer to update and merge our PRs.

**Comment by pkaminski** [comment]
Huh, sounds like there might be some demand for better support of the squash-merge workflow overall.  Could whoever feels most enthusiastic about this open up a new issue to scope and track it?  Thanks!

**Comment by feldgendler** [comment]
Seems like it varies a lot what exactly becomes the commit message after squashing. Not sure what issue to file.

**Comment by pkaminski** [comment]
The overall drift I got is "we want to default the squash commit message to something based on the PR, then be able to edit and review it", but I'm sure the devil is in the details.

**Comment by mkow** [comment]
> @feldgendler, @dhalperi, @mkow, would you be interested in (helping us beta test) this feature for reviewing commit messages? (I find it's also helpful for any kind of rebase-centric workflow, even if you don't care about formally reviewing the messages.) If so, please let me know a list of usernames whose PRs to turn it on for. Thanks!

Definitely! Could you enable this for some specific PRs, or only per author?

Regarding usefulness: In our case we work in git-rebase workflow (we're keeping linear history on master with meaningful commit messages), so it's quite important for us to be able to review commit messages after rebases.

**Comment by pkaminski** [comment]
The beta list is per author only.  When we leave beta our current intention is to turn it on for all PRs, without exceptions -- I think even when not reviewing commit messages it just makes for a better experience.

**Comment by mkow** [comment]
Ok, let's try with enabling this for my PRs :) Will this work for already submitted (but still open) ones, or will I need to create a new one?

**Comment by pkaminski** [comment]
Cool, I added you to the beta list.  New PRs you create from this point on will have the feature turned on.  (It's not retroactive to prevent confusion.)

**Comment by pkaminski** [comment]
This feature in now available to all, and we had a smooth launch in no small part due to the testing all you guys did.  Thanks!

**Comment by DamienCassou** [comment]
This feature works great. Thank you very much.

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill
