### ISSUE TITLE
Unable to update status due to GitHub API limitations

### ISSUE THREAD

**Issue by a13m** [Reviewable/Reviewable#509]
We've recently had several reviews get into a state where the commit's status look like:

```
  {
    "url": "REDACTED",
    "id": 4303172360,
    "state": "error",
    "description": "Unable to update status due to GitHub API limitations",
    "target_url": "https://reviewable.io/reviews/...",
    "context": "code-review/reviewable",
    "created_at": "2017-11-07T19:53:59Z",
    "updated_at": "2017-11-07T19:53:59Z",
    "creator": {
      ...
    }
  },
```

Reviewable does not seem to understand this "error" state, and still thinks the review is ready to merge, so we end up having to amend commits and force push, which sometimes works and sometimes take a couple of tries.  Any advice here?

**Comment by pkaminski** [comment]
So this is supposed to be a "it's never going to happen" error state, reached when the number of Reviewable status updates on a single commit gets uncomfortably close to GitHub's absolute limit of 1000.  There's really nothing Reviewable can do once this happens -- putting the status in an error state will prevent merging, but putting it in a success state might allow merging even though the review isn't complete.  The best workaround as you've figured out is to push a new commit.

That said, I just deployed changes to the code that 1) reduce the number of status updates by eliminating transient "update pending" ones, and 2) redact the status details when the number of updates exceeds 950, so that the status can stay in a generic pending (or success) state without wasting an update each time a file gets reviewed, a discussion gets started/resolved, or the list of pending reviewers changes.  (This assumes you're using the default review completion condition, but the problem is similar with custom ones and my solution applies as well.)

Hopefully this helps.  I'm going to leave the issue open for a week or two so you can confirm.  Thanks!

**Comment by a13m** [comment]
I appreciate the help.  Now that I see that we really are nearing the 1000-status limit, I have a different perspective on the problem.  I understood the usefulness of the "pending" state, and don't really care if you find you need to put that back.  I think the bigger issue is that you may be resetting the status too often.  We are using codecov for some of our repositories, and it seems that Reviewable and codecov are "triggering" each other (and reviewable may even be triggering itself) with updates to issue comments & status.  In one particular PR, we saw about 15-20 status updates per minute between these two integrations for a period of almost 90 minutes.  At that point, reviewable went into its error state.

It seems like there are a very limited set of things that should cause you to update.  If a review is complete and someone adds a random comment in the PR in github, I would not expect you to recalculate status on that.  It's not automatically a new "discussion," is it?  Likewise, when a tool such as codecov updates its status and edits a comment, nothing about that necessarily warrants a status update.

Please be aware that, separate from reaching the error state, situations like this are also exhausting our GitHub API limits for our admin users, which causes other headaches in our process.  I would appreciate anything you can do to help mitigate this.

**Comment by pkaminski** [comment]
Thanks for the additional detail -- I think we're getting closer to figuring out the root cause.  Reviewable takes a defensive approach to syncing GitHub data so most comment creations or updates will trigger a status check.  In my experience a precise incremental algorithm would be incredibly fragile, whereas just-in-case "recompute everything" updates tend to make the system self-healing at minimal expense.  So if codecov is updating comments regularly it could well have triggered this runaway.

I think the change I made should help, though.  Reviewable will no longer change a `success` state to `pending` while recomputing the condition, so as long as the final completion condition result comes out the same as before it will skip the GitHub status update and break the cycle.  An open question is why codecov would trigger a build/update based solely on a status change?  I'd imagine it should only react to pushes.

As for API quota, Reviewable will generally back off from using an admin account's credentials once 80% of the hourly quota is exhausted, which should still leave sufficient buffer for normal work.  There are a few exceptions to this rule for must-run updates but it should generally be sufficient to keep your admins in business.  I'd be interested in investigating further if you find that not to be the case.  (Note that API search quota is separate and much more limited, and while Reviewable does its best to back off here too GitHub doesn't make it easy and overruns are possible.  But it resets every minute so shouldn't be a big problem anyway.)

**Comment by pkaminski** [comment]
I'm going to call this one fixed -- let me know if we need to reopen.
