### ISSUE TITLE
Commits aggregated into single revision

### ISSUE THREAD

**Issue by mnonnenmacher** [Reviewable/Reviewable#511]
When selecting "Review each commit separately" it should create a revision for each commit. Instead for the review below all commits are aggregated into one revision which makes it impossible to see which commit a change belongs to.

https://reviewable.io/reviews/heremaps/oss-review-toolkit/54

**Comment by pkaminski** [comment]
There is a built-in limit to how many revisions will get created at a time, which is set to 20 for per-commit reviews by default.  Since this PR has 21 commits it collapses the commits into a single revision even in per-commit mode, as expected.  The limit is there both to protect Reviewable's backend from overloading (delaying or, in the worst case, preventing review creation/updates) and to reduce the chance that you'll end with an unmanageable quantity of revisions (which the current UI doesn't deal with very gracefully).  I can raise this limit a bit per-repo as required, though, if the admin understands the risks and high-commit PRs are common.  Let me know if that's something you'd like for heremaps/oss-review-toolkit.

**Comment by mnonnenmacher** [comment]
Thanks for the info @pkaminski! I don't think we will get PRs with >20 commits very often, but it would still be great if you could raise the limit for our repo to something bigger like 30.

**Comment by pkaminski** [comment]
No problem, changed to 30!

**Comment by mnonnenmacher** [comment]
Thanks a lot!
