### ISSUE TITLE
Make diff colors a bit stronger

### ISSUE THREAD

**Issue by sudden6** [Reviewable/Reviewable#515]
Depending on the exact monitor settings the current color scheme in diffs makes it hard to spot one character changes, because the red/green colors are very light.

Github uses much stronger red/green scheme to highlight changes and this is easier to read. I know that's quite a personal preference, but I hope it can be changed anyway :)

**Comment by sudden6** [comment]
![screenshot_20180113_195643](https://user-images.githubusercontent.com/5585762/34909161-132d1bbc-f89c-11e7-9c93-92290ff1f92c.png)

Example, one character change above cursor.

**Comment by pkaminski** [comment]
While I try to avoid adding preferences whenever possible, I agree that this is an important one since it's by definition impossible to get the right color for everybody (due to monitors, etc., as you mention).  It's possible to override this right now with custom CSS but not easy, so I'll add a "diff highlight contrast" slider to the settings in the near future.

**Comment by pkaminski** [comment]
There's now a contrast slider in the account settings!  At the moment it only affects diff highlighting, but the intent is that in time it will scale other intentionally toned down colors as well.
