### ISSUE TITLE
Indicate when we collapsed commits in "review each commit" mode

### ISSUE THREAD

**Issue by DamienCassou** [Reviewable/Reviewable#516]
In the (private) PR https://github.com/foretagsplatsen/monitor/pull/2932, there are 23 commits. Reviewable only shows 5 revisions (i.e., columns in the matrix).

**Comment by pkaminski** [comment]
There's a built-in default safety limit where a single push will refuse to create more than 20 revisions, since high numbers can make the UI cumbersome and the server slow to sync a review to the PR.  I can override the limit on a per-repo basis on an admin's informed request.  Would you like me to bump the limit to 30 for `foretagsplatsen/monitor`?  (It won't be retroactive, unfortunately.)

**Comment by DamienCassou** [comment]
Piotr Kaminski <notifications@github.com> writes:
> There's a built-in default safety limit where a single push will
> refuse to create more than 20 revisions, since high numbers can make
> the UI cumbersome and the server slow to sync a review to the PR.  I
> can override the limit on a per-repo basis on an admin's informed
> request.  Would you like me to bump the limit to 30 for
> `foretagsplatsen/monitor`?  (It won't be retroactive, unfortunately.)

no need to do anything for us then. However, it would be nice to display
a warning message explaining just that. Best would probably be to let
the user decides if he wants to see everything (and suffer the slowness)
or not.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by pkaminski** [comment]
I agree that a warning message would be nice -- I'll add that to my todo list and keep this issue to track it.  Letting the user override the limit on the fly would be much trickier, though, due to the way a review gets synced.
