### ISSUE TITLE
beta: couldn't interact with review in beta [until visited in prod?]

### ISSUE THREAD

**Issue by dhalperi** [Reviewable/Reviewable#517]
I was trying to look at a PR on beta reviewable and it said:

* changes: ???  (top menu)
* 0 revisions, +1 provisional (main review box)
* something like "all files are hidden because there are no files with changes in the selected revision" in a badge at the bottom

The File Matrix did show me 4 files with r1 that existed, but I could not get it to actually show me any changes.

* Clicking on the `changes: ???` button at the top did not let me select `show provisional diffs`
* Clicking on the File Matrix did nothing.
* nothing else I tried seemed to work.

I went to get screenshots, so I pulled up prod Reviewable (using same URL, just dropping `beta.`). Took a screenshot there, then went back to the Beta tab and all of a sudden the page was live and at the same revisions I had managed to successfully pick on the prod site!

[Causal or coincidence, I'm not sure.]

**Comment by pkaminski** [comment]
Huh, that's weird and worrisome -- thanks for the report.  It sounds like the derived data computation got stuck somehow on the beta until something nudged it onwards.  That may have been accessing the review on prod (since that will touch a couple properties on the review) or it may have been a timeout of some sort, hard to tell.  Also very hard to debug.  😞 If it happens again, can you take a screenshot ASAP (since the exact bits of data showing may provide a hint as to where the sequence got stuck) and check the JS console for anything informative just in case?  Thanks!

**Comment by dhalperi** [comment]
It seems that I was able to reproduce it, actually: just by looking at a PR using beta that I have not yet looked at in prod. Some more info:

* OS X
* Chrome up-to-date
* Private repository (have not yet been able to see if this matters)
* Nothing in the console log except a 404 to `https://api.github.com/repos/intentionet/OMITTED/branches/OMITTED/protection?access_token=OMITTED&per_page=100&_nocache=646879`, but I see those on prod too.

The behavior persists across a page reload and it lasts multiple minutes.

Censored screenshot attached, happy to send an uncensored one via a less public channel.

I also haven't interacted with the review on prod yet; happy to jump in a hangout or a slack if it will help you debug.
![2018-01-24-14-58-beta reviewable io](https://user-images.githubusercontent.com/526415/35362153-fda478b4-0118-11e8-895e-d642849f9a13.jpg)

**Comment by pkaminski** [comment]
Verrrry interesting, I'm going to follow those clues for a bit and see where they lead me.  Thanks!

**Comment by pkaminski** [comment]
Actually, if you could jump into a private channel on Gitter and let me know the full repo and PR number so I can check out what's in the database before you hit the review on prod?

**Comment by pkaminski** [comment]
I believe this is now resolved.  There were two bugs:  the review style wasn't being initialized properly (which is where loading the review in prod helped), and the proposed diffs were racing and being locked in too early, before some relevant data was ready, resulting in empty diff bounds.

Many thanks for the report and for narrowing it down for me so finding the root cause was easy!
