### ISSUE TITLE
Dropped commit still appearing as most recent revision

### ISSUE THREAD

**Issue by bcruddy** [Reviewable/Reviewable#523]
I pushed a commit that I then reverted locally using `git reset HEAD^ && git checkout . && git push origin branch-name -f`. Github is showing me the correct "most recent" version without the reverted commit but reviewable is still showing code that should no longer be there as the most recent revision:

Reviewable:
![image](https://user-images.githubusercontent.com/5150154/37097836-7102e966-21ea-11e8-981e-0ac9b548f279.png)

Github:
![image](https://user-images.githubusercontent.com/5150154/37097869-80181264-21ea-11e8-9031-2ca7651538eb.png)

**Comment by pkaminski** [comment]
Apologies for the delay in following up on this.  Can you confirm that you're talking about PR 4962 in a private repo?  If so, its current state appears to be correct:  `r2` is marked as obsolete, which means it's no longer in the PR.  However, since it was snapshotted before its commit was reverted, it can't be deleted -- this is working as expected.

Is your concern that the diff bounds didn't automatically update to exclude `r2` when the commit was reverted?  Or perhaps even after reloading the page Reviewable is still picking `base..r2` as the bounds?  (If so, can you specify whether this behavior is the same on stable vs https://beta.reviewable.io?)  Or that there's no obvious indication that `r2` is now obsolete?

Clarification on exactly what behavior you expected would help me a lot in fixing or clarifying things. 
 Thanks.

**Comment by bcruddy** [comment]
Ah that makes sense. After I submitted this I noticed `r2` was a but lighter and stiked out but that was only on the main file list - not the files themselves. It just wasn't obvious that the commit had been dropped so I don't know if this is a bug as much as the UI around the commit being dropped was confusing.
