### ISSUE TITLE
Add tooltips to all buttons

### ISSUE THREAD

**Issue by ryan-williams** [Reviewable/Reviewable#53]
preferably showing hotkeys for each:

![](http://f.cl.ly/items/1y1D4031092T3X3i2X2n/Screen%20Shot%202015-02-27%20at%201.31.05%20PM.png)

I don't know what the "M↓ok" means, for example.

**Comment by pkaminski** [comment]
Have you tried clicking on it?  :wink:  I'm generally not in favor of adding tooltips to buttons because 1) they keep popping up and getting in the way when you're just trying to click a button and 2) they're not friendly to touch devices.  Also, since hotkeys are customizable by the user, showing them in tooltips is hard (equivalent to the halting problem in the worst case).

Were you able to figure out the other icons in the comment toolbar?  If so, I propose that the real issue here is that "M↓ok" needs to be made clearer.

**Comment by ryan-williams** [comment]
I clicked on it several times and it didn't do anything, afaict.

Given that the two buttons it's next to are "delete" and "publish", "just try clicking on it" is probably not a good story.

Tooltips out of the box usually wait until you are clearly hovering over the thing, looking for information, before they display, right? I'm not saying it has to be instantaneous.

re: figuring out the other commands, no, I did not think that the "publish this comment now" button would do what it did. I thought it would "save as draft" + switch the compose element to a preview. The lack of something that does that is causing me issues touched on by a few of these... issues.

re: hotkeys customizable by user --> halting problem, I don't follow. If a user has a different hotkey set, show them that hotkey in the tooltip, right?

**Comment by ryan-williams** [comment]
also, lack of a good tooltip story on mobile doesn't really seem to me like an argument for not following this very established and useful convention of desktop UIs.

we can start a new issue to try to solve UI-discoverability on mobile in general :)

**Comment by pkaminski** [comment]
Huh, clicking on "M↓ok" opens https://guides.github.com/features/mastering-markdown/ for me.  Are you running any extensions that might be canceling that navigation somehow?  I'll add switching "M↓ok" to a more official Markdown icon to the todo list.

Last time I tried adding hovers they interfered with the touch (it's not just for mobile!) experience, as after touch-clicking a button the hover remained in place until something else was clicked.  This is probably fixable, and I added an internal task to investigate as part of the onboarding improvements coming in March.

Hotkeys are customized by assigning more-or-less arbitrary expressions to key combinations.  Those expressions will often come from a predetermined set, but not always, hence potential halting problem.  Also, routing the live hotkey definitions from page level down to the individual templates to perform the lookup would be a pain, so overall I don't think this feature is worth it at this point.  People who like keyboard shortcuts will know to hit "?", especially since that's how GitHub works too.

**Comment by ryan-williams** [comment]
**M↓ok**
tried again and "M↓ok" seems to do what you describe and open that page. I think that some kind of "?" icon is pretty well established in such semi-rich-text-editing interfaces as the escape hatch to a "what syntaxes can I type here?" page, and I would encourage you to add a tooltip for that too :)

**tooltips**
Seems like we're miscommunicating about what "tooltip" might mean. I'm thinking like `alt` text on an `<img>` or, TIL, the `title` attribute of `<div>`s. Here I added one to the page:

![](http://f.cl.ly/items/0N3z0n2i230S251g1o0l/Screen%20Recording%202015-02-27%20at%2002.30%20PM.gif)

Does that have undesirable side-effects for touch interfaces?

My understanding is that such alt-text in general is desirable for accessibility reasons / screen-readers, though I know very little about that. It feels strange to not have something like that on a desktop UI like this.

**hotkeys**
Surely you could just support some vanilla key combinations and get 90+% of users, no?

Also relevant to #55 about letting me see hotkeys while still in a comment-compose box.

**Comment by pkaminski** [comment]
The M↓ok button now has a legit Markdown icon, a question mark, and a tooltip.  That's probably about the best I can do given the available real estate.

Re: tooltips, yes, adding a `title` attribute will cause the tooltip to linger after touching the button until something else is touched.  At least sometimes -- I haven't completely figured it out.  `alt` is fine and should be added throughout, but will never produce a tooltip (except in very old versions of IE).  For now, I'm putting `title` only on buttons that are both rarely used and hard to understand, but once I get a proper tooltip infrastructure in place that's both mouse- and touch-friendly (if such a thing is possible) I'll be adding tooltips throughout.  I renamed this issue to track this.

Re: hotkeys in tooltips, yeah, it could be made to work well enough, just not in all cases.  I add it to the todo list but I'm not inclined to prioritize it since relatively few actions have a shortcut, many shortcuts don't have a corresponding UI element, and I still claim that most people who care about the keyboard this much know to bring up the cheatsheet.  Feel free to open up a new tracking issue for this if you'd like.

**Comment by ryan-williams** [comment]
cool, sounds good @pkaminski!

**Comment by pkaminski** [comment]
So, this took a lot longer than intended, but the help mode (aka Guide) is now live!  I managed to hit all my design goals -- try it out and let me know what you think.  Two caveats:

1. I turned off "point out new features" for 14 days for existing users, to avoid annoying them with help prompts for functionality they already know well.  If you'd like a new-user experience, you can toggle this back on from the main Guide screen.

2. There's more new-feature prompting functionality coming up, but I didn't want to hold up this release any further.
