### ISSUE TITLE
Copy + paste published comment into new draft comment

### ISSUE THREAD

**Issue by jwnimmer-tri** [Reviewable/Reviewable#538]
Following up on the #225 and related workflow about editing comments ... one random thought.

I'm a-ok with the immutability / no edit premise.  For non-cosmetic typos that I need to fix, sometimes posting a follow-up sentence fragment in the discussion is good enough.

However, if its a longer comment with detailed markup, sometimes I really need to just re-post most or all of it, but with the correction(s).  If I copy-paste my comment into the Reply box, right now it seems to lose the formatting.  If I could copy-paste the comment, edit it, and then resubmit, I think that would cover some fraction of the use cases that are currently frustrating.  Is a smart markdown copy + paste feasible?

**Comment by pkaminski** [comment]
I don't think a smart markdown copy is feasible, since the browser only gives me the HTML range / nodes and the GitHub markdown renderer doesn't provide any kind of map between the HTML and the source.  The markdown source of the full comment is available of course and I could make it available for copying, but I'm again stymied by the UI considerations.  Best I can think of is to add an extra button to the draft editor that will paste in the markdown source of the author's last posted comment in the discussion.  Given how rarely this feature would be used, though, I'm not convinced this is worth the additional UI complexity...

**Comment by jwnimmer-tri** [comment]
Yup, I was trying to think of ways to improve things without adding UI clutter.  I agree that we don't want more widgets for this case.

**Comment by mkow** [comment]
> GitHub markdown renderer doesn't provide any kind of map between the HTML and the source

I this still the case? I quote other's words a lot when answering them, and right now I need to manually re-apply formatting to it. 

Alternatively, maybe a "copy markdown source" button on already posted comments would be feasible? That would also solve my problem :)

**Comment by pkaminski** [comment]
Still no mapping from HTML to Markdown.  GitHub's API there hasn't changed in forever and I wouldn't hold my breath.

I'm not super keen on adding extra UI for this.  I think in general we rather encourage starting a separate discussion for each concern so that quoting isn't (much) needed.

Regarding the original issue (correcting your own comments) I have a new proposal in #836.

**Comment by mkow** [comment]
Too bad. Anyways, it's not super-annoying.

> I'm not super keen on adding extra UI for this. I think in general we rather encourage starting a separate discussion for each concern so that quoting isn't (much) needed.

Yeah, we usually start this way, but then it gets worse as the discussion and arguing grows :)

**Comment by mfonger** [comment]
I'm not super keen on adding extra UI for this. I think in general we rather encourage starting a separate discussion for each concern so that quoting isn't (much) needed.

**Comment by mfonger** [comment]
>
> 
> I'm not super keen on adding extra UI for this. I think in general we rather encourage starting a separate discussion for each concern so that quoting isn't (much) needed.
> 
>

**Comment by mfonger** [comment]
> Yup, I was trying to think of ways to improve things without adding UI clutter. I agree that we don't want more widgets for this case.

test
