### ISSUE TITLE
Problem with starting a review in a PR

### ISSUE THREAD

**Issue by johlju** [Reviewable/Reviewable#553]
In PR https://github.com/PowerShell/SharePointDsc/pull/800 the Reviewable button didn't come up in a PR as it usually do. So I tried to add it manually, but getting an error message when trying to start the review.

> "Unable to create review: There's already a review for this pull request in another instance of Reviewable: https://reviewable.io/reviews/powershell/sharepointdsc/800"

**Comment by pkaminski** [comment]
Adding the button manually will make Reviewable think that the review was already created, and refuse to create a "duplicate".  😛  You should remove the button and create the review by visiting the review URL directly, or by clicking on the PR in your Reviewable dashboard.

Incidentally, that repo's connection is broken because the user who connected it no longer has admin permissions for the repo, which is why the review wasn't created automatically.

**Comment by johlju** [comment]
Haha okay so by "cheating" I made things worse! 😆 It worked perfect when doing it the right way! 😃 

I sent in another PR and that worked. But will keep an eye on the broken connection.
