### ISSUE TITLE
Conversation participation seems overly aggressive

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [Reviewable/Reviewable#555]
Using [this PR](https://reviewable.io/reviews/RobotLocomotion/drake/8873#-LDINiaK4DD5DUCJEpMI) as an example. And, again, I apologize for the lack of rigor of this comment.

Since the most recent beta, I feel that Reviewable isn't doing as good a job at determining which comments require my action. Historically, if I didn't participate in a conversation, it didn't require my explicit acknowledgement to close (nor did the conversation counter at the top of the UI include them in the comments that needed my attention). That seems to no longer be the case. The PR linked above shows a case where I've made some comments, but my counter includes comments with which I've had no interaction.

In examining my particular "You are" state with respect to any of those apparently erroneous conversations, it shows that the "Uninvolved" and "Discussing" icons are identical (partially contributing to the confusion). It shows the "Uninvolved" row shaded (implying that's my current state). And the "Discussing" row indicates that it is "Currently: not OK". (Which makes sense as the comment consists of a single BTW comment.)

Things get *weirder* If I set my state to "Discussing". It resolves the conversation (removing it from my counter), shows the "Discussing" icon next to may name, but the "Discussing" state has now become "Currently: OK". However, the comment hasn't been "OK'd". And this is not the equivalent of clicking "Acknowledge", which doesn't resolve the conversation, but it *does* remove the comment from my counter and marks me as "Following". However, the "Discussing" state now has additional guidance: "This will resolve the discussion" (which wasn't included when I was "Uninvolved").

In my mind, a conversation should only flag the author of the PR and the author of the comment. If I choose to participate in the conversation, then it ends up in my queue. Is the logic of the various states and what causes state changes documented somewhere so that I can correct my misapprehension?

**Comment by jwnimmer-tri** [comment]
Possibly related to the changes planned in #510, though I thought they weren't rolled out yet.

**Comment by pkaminski** [comment]
Thanks for the thorough (and actually quite rigorous) feedback.  I started digging into the relevant code's details but quickly realized that honestly the current system is just fundamentally broken: wrong icons, confusing resolution semantics with no guidance, and unreasonable determination of what's unreplied.  It's possible that some of this got broken by the beta, but I think it's more likely that it was always broken and nobody noticed due to the complexity.

I will be rolling out #510 tonight, and while I'm sure there will be bugs initially at least the system is better thought out -- and, dare I say, sane.  I'll close this issue now because it's about to become irrelevant!
