### ISSUE TITLE
Code using backtick quotes (`) disappears

### ISSUE THREAD

**Issue by dschwank** [Reviewable/Reviewable#558]
I just made a big review and used quite often the backtick quotes (`) to make some code highlighting in the comments (single and multiline). But right after publishing the comments, most of the code blocks are gone. In reviewable I just see text and the first backtick quote and that's it.

Here is an example:

![bug-backtick_quotes](https://user-images.githubusercontent.com/8232196/40726000-1778271c-6425-11e8-85dd-d45ee226c1b6.png)

It should be something like:

```
Here is the same, use a default value for `inputMode: string = 'whatever'`
```

Hopefully they can be restored and are not gone completely ... Let me know if I should add some more details.

---
OS: macOS High Sierra
Browser: Chrome 66.0.3359.181

**Comment by dschwank** [comment]
I just reproduced it multiple times. Then I inserted at another discussion a multiline code block, using three backtick quotes (```) and then suddenly it worked again :-/

Here is a screenshot of a comment section:
![bug-backtick_quotes2](https://user-images.githubusercontent.com/8232196/40729309-60a4e478-642c-11e8-9d21-77412ee659ec.png)

What you see in the screenshot is equal to:
```
- - - - - - - - - 1 - - - - - - - - - - -
Better `localColumnTemplate`?
- - - - - - - - - 2 - - - - - - - - - - -
Better: `localColumnTemplate`?
- - - - - - - - - 3 - - - - - - - - - - -
WTF ...
- - - - - - - - - 4 - - - - - - - - - - -
Better: localColumnTemplate?
- - - - - - - - - 5 - - - - - - - - - - -
Better: `localColumnTemplate`?
- - - - - - - - - - - - - - - - - - - - -
```

Between comment 4 and 5 I used the multiline code block in another discussion in the same review.

**Comment by dschwank** [comment]
Here is another example ...

**Write mode**
![bug-backtick_quotes3](https://user-images.githubusercontent.com/8232196/40730475-06e053ca-642f-11e8-80c8-599386b4eecf.png)

**Preview mode**
![bug-backtick_quotes4](https://user-images.githubusercontent.com/8232196/40730485-0d1eb614-642f-11e8-999b-bdcda76a9c99.png)

Suddenly the text after the first backtick disappears. The complete second section is missing.

**Comment by pkaminski** [comment]
Hey Dominik, thanks for reporting this and sorry for the trouble.  I haven't been able to reproduce the issue so far (Chrome 66.0.3359.181 on Win 10).  Could you point me to the review and discussion where you have some published comments with broken backticks?  That will allow me to check whether the issue was with the Markdown source, the Markdown render (both persisted), or the view.  Also, please double-check that you still see this issue if you turn off all extensions.  Thanks.

**Comment by pkaminski** [comment]
Still unable to reproduce, even following your simple instructions...  :(  Which version of Reviewable Enterprise are you using?  (It's shown at the bottom of the Support menu.)  Does the source text (on the Write tab) get mangled as well, or just the Preview / render?  It's pretty suspicious that this only occurs in Chrome since I doubt it's a browser compatibility issue.  Any chance that there's some corporate extension preloaded for Chrome on all your machines, and enabled even in incognito mode?  Or perhaps some proxy that's intercepting API calls to GitHub?

One thing you can easily check is to do your repro and look in the Network tab for a POST to `/markdown` on your GHE instance, then check whether the input or output (or both, or neither) are broken.  That will at least narrow down where the issue gets introduced.

**Comment by dschwank** [comment]
I think it is an issue of Reviewable + Mac + Chrome ...
We are using version: v1785.2755

It's just the rendered text which doesn't work, but it seems like the problem is with the raw text. As you recommended I just checked the`/markdown` call.

Here is what is *written in the comment*:
![bug-backtick_quotes5](https://user-images.githubusercontent.com/8232196/40827602-53b2b01c-657e-11e8-9741-13ba6b4b4f86.png)

And here is the *request* to `/markdown`:

```json
{
  "text":"Hey this is a `",
  "mode":"gfm",
  "context":"frontend/cave"
}
```

So the wrong text is handed over to the `/markdown` endpoint. It must be some problem of Reviewable + Mac + Chrome, because on other platforms (like GitHub) I can use the Markdown code highlighting in a normal way. Maybe something is wrong with the parsing of the raw text?

**Comment by dschwank** [comment]
I just debugged the code a little bit - it seems like something is wrong with the `draftForm` / `draftText`, the model value is already wrong. But due to the minification & mixture with Vue it's hard for me to see where it comes from ;)

**Comment by pkaminski** [comment]
You're running the latest (Enterprise) version, and there's no related fixes pending, so that's not the problem.

If you're up to it, there are some things that will help you poke around better (though the code will remain minimized -- sorry!).  You can load the page with `?debug=scope`, then inspect the draft and check `$($0).scope().draftText`.  This is the raw Angular model that's connected directly to the textbox.  If it doesn't reflect the contents of the field then something's wrong with Angular.

You can also load the page with `?debug=model` and dig into `truss.root.users['github:NNNN'].state['XXXX'].drafts` to find your draft and check its `markdownBody`.  If this doesn't match, then there's a problem in saving the draft from `draftText` to Firebase.  (`NNNN` is your GHE numberic user id, which you can find by inspecting your avatar URL.  `XXXX` is the review key, which you can get in `?debug=scope` mode by inspecting somewhere around the Changes box and checking `$($0).scope().review.$key`, or just browse around the `state` structure since there should only be one review loaded anyway.)

I'm also going to try to reproduce on a Mac later today.

**Comment by pkaminski** [comment]
Failed to repro in Chrome 67.0.3396.62 on Mac OS X Sierra 10.12.6.  This narrows down the potentially buggy platform combinations...  Could you upgrade your Chrome and try again?

**Comment by dschwank** [comment]
Hey!

Sorry for replying so late.
I just checked it with Chrome 67.0.3396.62 and I also checked it on two more machines - always the same problem.

I also used your debug helpers to get some more insights - and it seems like it is somehow connected to Angular - at least the model value is already wrong. Whoever is setting the model value, is probably the root cause for the problem.

Would like to give you some more details, but it's hard to debug the code :-/ ...

**Comment by pkaminski** [comment]
So to double-check I tried this again on a local copy of Reviewable Enterprise v1785.2755 (still Chrome 67 on OS X 10.12.6) with no luck getting a repro.  Also, `draftText` is directly connected to the `textarea` through Angular with no additional filters:  `<textarea ng-model="draftText" ng-trim="false" ng-model-options="{debounce: {default: 100}}">`.  The only other piece of code that writes to this property is the one that syncs the database value to the view model, but again it is content-agnostic (as is the view to database direction).

Given that I can't repro and that nobody else has mentioned the issue, I think chances are high that this is something weird in the environment on your side -- sorry.  Can you double-check with extensions disabled, making sure that none are enabled to run in incognito mode?  Since it only happens in Chrome, are you always the user signed into Chrome or does it happen for different users / no user too?  Is it still limited to OS X or did you successfully repro on other machines?

**Comment by pkaminski** [comment]
Ping -- any luck on isolating this further?

**Comment by dschwank** [comment]
No luck so far - we still have the same problem ... quite frustrating. I will try to reproduce it on some other operation systems ... but probably it is related to OS X.
