### ISSUE TITLE
Could not start a top level discussion

### ISSUE THREAD

**Issue by johlju** [Reviewable/Reviewable#559]
When I was writing a comment, I wanted to make a new top level comment. But the 'Start new disucssion' button did not respond. I refreshed the page, and it started to work again. I have not been able to reproduce this, but wanted to report it just the same.
 
https://reviewable.io/reviews/powershell/xwebadministration/359

*When reviewing this particular PR it behaved strangely - cannot put my finger on it - but at one point clicked to view a file, and all the header information, including the bunny-dropdown, disappeared, I got an icon "arrow pointing upward", when clicking on that I got back again. Never seen that before. I don't know what I did. Just mentioning this as there could be an extreme edge case to reproduce the above.*

**Comment by pkaminski** [comment]
You got to the special single-file view, where the toolbar and all top-level discussions are removed.  You get there by holding {cmd, ctrl} while clicking on the file name.

I tried going through single-file mode and using the up-arrow to get back to normal mode, but I was still able to start a new top-level discussion, so not sure what went wrong especially since the only guard on that method is whether you're signed in.  If it happens again please check the console for any messages, though it's unlikely there'd be any...  Normally I'd ask for a live debug session, but if reloading the page makes the bug go away that wouldn't be helpful either.

I'm going to leave this issue open for the time being but unless it starts happening more often / reliably it's unlikely I'll be able to get enough info to fix it.  Sorry.

**Comment by pkaminski** [comment]
Closing until we can get at least one repro...
