### ISSUE TITLE
Request for Github CI check information in request data

### ISSUE THREAD

**Issue by tmollerus-zaius** [Reviewable/Reviewable#574]
I really like the fact that we can customize whether or not a review is complete, but we'd like to include our Github CI checks in our logic. I see they're included in the "Checks" tab, but aren't available in the JSON for the request. Any way you can pull that data in? Thanks for the consideration.

**Comment by pkaminski** [comment]
Hmm, so I purposely kept the status checks out of the completion check's input data structure because GitHub's branch protection can already take them into consideration, so it seemed unnecessary to "nest" them inside another status check.  Can you let me know what's your use case?  I assume it can't be implemented using branch protection?  Thanks.

**Comment by pkaminski** [comment]
Closing stale feature request with no motivating use case.  Happy to reopen given more details.
