### ISSUE TITLE
No way to move a review out of "being reviewed by me"

### ISSUE THREAD

**Issue by ggould-tri** [Reviewable/Reviewable#585]
If I comment on a review (eg, to answer a question asked in a comment) then the review moves into the "being reviewed by me" section of the "My Reviews" page (and gets the associated red flair on the page, suggesting I need to act on it).

There should be a way to remove myself from "being reviewed by me" status.

![blurred_ss](https://user-images.githubusercontent.com/17596413/44589493-b2155980-a786-11e8-8530-29667cdf4c57.png)

**Comment by pkaminski** [comment]
Good point.  I changed the logic so that past participation in a resolved discussion will no longer put the review in the "being reviewed by me" section.  Participation in a currently unresolved discussion will still qualify for that section, though.  I think this is a fair compromise and avoids adding more manual controls to the page.  

Of course, ideally we'd know with precision whether you're a reviewer or a bystander and I had originally hoped that GitHub's "requested reviewers" would fill that need, but unfortunately its semantics are not a good fit and I don't want to introduce yet another explicit mechanism for identifying reviewers.
