### ISSUE TITLE
Error: Hubkit error on GET ....

### ISSUE THREAD

**Issue by nparrag** [Reviewable/Reviewable#593]
I have got this exception in the reviewable:
Error: Hubkit error on GET https://api.github.com/repos/**************: Request terminated abnormally, network may be offline

I got this about 40 times during 2 hours.

Could you check what is the problem? (my github account is OK, reviewable my collegaues on the project reviewable is WORKING)

**Comment by pkaminski** [comment]
Sorry about that.  This is the error Reviewable gets back from the browser when the browser doesn't want to tell it what actually went wrong, sometimes due to security concerns (real or imagined).  There's no way to debug further without more information:  could you please check if there any errors or warnings in the console, or keep the Network panel open and see if you can find more details about one of the failed requests?  Thanks.

**Comment by nparrag** [comment]
Sorry, but I couldn't reproduce it ever since. The good new is that, I had a problem for one day and now everything is working.
Thanks.

**Comment by nparrag** [comment]
Sorry, I have to reopen the issue.
I couldn't work with reviewable.io, I'm getting the same exception as I mentioned above.
I couldn't find any useable information on the Network panel. (Checked: Network traffic XHR)

On the console all of the requests end with CONNECTION_RESET.
for instance:
raven.js:1495 GET https://api.github.com/emojis?access_token=c1214e5ca32179c3b934bacd6f7676d1d339d928&per_page=100&_nocache=571970 net::ERR_CONNECTION_RESET

My browser version: Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by pkaminski** [comment]
Please try with no extensions loaded, as connection reset errors are out of Reviewable's control.

Also you'll want to revoke your authorization since you posted your access token in the clear (I edited your message to delete it).

**Comment by nparrag** [comment]
Thanks.
I try to hard reload with empty cache the page without any kind of extensions, it isn't working.

**Comment by pkaminski** [comment]
Thanks for checking.  Looks like the problem is somewhere outside the browser then, since AFAIK there's no way for JS code to cause (or prevent) this error.  Some things to try:

1. Turn off any local firewall or virus checker.
1. Check your proxy settings and try turning off if there is one.
1. Try using a different ISP (e.g., on your cell phone, or home vs office).
1. If this only happens for GitHub, check that they're not blocking your IP by issuing a simple API fetch from a command line:  `curl https://api.github.com/zen -v`.

Hopefully one of these will provide a clue as to what's going wrong.

**Comment by pkaminski** [comment]
Closing as stale -- happy to reopen if you'd like to follow up on this.
