### ISSUE TITLE
Diff: detect moved or copied files

### ISSUE THREAD

**Issue by pkaminski** [Reviewable/Reviewable#6]

**Comment by marekrogala** [comment]
+1. For me this is the main issue with reviewable at the moment.

Having a file rename clutter the review with apparent removal and addition of files is terrible. And this happens quite often in refactoring and forces us to resort to github for such reviews.

This should be an easy fix, since this is handled cleanly by git itself.

**Comment by DamianRodziewicz** [comment]
+1 This would be a very useful feature

**Comment by dolmen** [comment]
Here is [another PR](//reviewable.io/reviews/perl-pod/Pod-Spell/20) where this is problematic. I have moved a 1220 lines files. The 1220 lines are shown, but this is useless. What matters is just the rename.

**Comment by pkaminski** [comment]
Detection of renamed/moved (but not copied) files is now implemented.  Since Reviewable doesn't make use of git's or GitHub's diffs, it applies a custom algorithm that will always detect exact renames, and heuristically match rename-and-edits.  Note that matches are only attempted between Reviewable revisions, so committing after moving but before editing a file won't help detection unless you also capture that commit as a revision in Reviewable.  Please let me know if you spot false positives or false negatives!
