### ISSUE TITLE
Merge button broken

### ISSUE THREAD

**Issue by dedan** [Reviewable/Reviewable#602]
I experience this regularly since a few weeks I would say. I approve a PR and the top right button changes to "merge and submit", but it's deactivated or hidden behind something, so I can't click it. 

See screenshot:

<img width="676" alt="screen shot 2018-11-05 at 1 38 09 pm" src="https://user-images.githubusercontent.com/196905/47998606-46455a80-e100-11e8-8f4e-034975018bde.png">

**Comment by pkaminski** [comment]
This appears to be an issue specific to the Squash merging style but I haven't managed to nail it down yet.  @dhalperi also reported it.  If my current guess as to the root cause is correct then switching to another merge style then back to Squash in the dropdown should be a viable workaround -- could you please give it a try next time this happens?  Thanks.

**Comment by pkaminski** [comment]
I've rewritten the button's logic so it can never get stuck in this state again.  Of course, there's always the chance I introduced new bugs...  I'm sure you'll let me know.  😉
