### ISSUE TITLE
Large file with Changes Collapsed

### ISSUE THREAD

**Issue by deiden26** [Reviewable/Reviewable#609]
A review I was working on had a large file (roughly 4000 lines) with a handful of changes to review. Reviewable collapsed the entire file, forcing me to open the entire file and scan through it manually to find where the changes were. This was both tedious and resource intensive for my computer.

![screen_shot_2018-12-12_at_12 52 12_pm](https://user-images.githubusercontent.com/2993523/49898484-0a439a80-fe0e-11e8-9202-74780ec4dfe1.png)
![screen shot 2018-12-12 at 12 57 52 pm](https://user-images.githubusercontent.com/2993523/49898658-70302200-fe0e-11e8-872a-a7cb9cef54a0.png)

This happened with the "collapse whitespace changes" toggle both switched on and switched off.

**Comment by pkaminski** [comment]
Notice the bit about "4041 lines with base commit changes" -- all the changes were in the base (likely due to a rebase-and-force-push, but there are other ways to get there), and Reviewable hides those by default.  You can click on the "base commit changes" link to expand just those lines.

Unless those were real changes that got misinterpreted as base commit changes it seems to me that things are working as expected.

**Comment by deiden26** [comment]
Ah. Thank you for the help. Closing this issue. I would, however, consider adding a more explicit indication that clicking that link will display the changes. Maybe remove the link from "base commit changes" text and add "Show Changes" linked text after the current text. That would b much, much clearer. I asked around to see if people knew what was going on. The response I received is that this behavior looked like a bug.

**Comment by pkaminski** [comment]
Thanks for the feedback -- this bit of the UI is tricky, since there can be many "kinds" of lines hidden by default, so a single "show changes" link wouldn't work.  Keep in mind that there's always F1/h online help available, and I'll be transitioning it soon to show on hover, which should make it even more convenient to access.

**Comment by deiden26** [comment]
>
> I'll be transitioning it soon to show on hover, which should make it even
> more convenient to access.


Sounds great!
