### ISSUE TITLE
Collapse files with no changes

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#61]
In the later stages of a code review (e.g. r3..r4 [here][1]), the number of files changed per revision can be quite small relative to the total number of files in the PR.

Each unmodified file takes ~230px of vertical space, so when only 3/17 files have changes, you wind up scrolling through a lot of uninteresting diffs.

It would be nice to have a way to hide these completely, either via keyboard shortcut or as a global setting.

![screen shot 2015-03-05 at 1 26 47 pm](https://cloud.githubusercontent.com/assets/98301/6511503/55bc3416-c33b-11e4-82da-7e989592d68c.png)

[1]: https://reviewable.io/reviews/hammerlab/cycledash/513

**Comment by pkaminski** [comment]
I think my idea was that most users would use the status bar or keyboard shortcuts to jump to the next file that needs attention, rather than scrolling through manually.  I'm a bit averse to hiding things completely, but I'm mulling some kind of experts-only "zen mode" that would also hide resolved discussions (and perhaps all discussions, optionally: #40).

**Comment by pkaminski** [comment]
Files with an empty diff and no comments are now hidden automatically, using up only ~19px of vertical space each.
