### ISSUE TITLE
Error: No such user when requesting reviewers: ApiResourceProperty

### ISSUE THREAD

**Issue by nparrag** [Reviewable/Reviewable#614]
I tried to publish my comments to a pull request but I got this error:
"Error: No such user when requesting reviewers: ApiResourceProperty"

Could you help me, what is the problem? (Could you see in your logs, what is the problem?)
I use reviewable with github login.

**Comment by pkaminski** [comment]
Hi -- the error message is misleading, I'll fix it.  Chances are that you have @ApiResourceProperty somewhere in a comment, and Reviewable is trying to interpret it as an @-mention but failing because there's no user named @ApiResourceProperty.  If this was meant to be a Java-like annotation then you should make sure it's formatted as code using either single or triple backticks per Markdown syntax.

**Comment by nparrag** [comment]
Thanks!

**Comment by jwnimmer-tri** [comment]
@pkaminski As I understand from #616, the current intention is that these mentions are not supposed to prevent publishing?  I am seeing `@keyword` in a discussion produce a `Failed to publish: No such user when processing directives: keyword` error on Enterprise version v2056.3350.

**Comment by jwnimmer-tri** [comment]
Oops, I see that our Enterprise version is out of date; this fix was only applied as of Release 2066.3418 if I'm reading correctly.  Comment withdrawn!
