### ISSUE TITLE
Use more granular GitHub permissions

### ISSUE THREAD

**Issue by samtstern** [Reviewable/Reviewable#615]
Currently enabling reviewable requires giving write access to the whole repo.  While we certainly trust you, this is against my company's (Google's) policy and we are not allowed to grant it.

If we could give permission to write Pull Requests only (or some other minimal set) my team and others at Google would adopt Reviewable:
https://developer.github.com/v3/apps/permissions/#permission-on-pull-requests

Even though our repos would fall under the free open source tier, we'd be happy to pay for such an excellent service anyway.

**Comment by pkaminski** [comment]
I wish I could do this -- please see #482 for the canonical discussion about switching to apps-based integration.  The short of it is that the API available to apps is incomplete, and missing some key function points that Reviewable needs.

In the past, we solved this for Google teams by having them set up a self-hosted "Enterprise" instance and running it against github.com.  This does cost money, though.  If you're interested, please ping me by email and we can discuss this option.

**Comment by samtstern** [comment]
@pkaminski thank you for the response!  That makes sense, although it is a shame.

**Comment by qdm12** [comment]
Hello all, since it has been quite a few years since the last comment, is it now possible to use Reviewable without giving it full R/W access to all your profile and/or organization(s)? I would really like to try using it for a single repository to start with, but giving full R/W access sounds like a pretty big security risk for my personal account as well as for organizations. Thank you! 🙏

**Comment by pkaminski** [comment]
Sorry, this is still not practical — please see the tail of the discussion in #482, starting at [this comment](https://github.com/Reviewable/Reviewable/issues/482#issuecomment-2014437006).
