### ISSUE TITLE
Feature: display diffs in one directory

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#625]
If the PR is small enough, you can see all the diffs at once. If it's bigger than that, you can see one file at a time, and the interface becomes much less convenient at this point. I understand it's an important trade-off, though.

I suggest a middle-ground level that kicks in at intermediate sizes: see all diffs in a directory at once. So for `a/b/file`: if the entire PR is small enoguh, show everything; else if the `a` subtree is small enough, show all files under `a`; else if the `a/b` subtree is small enoguh, show all files under `a/b`; else show just `a/b/file`.

**Comment by pkaminski** [comment]
At the moment, my intention is to improve performance to the point where it's possible to show hundreds of files on a modern machine so switching to single-file mode will be a user choice rather than a necessity.  Work on this is ongoing with a transition from AngularJS to VueJS.

If hiding files remains necessary, though, I'm more likely to do it by [file group](https://docs.reviewable.io/#/files?id=file-list) (see last paragraph of section) rather than by directory.
