### ISSUE TITLE
Actionable discussion without a way to proceed

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#635]
I stumbled upon another case where I can see one actionable discussion but there is nothing I can do. The last message in the discussion is mine, so I don't really see what else I can be expected to do.
[state.txt](https://github.com/Reviewable/Reviewable/files/3034149/state.txt)

**Comment by pkaminski** [comment]
Could you please also point out which discussion has the confusing state?  Either by hash (shown in the address bar as the hash after you click anywhere in the discussion) or by filename / line number.  Thanks.

**Comment by feldgendler** [comment]
`#-LaFuQiy-RHDScEW8YDg` if I'm doing it right.

**Comment by pkaminski** [comment]
Thanks, found it.  This is an interesting case -- you're `blocking` and posted the last comment, but the PR author is `satisfied` and has acknowledged your latest comment [1].  This makes Reviewable's logic fall through all the "normal" cases until it hits the backstop of "just make whoever's blocking responsible, since we don't know what else to do".

Posting a new comment would punt back to the PR author, at least until they acknowledge that one too.  That doesn't seem like the right way to resolve the problem, though.

I think in the case where everyone's up-to-date yet things still aren't resolved, responsibility should fall on all active participants other than the last one to post a comment.  Does that sound reasonable to you?

---

[1] In this case, the UI doesn't offer the `Done` button since the author is already `satisfied` (perhaps due to having hit `Done` in a previous round).

**Comment by jwnimmer-tri** [comment]
If I'm understanding this issue correctly, then I see this come up not-infrequently, actually.

In this case, If I'm a reviewer and I'm **happy** with the outcome of the discussion, I'll just click on the lower-right circle and mark myself satisfied, at which point the red bubble is gone (and the discussion is resolved).  If I'm still **unhappy**, but the PR author thinks that I should be happy (as was signaled by the author clicking "Acknowledge"), then I feel like the red bubble is correct -- I need to reply to the author, explaining (or at least reminding them) what is still wrong with the PR.  They think they are done, so it's on me as the reviewer disabuse them of their misconception.

> Posting a new comment would punt back to the PR author, ...

I think a reply is correct way to put the red bubble back to the author, actually.  I could imagine some sugar where the UI explicitly offers to either [Resolve] xor post ["Still undone."] for me, to help guide me and prevent @feldgendler's confusion.  Per your question @pkaminski though, I would be sad if the author got the red bubble without me interacting -- I feel like by the author clicking "Acknowledge", the ball should say in my court until I do something.

**Comment by feldgendler** [comment]
> I think in the case where everyone's up-to-date yet things still aren't resolved, responsibility should fall on all active participants other than the last one to post a comment. Does that sound reasonable to you?

Yes, I think this will be natural

**Comment by pkaminski** [comment]
TBH I'm torn -- it's clear that either algorithm will be confusing to some, and it's not self-evident whether posting recency or stated disposition should be dominant.  I think I'm going to stick to the current behavior: while it's confusing to the blocking user, the alternative would be even more confusing to the user who's satisfied.  (Once I'm satisfied, why should the discussion be my problem at all?)

I'm happy to hear counterarguments, or alternative suggestions, though.

**Comment by feldgendler** [comment]
It's possible to keep the current behavior but make it less confusing. Currently the problem is not that I should post to keep the ball in the air, the problem is that I don't know what I should do.

I can imagine a “bump” button that's equivalent to posting a comment, just without an actual comment. Or alternatively, if that doesn't seem like a good idea to you, some text explaining that I need to either resolve the thread or write a comment.
