### ISSUE TITLE
Make it possible to ignore or collapse files in specific folders

### ISSUE THREAD

**Issue by kennethlynne** [Reviewable/Reviewable#638]
We have a react-native app with lots of CocoaPods that are checked in to GitHub. Anytime we add a dependency it blows up the review.

We would like to be able to add a .reviewableignore file or similar that lets us tell reviewable that everything under the ios/pods should be ignored.

After a react-native upgrade, we had 14k files changed, making reviewable unusable for that PR

**Comment by pkaminski** [comment]
Have you tried the (relatively new) [grouping feature](https://changelog.reviewable.io/directory-tree-and-grouping-92404)?  You should be able to easily write a custom code snippet that would group all the CocoaPods together, and collapse the group in your file matrix once.  From that point on, the group will always be collapsed whenever you open the review page, which may be sufficient to bypass the performance issues which presumably is what "blew up" the review.

You can also use `.gitattributes` to suppress diffing of these files (treating them as generated files), as [documented here](https://docs.reviewable.io/#/files?id=generated-files).

Do either or both of these help?  I'm hesitant to allow completely ignoring files in the review to the point where they don't show up at all, since you then wouldn't be approving what's actually going to be committed.

**Comment by pkaminski** [comment]
Ping -- could you please address my comments above?  Thanks.

**Comment by kennethlynne** [comment]
Thanks for the reply, I will give it a try and close this issue for now! Thanks for the help @pkaminski
