### ISSUE TITLE
More prominent inline changes

### ISSUE THREAD

**Issue by nbali** [Reviewable/Reviewable#642]
When there is a file that has a few comments on it already, and a small inline change is performed it's rather hard to notice that among the visually much "stronger" comments, etc as the context for such comments are shown, so what we see is dozens of lines, multiple comment "boxes", and somewhere in all that is the actual inline change.

My proposition is to mark the lines with the proper color at the side, so you can just scroll through the file focusing on that "vertical ruler", and check the actual content for the change if it indicates there is any.

**Comment by pkaminski** [comment]
This issue comes up every so often and I have two standard suggestions for resolving it:
1. You can increase the contrast of the diff highlights in the account settings dropdown.
2. You can set a custom stylesheet to force highlighting of the whole line (like in single-column diff views), as explained [here](https://docs.reviewable.io/#/accountsettings?id=custom-stylesheet).

I think your suggested visual treatment has merit, but Reviewable currently uses vertical rulers to indicate overflow (i.e., a line exceeding the set margin) so I think overloading these semantics could be confusing (even with different-colored rulers) and the CSS would likely be tricky to get right.
