### ISSUE TITLE
Enforce "Merge style" restrictions in completion conditions

### ISSUE THREAD

**Issue by jwnimmer-tri** [Reviewable/Reviewable#643]
Use case: In our repositories, we permit both "Create a merge commit" and "Squash and merge" in our GitHub settings.  However, on a particular PR either the author or a reviewer might want to designate a preference for one or the other.  Currently my team communicates this using PR labels as a hint, but occasionally someone sees the exciting big green button on their Reviewable screen and pushes it, without noticing the label that recommended a specific merge style request.

Feature request: In the big green "Merge" / "Finish" widget, I'd like to be able to restrict the "Merge style" alternatives more narrowly than what GitHub allows, hopefully via the review completion condition that I've already customized.  When merging via Reviewable, merge styles excluded by the completion condition would be unavailable (i.e., not merely a suggestion, but a hard and fast rule).

Really this should be a GitHub feature and Reviewable should just come along for the ride, but I suspect my odds of making it happen are better with Reviewable than GitHub.   This means that merging via the GitHub web interface would still be open to mistakes, but my team rarely uses the GitHub interface anymore; their everyday interactions are always with Reviewable.

Along with Reviewable's new feature of suggesting commit messages via the completion conditions, having this related feature would be a real bonus for our daily workflow.

**Comment by pkaminski** [comment]
I like this idea and it wouldn't be too hard to add.  One concern is how to deal with the situation where some combination of GitHub and Reviewable constraints exclude _all_ the merge styles.  (This isn't preventable with a post-condition data validation check since it's the union of the two systems that is determinative.)  Just ignoring the condition's constraints in that case seems like it could be confusing but I can't think if any better approach.  Thoughts?

**Comment by jwnimmer-tri** [comment]
If my condition reduces the allowable options down to the empty set, I don't think I have any preference for what Reviewable would do.

If Reviewable decided to present the green button in that case and offer GitHub's options (ignoring the the completion condition culling), but I really did want to prevent merging of any kind, then I could still write my completion condition to set `completed == false` acutely in that case, apart from the merge options.

If Reviewable decided not to present the green button in that case (since the set was empty), then the GitHub merge button would always still work as an escape hatch (assuming the review was marked as completed).

**Comment by pkaminski** [comment]
OK, thanks for the feedback.  My concern is that debugging "my merge button isn't showing up!" or "my constraints aren't being respected!" complaints will get harder either way.

Also, what do you think about designing this as a single forced `mergeStyle` feature, rather than a whitelist (or blacklist) of styles?  There's no real difference in implementation difficulty, but the API is a bit cleaner:  `return {mergeStyle: 'squash'};` instead of `return {mergeStyles: {squash: true}};`, say.  Though of course this would preclude more complex "2 out of 3" constraints.

**Comment by jwnimmer-tri** [comment]
> Also, what do you think about designing this as a single forced mergeStyle feature, rather than a whitelist (or blacklist) of styles? 

In my case that would be fine.  We currently only allow 2 of the 3 GitHub styles, so if I'm going to blacklist one of them, then I'm necessarily down to a single option.

**Comment by pkaminski** [comment]
Implemented as `mergeStyle` in condition output.  If it conflicts with GitHub-permitted styles Reviewable will just ignore it, and let the user select any style.  (This turned out to be easiest to implement.)
