### ISSUE TITLE
Reviewable shows loading spinner indefinitely

### ISSUE THREAD

**Issue by benbelow** [Reviewable/Reviewable#644]
When the `Also show pull requests you're not involved with from all repos to which you can push. ` toggle is on, my revieable has recently (some time this morning) started just showing an indefinite loading spinner. 

I can access reviews directly, I Can view the repositories page, and I can see my reviews with this toggle on.

However our team uses default reviewer groups in Github, which are not respected by this filter, so my workflow does not suit leaving this turned off - in order to continue using Reviewable as my primary review tool I will need this to be fixed. 

This is not reproducible by another member on the team, who can still load reviewable with that setting as expected.

**Comment by dhalperi** [comment]
Having this problem too - when I turned off both toggles at the bottom, the page came in right away.

**Comment by pkaminski** [comment]
I'm reverting some changes to permission checking I made last night.  I don't yet see how that would have affected the page in this way but it's the most likely culprit.

**Comment by pkaminski** [comment]
Rollback complete, can you please try again?

**Comment by benbelow** [comment]
Yup, that's working again now. (It's a little slow to load, but I don't
think that's new)

**Comment by pkaminski** [comment]
OK, thanks.  Unfortunately, I can't reproduce the original failure locally so it must be some edge case in permission checking that you're both hitting.  I'll keep looking and give a heads-up here if I decide to push this change again.

**Comment by pkaminski** [comment]
I have rolled part of the change forward again, retaining only the modifications that affect the Repositories page (and no other).  This shouldn't affect the Reviews page but please let me know if reality disagrees with this assessment.

**Comment by benbelow** [comment]
I'm afraid the issue has returned this morning.

**Comment by pkaminski** [comment]
Hmm, I'm not seeing anything in the logs or metrics to indicate a problem.  @dhalperi are you affected as well?  @benbelow are the symptoms exactly the same as originally described?  If so, do you happen to know what repo(s) should be showing up when the toggle is one that don't show up when it's off?  (i.e., the repo delta between working and non-working states -- one of those is likely to be causing trouble)

**Comment by dhalperi** [comment]
Yes, I see the issue and now I am also getting 403s from github:

```
{
  "documentation_url": "https://developer.github.com/v3/#abuse-rate-limits",
  "message": "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
}
```

**Comment by bharath23** [comment]
I am hitting the same issue. Only way to get the review page to load is to turn off "Show pull requests not yet connected to Reviewable" and "Also show pull requests you're not involved with from all repos to which you can push"

Disabling both gets the page loaded, albeit a bit slow.

**Comment by pkaminski** [comment]
I'm starting to wonder if the timing of this issue is coincidental, and GitHub just happened to change their abuse rate limiter logic near the time I pushed the last change.  Are you seeing the 403's filter all the way up to the UI on the page, or only in the console / network panels?  If the latter, does the page just stay in the spinner state?

I'm pushing a small update now that increases the interval between query chunks from 500ms to 800ms to see if that helps with the "abuse" detection.  If it doesn't, it would be helpful to get a list of queries that the page is running for you along with result codes -- perhaps the "abuse" is being detected earlier in the workflow, before the current rate limiting mechanism kicks in.

**Comment by dhalperi** [comment]
Was not getting 403s the first time.

**Comment by dkeitel** [comment]
Just chiming in, I am experiencing the dreaded infinite spinner in the "Reviews" section as well.

Not seeing any 403s from GitHub in the network tab when loading that view though.

**Comment by pkaminski** [comment]
OK, I think the 403s were a red herring due to folks reloading the page to get it to work.  I've reverted the query interval to 500ms and added a state display to the spinner.  Please let me know which message it gets stuck on -- that should cut the search area for the bug to a third!

**Comment by bharath23** [comment]
I re-enabled the "Also show pull requests you're not involved with from all repos to which you can push" and I am experiencing the infinite spinner. I checked console/network panel and there are no 403s. Eventually it is trying to load summary.json and ends up alternating between 204 and 200 and an occasional 304.

Disabling "Also show pull requests you're not involved with from all repos to which you can push"  allows the page to load again.

**Comment by pkaminski** [comment]
What does the message under the spinner say when it gets stuck?  (The `summary.json` fetches are unrelated, it's doing regular checks of GitHub's status API.)

**Comment by benbelow** [comment]
I'm still experiencing the issue: The message is "Running Queries"

**Comment by dkeitel** [comment]
> I'm still experiencing the issue: The message is "Running Queries"

Same here.

**Comment by pkaminski** [comment]
Thanks everyone.  I've thoroughly instrumented the query code to narrow things down further.  Could you please load https://reviewable.io/reviews?debug=dashboard and copy the contents of the console here after things have settled down?  (Or send to support@reviewable.io if you're concerned about the private team and repo names contained therein.)

**Comment by dhalperi** [comment]
emailed

**Comment by pkaminski** [comment]
Thank you!  The issue is specific to the "only connected repos" filter on the toggle.  Reproduced and working on fix now.

**Comment by pkaminski** [comment]
Turns out that turning on "connected repos" does a bulk fetch of user permissions, and there's a [bug](https://github.community/t5/GitHub-API-Development-and/Grapql-viewer-repositories-gets-only-repositories-where-the-user/m-p/14318) in GitHub's GraphQL API that I recently switched to because the old REST API was breaking under heavy load.   😭

Reverted to REST since slow and occasionally broken is still better than fast but often incorrect.  This should resolve things over the next half hour or so, as cached permissions get refetched.  Apologies for the issue and how long it took to resolve -- this week has been uncharacteristically filled with meetings.
