### ISSUE TITLE
Filenames are not selectable

### ISSUE THREAD

**Issue by macmason** [Reviewable/Reviewable#648]
The filenames shown in a diff (or in the file matrix) are mouse-selectable (ie if I want to highlight it with a cursor and copy it).

@lshamis FYI

**Comment by pkaminski** [comment]
The filenames in the diff headers are selectable; in fact, you should be able to double-click on one to automatically select the whole thing for copying.  Is that not working for you?  If not, which browser are you using?

The filenames in the matrix are indeed not selectable, in part due to the on-hover "expand full path" effect.  Given that you can get to the diff header from there in one click I don't see it as a big issue.

**Comment by macmason** [comment]
Aha, double-clicking does the trick. Agreed, the triple-click (file matrix to jump, double-click to select) is a good solution. Thanks!
