### ISSUE TITLE
Check-mark visually challenging

### ISSUE THREAD

**Issue by RemiTorracinta** [Reviewable/Reviewable#649]
Due to my grey profile picture, the check-mark overlaid over my review icon is difficult to make out. I'm not the only person with this problem at my company.

Perhaps something less transparent (or colored green?) would be easier to see?

![Image of Checkmark On My Profile Pic](https://i.imgur.com/9ILYb82.png)

**Comment by pkaminski** [comment]
Hey, sorry for the delayed reply.  I agree that the transparency makes the icon hard to make out, especially with greyscale avatars.  Ideally, I'd like the checkmark itself to be opaque while the surrounding disc is transparent, but the only way I can think of doing that is via luminance-based masking which is basically unsupported in CSS.  Changing the color is also not a great option, as the color is orthogonal to the icon's contents: red/grey indicates whether the review/discussion is pending on the person, while the icon indicates their current disposition.

I'll need to play around with making the whole icon opaque but that can also make certain avatars harder to recognized.  I don't see a clear win here at the moment.

**Comment by RemiTorracinta** [comment]
I don't know much about how to render things on the web. Can't you get different opacities for the disc and check-mark and using the alpha channel in a png?

**Comment by pkaminski** [comment]
These icons are not bitmapped images since that would look terrible at different resolutions / zoom levels.  They're vector images, currently encoded as a custom font, which precludes any kind of manipulation of parts of a glyph.  I intend to switch to an SVG encoding in the future but I'm not sure if that will help with the issue or not.

There may be some combination of layering, masking, and blend modes that would achieve the desired effect, but if so it requires more CSS-fu than I can muster right now.

**Comment by yonch** [comment]
+1 on this.
