### ISSUE TITLE
"Squash and Delete" closes and deletes branch if another PR is merged just before

### ISSUE THREAD

**Issue by chronal-xnor** [Reviewable/Reviewable#650]
What happened: I was trying to "Squash and Delete" a pull request whose checks had passed. Reviewable let me "arm" and press the button to do so. However, the status then updated to "Abandoned and deleted". I checked the PR page and the PR had been closed and the branch deleted, apparently by me.

The apparent cause is that another PR had been merged into `master` between the time the Reviewable page last updated and the time I hit "Squash and Delete Branch". However, *closing* and deleting the branch seems like the wrong behavior to do in this case! 

If it helps to reproduce the issue, I'm using Firefox on Ubuntu 16.04. I had locked the machine during lunch and tried to merge the PR first thing after unlocking it, which may explain the Reviewable page being out of date.

**Comment by pkaminski** [comment]
Ouch, that's rough -- sorry about that.  Reviewable uses GitHub's [merge API](https://developer.github.com/enterprise/2.16/v3/pulls/#merge-a-pull-request-merge-button) and this "fail closed and report success" mode is neither documented nor expected.  It's also not clear to me why a change in the target branch would cause the merge to fail, much less to close the branch instead.  Reviewable doesn't specify a target SHA when calling the API, which requests a merge onto whatever the current head of the target branch happens to be.

Could you please document the repo and PR number here (or send to me at piotr@reviewable.io for privacy) so I can involve GitHub support in figuring out the root cause of this issue?  This feels like it may be a bug on their side but I'm not sure yet.

**Comment by chronal-xnor** [comment]
I was able to reproduce the problem again, I'm not sure but I think it could in fact be a Reviewable issue. I was paying closer attention this time and here's a play by play of what happened:
 - ~2 minutes before this another PR was merged to master
 - Reviewable showed all status checks passing. I armed and released the "Squash and Delete" button.
 - The PR still showed as mergeable for a little bit instead of updating to "Merged" as usual. 
 - I then armed and released the "Squash and Delete" button *again*.
 - The PR status updated to "Abandoned and deleted" as before and GitHub showed the actions as "closed PR" and "deleted branch"

I believe this double-arm happened last time too, but I didn't make note of it at the time. Is it possible Reviewable has a race condition where trying to "Squash and Delete" again before Github has responded (or Reviewable has processed the response) the first time causes this to happen instead?

**Comment by pkaminski** [comment]
Interesting.  I still don't think it's possible for Reviewable to be the root cause of the issue because the client never invokes the only API documented to close a PR (and the server does, but never sets the relevant field).  I'll see if I can reproduce what you experienced, though -- at a minimum, it looks like Reviewable isn't reacting to status changes properly.  Was this an old-style commit status, or one of the fancier new Checks?  (Reviewable presents them the same way, but they follow different code flows under the hood.)

**Comment by chronal-xnor** [comment]
I believe they are simple commit statuses. We have three, including Reviewable's own status, which are required to merge a PR (plus the mergeability "status", which is only green if the PR has merged the latest `master`).

**Comment by pkaminski** [comment]
Thanks, I found and fixed a bug where errors during merging were sometimes ignored, causing Reviewable to proceed with branch deletion when the merge had in fact failed.

I think there's another potential issue if you regularly see Reviewable lagging more than a few seconds behind the current state of the PR (for a connected repo).  In principle, GitHub should be sending webhook events that will cause Reviewable to update the review state, even without reloading the review page.  It's possible for this to fail or run late occasionally, e.g. because webhooks aren't guaranteed or retried, or because Reviewable is temporarily out of API quota to process them, but if it happens more often than "once in a while" please open another issue so we can get to the bottom of it.

**Comment by chronal-xnor** [comment]
Will do, thanks for the fix!
