### ISSUE TITLE
as a reviewee, see context that a reviewer's comment was left in

### ISSUE THREAD

**Issue by seansfkelley** [Reviewable/Reviewable#665]
As a reviewee, it can be helpful sometimes to be able to see the diff that a reviewer was looking at when they left a comment.

For instance, they may have been viewing a small change from only one commit, but it's in the middle of a large block of changes from previous commits in the PR. If they use vague phrases like "these changes", it's not clear to the reviewee what is being referred to because the reviewee doesn't know if the reviewer was looking at the diff from one commit or many when they left the comment.

Using the dog-ear on the top right shows me the revision they were looking at, but not the diff they saw.

I was not able to find a way to do this nor find an issue that describes this feature, so apologies if it already exists or has been filed.

**Comment by pkaminski** [comment]
Hmm, I like this idea in principle, but right now the full diff bounds are not saved with a discussion, only the target revision and line.  This is fixable of course but it's not clear which diff bounds to save:  when the draft was first created, when the draft was last "touched", or when the draft was published?  (Or even more complicated, the bounds during which most of the draft's contents were written -- but that would require a lot more code to estimate.)

Other than that, I like the idea, especially as it wouldn't require any extra UI (we'd just redefine the dog-ear to switch to the saved diff, instead of only switching one bound).

**Comment by seansfkelley** [comment]
Of the cuff, I'd say it makes the most sense to keep it when the draft was published. I personally review all my outstanding comments right before I hit publish, so for me that would reflect my intent as a reviewer best.

This came up today as I was teaching others how to use Reviewable -- they found it a little difficult to understand exactly what comments were referring to because there were a lot of changes in the PR, and when going-to-next-comment there would be no red/green diff visual cues, just the text.

**Comment by pkaminski** [comment]
Actually, I think capturing diff state at publishing time would break badly for everyone using commit-by-commit review style, since they'll go through a series of diffs during the review and end up on the latest one (or some other arbitrary one).  I think capturing at draft creation is probably the least surprising approach.

I get that seeing comments against nil-diff files as the PR author is a bit weird but I'm not sure that capturing "intended diffs" would help, since a file may well contain discussions linked to many different such diffs and we can only pick one to show initially.  Perhaps for PR authors it would make sense to diff the latest revision against the last one they made a comment on (or base by default), but this would lose the current somewhat useful feature of diffing provisional revisions to quickly self-review changes that you just pushed.  Thoughts?

**Comment by seansfkelley** [comment]
Ah, I never use commit-by-commit, so I didn't think of that use-case.

For me, creation-time and publish-time diff bounds are almost always identical, assuming you respect not which diffs _existed_ at the time the comment was made but which diff bounds were being _viewed_. In my case, the only time I change diff bounds after comment creation is if a new revision was pushed _and_ I want to see that revision, at which point I hit "Show Provisional Diffs" to get it for the entire review. (I have probably done it in other cases, but those are exceedingly rare.)

> Perhaps for PR authors it would make sense to diff the latest revision against the last one they made a comment on (or base by default), but this would lose the current somewhat useful feature of diffing provisional revisions to quickly self-review changes that you just pushed.

Showing provisional diffs as the author is somewhat useful and I do take advantage of it, but it requires some synchronization of the reviewer and author in the sense that provisional diffs are shown w/r/t the last thing the reviewer marked reviewed, not the author (right?). I wouldn't lose that feature.

> I get that seeing comments against nil-diff files as the PR author is a bit weird I'm not sure that capturing "intended diffs" would help since a file may well contain discussions linked to many different such diffs and we can only pick one to show initially.

I think the default view settings/diff bounds as-is is perfectly alright. Usually the comments are indeed clear enough that you can work off the comment as written or simply view the revision as it was when the comment was left.

It's only in infrequently and, perhaps while learning, that it's useful to see exactly the diff the reviewer saw (for some definition of "exactly" that is under discussion above). These cases would include unclear or really old comments that a reviewer can't clarify (or clarify quickly enough, in the case of a time-sensitive PR) either because they aren't present or the comment is old and the context has been lost.

I like your idea that it would simply replace the functionality of clicking on the dog-ear: it feels more like a feature upgrade than a new feature, and it doesn't seem to lose any of the functionality of the feature it would replace or require users to adapt their workflows if they don't use the dog-ear feature.

**Comment by pkaminski** [comment]
Implemented -- exact diff context is stored when a discussion is created, and restored when clicking on the corner label.  There were lots of corner cases so please let me know if I didn't get it right!

**Comment by seansfkelley** [comment]
I just tried it out for the first time cause I needed too -- it's great! Thanks a ton for adding the feature.
