### ISSUE TITLE
Reviewable will not load

### ISSUE THREAD

**Issue by benbelow** [Reviewable/Reviewable#685]
This morning, reviewable loaded, but failed to post any new comments, claiming a timemout had been exceeded. 

Now, The review dashboard will not load at all, with the error message "Unable to create review: Request queued but server did not respond"

**Comment by dkolistratova** [comment]
Similar issue. Service loads, but force-pushed changes are not fetched.

**Comment by pkaminski** [comment]
Issue confirmed.  Proximate cause is a slew of GitHub API timeouts starting at 2:40am EDT and apparently not caused by any changes on Reviewable's side.  I have a query out to GitHub support to assist and will continue trying to find a workaround in the meantime.

**Comment by pkaminski** [comment]
I pushed a workaround and things should be returning to normal over the next hour or so.  I still don't know exactly what happened but I eventually worked out that all requests with `If-None-Match` headers suddenly started timing out last night.  That's not the whole story since I can't reproduce the issue with plain `curl` yet but I disabled caching for GitHub API calls in production for now to get everyone unstuck.

If you happen to have a contact at GitHub that might have some idea what's going on, please point them my way!

**Comment by pkaminski** [comment]
The workaround took care of the original issue, but now everything's backing up since the lack of caching is exhausting API quota.  :(  Still looking for the root cause...

**Comment by pkaminski** [comment]
I rolled back to an older version of our HTTP library and I think this has finally fixed the issue, at least server-side.  Please let me know if you see any client-side issues as that's still on the newer (and apparently buggy) version as rolling back there would be much trickier.
