### ISSUE TITLE
Suggestion: show reviewer's disposition more visibly

### ISSUE THREAD

**Issue by dato** [Reviewable/Reviewable#714]
Hello!

I've been using Reviewable to perform code review in my CS courses, and I was planning on introducing next term the use of comment-level dispositions (Blocking/Discussing/Informing) to indicate to my students what issues they _must_ fix, which they _may_ fix if they want to, and what is merely an informational comment.

Our tutorial for code reviews on Reviewable explains about these three dispositions, and shows —together with appropriate explanations in Spanish— the three icons from Font Awesome that represent each of them.

What seems to happen —and I hadn't much realized before— is that the icon representing the disposition of the _reviewer_ (in this case, me) is less visible than I would expect (or like?) once the PR authors (my students) open the pull request on Reviewable. In particular, it seems the bottom-right corner shows _one's_ disposition by default (initially, for them, just Following), and the icon must be hovered over to show the reviewer's avatar and disposition. (This is something I hadn't paid much attention to on my own reviews, but became very noticeable when thinking on the workflow for my students.)

So, TL;DR: do you think it would make sense to display the disposition of a commenter (for a particular comment) in a more visible manner? Perhaps in the author's avatar on the left? I'm not sure whether it'd be too much to do it for every comment, but it seems useful to me at least for the opening comment in a thread (for the reasons explained above). Is there something that I missed? Is there an easier way to check a disposition _for a particular thread_ that I'm not aware of?

Many thanks for considering! (or commenting).

P.S.: Alternatively, it just crossed my mind: if it's better not to touch the current UI (which I'd understand completely) is there or there could be an emoji-like shortcut that I could type to display the icon that represents a particular disposition? Without UI changes, I guess I could take the work to include the appropriate icon as the first thing in each comment. (Of course, in the absence of icons, I'd just use text, but having a way to show the exact same icons would yield a prettier result, that's all.) Thanks for reading!

**Comment by pkaminski** [comment]
Hey there!  So the way this is typically addressed -- in both Reviewable and other review systems -- is that there's a sort of de facto standard for wording comments.  For example, a comment that starts with "Nit:" is usually considered of low importance, while one that starts with "FYI" is fully optional.  Reviewable understands these keywords and automatically sets the corresponding disposition on the comment (see https://docs.reviewable.io/#/discussions?id=change-disposition).  The default assumption is that a comment is blocking, which lines up well with Reviewable's defaulting to Blocking disposition on comments that start a new discussion.

Do you think this would address your concerns?

**Comment by dato** [comment]
Yeah, I'm aware of the shortcuts, I've particularly used FYI often. But, in a way, I wanted the _actual_ disposition to be the ultimate source of truth for the "list of things to do", since that's what consistently I don't forget to set when reviewing student code. And I guess I was a bit enamored of the idea of being able to say, "this icon means that, that icon means this".

>Do you think this would address your concerns?

In the end, I think I'll just end up prefixing my comments with GitHub emoji like :no_entry: and :information_source: (and it has the small advantage that it'll display if the comment is read through GitHub, unlike the disposition). I still think, though, it'd be nice to have the disposition more visible—yet I understand, as I said in my previous message, that the UI is something to be modified with much care and thought.

Short of adding shortcuts for the exact disposition icons Reviewable uses (i.e., to make them writable in comments), I think this issue could be closed. Many thanks for your response.

**Comment by pkaminski** [comment]
I definitely see where you're coming from but there are both philosophical and structural reasons why your suggestions won't work.  Philosophically, whether a discussion is unresolved is supposed to be the ultimate indicator of whether the issue needs to be / has been addressed.  I also believe that every comment deserves a reply (or at least an acknowledgement), which is why the discussion counter prioritizes counting unreplied discussions.  Once all have replies pending, though, it switches to tracking unresolved ones -- which are also indicated by an icon in the top-left corner of the discussion UI.

Structurally, Reviewable doesn't track per-comment disposition but just the current one, so automatically displaying a per-comment indicator would require adjusting a lot of stuff.  Also, it's possible to change one's disposition without writing a comment, in which case there would be nowhere to display the new icon.  As for giving access to the FA icons via custom emojis, that could work and there is precedent with the :lgtm: emojis, but I consider those a failed experiment and would rather not entrench the idea further.  (They make parsing and rendering messages much more complicated, can only be rendered in ugly raster formats rather than clean vector ones, and don't even consistently render in every outside context.)

Finally, I did give some thought to changing the bottom right corner disposition to showing a sort of "worst case" common denominator of all dispositions on the discussion.  This would be more useful for the author, particularly in multi-party reviews.  However, I think seeing your own disposition is much more useful for the reviewer and changing how the display works based on role would be very confusing (especially since it's possible to hold a dual author/reviewer role!).

All that said, I think your proposed workaround is the best you can do for your proposed workflow -- sorry.  Closing as suggested.

**Comment by dato** [comment]
(Not reopening, just clarifying that I, as well, only care about the current state of the discussion, not of every individual comment. Said that, thanks for your detailed message. Also, I appreciate the time you take to compose detailed and reasoned responses in every Github conversation I’ve observed.)
