### ISSUE TITLE
The difference between blocking and non-blocking comments is too subtle

### ISSUE THREAD

**Issue by misha-ridge** [Reviewable/Reviewable#715]
I find it quite hard to notice the difference between blocking and non-blocking (disposition: discussing) comment threads in reviews while working on a PR: former has a "Resolve", latter has "Done" buttons, and that's all.

**Comment by pkaminski** [comment]
You can always check by unrolling the participant dispositions widget (hover over the circle in the lower-right corner).  However, I'm curious what workflow you're using where this distinction is important up front, rather than at the point where you're ready to resolve the issue (when the button label indicates what will happen)?

**Comment by misha-ridge** [comment]
My use-case is the following: when I first receive a PR with a ton of comments, some of them non-blocking (so I can ignore them at my discretion), and some of them are blocking, I'd like to see that without fishing out the status every one of them.

This would make it easier to estimate how much time I need to spend handling comments and generally bringing PR into the shape.

**Comment by pkaminski** [comment]
OK, let's merge this issue with #714 and continue the discussion there, as it's pretty much the same concern and I made more substantive comments there already.  I'll reopen it if needed.
