### ISSUE TITLE
All PRs are edited by the user that connected reviewable

### ISSUE THREAD

**Issue by jlewi** [Reviewable/Reviewable#724]
It looks like all PRs end up getting edited by the user that connected reviewable.

It looks like the edit is adding the Reviewable banner to the PR.

This is undesirable as it can mess up notifications and other signals for the user; e.g. searching for PRs edited by the user is now really turning up PRs edited by reviewable which is confusing.

Is there anyway to fix this?

Can reviewable use a GitHub App to modify PRs as opposed to acting as a human?

**Comment by pkaminski** [comment]
You can change the Reviewable badge placement in the repository settings, for example to switch it to a comment instead:  https://docs.reviewable.io/#/repositories?id=reviewable-badge.  You won't be allowed to disable it altogether on a public repo, however.  If this still poses an issue for queries the only workaround is to create a separate GitHub account to handle the repo connection in Reviewable (though note that if this account runs low on quota, Reviewable may use any other account it has credentials for that has admin privileges for the repo).

Reviewable is unable to switch to the GitHub App integration because it still doesn't provide access to some critical APIs.  See https://github.com/Reviewable/Reviewable/issues/482.
