### ISSUE TITLE
Partial Incompatibility with Safari LastPass Extension

### ISSUE THREAD

**Issue by maxg7** [Reviewable/Reviewable#727]
Note: this is a strange issue only noticed with Safari's LastPass Extension. It may be applicable to others

Issue: With the LastPass extension enabled, when navigating to https://reviewable.io/ the page loads as expected and I'm able to see My Reviews. When checking the url after that it becomes https://reviewable.io/reviews#-. If I press refresh I'm redirected to an error page with the following error. If, however, I remove the `reviews#-` and navigate back to reviewable it loads as expected once again.  Finally, if I disable the Safari Extension it too works even with the `/reviews#-`. 

```
Something on the page crashed, but it doesn't look like it was Reviewable. Please try reloading the page with your browser extensions disabled.

Don't worry, your data is safe. You can also report the issue to provide more details if it's reproducible.

TypeError: a.LegacyGlobal.LP_explicit_ignored is not a function. (In 'a.LegacyGlobal.LP_explicit_ignored(document,e)', 'a.LegacyGlobal.LP_explicit_ignored' is undefined)
```

**Comment by pkaminski** [comment]
The short of it is that this is a bug in the LastPass extension, though similar bugs exist in others too.  You should ask LastPass to fix their code or disable the extension.

What's happening is that Reviewable hooks itself into some page-level error reporting callbacks, because in a promise-heavy architecture that is the only way to catch certain failures.  Unfortunately, browsers don't partition this hook between the page and extensions, so failures in either will trigger it.  While Reviewable attempts to determine whether a failure came from its own code or somewhere else, this is far from 100% reliable so I decided to crash on any detected failure.  Another reason to do this is that if an extension is suffering from such failures its state may be corrupt, which can affect Reviewable's functioning and lead to spurious bug reports that I'd rather avoid.
