### ISSUE TITLE
Opening reviewable in a new tab logs me out of reviewable in all tabs

### ISSUE THREAD

**Issue by bitdancer** [Reviewable/Reviewable#733]
The title says it all.  It started when I upgraded my browser to firefox-esr-60.9.0-r0 on Alpine.  I have 'accept cookies' set to 'always'.  It happens regardless of whether I open the tab via right click/open in new tab, or just open a new tab and go to reviewable.io.

**Comment by pkaminski** [comment]
That's odd, I'm not sure what's going on.  Note that all session info is stored in the IndexedDB and local storage, so you might want to double-check any settings related to those.  You could also try running Reviewable with `?debug=workers` appended to every URL (but before any hash anchor); this will force Reviewable to use per-tab workers rather than sharing them across tabs.  If that fixes the problem it would narrow down the possible causes.

Note that FF 60 is over a year old now and, even though it's an ESR, we generally don't commit to supporting releases that old -- though of course we try our best.

**Comment by bitdancer** [comment]
OK, I finally got around to upgrading to ESR 68.  It didn't fix the problem.  So I started over with a new profile, and things work fine.  So it must have been either bad stuff left over in my profile after one or more firefox upgrades, or some problem with the way my preferences got carried over between versions.  Setting things from scratch seems to be working fine, even though I think I'm using the same settings.

As an interesting aside, after the upgrade but before I created a new profile, logging in to another application that uses github auth also caused reviewable to be logged out.  So whatever was going on, it was definitely odd, but was also directly related to the github authentication process.
