### ISSUE TITLE
Relative dates gain tooltip showing absolute date

### ISSUE THREAD

**Issue by dato** [Reviewable/Reviewable#739]
It would be nice if it was possible to disambiguate dates like "1 week ago" by hovering and getting a tooltip to show the absolute date, like Github does.

Funnily enough, I find myself opening the pull request page in Github _just_ for this, because my workflow sometimes requires that I write down the day a PR had activity last.

Is there a way to get this info, or a setting, that I might have missed?

Thanks for considering!

**Comment by pkaminski** [comment]
To clarify, do you mean the relative last activity timestamps in the people section at the bottom of the main review discussion?  We could definitely get an absolute date into the tooltip there.  We could also do it for the status check timestamps, but it might not make sense for the comment separator timestamps since those get rounded off and often aggregate multiple absolute dates.

**Comment by pkaminski** [comment]
Released.  Also added absolute timestamps on the comment avatar tooltips.
