### ISSUE TITLE
The 'view on github' button should link directly to the given file

### ISSUE THREAD

**Issue by dhalperi** [Reviewable/Reviewable#741]
Example: https://reviewable.io/reviews/batfish/batfish/5851

<img width="935" alt="Screen Shot 2020-06-10 at 5 27 26 PM" src="https://user-images.githubusercontent.com/526415/84331676-afdce480-ab3f-11ea-9fb2-7feae5961827.png">

That button takes you to `https://github.com/batfish/batfish/compare/924f3cc8f8e499d59499d2cb36fb5db1df4d1bb4...2f6d93093ebc6f3cd4ad4614182e6e27041efb98#files_bucket` ; the link to the correct file (`tests/parsing-tests/unit-tests-vimodel.ref`) is `https://github.com/batfish/batfish/compare/924f3cc8f8e499d59499d2cb36fb5db1df4d1bb4...2f6d93093ebc6f3cd4ad4614182e6e27041efb98#diff-49f73cce5a630bb6facc40ec6cee7e93`.

When we discussed this in the past, the problem was that github did not document the anchor tags and we couldn't figure it out.

Either it's changed or we were dumb in the past, but the anchor seems to be `diff-{md5sum $filename}`:

```
echo -n "tests/parsing-tests/unit-tests-vimodel.ref" | md5sum
49f73cce5a630bb6facc40ec6cee7e93  -
```

Since GitHub does not document this (on purpose, it seems on querying), generating these links is risky. The flip side is that linking to incorrect anchor takes you to the top of the page, which frankly is not very far from `#files_bucket` - so not much of a regression and it would be easy to revert if they change the alg...

**Comment by dhbradshaw** [comment]
This is now live...thanks for speccing this out @dhalperi !

**Comment by dhalperi** [comment]
Yesss! 🎉

**Comment by dhalperi** [comment]
I'm surprised it happened this quickly, but github has changed the algorithm from md5sum to sha256sum. (I confirmed locally that the same approach works). Would it be a hard change to update the anchors?

**Comment by pkaminski** [comment]
This shouldn't be too hard from a technical POV, but doing so unconditionally would break the functionality for older versions of GHE Server.  Since this isn't an official API the change isn't documented -- do you have an idea when the change might have been made?  As in, what's the last day you remember this working?  Thanks.

**Comment by dhalperi** [comment]
Lol, of course. *sigh*. The only hard date I can find is when I told people about it the first few times I used it, which would have been right around August 18th.

I can also confirm that the failure is not too bad -- it's basically the same as the behavior before (anchor doesn't exist, so just stays at the top of the page)

**Comment by pkaminski** [comment]
If we assume that this change was made in a major GHE revision (since minor ones are usually reserved for fixes), then it's likely that it was either in 2.22 (2020-09-23) or is scheduled for 2.23.  I'm going to assume 2.23 since it's plausible it happened around the same time as the switch to [SHA-256 webhook fingerprints](https://github.blog/changelog/2020-10-26-webhooks-configuration-enhancements/) (2020-10-26) and it doesn't feel important enough to stand up an instance and check.

**Comment by pkaminski** [comment]
This should be working again, hopefully.
