### ISSUE TITLE
Allow using Reviewable to review repositories I don't have write access to

### ISSUE THREAD

**Issue by jyasskin** [Reviewable/Reviewable#75]
I'd like to use Reviewable to review https://github.com/w3c/web-nfc/pull/13/files, but since I don't have write access to that repo, the option doesn't show up. I imagine you could do it by just posting the review as my comment, without editing the initial request to include the Reviewable image link.

**Comment by pkaminski** [comment]
Hey Jeffrey, this is already possible.  You can go to https://reviewable.io/reviews/w3c/web-nfc (this works for any repo you have pull permissions for) and click on the PR.  When you publish comments, the message will have plenty of links to Reviewable, and if the author (or someone with admin privileges on the repo) follows any of them then the Reviewable badge will be added to the description.  I decided not to write the badge into a comment instead so that its location is consistent.

(Note that the first time you do this for a PR it'll take a few seconds to create the review.  In some cases the UI seems to get stuck at the "Loading review" stage -- I'm looking into it, but you can just reload the page for now.)

As for the PR not showing up in your dashboard by default -- there's really no way for me to know that it's of interest to you until you've become involved in it somehow.  I can't very well show all PRs in all repos that you have pull access to.  :smile:

**Comment by jyasskin** [comment]
Aha! Thanks. I think I gave up on it because editing the URL for a closed review didn't work (but maybe that was the "Loading review" bug). This would be more discoverable if there were a field in the UI that let me paste, say, the repo name or PR URL. I totally understand not showing absolutely everything in the My Reviews section by default. I don't suppose it's possible to notice when I've 'Subscribe'd to a PR?

There's also a small bug: https://reviewable.io/reviews/w3c/testharness.js returns a 404, even though https://github.com/w3c/testharness.js/pull/115 exists.

**Comment by pkaminski** [comment]
Good idea about the PR URL field -- added.  AFAICT there's no way to detect what you've subscribed to.  Well, maybe there is, but for the life of me I can't figure out GitHub's [notifications API](https://developer.github.com/v3/activity/notifications/).

Fixed the 404 bug -- that was me trying to be clever with rewrites, so thing won't blow up in development if you try to load a missing file.  But I didn't consider the possibility of repo names looking like files.  Oops.

Still looking into the "Loading review" issue.

**Comment by pkaminski** [comment]
Actually, I take that back: it is possible to [list all issues](https://developer.github.com/v3/issues/#list-issues) you're subscribed to.  It's a different API than I use to populate the list but I could merge in the results.  I'm not yet convinced yet that including PRs you're subscribed to but not otherwise participating in is a good idea, though.  What are the cases where somebody would do that do you think?

**Comment by jyasskin** [comment]
I was thinking of watching subscriptions mostly as an alternative to the URL input box. Now that you have that, I think it'll be just as convenient to copy the PR's URL into Reviewable as to subscribe to the PR. Thanks!

**Comment by pkaminski** [comment]
BTW, the "Loading review" issue should be resolved now as well.  `undefined !== null`...
