### ISSUE TITLE
Unclear how to get multiple independent reviews

### ISSUE THREAD

**Issue by cjancsar** [Reviewable/Reviewable#750]
I have read through the following issues:
- https://github.com/Reviewable/Reviewable/issues/560
- https://github.com/Reviewable/Reviewable/issues/404
- https://github.com/Reviewable/Reviewable/issues/455

It is still not really clear how to achieve the following:
> - Enable multiple independent reviewers (and get individual solid red for unreviewed and green for reviewed).
> - Have a minimum required number of approvers

Is see this comment here: https://github.com/Reviewable/Reviewable/issues/560#issuecomment-394552605

```
_.forEach(review.files, file => {
  _.forEach(file.revisions, rev => {
    rev.reviewed = /* custom logic here */;
  });
});

return {
  files: review.files, // ... other properties, as documented
}
```

What should my custom logic be?

**Comment by pkaminski** [comment]
So the answer, of course, is "it depends" 😄, but let's see if we can get you on the right track.

First, here's what you would use to require more than one review per file:

```js
const numRequiredFileReviewers = 2;

_.forEach(review.files, file => {
  _.forEach(file.revisions, rev => {
    rev.reviewed = _.size(rev.reviewers) >= numRequiredFileReviewers;
  });
});

return {files: review.files};
```

This should take care of the red/green button colors.

For PR approvals, you could set things up a few different ways depending on exactly what effect you're looking for.
1. The easiest would be to use GitHub's approval system and set a minimum number of reviewers in the branch protection rules, but this would be independent of the review status of individual files.
2. You could also just use Reviewable's default completion logic (all files reviewed, all discussions resolved) and make Reviewable's status check required in branch protection.  The condition above works as-is for this scenario, since it leaves `completed` unset.  You also would turn off GitHub's approval system.
3. Finally, you could compute completion manually in the condition to gain full control (and set Reviewable's status check as required in branch protection, as above).  For example, to require all files to be reviewed but allow discussions to be left unresolved, you could add this to the above:
```js
const allFilesReviewed = _(review.files)
  .map(file => _(file.revisions).reject('obsolete').last())
  .compact()  // ignore files where all revisions are obsolete
  .every(rev => rev.reviewed);

return {completed: allFilesReviewed, files.review.files};
```

Hope this helps -- let me know if you have any further questions.

**Comment by cjancsar** [comment]
Thanks man, this should do it I think. I do love reviewable. Makes reviews so stream lined and consistent.
