### ISSUE TITLE
E-mail address default for merge action

### ISSUE THREAD

**Issue by dato** [Reviewable/Reviewable#751]
Hello!

When I click _Merge pull request_ in Github, it seems that it doesn't default to my primary e-mail address for the author field, but that address I've configured in _Settings → Notifications → Custom routing_. I don't know if this behavior is properly documented somewhere—but it’s terribly convenient.

I know Reviewable doesn't offer UI to pick an email address at merge time, but it’d be so convenient if it’d just match Github’s behavior, particularly when combined with the click-hold-and-release to merge behavior in the dashboard (which I only found about today, and is awesome)¹.

Thanks for considering!

(¹) That button is actually why I’m writing this report: I’d love to use it. Previously, I was just doing the merge via Github, it’s no biggie and it was the same number of clicks. :)

**Comment by pkaminski** [comment]
Hey, so Reviewable doesn't get to pick the email address to use at all:  we just invoke GitHub's "merge PR" API and let it do its thing.  What kind of merge are you running, though -- is it a Squash Merge?  If so, there's a known API limitation:  https://github.community/t/which-email-is-used-for-squash-and-merge-commits/2959.  Otherwise it might be a similar limitation or a bug in GitHub.

**Comment by dato** [comment]
Ah, interesting; thanks for answering (and thanks for the link, it was a useful read). There's nothing to address in Reviewable, then. :)

When I get a chance, I'll try to verify if by chance the merge end-point would use the last address used in the repository, as mentioned in that thread. That'd be suboptimal, but progress.

Cheers!
