### ISSUE TITLE
Support context snippets for bazel BUILD files

### ISSUE THREAD

**Issue by jxramos** [Reviewable/Reviewable#753]
It's super useful the feature I find for python `*.py` diffs whereby you get a "diff context header" provided by reviewable. I'm not sure what the official term is but I'm talking about this stuff where you get the python scope of where you're at in the diff among all the collapsed/hidden unchanged stuff.

![ellipses diff expansion](https://user-images.githubusercontent.com/13857038/85805993-b30cce80-b702-11ea-900a-f590a933bc9a.png)

Reviewable's doing something intelligent to give us hints to the context where the diff is taking place which is incredibly useful. I have another filetype, very close to the python syntax, which is the bazel `BUILD` files which adopt the starlark language. Likewise for all the other `*.bzl`, `*.bazel` files as well.

By way of practice here's a list of public bazel projects https://github.com/jin/awesome-bazel#projects you can find BUILD files to develop with if you so choose to dig in. For example...
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/BUILD

Is there any possibility to get diffs to lend context for these file types too please?

What I'm thinking is the rule instantiation followed by the name declaration, eg

```python
tf_cc_shared_object(
    name = "tensorflow_cc",
```

I think if you hook on the nearest name match and walk back a line you'd handle the bulk of the cases outright! Thanks again.

**Comment by dhbradshaw** [comment]
Interesting.  I wonder how hard it would be to introduce some kind of plugin system...

**Comment by pkaminski** [comment]
Reviewable uses syntax highlighting information from [highlight.js](https://highlightjs.org/) (plus indentation) to make the magic happen.  I don't see Bazel as a supported highlight.js language so somebody would need to add a regex-based recognizer for it or adapt an existing one if it's close to another supported language.  Once that's done and makes it into a highlight.js release, we'd just need to add a file extension mapping in Reviewable to make sure it uses the correct parser (as I turned off auto-detect since it was too flaky).

@jxramos, want to give this a try?  highlight.js has pretty good dev documentation and infrastructure.

**Comment by jxramos** [comment]
I'll dig around, sounds promising, I know a lot of folks would dig this. I'll start casually reading up on the subject, hopefully there's some youtube conference talks or something on the subject. What would the concrete deliverable be for reviewable to actually consume? Must be something like one of these files tailored for bazel...

https://github.com/dullin/highlightjs-vba/blob/master/src/vba.js

Quickly came across that in their list
https://github.com/highlightjs/highlight.js/blob/master/SUPPORTED_LANGUAGES.md

Exciting stuff.

**Comment by pkaminski** [comment]
Good luck!  You'd need to first get your PR accepted into highlight.js, then ping this issue so we pick up the new library release and add Bazel to our list of supported languages.

**Comment by jwnimmer-tri** [comment]
For the record, until the highlight.js work is done, reviewable users can place this snippet in their `.gitattributes` file to get a reasonable approximation:
```
WORKSPACE diff=python
**/*.bazel diff=python
**/*.bzl diff=python
```

**Comment by pkaminski** [comment]
Based on the [Starlark language summary](https://docs.bazel.build/versions/master/skylark/language.html) it looks like the language is a strict subset of Python, at least in terms of surface syntax features.  Perhaps we can just remap `.bazel` and `.bzl` to the Python syntax highlighter?  It might incorrectly highlight stuff that the language doesn't support (e.g., `class`, `import`, `while`, etc.) if they're used as variables rather than keywords but I think that's about the worst that could happen.

On the other hand, the language is so close that making a new highlight.js plugin for it should just involve stripping out unsupported keywords from the Python highlighter, which should be quite easy too.

One thing that I'm not sure how to address by default is `BUILD` files, since those aren't necessarily going to be written in Bazel (it's a popular filename).  I think a custom `.gitattributes` as shown above is the right solution there.

**Comment by jwnimmer-tri** [comment]
There is a slightly subtlety here -- there are two concepts in play.

One is syntax coloring, where the `.gitattributes` trick to map to `python` is a fairly robust workaround, and which your prior message speaks to.

For that, I think mapping `**/*.bazel` and `**/*.bzl` to `python` by default would be suitable, even without keyword tweaks.  I agree that deferring `**/BUILD` to the user's `.gitattributes` customization is a good compromise.   We've been using `python` highlighting via `.gitattributes` for almost 5 years  (https://github.com/RobotLocomotion/drake/pull/4759) with no complaints.  It would be great to have this built-in so we don't need the `.gitattributes` added to every repository, and it would be great to customize the keywords for Starlark vs Python, but neither are particularly onerous (to me, at least).  

The specific request in the top post, though, was beyond just coloring -- it was for the "function name" to be shown before the diff hunk begins, to provide some context for the lines of code under review.

On that front, for `**/BUILD` or `**/BUILD.bazel` files, the `python` style falls down.  Bazel's build recipes are listed declaratively, as if they were function calls.  ([See an example here](https://github.com/bazelbuild/bazel/blob/master/examples/cpp/BUILD).)  In this example the attributes are few and compact (name, srcs, hdrs, deps), but in many cases a single target will span 20+ lines, in case it contains many sources, or has many dependencies (they are always listed one-per-line).  It is not uncommon to have one-liner changes within it (e.g., adding a new dependency), where the diffs shown by Reviewable do not show the key `name = "foo"` attribute.  It would be great it we could get `name = "foo` into the "function name" header prior to the start of each hunk.

Here is a specific example -- in https://reviewable.io/reviews/RobotLocomotion/drake/15115 for `geometry/BUILD.bazel` around line 244 we add `":collision_filter_manager"` to someone's `deps`, but we can't tell _whose_ deps unless we expand the diff to show more lines.  It would be _superb_ if the context prior to the diff said something like `name = "scene_graph",` -- or even better, `drake_cc_library(name = "scene_graph",`.

For the less-common case of `**/*.bzl` files (which are reusable functions to be imported and reused across BUILD files), the `python` style gets us most of the way -- bzl files contain either macros or implementation rules, and the macros start with `def foo(...)` just like python.  The _rules_ have a different syntax (see https://docs.bazel.build/versions/4.1.0/skylark/rules.html#attributes for an example), as in `foo = rule(... large block of kwargs ...)` so do not match the python function signature.  However, these are uncommon enough that they are probably not worth worrying about.  Solving `**/BUILD.bazel` context would be much more valuable.

**Comment by pkaminski** [comment]
Thanks for the extra detail Jeremy!  This confirms that the syntax coloring should indeed be quite trivial to achieve.

The declaration extraction will be trickier, though.  First, there is precedent for having language-specific rules for this (see: Go) but it would require having a separate Bazel-specific plugin for highlight.js with its own language code.  Second, the declaration extraction system is currently unable to show more than one source line, or combine multiple consecutive source lines.  This means that it would be pretty easy to tag the `drake_cc_library(` line as a declaration (any function call at indent 0), and feasible to tag `name = 'scene_graph'` as a declaration (the line following a function call at indent 0).  I _may_ have an idea on how to tweak the system to merge consecutive lines into one declaration but I'd need to play around to see if my hack would work.

Based on your knowledge of the build file format, does it sound like the rules I sketched out above would successfully capture most of Bazel's usage patterns?  If we'll need to build a separate plugin anyway, is there any syntax highlighting that the current Python stand-in could do better on?

**Comment by jwnimmer-tri** [comment]
> Based on your knowledge of the build file format, does it sound like the rules I sketched out above would successfully capture most of Bazel's usage patterns?

I think so, yes.  I also did a skim of some of tensorflow's BUILD files (mentioned in the top post), and they seem like they would match well enough with these rules.

If anyone else on this thread has counter-examples, please chime in.

If you'd like to see a test case that contains a wide selection of BUILD syntax, this one looks pretty good:
https://github.com/tensorflow/tensorflow/blob/v2.5.0/tensorflow/lite/BUILD

The first ~90 lines are prologue that doesn't quite fit the regular patterns, but on the other hand the next 800+ lines do fit the pattern, and the kinds of things we see in the first ~90 lines are typically more compact like we see in this example, so don't usually suffer from lack of context.

> If we'll need to build a separate plugin anyway, is there any syntax highlighting that the current Python stand-in could do better on?

Looking at that example link, on github.com it seems like function names are colored (purple), and in current Reviewable when BUILD is set to use Python highlighting they are uniformly black just like the attributes or anything else.  (The strings _are_ colored as strings, though.)  If the declaration matching learns about BUILD files, though, I suspect that might automatically be fixed anyway?  Anyway, looking at hightlight.js vs github.com's styling of BUILD files would at least point out things that _could_ be colorized differently.

(Also note per https://github.com/bazelbuild/starlark/blob/master/spec.md#lexical-elements that even though Starlark is a dialect of Python with fewer keywords, most of Python's keywords are at least _reserved_ words in Starlark, so I'm not sure the highlight plugin would be that different for keywords.)

**Comment by jxramos** [comment]
Absolutely correct, it's the name attribute that's the juicy context to secure since the bazel rule/macro instantiations will be repeated much, eg `cc_test`, `cc_binary`, `py_test`, `py_library`, `py_binary`. It's the name attribute that will differentiate each and give the unique context to the diff.

I started to study up the highlight.js library but never finished those studies. All my notes thus far were compiled into this gist: https://gist.github.com/jxramos/2a95a5f51c1e0614995df6e6ff738d0b

**Comment by pkaminski** [comment]
Support for Bazel is now live -- it went much more smoothly than I expected.  Please give it a try, but don't forget to remove any custom `.gitattributes` files first.

Admittedly I took some shortcuts to get there.  I declared `bazel` as an alias for `python` in highlight.js to bypass needing to define a new language and get it accepted into the project, since the syntax should be close enough.  I then added a custom `if` fork that treats any non-indented line in Bazel as a declaration, and if the following line is an indented `name = ` line it gloms the two together.  I even decided to force `BUILD` files to be treated as Bazel, as the only other use of the file I could find was Pants and its syntax looked extremely close to Bazel.  (I may have to revert this part if I overlooked another significant source of usage, thought.)

Anyway, things seem to be working well in my quick tests so hopefully it'll work for you too!

**Comment by jwnimmer-tri** [comment]
Looks good in a first pass, thank you!
