### ISSUE TITLE
Target branch head commit sha in completion condition

### ISSUE THREAD

**Issue by jwnimmer-tri** [Reviewable/Reviewable#763]
In my review completion condition, I would like to implement a (more customized) flavor of the "Require branches to be up to date before merging", but where it only applies under certain conditions -- in my case, only when using `mergeStyle: merge`.

I already have `revisions[].baseCommitSha` available to the condition.  I think if I also had `pullRequest.target.headCommitSha` available, I would be able to implement this comparison.

Is it possible to add the target commit sha to the condition input?

**Comment by pkaminski** [comment]
Ask and ye shall receive!  This is live now, but without backfill so you may not see a value right away on all reviews.

**Comment by jwnimmer-tri** [comment]
I'm working through testing this now, but I'm not seeing the results I expect.

For https://reviewable.io/reviews/RobotLocomotion/drake/13823, I am computing in my completion condition:
```
var baseSha = review.revisions.slice(-1)[0].baseCommitSha;
var headSha = review.pullRequest.target.headCommitSha;
```

The `baseSha` is correct -- `8d65c5920d79564b932d6aeefd858ee7e7920819` was the commit on master that the branch was created form.

But I am _also_ seeing `headSha` come out as the same value, even though there have been commits to master since that point.  Currently there have been two commits to master since the branch, so I would have expected the `headSha` to be `b331672ecfd84b0759259669855c3411a37986f7` as of now (or possibly even a newer one as more things continue to merge today).

**Comment by pkaminski** [comment]
I agree that something's wonky -- it looks like either GitHub's API is wrong, or I don't understand how it works.  When pulling current data directly from GitHub, I'm seeing different values for `base.sha` in the PR data structure and for `refs/heads/master.object.sha` in the git data structure.  I expected the PR data to be updated along with the branch rather than keep the stale value.  I guess maybe the PR base sha is the last commit the PR was updated to target?

I updated the code to use the raw ref value instead, let's see if that helps.  No backfill, so values will not be updated until the review resyncs (e.g., by visiting the review).

**Comment by jwnimmer-tri** [comment]
Thanks!  I can confirm that it's operating as expected now -- I am seeing the latest sha.
