### ISSUE TITLE
Avoiding notification emails upon doing minor changes to pull request details or fields

### ISSUE THREAD

**Issue by poornima55** [Reviewable/Reviewable#774]
HI,

I see that whenever I reply to different review comments, the Github sends a notification email to each of the replies separately and making a minor changes to fields like description of the Pull Request sends a notification email. This will spam the email of my reviewers. How can I avoid it? Is there a way to selectively turn on/off the notification emails?
Exploring on the internet did not help me find a solution.

**Comment by dhbradshaw** [comment]
Github will send notifications whenever it gets a new comment and whether or not a recipient receives a notification is up to the recipient, not you.

However, one thing that Reviewable allows you to do is to batch up your comments instead of sending them one at a time.  So instead of publishing each comment, make all your comments but don't publish them.  Then when you've made all the comments you want to make for that batch, press publish.  They should end up just getting one email for the whole batch.

**Comment by pkaminski** [comment]
Closing due to lack of follow-up.  Please update with more information and we'll reopen!
