### ISSUE TITLE
Dismissing reviewers from discussions is very hidden

### ISSUE THREAD

**Issue by gsuess** [Reviewable/Reviewable#783]
We often lose a lot of time, because the feature of dismissing a blocking discussion for someone who is currently unable to mark it as resolved.

This is because the feature is super hidden. You have to hover over an icon. So unless you know where to look it cannot be found. This feature is not even documented anywhere.

I think this feature could be made more visible.  Also in order to avoid this feature being overused when made visible, It would be nice every dismissal would require a comment on why it was dismissed.

**Comment by pkaminski** [comment]
Hmm, so this is actually [documented](https://docs.reviewable.io/discussions.html#checking-and-changing-dispositions) in the user manual and can be easily searched for there.  I'm also not sure where else it would make sense to put this function -- it seems to belong pretty clearly with the disposition being dismissed, so unless I unroll all those by default it's not clear to me how to improve the feature's visibility.  Any suggestions?

**Comment by gsuess** [comment]
I suppose you are referring to this part of the documentation:

![image](https://user-images.githubusercontent.com/1558575/98009888-5d55da80-1df6-11eb-8ea2-a96ebdb02cba.png)

I guess it ticks the box, but is not clear what "disposition dropdown" is referring to.

On our internal stackoverlfow we have documented it as follows:

![image](https://user-images.githubusercontent.com/1558575/98034721-ba15bd00-1e17-11eb-855d-beb6fc7db144.png)

What makes it hard to find is that the so called disposition drop-down is hiding behind a mouse hover and that actionable to "dismiss the discussion" does not look very actionable, because the link has the same visual prominence as the the link next to it, which is not an actionable, but just a link towards another page. 

Unrolling them by default would in my opinion improve the feature's visibility as it requires one less interaction to find it. And particular interaction is also the least intuitive in the whole flow. Maybe it could also just unroll those which are blocking.

However I would think the better solution would be to add a button somewhere that explicitly says "Dismiss blocking discussion". When that button is clicked it prompts for a "Reason", which would then be added as a comment saying "x has dismissed y's discussion: reasonz".

**Comment by pkaminski** [comment]
Perhaps instead of dismissing per-user per-discussion, or even per-discussion, it would be a better idea to dismiss per-user as suggested in #617?  I think this is the most common use case, and this way we could also integrate with dismissing GitHub's reviews.  What do you think?

**Comment by gsuess** [comment]
I can see the value in #617 as bulk dismissal for all discussions of a user.

However it very much based on the principle that Code Reviews are an approval process. For us code-reviews are a feedback process, but we do not want feedback to ever be ignore and not acknowledged.

This is why we allow authors to override blocking feedback as long as they can justify why they did do so.

Doing this in bulk would mean that there is a higher risk that some feedback will go unacknowledged.

#617 may be about making it more effortless to dismissing blocking discussions. This is about making it easier to find in high level of control that we have here already.

**Comment by pkaminski** [comment]
Thanks for explaining your use case in more detail, that makes sense.  Permanently expanding the participants list would require a rework of the UI, since right now it's not guaranteed that there would be space for it (the list can be arbitrarily long, and often overlaps the button/field when expanded).  And frankly, the dismissal feature is meant to be used very sparingly, so I don't think it makes sense to make it more prominent.

How about this, though:  when a discussion isn't resolved, the user's disposition is Satisfied, they could dismiss other participants to resolve the discussion, _and_ they have a draft open, a small link to "dismiss dissenters" appears above the draft, next to the participant dispositions stack.  Clicking the button automatically dismisses anybody blocking the discussion from resolving.  (Requiring a draft to be open is mainly due to needing space for the button, but it also encourages writing an explanation.)

I still wouldn't make the link very prominent since I don't want to encourage this behavior, but it would be a lot more obvious and easier to use than the current placement.  Thoughts?

**Comment by gsuess** [comment]
The proposal sounds very good to me. Nice and simple.

**Comment by pkaminski** [comment]
Great, that shouldn't be too hard to put in.

@benjamin-t-wilson See [above](https://github.com/Reviewable/Reviewable/issues/783#issuecomment-725918398) for spec.  Also, if any dismissals on the discussion are pending, the link should change to a "N dismissals pending" blurb with a link to "(undo)".  (It doesn't matter how the dismissals were enacted, we can still call it "undo".)

**Comment by pkaminski** [comment]
This is now live, let me know if it does the trick @gsuess.
