### ISSUE TITLE
Open images in comments in new tab

### ISSUE THREAD

**Issue by Cellule** [Reviewable/Reviewable#795]
Since loading a reviewable page can take quite some time, navigating away when clicking on a link or an image is really annoying.
It would be better if it opened in a new tab instead. 
Which is the behavior that Github has currently

**Comment by pkaminski** [comment]
So some years ago I just decided to make all links same-tab for consistency, and because developers typically know to use ctrl-click or middle mouse button to open a link in a new tab if so desired.  I do think that consistency with GitHub is a powerful argument, though.  However, AFAICT links in comments don't actually open in a new tab in GitHub.  Let's try:  [this is a link](http://example.com).  (Not sure what you meant about images -- just an image link like this?  [<img src="https://reviewable.io/review_button.png" height="20">](https://reviewable.io))

**Comment by Cellule** [comment]
I meant an image like this
`![image](https://user-images.githubusercontent.com/4157103/99308431-f4bf2280-2825-11eb-9be9-7a521fc63852.png)`
![image](https://user-images.githubusercontent.com/4157103/99308431-f4bf2280-2825-11eb-9be9-7a521fc63852.png)

Usually I do a screen capture and just paste the image in Github/Reviewable.
Looks like I was wrong about links though, even in github they open in same tab, my bad there.


For the images, looks like by pasting an image github uses 
```html
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/4157103/99308431-f4bf2280-2825-11eb-9be9-7a521fc63852.png">
  <img src="https://user-images.githubusercontent.com/4157103/99308431-f4bf2280-2825-11eb-9be9-7a521fc63852.png" alt="image" style="max-width:100%;">
</a>
```
While images the way you used them uses
```html
<a href="https://reviewable.io" rel="nofollow">
 <img src="https://camo.githubusercontent.com/1a2a06f019b1d167697a8ead981241f5fbba5cb5d5f4cc45a767deb35db19527/68747470733a2f2f72657669657761626c652e696f2f7265766965775f627574746f6e2e706e67" height="20" data-canonical-src="https://reviewable.io/review_button.png" style="max-width:100%;">
</a>
```

**Comment by pkaminski** [comment]
Nice detective work!  It looks like DOMPurify (the library we use for sanitizing HTML) strips `target` attributes by default.  We'll need to override this to keep them if there's a `rel="noopener"` on the element as well.

**Comment by pkaminski** [comment]
This should be fixed now.
