### ISSUE TITLE
Review is missing commits

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#80]
When I look at https://github.com/hammerlab/pileup.js/pull/79 on GitHub, I see three commits and nine files changed:

![screen shot 2015-04-17 at 12 59 02 pm](https://cloud.githubusercontent.com/assets/98301/7206667/a76456b2-e501-11e4-9408-5b98673cbb5e.png)

When I view the [same PR on Reviewable][1], I only see two commits and four files changed:

![screen shot 2015-04-17 at 1 00 20 pm](https://cloud.githubusercontent.com/assets/98301/7206676/bb0912b6-e501-11e4-9859-fa772f1d1dea.png)

The revisions grid does say "three commits", but it only shows the changes for the first two.

This persists when I reload the Reviewable page.

[1]: https://reviewable.io/reviews/hammerlab/pileup.js/79#-

**Comment by danvk** [comment]
Pushing a new commit made both the new commit and the missing one show up in r2. I'll leave this open in case you're interested in doing forensics.

**Comment by pkaminski** [comment]
This is strange and worrisome.  :frowning:  The only time I've seen this happen is when there's a persistent error in a GitHub API call that prevents Reviewable from retrieving needed data from GitHub, but that would've left a trace in the logs.  Even stranger is that the missing commit was the oldest one, rather than the newest.  My only guess is that the GitHub API somehow didn't return all the commits when requested.  I added a check on the server that the number of fetched commits equals the number claimed by the PR -- let's see if that gets triggered in the next few days.

**Comment by pkaminski** [comment]
The check I added never triggered so it was likely something else.  I recently made some cleanups in this area and it's possible that the bug was caused by a wayward `uniq` call that I just removed.  Lacking anything else to go on, I'm going to assume that fixed it unless the bug rears its ugly head again.

**Comment by pkaminski** [comment]
The number of commits mismatch guard got triggered last night, so apparently this is a thing that can actually happen (if very rarely).  The logs around the event are missing the context for some reason so it's not clear what PR this happened for, but the sync was retried and succeeded 30 seconds later.  I'll keep the guard in place.

**Comment by pkaminski** [comment]
Found another instance: https://reviewable.io/reviews/mozilla/shumway/2271

**Comment by pkaminski** [comment]
@tschneidereit: The commit structure of https://github.com/mozilla/shumway/pull/2271/commits is pretty weird: the first commit has the second as its parent even though it was nominally authored before.  This confuses Reviewable.  Can you provide any details on how the branch might've ended up with this weird structure, so I can figure out how best to handle it?  Thanks.

**Comment by tschneidereit** [comment]
Ah, interesting. It's quite simple really: I switched the order of the commits around using `git rebase -i`. If that's the reason, building additional test cases should be easy, at least.

**Comment by pkaminski** [comment]
OK, thanks.  Looks like I just need to do a topological sort instead of trusting the order that GitHub supplies the commits in.  Fix coming up.

**Comment by pkaminski** [comment]
Fixed.  The order of those two revisions on PR 2271 will be a bit weird (because the second one got snapshotted first), but all the files are there and things should work fine from now on.  Thanks for providing the repro!

**Comment by tschneidereit** [comment]
Thanks for the quick turnaround here!
