### ISSUE TITLE
Allow Reviewable to work without write access to code in the target repo

### ISSUE THREAD

**Issue by markdroth** [Reviewable/Reviewable#801]
Is it possible to allow Reviewable to work without having write access to code in the target repo?  My team is concerned about the security implications of that kind of broad access (e.g., someone compromising the Reviewable site could potentially inject malicious code into our code-base, and it's not clear how we'd detect that automatically).

It seems like Reviewable doesn't really need permission to modify the code in the first place, since it never does that; it just posts comments and approvals.  I'm not familiar with the github permissions structure, but I assume it's granular enough to allow posting comments and approvals without allowing code modifications.  (If that's not true, let me know, and I can try filing a feature request against github.)

Please let me know if this is feasible.  Thanks!

**Comment by pkaminski** [comment]
Hey Mark -- unfortunately, GitHub's permission structure is indeed not sufficiently granular to do this, at least for OAuth apps.  There's a longer explanation in [Reviewable's docs](https://docs.reviewable.io/registration.html#github-authorizations).  GitHub Apps do have finer-grained permissions but still lack some functionality that Reviewable relies on, as tracked in #482.  I'm still trying to think of a workaround for the missing API (user-involved PR query) so I don't know if/when we'll be able to migrate.

I'm marking this issue as duplicate of #482, since they require the same fix.
