### ISSUE TITLE
Sync "resolved" state of a thread from GitHub to Reviewable

### ISSUE THREAD

**Issue by ibrahima** [Reviewable/Reviewable#803]
This only arises when using GitHub PR reviews and Reviewable on the same PR, but sometimes this happens because we'll use GitHub for a smaller review and then transition to Reviewable as the review gets bigger, or also we have linter bots that leave GitHub comments, and then we want to hide them from GitHub by resolving them. Unfortunately, these threads that are "Resolved" on GitHub's end still show up as open on Reviewable. I realize that GitHub's resolution model is more simplistic and Reviewable's states are more featureful, but it would be nice to at least have the option to automatically resolve threads on Reviewable when the thread on GitHub is resolved. As it is, it makes it more annoying for us to use Reviewable because e.g. those linter comments which have been collapsed on GitHub are shown in full detail on Reviewable.

Kinda related to #94 but a bit of a different issue since once a thread is resolved it's at least more compact on Reviewable.

**Comment by pkaminski** [comment]
Yep, we should do this.  AFAICT, though, the resolved flag is only exposed through GraphQL so we'll first need to migrate all comment-related code in our backend away from the REST API, which will be a non-trivial task.

**Comment by snoack** [comment]
We decided not to move forward with this feature request at this point. We thought this through and ultimately given GitHub’s limitations we cannot reliably sync a discussion thread’s resolved status between GitHub and Reviewable.

On GitHub’s end, whether a thread is resolved is a simple checkbox that can be set and unset by the author of the PR as well as anybody with push permissions to the target repository.  In Reviewable, a discussion is resolved if at least one participant’s disposition is “satisfied” or “informing” and none of the participants’ disposition is “working” or “blocking”. Depending on the repository settings, users with push, maintain or admin permissions can also dismiss other participant’s dispositions in Reviewable.

Therefore resolving a thread on GitHub would translate to changing your disposition to “satisfied” and dismissing anyone else’s disposition in Reviewable, and unresolving a thread on GitHub would translate to changing your disposition to “blocking” in Reviewable.

But there are the following issues with implementing this synchronization logic:

1. Not everyone that has permission to resolve a thread on GitHub necessarily has permission to dismiss other participants in Reviewable.
2. GitHub does not keep track of who has unresolved a thread. So when syncing the thread  to Reviewable, we don’t know which participant’s disposition to change to “blocking”.

**Comment by pkaminski** [comment]
After thoroughly reviewing this issue and #437, we decided that it's not possible to offer a good mixed-platform experience where part of a review is done in Reviewable and part on GitHub, due to both irreconcilable differences in semantics and limitations in GitHub's APIs.  This situation doesn't seem likely to change in the foreseeable future, though we can certainly revisit if it should do so.

In the meantime, our philosophy is that if Reviewable is used at all on a PR then it needs to be used by all human users.  We'll only support bots interacting through GitHub on a best-effort basis (e.g., by syncing GitHub line comments into Reviewable, threading replies to such comments correctly, and propagating Reviewable discussion resolutions back to GitHub).  This is admittedly limiting and means that some teams who can't come to a consensus won't be able to use Reviewable, but we think it's the right trade-off to make — the alternative would be to either offer an experience with a number of pitfalls, or to have Reviewable become a mere alternative UI for GitHub, and we're not on board with either of these.
