### ISSUE TITLE
Review page consumes doesn't load when a lot of emoticons are involved

### ISSUE THREAD

**Issue by cytadela8** [Reviewable/Reviewable#807]
When one puts a lot of emoticons in a reviewable comment (what as I understand can be achieved by any person on GitHub by  posting comments directly on GitHub). Review page loads for a very long time consuming a lot of resources in the process. Firefox reports the page is "slowing down the browser" = consuming a lot of resources.
---
Our case: https://reviewable.io/reviews/warsztatywww/aplikacjawww/301#-
GitHub link to PR: https://github.com/warsztatywww/aplikacjawww/pull/301
:duck:  

GitHub review page loads without problems, but I wasn't able to get the Reviowable page to load. SS:
![obraz](https://user-images.githubusercontent.com/3736271/105555283-f7943300-5d00-11eb-84c3-f64e80d768db.png)

![obraz](https://user-images.githubusercontent.com/3736271/105555396-34602a00-5d01-11eb-802f-616f022710ab.png)

**Comment by cytadela8** [comment]
I think I should add that not putting a lot of :duck: in comments is not a solution as it would break our workflow :upside_down_face:  /s

**Comment by pkaminski** [comment]
@anthonykawa could you take a look, if you're comfortable debugging performance issues?  (Tip:  check `Truss.computedPropertyStats.log()` can reveal issues with computed property performance that can be hard to find using the profiler.)

**Comment by pkaminski** [comment]
@anthonykawa This Sentry exception capture is likely related, but may or may not account for the whole problem:  https://sentry.io/organizations/reviewableio/issues/2172522061/?project=124660

**Comment by cytadela8** [comment]
@pkaminski: Sorry, but this doesn't seem to have been fixed. Could you provide some comment?

**Comment by pkaminski** [comment]
Sorry, the issue got autoclosed because the fix was committed but it wasn't deployed yet.  I just deployed it now, please give it another try.

I think we'll need to stop linking PRs to issues since it's too confusing to have them closed automatically and I can't find any way to block the autoclose on deployment.  :(

**Comment by cytadela8** [comment]
Oh, that explains it.

> I think we'll need to stop linking PRs to issues since it's too confusing to have them closed automatically and I can't find any way 
to block the autoclose on deployment. :(

I think it would be good if the PR would be mentioned in the issue. I think Github normally does that, but you use something else for PRs as I understand.

I can confirm the issue is fixed, it works as expected now and it's magnificent! :rofl: 
![obraz](https://user-images.githubusercontent.com/3736271/106906409-0ca39580-66f5-11eb-9584-db0a0464ca6a.png)

**Comment by pkaminski** [comment]
The PR is indeed mentioned in the issue, but you can't see it since it's from a private repo.  It looks like others are [running into this problem](https://github.community/t/how-to-organize-auto-closed-issues-solved-on-master-branch-but-not-in-a-release-yet/2368/4) too.  We might need to build our own auto-closing system with Actions but I'm not sure it's worth it.
