### ISSUE TITLE
link back to original PR is hard to find and opens new tab

### ISSUE THREAD

**Issue by metajack** [Reviewable/Reviewable#81]
It takes me forever to find the link because it's almost hidden. Also when I do click it, it loads a new tab, which is not what I want.

**Comment by jdm** [comment]
This gets me every time. I always look for it in the overlay at the top, and it's never there.

**Comment by pkaminski** [comment]
My reasoning for loading it in a new tab was that the review page is pretty heavy and can take a few seconds (or more) to load, so I wanted to minimize the chance of getting it unloaded accidentally.  But perhaps having the link be "almost hidden" is protection enough.

The link is subtle because it's not supposed to be needed very often.  Why do you find yourself going back to the PR?  Perhaps there's a feature missing in Reviewable that I need to add instead.

**Comment by metajack** [comment]
We do not merge PRs directly, but a bot does it after they pass tests. So the big green button is never used and we must go back to the PR to write `@bors-servo: r+` which trigger the integration. So right now in our workflow, it is extremely difficult post-review to finish up.

**Comment by pkaminski** [comment]
Can you write `@bors-servo: r+` in the top-level discussion thread in Reviewable?  There's even convenient access to that draft via the bunny drop-down menu off the floating bar.

**Comment by jdm** [comment]
We also have various triage tasks that are performed in Github right now, such as modifying labels to indicate the PR's status.

**Comment by pkaminski** [comment]
Cool, adding full control of label assignment is on my short-ish-term internal todo list.  Want to open an issue for it so I can gauge demand?  If this feature was added, would you still need to visit the PR regularly?

**Comment by jdm** [comment]
Huh. I... suppose not?

**Comment by pkaminski** [comment]
Reviewable now has full support for labels, so I believe this addresses all the issues raised here.  Closing, but please reopen if you still find yourself needing to visit the PR page often.
