### ISSUE TITLE
Cannot post comments 

### ISSUE THREAD

**Issue by benbelow** [Reviewable/Reviewable#810]
Multiple of my team members have recently stopped being able to post comments. 

Posting comments manually from Github's UI still works fine.

**Comment by pkaminski** [comment]
Hey Ben -- that's really weird.  Are you seeing an error in Reviewable's UI?  If not, can you tell if something is spinning the CPU?  Also, how recently is "recently"?

Let's figure this out quickly.  Thanks.

**Comment by benbelow** [comment]
Hi - I could definitely leave comments last night, and I believe I also left some this morning. I noticed the failure around 11:50.

I was getting an message along the lines of "message queued but not sent". I've just tried again and it seems to be working again!

**Comment by benbelow** [comment]
Thanks for the speedy reply, looks like this was some transient issue, so I've closed it :)

**Comment by pkaminski** [comment]
Looks like there was a processing spike that started ~30 minutes ago, prompting the server pool to scale up.  We're still in an elevated state so further interruptions are possible.  I'm digging deeper to see if I can find the root cause.

**Comment by pkaminski** [comment]
Ah, looks like somebody just turned on a bunch of bots for their repos resulting in a huge burst of traffic.  Perhaps the bots were caught in a feedback loop, I'm not sure.  In any case things are settling down now.

I really need to figure out how to effectively prioritize specific queues or throttle on a per-user or per-repo basis in our stateless horizontally-scaled setup, since it doesn't seem to be able to scale fast enough sometimes...
