### ISSUE TITLE
Do not edit PR descriptions

### ISSUE THREAD

**Issue by GMNGeoffrey** [Reviewable/Reviewable#829]
Reviewable looks cool. I'd love to try it out. However, I've now twice gone through the flow of:
1. Get annoyed at GitHub's awful PR review UI
2. Try out this alternative "reviewable" thing
3. Give it reasonable and innocuous permissions
4. Poke around the UI a bit
5. Discover it has *edited the PR description of the PR I'm reviewing to advertise itself*
6. Look for a setting to disable that. Fail
7. Revoke all permissions

I'm now doing
8. File an issue
 
Please please do not edit PR descriptions to advertise your product. When I actually post a review, I think it would be ok to include a comment in a non-intrusive place that the review was performed on reviewable, but this happens at the point where I'm just *looking* at a PR and it *edits the description* that someone else wrote. This feels like a violation of the trust given when authorizing an app.

**Comment by jwnimmer-tri** [comment]
I'm just a user, not anyone officially associated with this product, but per https://docs.reviewable.io/repositories.html#repository-settings there is a configuration setting for how the badge should appear, at least when using Reviewable repository-wide.  I am not sure if it helps in your case (and perhaps the default setting should be different), but I thought I'd toss it out there in case so.

**Comment by GMNGeoffrey** [comment]
Hmmm I didn't look there because I hadn't connected the repo explicitly. I'd just poked at doing a single review. Also that setting doesn't allow "none" unless it's a private repo.

**Comment by pkaminski** [comment]
Hey Geoffrey, sorry for the poor experience you've had.  We put the badge there both for marketing (in lieu of payment for public repos) and to help other participants find the review, though for single-PR tryouts the latter is obviously much more important than the former.  You're right that it doesn't need to show up as soon as you visit the review, though.

TBH, we haven't been putting a lot of work into the ad-hoc (non-connected repo) review use case because we expect that feature to go away in the future, in part because the experience is [suboptimal](https://docs.reviewable.io/repositories.html#reviews-in-connected-vs-unconnected-repos) and in part because it won't make sense to support it once we switch to GitHub's Apps integration (which is repo-centric).  Also, changing the current behavior is surprisingly tricky due to some past design decisions and Reviewable's overall architecture -- I'll spare you the details.

That said, I think I see a way in which I could delay putting in the badge in a disconnected repo until somebody publishes a review.  I'd be willing to put in the 2-3 hours of work this would require if it would address your concerns.  I'm not willing to remove the badge altogether in public repos, though, for the reasons above.  What do you say?

**Comment by GMNGeoffrey** [comment]
Thanks Piotr. That makes sense and I understand the balance you're trying to strike. At the point that I'm actually publishing a review, a badge feels appropriate and not like invasive advertising. And FTR the fact that it's a badge, as opposed to text or what have you is not my concern at all: make it as aesthetically appealing as you'd like :grin:

I think the changes I'd like to see is that reviewable not take an action until I actually publish a review (this is the point as a user where I'd expect it to take some action on the PR) and by default post the link to the reviewable review as a comment rather than editing the PR description. I understand why folks might prefer the PR description editing, but for the one-off case it feels very invasive. It's not something I would expect a tool "publishing a review" to do by default.

A bit sad that ad-hoc reviews will go away, since this raises the barrier to entry, but also I understand that GitHub apps need to be installed on the repo and having multiple ways to do auth is super painful.

I also understand you trying to budget your time appropriately for something that's likely to get turned down soon. I can say that if this is how reviewable operated when I tried it out then I would have been more likely to learn more, try it out a bit more, and see if this was something I wanted to suggest to the team. I can't promise that we'll use reviewable if it just makes this one change or something, but I suspect that you might be losing potential users who like me are very turned off by the current behavior. I'll leave it to you whether this is something worth prioritizing.

**Comment by pkaminski** [comment]
OK, I'll see what I can do.  While we've had a few complaints from people connecting repos in the past (and went as far as to build a [special tool](https://reviewable.io/goodbye) to rip all the badges out of a repo for truly irate folks), I believe this is the first time somebody raised the concern for one-off reviews.  Doesn't mean other people didn't have the same thought, of course...

Ironically, PR editing is the default in part because I feel it's _less_ invasive: it doesn't trigger a notification to anyone else watching the PR, and it's less likely to be mistaken for a personal endorsement from the person whose account we happen to use to send it (bot accounts are only a thing for Apps).  It's also a more consistent placement that precedes any Reviewable-originated comments, which are best read in Reviewable.

**Comment by GMNGeoffrey** [comment]
> Ironically, PR editing is the default in part because I feel it's _less_ invasive: it doesn't trigger a notification to anyone else watching the PR, and it's less likely to be mistaken for a personal endorsement from the person whose account we happen to use to send it (bot accounts are only a thing for Apps). It's also a more consistent placement that precedes any Reviewable-originated comments, which are best read in Reviewable.

Ah that's an interesting counterpoint. I find editing the PR invasive because it's not something that is part of standard review flows. I might edit someone's description to fix a typo or something, but mostly it's something that they wrote and I don't touch it. We also use PR descriptions as the basis for the commit message when squash-merging (I think for a single commit this is even GitHub's default behavior) and I definitely don't want badges in my repo's commit history. The place where I'd expect the badge to show up in the unconnected case is in the comment when someone posts a review:

![reveiwable_comment](https://user-images.githubusercontent.com/5732088/116431963-1b35b080-a7fd-11eb-9c57-38747f1da6cf.png)

That seems like a very natural place for it.

I agree that for a repo-wide integration, it's not the best place, but in that case someone is configuring reviewable for their repo, so they can decide what's best for them and they're opting in.

**Comment by pkaminski** [comment]
Fair point that editing the PR description is a bit unusual, but that's also why we put in a big horizontal divider to make clear that the badge is a kind of separate footer.  AFAICT the PR's description is [never used](https://github.community/t/how-to-change-the-default-squash-merge-commit-message/1155) in the squashed commit message though clearly many people would like it to be!  If that ever changes we'd definitely reassess.

As for putting the badge in the published comment itself, we run up against architectural limitations yet again:  that comment is posted from the client, whereas the badging function lives on the server.  We could trigger a separate badge comment upon publishing but it would show up after the published one, which is not ideal.  We could also, of course, move or unify the badging code, but that's more work than I'm willing to put into this use case.  :)  I'm also not convinced that having different default behaviors for connected vs disconnected repos is a good idea.

In any case, I've implemented and pushed the change discussed above (hold off inserting the badge until something has been posted from within Reviewable) so I'm going to call this one closed for the time being.  😀
