### ISSUE TITLE
Show commit description as tooltip for revision

### ISSUE THREAD

**Issue by RaduBerinde** [Reviewable/Reviewable#833]
When reviewing large PRs, they are typically broken up into multiple commits and I use "Review each commit separately". I then use the file matrix to look at the diffs for each commit separately. But the first thing I want to look at before reviewing the files is the description of that commit.

Currently I have to go scrolling through potentially many pages of comments (including descriptions of earlier versions) and look for the description for the right revision (e.g. `r4`). This is obnoxious; it would be nice if there was an easy way to see the description. A natural place would be as a tooltip when you hover `r4` in the file matrix.

**Comment by pkaminski** [comment]
I agree that the workflow for "review each commit separately" is suboptimal right now.  We've been working on improving it but there's still work left to do.  For commit messages, what do you think about presenting them as diffs for approval instead of as comments, as proposed in #507?  I like that approach for its two-birds-one-stone quality.

**Comment by RaduBerinde** [comment]
Yeah that would work well!

**Comment by pkaminski** [comment]
Sounds good, I'll close this as duplicate then.  We should be getting on to #507 in the near future, with any luck.  :)
