### ISSUE TITLE
Deleted file incorrectly identified as reverted at a later revision

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#841]
In https://reviewable.io/reviews/ridge/tectonic/10894, r1 deletes the file `ops-product/tf/devel/hot_start.tf`, and r2 is a merge from `master` that has nothing to do with that file.

The file matrix shows the file in question as deleted at r1 and then as reverted at r2.

**Comment by pkaminski** [comment]
@feldgendler We didn't have time to dig into your case yet, but based on a casual look it seems that the file was removed at r1 but still present in the base branch, then it was also removed from the base branch at r2 (presumably due to the merge).  We have some new code to flag that as a revert even though it wasn't caused by a direct change to the file, since at r1 merging the PR would've deleted the file from the tree, whereas at r2 it became a no-op.

Does that fit with what you know?  If so, do you disagree that the file should be flagged as reverted in these circumstances?

**Comment by feldgendler** [comment]
That file was actually renamed in the base branch.

I don't think it's right to call this “reverted”. “To revert” sounds like something the author did to return the file to the way it was in the base branch. But if instead the base branch catches up with the PR, that's something entirely different.

**Comment by pkaminski** [comment]
I agree that the file _was not_ reverted, but I think it's fair to say that it _is_ reverted (action vs state).  And really, does it matter whether you revert a file by changing the head branch or the base branch?  It's an author-driven change to the PR either way.

More importantly, though, if we were to introduce a new name for this situation, does the benefit of extra precision outweigh the cognitive overhead of yet another concept and icon?  (You can in fact already distinguish between "active" and "passive" reverts:  only the latter will have a white "no changes" cell background.)

**Comment by feldgendler** [comment]
Actually, it did matter in this case; it wasn't just “the file got deleted anyway”.

The PR was deleting the file. Meanwhile, a mass rename happened in another PR (the naming convention was changed), so that file got renamed. This didn't cause a conflict, and the file ended up escaping deletion under its new name.

I'm not really sure Reviewable could help prevent this. After all, git itself doesn't treat it as a conflict.

**Comment by pkaminski** [comment]
Yeah, there's no way to detect that this is in fact a conflict.  Given that it's already possible to distinguish the two cases (revert with color background vs revert with white background) I don't think there's much more we can do.  At least we did bring the file to the reviewer's attention rather than skipping over it altogether, as we were doing previously!
