### ISSUE TITLE
PR with file moved then re-added with different content won't allow review of old file path

### ISSUE THREAD

**Issue by elistevens** [Reviewable/Reviewable#843]
I had a file `build/requirements.txt` that was moved to a new location in PR commit 1. Later on in around commit 6 or so, `build/requirements.txt` was re-added to the PR with content that basically said "This file has moved to $newlocation."

Now, the reviewable UI only shows: 
![image](https://user-images.githubusercontent.com/138016/122996563-da22ce00-d35f-11eb-884a-6019bdfa435f.png)

And we can't seem to find any way to mark the files as reviewed.

The $newlocation files behave just as expected.

**Comment by pkaminski** [comment]
This looks correct to me -- you just need to select some diff bounds for the `requirements.txt` file to be able to mark it as reviewed (likely `r6` vs base).  I'm not sure why those bounds didn't get selected for you automatically though that depends on your review style (aggregated commits vs commit-by-commit) and the current state of the review.  If you include a screenshot of the full file matrix right after a page reload I may be able to make a guess and figure out if there's a bug there or not.

**Comment by marczych** [comment]
None of us could get any diff to display after dragging the diff bounds for the individual files in question or at the top of the file matrix. Also, clicking on the file in the matrix takes you to the file down below but it's stuck with a loading spinner without any observable network request in the network tab of the dev tools.

In case it helps, here's the completion condition input:

```json
{
  "path": "build/requirements.txt",
  "revisions": [
    {
      "key": "r6",
      "action": "added",
      "obsolete": false,
      "reverted": false,
      "reviewers": []
    }
  ]
},
{
  "path": "build/requirements3.txt",
  "revisions": [
    {
      "key": "r6",
      "action": "added",
      "obsolete": false,
      "reverted": false,
      "reviewers": []
    }
  ]
},
```

`"action": "added"` seems wrong because it should only be modified at this point. However, there are a _lot_ of renames for the PR in question based on a command line diff so it isn't too surprising that something funky is going on.

We're using "Combine commits for review". Should we try changing it to "Review each commit separately"?

**Comment by pkaminski** [comment]
The review state looks correct.  Because the file was renamed earlier, then recreated, the file is considered new and hence `added`.  (Its earlier revisions got shanghaied into the renamed file so there's nothing for it to be `modified` from!)

Can you describe more precisely what happens when you try to drag out diff bounds?  Is there any feedback as you're dragging?  Do the bounds disappear as soon as you release the drag?

Having the file stuck with a spinner is definitely wrong but might just be a side-effect of the failure to set diff bounds.

**Comment by elistevens** [comment]
Aside from clicking on the file name scrolling down to the spinner that Marc mentioned, none of the UI elements in the screenshot react to left clicks or left drags as far as I can tell.

**Comment by pkaminski** [comment]
Dragging from the green cell to the empty (base) cell on the left -- or vice-versa -- does nothing at all?

**Comment by elistevens** [comment]
Correct.

**Comment by pkaminski** [comment]
Does the mouse cursor turn from an arrow into a pointing hand when hovering over the green cell?  When hovering over the base cell?  (Sorry for the game of 20 questions but I have a very similar scenario as one of my standard test cases here and can't repro anything like what you're seeing.)

**Comment by elistevens** [comment]
It turns into a pointing hand over all three roughly square cells in the table above: the one that corresponds to the upside-down T at the top of the table (the list of changed files is too large for me to screenshot it all), the green cell at r6, and the white cell at 7.  The merged white cells between T and r6 do _not_ turn into a pointing hand.

**Comment by pkaminski** [comment]
This is exactly as expected too.  Frankly, I'm rather stumped by the observed behavior:  the cursor shows that the cells are correctly bound to the underlying model, and both the display and the drag handler use the same data structures.  The only way I can see for a drag-select to silently fail is if it can't map the pointer location to the correct underlying cell, but since it presumably works for other files I don't see why it would be failing here.

Just to make extra-sure, could you inspect the `⊥` and `r7` cells for the file and check that the element with class `revcell bound` also has a non-empty `data-index` attribute?

Beyond that, we'd either need to get into interactive debugging by proxy or, ideally, a remote screen control session.  I don't know if you (or @marczych) have time for that, though...

Otherwise, let's see if sleep brings any more hypotheses to invalidate.

**Comment by elistevens** [comment]
The working file above the problematic file has `revcell bound` but the problematic row has only `revcell` (with a `data-index` attribute): 
![image](https://user-images.githubusercontent.com/138016/123053610-edae5300-d3b8-11eb-853a-bf2101462b90.png)

I have some time tomorrow around 9:30 am PDT, or 3:30 pm. I can do a screenshare; can you send me an email at estevens@? The domain is the same as Marc's, which I presume you have.  If not, send it to the email listed on my profile and I'll reach out from my work account.

**Comment by pkaminski** [comment]
Yep, everything still looks normal.  I'll reach out to estevens@, let's pencil in 3:30pm.  Thanks!

**Comment by pkaminski** [comment]
Once we identified the bug (thanks so much @elistevens!) the fix was trivial.  It's live in production now and will make the next Enterprise release.
