### ISSUE TITLE
lodash v4

### ISSUE THREAD

**Issue by pcorpet** [Reviewable/Reviewable#844]
Hi @pkaminski , in [our code](https://github.com/bayesimpact/bayes-developer-setup/tree/main/reviewable) to test our Reviewable configuration we have a dependency on `lodash` v3 which raises security alerts by GitHub. Would it be possible/easy to move to `lodash` v4+ to evaluate conditions?

I saw that you've closed the corresponding [dependabot PR](https://github.com/Reviewable/Reviewable/pull/697) but that was more than 1 year ago (pre-Covid!), so maybe things have changed?

**Comment by pkaminski** [comment]
It would be possible, as we vendored out that dependency a while ago, but it would probably require an additional per-repo flag as to which version to use since v4 isn't backwards compatible.  I guess an alternative would be to have some indicator we could parse out from the code snippet itself but I don't know how I feel about imposing extra hurdles on modern code when v4 should really be the default.  Any ideas on how to build this cheaply?

As for the dependabot PR, I had nothing specifically against it, I just found that dependabot didn't work well for us so I killed it and batch-closed all its PRs.

**Comment by pcorpet** [comment]
Thanks for the quick answer.

I think that modern code should indeed use v4 for now, however I think it's not possible to both have modern code relying on the default being the best one **and** having it stable as well. When lodash v5 will be out, then the code using v4 might be happy that they had tagged their code as such.

Some ideas:
- you could update all existing configurations and prepend a comment ` // lodash v3.x` at the top if the config is using lodash (con: modifying user data might be problematic for those who keep it somewhere else like us in git)
- you could version the dependencies, and force all new configs to start with a `// reviewable-deps v1.0.0` in the future ; those who don't care about breaking changes could add `// reviewable-deps latest`
- you could add an extra field and handle it as a separate value (but might be more work to update the UI).

**Comment by pkaminski** [comment]
Hmm, what do you think about this approach instead:
- Every condition is bound to the most recent version of the dependencies at the moment it's first created.  This gets stored with the condition but isn't directly visible to the user.  Current conditions get backfilled with `lodash3`.
- A condition can override this default with a `// dependencies: lodash4` unindented comment anywhere in the file (and list more comma-separated ones, if we ever allow it).

This way, new conditions always get the most current dependencies without needing to opt in in any way, and will retain them forever for backwards compatibility by default.  More advanced users can take explicit control of their dependency versions if they want to.  And (most importantly?) I don't need to build any UI.  😄

Can you poke any holes in this?

**Comment by pcorpet** [comment]
Yep that sounds easy enough.

If it's completely hidden, it might be hard to understand for users but most of the time they don't need to care. As long as the doc is explicit, I think that's fine. And you'll be able to add more UI later if needed.

**Comment by pkaminski** [comment]
<details>
<summary>Internal implementation notes:</summary>
- Add a `reviewCompletionDependencies` schema property for `rules`.
- Add this property (with a hardcoded `lodash3` value) to the client when saving a completion condition.
- Deploy client.
- Add a migration task to `cron.ts` to set `reviewCompletionDependencies` to `lodash3` for all rules.
- Update `executor.ts` to parse dependencies out of code and fall back on database value in `run` and pass into each executor flavor.
- Update every executor flavor to take the dependencies into consideration.  We might want to remove the deprecated `sandcastle` first to save on work.  AWS Lambda will need to work the dependencies into the container name somehow.
- Update `sweepLambda` in `cron.ts` to correctly sweep away unused functions.  It's not clear how to make this work since currently it just deletes functions whose name indicates an executor version older than the current one, whereas now we'll need to delete functions at the current version but a dependency configuration that the condition is no longer using.  Or perhaps we just let those live since custom dependencies shouldn't be used too often and there's not a lot of variants possible (so zombie functions shouldn't bloat the pool too much), and just have them all swept the next time we bump the executor version.
</details>

**Comment by cgiroux86** [comment]
Hey folks, Lodash v4 support is now implemented.  Please try it out and let us know if you have any issues!

**Comment by zozoens31** [comment]
Hi, there seem to be an issue with this new feature.
After having changed our configuration for our repo, using a comment
```javascript
// dependencies: lodash4
```
I got the following error, when trying to publish comments from https://reviewable.io/reviews/bayesimpact/bob-emploi-internal/16835#- (private repository): 
```
Failed to publish: Failed to execute custom review completion condition: evalmachine.<anonymous>:22 const emojis = _.keyBy(sentiment.emojis) ^ TypeError: _.keyBy is not a function at evalmachine.<anonymous>:22:20 at arrayEach (/var/task/node_modules/lodash/index.js:1034:21) at Function.<anonymous> (/var/task/node_modules/lodash/index.js:2836:23) at evalmachine.<anonymous>:21:3 at evalmachine.<anonymous>:81:3 at Script.runInContext (vm.js:144:12) at Script.runInNewContext (vm.js:149:17) at Object.runInNewContext (vm.js:303:38) at Runtime.exports.handler (/var/task/index.js:45:27)
```

You can see the full config that was used at https://github.com/bayesimpact/bayes-developer-setup/pull/315. When I rolled back to the previous config, it worked just fine.

Could you please investigate this issue, or point me towards a documentation on how to use lodash4, if I got it wrong?

**Comment by pcorpet** [comment]
It actually seems to work now, I wonder what happened.

**Comment by pcorpet** [comment]
OK, I believe that the issue is that the "dependencies" are only taken into account for the "Checks" and for the submission; but that you use another engine (or another server) to publish comments. It worked only because @zozoens31 reverted the change, got his comment in, and then I reapplied the change, and the change works for submission. We got stuck at the next "publish comment" action :-(

**Comment by cgiroux86** [comment]
@pcorpet Thanks for bringing this to our attention.  Fix is live now.
