### ISSUE TITLE
"Done" button shown even after the author already used it

### ISSUE THREAD

**Issue by mkow** [Reviewable/Reviewable#863]
Under some review discussion under a PR I was the author, I clicked "Done" and submitted it. Then, after some more changes, I wanted to reply to a few more discussion, but I noticed that the discussion which I marked as "Done" still has this button shown, despite it wasn't waiting for me, but for the reviewer to approve the fixes.

![reviewable_done](https://user-images.githubusercontent.com/5244565/131470461-2a9341cd-0141-4d88-b2fc-db30293016d2.png)

This kind of suggests that this is a reasonable action to do, and it also explain why some beginners in our project end up with a stream of duplicated "Done" comments under discussions :)

**Comment by pkaminski** [comment]
Good catch!  All the other button states are naturally non-repeating, since they're gated on disposition and clicking the button will change it.  But the Done button intentionally remains usable even if the author is already satisfied, in case of a follow-up by a reviewer that needs another Done response.  I fixed it by adding another mechanism to turn off the button if the author is caught up on the discussion.

**Comment by mkow** [comment]
Makes sense. Thanks for the fix!
