### ISSUE TITLE
Reviewable does not load

### ISSUE THREAD

**Issue by mwoehlke-kitware** [Reviewable/Reviewable#868]
I'm getting the following error trying to use Reviewable:
![image](https://user-images.githubusercontent.com/6474409/132867389-7643c39c-8caa-4dda-8634-81cca75501d0.png)

I'm using Firefox 89.0 with uMatrix, but I've allowed everything that's showing up and the logger is not reporting anything being blocked.

Any ideas? It looks like there may be a CSP issue? (I've known Firefox to be more strict about that than other browsers.)

**Comment by pkaminski** [comment]
That looks odd, particularly since we don't set CSP headers at this time.  Could you please try with all extensions completely disabled?  I suspect one of them is interfering, whether uMatrix or something else.  Thanks.

**Comment by mwoehlke-kitware** [comment]
[This article](https://gitter.im/Reviewable/Reviewable?at=5d1642b29cbde24b2f33a525) pointed me at`?debug=worker`. I can get it to work with that; without that, it breaks.

**Comment by pkaminski** [comment]
Sounds like something is interfering with requests from shared workers, perhaps because they're not attached to a specific page and hence don't get whitelisted properly.  At this point I'm pretty sure this is caused by an extension so I'm going to close as `invalid` on our side, but happy to keep helping you debug this.
