### ISSUE TITLE
Links stopped to have an underline

### ISSUE THREAD

**Issue by mkow** [Reviewable/Reviewable#883]
Recently all the links in review comments stopped to be underlined for me and are now formatted as usual text, which is pretty confusing. I guess this is just an accidental regression?

I'm on Firefox 78.15.0esr (64-bit) on Debian 10.

**Comment by pkaminski** [comment]
I recently changed our CSS to avoid underlining images in comments.  However, this uses link sniffing to figure out if something is an image (because CSS) and you're likely getting caught by a false positive.  Can you share the host part of a few of the links that are breaking for you?  Thanks.

**Comment by mkow** [comment]
For me it's _all_ the links which miss underlines, including e.g. #<num> links to GitHub PRs/issues. So, the sample hostname could be github.com :)

**Comment by pkaminski** [comment]
OK, I reproduced the issue on FF78.  Since it doesn't reproduce on any modern browser versions it would appear to be an old Firefox bug in handling CSS attribute selectors.  I'm afraid that at this point I'll just have to ask you to upgrade: the 2021 ESR has been out for a while and we can't keep supporting old versions forever.  Sorry!

**Comment by mkow** [comment]
No problem, time to upgrade to Debian 11 it seems :)
