### ISSUE TITLE
Possible code injection

### ISSUE THREAD

**Issue by wojciech-malota-wojcik** [Reviewable/Reviewable#884]
I created PR titled `Use libvirtd address of form <protocol>://<address>`
In Reviewable, `<protocol>` and `<address>` does not appear in the title.
Instead, html inspector shows this:

```
<span data-v-5f6bad32="" class="html pr-title" tabindex="0">Use libvirtd address of form ://<address></address></span>
```

So `<address>` tag was directly added to html

**Comment by pkaminski** [comment]
That's embarrassing.  😓  Thanks -- fixed!  FWIW this wasn't a security issue because the value was passed through `DOMPurify` first but it's still a bad look.

For the record, it's better to report potential security issues via support@reviewable.io, so that they're less likely to be exploited until we can fix them.  But a report over any channel is better than no report -- thanks again!
