### ISSUE TITLE
Deferral hides a thread where you are Working

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#886]
# Steps to reproduce

As a reviewer, leave a comment with a Working disposition (something like “I'll go check if this is correct and get back to you”) without marking the code as reviewed.

# Expected

The review stays in your “Awaiting my action” because you are Working on it.

# Observed

The review disappears from your “Awaiting my action”.

# Remarks

Deferral hides the review, but IMO Working should trump deferral.

**Comment by feldgendler** [comment]
Looks like you guys fixed this but forgot to close?

**Comment by pkaminski** [comment]
Actually we haven't touched this yet -- did the observed behavior change?

I was considering removing the Working disposition altogether, since deferral handles many of the same use cases and doesn't rely on the worker i) understanding the Working disposition (rare!) and ii) remembering to apply it.

**Comment by feldgendler** [comment]
I think I did something differently, because it worked as expected.

Please keep the Working disposition! We love it and use it all the time. Deferral doesn't cut it because Working puts the PR into the “Awaiting my action” list of the one who's Working, so it can't fall through the cracks.

**Comment by cgiroux86** [comment]
Hey @feldgendler,

We have a proposed solution and would appreciate your input.  Our idea is to add a new section to the dashboard called something along the lines of "Working", "In the works", etc.  If you publish a review with a working disposition but are deferring, your review will fall into this category.  The deferred counters will remain the same when the review is in this category, but we'll indicate how many discussions you have a working disposition on via a tooltip.  Does this sound like a reasonable and workable solution to you?

**Comment by feldgendler** [comment]
That sounds reasonable so far! I'd say it's even better than today.

> If you publish a review with a working disposition but are deferring, your review will fall into this category.

But what if I'm working but not deferring?

**Comment by pkaminski** [comment]
> But what if I'm working but not deferring?

That's a fascinating question.  Our thinking was that if you're working but not deferring then the review goes into the "Awaiting my action" section as usual, since you're blocking the review.  But perhaps a better condition for the "In the works" section would be:  reviews that are blocking on you *only* because of your Working disposition(s).  This could happen because you deferred (which overrides all other dispositions) or, if you haven't deferred, because the only discussions you're blocking are ones where you're Working.

The root question to answer is:  is it useful to split out reviews blocked only because you're Working from the other ones you're blocking, and to implicitly lower their perceived priority?  My intuition is leaning towards yes.

**Comment by feldgendler** [comment]
What about letting the custom function make that decision?

> But perhaps a better condition for the "In the works" section would be: reviews that are blocking on you only because of your Working disposition(s).

This could be the default if the function doesn't set the new property in the output.

**Comment by pkaminski** [comment]
What kind of scenarios would you expect the completion condition to disambiguate?

**Comment by feldgendler** [comment]
Oh, we use our custom function to bring (or to no bring) reviews to our attention based on our own undertanding of what needs attention. For example, we make the review ask for its author's attention when its CI run failed. Even though there's nothing wrong with the review itself, we simply use the tool so that Reviewable's home view is the only dashboard about PRs that one needs.

**Comment by pkaminski** [comment]
Hmm, in that case it may be better to just always leave blocking reviews in the "awaiting my action" section, as per the original proposal.  Your condition could then control whether an only-working review shows up in the top or second sections just be setting `pendingReviewers` appropriately.

I'm hesitant to give the condition full control over which section to put a review in simply because it would make future design changes on the dashboard harder.  Not saying we'll never do that but I'd like a stronger reason than a corner case of an edge condition.  😄

**Comment by feldgendler** [comment]
I didn't mean to introduce a dumb control such as “in what section the PR should be”. That would be too low-level indeed. But you said:

> But perhaps a better condition for the "In the works" section would be: reviews that are blocking on you only because of your Working disposition(s).

If my completion function made the review ask for my attention, Reviewable can't tell if that's _only_ because of my _Working_ disposition, or there is another reason as well. So my function could help Reviewable understand that.

**Comment by pkaminski** [comment]
> If my completion function made the review ask for my attention, Reviewable can't tell if that's only because of my Working disposition, or there is another reason as well. So my function could help Reviewable understand that.

That actually aligns somewhat with a request from another customer or two, to let their condition determine a "reason" why a reviewer is pending and to pass that through the webhook notification so they can be more precise when nagging people.  My thinking was to just make that a free-form string, but perhaps adding some structure to it could be leveraged on the dashboard as well.  I'm not sure we have enough examples right now to make a good generalization, though, and without some abstraction this will devolve into a "what section the PR should be" property.

**Comment by feldgendler** [comment]
We're already using the `description` and `shortDescription` as the “reason” strings. Or did you mean different strings for different people at the same time?

**Comment by pkaminski** [comment]
> Or did you mean different strings for different people at the same time?
Yes, precisely.

**Comment by pkaminski** [comment]
We've decided to go with the original proposal:  deferred reviews where you're working will be "lifted" into the new section, but reviews where you're a pending reviewer will remain in the top section even if the only reason you're pending is because of working dispositions.  It turns out that computing "the only reason" is pretty hard on the client and doesn't play well with custom completion conditions anyway.

Ultimately we may well have the condition output more metadata to help deal with this, but I think it's premature to set a design in stone right now.  Instead, if you detect a "just working" situation in your condition you will be able to purposely set the user as not a pending reviewer, as this will force the review into the working section.  We'll see how that goes and consider refining the design as we gather more experience.

**Comment by feldgendler** [comment]
Closing because we're happy with the current behavior. Thank you!
