### ISSUE TITLE
Assigning reviewers when posting a PR

### ISSUE THREAD

**Issue by jwnimmer-tri** [Reviewable/Reviewable#897]
In https://github.com/RobotLocomotion/drake/pull/16532, we hit a common misconception of Reviewable from newer users.  I've often seen the same in use of the enterprise version over the years, especially for new hires.

The author wants to assign a reviewer immediately as they file a PR.  (They should probably have waited for CI to pass before assigning review, but in any case, they think they want this.)  They put the `+@username for review, please` text into the PR overview when they post, with the expectation that the assignments will change, as it would if this were a comment, instead of the overview.

It would be helpful if Reviewable could notice this and update the assignments even if the magic word is part of the overview, e.g., when it's adding the "[Reviewable]" badge and/or otherwise somehow setting up the PR.  If the user subsequently edits the overview we can ignore any changes to the magic.  It's really just the "first initial submission" where people try to add reviewers, but fail.

**Comment by pkaminski** [comment]
Excellent idea.  One slight complication is how to deal with edits, but that's a problem with comments too -- we just ignore them.  @cgiroux86, I think this would make a good next task!  (Tip: look for functions related to `directives` in `comments.ts`.)

**Comment by cgiroux86** [comment]
@jwnimmer-tri The fix for this should be live shortly.  One thing to note, we will still follow the same directives we use on Reviewable when assigning reviewers and labels.  Just `@`'ing someone will not count them as a reviewer -- instead you'll need to make sure people are using the following format(s):

To request a reviewer - `+reviewer:@username`
To assign someone - `+@username`
To add labels - `+labelname`
