### ISSUE TITLE
Support git spr (stacked pull requests)

### ISSUE THREAD

**Issue by schreter** [Reviewable/Reviewable#901]
There is a nice tool `spr` (https://github.com/ejoffe/spr) which allows Gerrit-like stacked push requests. We use it now internally in our group quite frequently, since in conjunction with Reviewable, it's very easy to review and re-review rebased changes "in the middle".

Although it works quite well out-of-the-box, it would be nice to at least add two helpers in Reviewable:
- navigation across the PRs in the stack, so it's easy to switch to the related request
- support for "properly" merging PRs

The latter point needs some explanation. The PRs are stacked in such a way that PR1 merges to master, PR2 merges to PR1 (so it's only the feature based on another feature in PR1) and so on. When PR2 is reviewed, it can be merged. However, it merges then to PR1, which breaks the chain. So instead of this, Reviewable should prohibit merging PR2, since it doesn't merge to master. Ideally, if both PR1 and PR2 are done reviewing, then Reviewable should merge both, keeping the history in git (two commits, one from PR1 second one from PR2) as also done by `git spr merge`.

There is also one small nuisance with `spr`: the PR1 would be marked as "closed" and only in the comment mentioned that it was merged with PR2. It would be ideal if the PR1 would be also marked as "merged" somehow, at least within Reviewable, if it detects that it was a commit which was closed by `spr`, but in fact merged by a dependent PR2.

@pkaminski Thanks for pointing us to the tool. Now you have some more work :-).

**Comment by pkaminski** [comment]
Hey, good to hear `spr` works for you!  I think we could add some limited support for the tool in Reviewable:
- Prohibit merging of `spr` PRs.  I don't want to try to duplicate `spr`'s merge logic in Reviewable, and since you already need to use it to manipulate the PRs in all other ways I don't think it's too onerous to ask users to merge from the command line as well.
- Detect closed-but-actually-merged PRs.  It looks like `spr` posts a comment that looks like `✓ Commit merged in pull request #NN` that we could scan for to override GitHub's PR state.
- Support navigation across PRs by rewriting link URLs in the description and comments to point to reviews instead if the repo is connected (or perhaps iff the target review exists?).  We could do this in all reviews, or only in `spr` reviews -- it's not clear which one would better align with users' expectations.  Later, once we have a sidebar, we could detect `spr` and give the PR stack its own dedicated section so you wouldn't need to navigate back to the PR description for the links.

How's that sound?

**Comment by schreter** [comment]
> How's that sound?

Sounds good :-), thanks.

**Comment by cgiroux86** [comment]
This is now live -- let us know what you think!

**Comment by schreter** [comment]
> This is now live -- let us know what you think!

Well, it doesn't work in Enterprise (and no wonder - it's in the list of "upcoming changes"). So I can't give you the feedback yet :-).

Can you please let me know when it lands there? Thanks.

**Comment by cgiroux86** [comment]
@schreter Ah yeah, Enterprise changes usually land a couple weeks after sass changes do. Sorry, didn't realize you were on Enterprise. Will update this on the next Enterprise release (usually towards the end of the month).
