### ISSUE TITLE
version-controlled "Review completion condition" code?

### ISSUE THREAD

**Issue by thirdpwais3** [Reviewable/Reviewable#927]
(hello from thirdwave-ai, a customer of yours)

We have a very customized "Review completion condition" that governs our review process.  I just made some changes to it today and recognized that our stuff was just in Reviewable but was not actually version controlled in our own code.  Is there a chance Reviewable might be open to supporting a special dot-file or some other way to support version control of the code for this feature?  Pardon if there is and I am simply ignorant.

CC @macmason

**Comment by pkaminski** [comment]
👋 Hi there!  You're right on all counts:  yes, loading the condition from a repo would be very useful, and no, this feature doesn't yet exist.  I do want to implement it but there are some challenges because Reviewable is an OAuth app (i.e., must always impersonate a user) and appropriate credentials are not reliably available at the point where we'd need to fetch the condition.  I have ideas for a workaround but...

I'll close this issue in favor of the canonical one, #722.  I'll post any updates there.  Thanks!
