### ISSUE TITLE
Support semantic diffs with difftastic diffs

### ISSUE THREAD

**Issue by skykanin** [Reviewable/Reviewable#976]
It would be nice if reviewable supported [difftastic](https://github.com/Wilfred/difftastic) for semantic diffing as it would make diffs less noisy and let reviewers focus on the important bits. Difftastic uses [treesitter](https://tree-sitter.github.io/tree-sitter) to do the parsing so it supports a wide variety of languages and will otherwise fall back to a textual diff with word highlighting if the language isn't supported. I also think it would make sense to add a setting to the reviewable UI for toggling between semantic diffing and textual diffing.

**Comment by pkaminski** [comment]
Thanks for letting me know about difftastic!  It does look pretty cool, but at the moment it wouldn't fit into Reviewable's architecture: all our diffing is done client-side (by design) and difftastic [doesn't have a WASM build](https://github.com/Wilfred/difftastic/issues/407).  I'm tracking that issue, though, and if and when that changes I'd be happy to take another look at it.

Somewhat ironically, the first example on difftastic's home page:
![js](https://user-images.githubusercontent.com/1646896/198788492-038a2ae6-845b-443d-8ca9-7de582b2307f.png)

Is already perfectly diffed by Reviewable, with no knowledge of semantics whatsoever, which does cast some doubt on the claimed advantages of a semantic differ:
![image](https://user-images.githubusercontent.com/1646896/198789252-fff86705-5512-41de-9e7e-4d4e65a00b24.png)

I'm sure there are more complex examples where difftastic would do a better job, though.

**Comment by CetinSert** [comment]
@pkaminski

I did not have these files on a caching CDN!

Well, I do know and load times dropped from `7160ms` to `436ms` for `difft`!
<img width="3456" height="2234" alt="Image" src="https://github.com/user-attachments/assets/1ad68c4a-0cf0-4759-8e26-647c5db2155d" />

The load times are now near instantaneous!
