### ISSUE TITLE
Persistent "Incomplete SAML authorization" errors on repositories

### ISSUE THREAD

**Issue by jlinder** [Reviewable/Reviewable#981]
We began using SSO for our GitHub orgs recently and the `Incomplete SAML authorization` errors have been plaguing us since. 

The problem:

- Sometimes repo syncing gets stuck saying `Incomplete SAML authorization`. When it gets stuck, it stays stuck until we log into Reviewable with the GitHub user who originally connected the repo to Reviewable.
- We've been experiencing stuck repo syncs multiple times a day every day this week.

Context:

- We are aware that the account that connected a repo to Reviewable is the primary account used to sync data and that Reviewable cycles through the API tokens of all the other org owners and repo admins during the repo syncing process. 
- We have a number of org owners and repo admins. Most are SSO linked. Some have not logged into Reviewable since SSO linking their GitHub accounts.
- All the repos that we have connected to Reviewable were connected by the same bot account. That bot account is SSO linked and has re-logged into Reviewable after linking to SSO. 
- The bot user is receiving the `Reviewable GitHub authorization no longer valid` email from Reviewable a couple times a day (at least).
- Sometimes it encounters the `Incomplete SAML authorization` error and then recovers.

**Comment by pkaminski** [comment]
Sorry about that -- dealing with SSO as a GitHub app can be a pain in the neck.  Could you let me know (via email to support@reviewable.io) which organization is affected, and the username of the bot account?  Perhaps I can find some clues in our logs.  Thanks.

**Comment by pkaminski** [comment]
Never mind, the organization and bot account in question are pretty clear from the logs.  💥 

It looks like initially a few repos were disconnected due to SAML errors encountered for non-bot admins, but this is presumably because they were connected directly by those users.  In the last couple days I only see disconnections due to the bot account, which makes sense since (in principle) we only flag connections as broken when processing an event via the connecting account (otherwise, we just fail and retry silently).  Having other users not signed in via SSO shouldn't be a problem as long as all repos are connected via the bot.

Unfortunately, I don't have a hypothesis as to why the bot keeps erroring out.  The issue appears to be intermittent so I haven't been able to get a repro directly via command line.  We only keep the latest OAuth token around and all our instances have restarted since you refreshed the bot's token so it's not a cache invalidation problem (at least on our side).

Are you able to try connecting a repo or two via a different account to see if that happens to address the issue?  I'm wondering if the problem is somehow specific to the bot account, since I see the same errors occurring in two distinct organizations.  Thanks.
